### ISSUE TITLE
Anker Uboot

### ISSUE THREAD

**Issue by Statev-Bonsai** [eiksch/statev_v2_issues#1151]
Der Anker des U-Bootes funktioniert nicht richtig.
Das Boot treibt einfach irgendwann weg und wird wenn es an Kaimauer etc anstößt beschädigt.

Wenn man beim normalen Boot einen Anker setzt hebt sich das Boot ein wenig an, dieses verhalten ist beim U-Boot nicht zu beobachten.

**Comment by its4l3x** [comment]
Anker vom UBoot ist ein bisschen besonders 😂 Da hängt ein ganz andere Call einer ganze anderen GTA Funkion eig. hinter, welchen wir aber nicht nutzen. Wir müssen erstmal überhaupt die function finden & einbauen.

Werde das eher als enhancment markieren, wenn wir mal Zeit haben uns das genauer anzuschauen.
