### ISSUE TITLE
Fahrzeug repariert sich selbst  mit ausschalten der Unterbodenbeleuchtung

### ISSUE THREAD

**Issue by FarkasCian** [eiksch/statev_v2_issues#1570]
**Character Name**
Farkas Cian

**Auftrittszeitpunkt (Datum / Uhrzeit)**
29.05.2021, gegen 1:45 Uhr
25.05.2021, Zeit weiß ich nichtmehr, irgendwann Abends

**Beobachtetes Verhalten**
Obey Omnis wechselt beim Ausschalten der Unterbodenbeleuchtung von Kontrollleuchte gelb auf weiß, auch äußerlich ist das Fahrzeug wieder komplett repariert. 

**Erwartetes Verhalten**
Bei der Betätigung des Schalters für das Unterbodenlicht, sollte es aus gehen, aber der Wagen kaputt bleiben.

**Schritte um den Fehler nachvollziehen zu können**
Fahrzeug verunfallt, brennt --> Kontrolleuchte Rot
Anschließend Reparatur mit Repkit --> Kontrolleuchte Gelb
Auf der Fahrt danach Unterbodenbeleuchtung über X-Menu ausschalten --> Kontrollleuchte welchselt auf Weiß, Wagen auch Optisch wieder repariert 

**Optional: Video / Bilder des Fehlers**
https://www.youtube.com/watch?v=YYGe_phvBxA

**Comment by PlayInc89** [comment]
Sowas Ähnliches ist auch beim Paradies nur das beim Unterboden an/ausschalten sich die Fahrzeug Folierung ändert

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/1635
