### ISSUE TITLE
[SAMMEL-Ticket] - Fahrzeugbilder StateNet

### ISSUE THREAD

**Issue by TheBroady** [eiksch/statev_v2_issues#1659]
**Beobachtetes Verhalten**
Der Winki hat im StateNet kein Bild

**Optional: Video / Bilder des Fehlers**
https://static.wikia.nocookie.net/gtawiki/images/5/59/Winky-GTAO-front.png/revision/latest/scale-to-width-down/1000?cb=20201216100324

https://static.wikia.nocookie.net/gtawiki/images/a/a4/Winky-GTAO-FrontQuarter.png/revision/latest/scale-to-width-down/1000?cb=20201218104456

**Comment by callmerusty** [comment]
Der Progen Emerus fehlt auch noch.

https://wiki.statev.de/index.php?title=Emerus

**Comment by epichalt** [comment]
https://wiki.statev.de/index.php?title=Trailer_Pisswasser

Pisswasser Trailer ebenfalls

**Comment by Statev-Bonsai** [comment]
![Screenshot_6](https://user-images.githubusercontent.com/70241137/124338139-85c0ef00-dba6-11eb-938a-68a1c938b90a.jpg)

![Screenshot_7](https://user-images.githubusercontent.com/70241137/124338142-88bbdf80-dba6-11eb-9863-00cc9ae7415b.jpg)

**Comment by PrimroseBloom** [comment]
![buffaloudominator](https://user-images.githubusercontent.com/70226823/124344300-9cc90680-dbd1-11eb-944c-707186a97d95.JPG)
![neo](https://user-images.githubusercontent.com/70226823/124344301-9d619d00-dbd1-11eb-89a8-a629b060bd1d.JPG)
![mixer(biffvariant)](https://user-images.githubusercontent.com/70226823/124344302-9d619d00-dbd1-11eb-91d0-5d7b1e34b550.JPG)
![tipper](https://user-images.githubusercontent.com/70226823/124344303-9d619d00-dbd1-11eb-979f-663c124dbe46.JPG)

**Comment by LouieLagarde** [comment]
Dann mach ich mal mit. 

Der Trashmaster fehlt leider auch noch.

https://gyazo.com/d6aeb46319a855ffd5b71afe0fa3817c

**Comment by TheBroady** [comment]
Gang Burrito (Lost)
![20210703102021_1](https://user-images.githubusercontent.com/70150887/124348330-a5c5d200-dbe9-11eb-9ab5-968ee9f28c68.jpg)

Gang Burrito
![20210703102143_1](https://user-images.githubusercontent.com/70150887/124348331-a6f6ff00-dbe9-11eb-8d49-34769ed4a77e.jpg)

HVY Barracks Semi
![20210703102415_1](https://user-images.githubusercontent.com/70150887/124348333-a78f9580-dbe9-11eb-8718-885acf98f364.jpg)

Dock Trailer
![20210703102519_1](https://user-images.githubusercontent.com/70150887/124348334-a8c0c280-dbe9-11eb-97a9-18f0bfdd7293.jpg)

Buffalo Race
![20210703102608_1](https://user-images.githubusercontent.com/70150887/124348335-a9595900-dbe9-11eb-9104-e1420b1f2752.jpg)

Dominator Race
![20210703102725_1](https://user-images.githubusercontent.com/70150887/124348336-a9f1ef80-dbe9-11eb-9742-fe62b20ff266.jpg)

Vysser Neo
![20210703102831_1](https://user-images.githubusercontent.com/70150887/124348338-aa8a8600-dbe9-11eb-991a-d65018788f5c.jpg)

HVY Mixer (Biff variant)
![20210703102945_1](https://user-images.githubusercontent.com/70150887/124348339-abbbb300-dbe9-11eb-8e20-ec7fbc101c0a.jpg)

Tipper
![20210703101628_1](https://user-images.githubusercontent.com/70150887/124348341-ac544980-dbe9-11eb-9ab8-dac3dda35e31.jpg)

Trashmaster heist
![20210703101818_1](https://user-images.githubusercontent.com/70150887/124348342-ad857680-dbe9-11eb-9173-66267305e243.jpg)

**Comment by DonVitoDiangelo** [comment]
------------------------Bis Bilder eingepflegt bis hierher

**Comment by DonVitoDiangelo** [comment]
P.S. Bilder braucht Ihr keine machen. Wenn dann am besten einfach Hashes auflisten.

**Comment by epichalt** [comment]
Coquette ebenfalls

**Comment by epichalt** [comment]
Gauntlet Classic Custom + BF400 Cross auch

**Comment by Herr-Blitz** [comment]
Der Declasse Impaler fehlt auch noch
![State V Net - Declasse Impaler](https://user-images.githubusercontent.com/87550322/126014958-c65082ef-87d8-4ded-ba88-b01fb35e9e1a.png)

**Comment by vialis-one** [comment]
Das Bild des Pisswasser-Trailers wird ebenfalls nicht im StateNet angezeigt

**Comment by Statev-Bonsai** [comment]
Dinka Verus

**Comment by TheBroady** [comment]
> Coquette ebenfalls
Welche genau?


@DonVitoDiangelo alle Hashes in allen Motor Varianten
gauntlet5_engine_gauntlet5_289ps
gauntlet5_engine_gauntlet5_299ps
gauntlet5_engine_gauntlet5_311ps
gauntlet5_engine_gauntlet5_349ps

bf400_engine_bf400_66ps

impaler_engine_impaler_173ps
impaler_engine_impaler_178ps
impaler_engine_impaler_184ps
impaler_engine_impaler_193ps

trailers2_engine_trailers2_0ps

verus_engine_verus_24ps
verus_engine_verus_35ps

**Comment by DonVitoDiangelo** [comment]
Bis hierhin DONE

**Comment by Statev-Bonsai** [comment]
Dinka Verus
Benefactor Glendale Custom
Brute Shuttle Bus

**Comment by PrimroseBloom** [comment]
Western Deathbike
Lampadati Novak
Willard Faction

**Comment by DonVitoDiangelo** [comment]
> Dinka Verus
> Benefactor Glendale Custom
> Brute Shuttle Bus

Verus kam doch erst mit dem letzten Patch rein?! Bitte nochmal prüfen.

**Comment by TheBroady** [comment]
Dinka Double T (Race)

**Comment by Statev-Bonsai** [comment]
@DonVitoDiangelo Verus hat jetzt ein Bild, aber wo ich den Beitrag erstellt hatte war noch keins im Statenet ;D

**Comment by vialis-one** [comment]
Speedo Custom

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/1843

**Comment by cadpri** [comment]
Trailer 200
ich glaub der heisst
trailersmall

**Comment by cadpri** [comment]
Declasse Impaler Apocalypse hat kein Vorschaubild

**Comment by M4cm4ni4c** [comment]
Imponte Dukes hat auch kein Bild im StateNet

**Comment by nox142** [comment]
![Screenshot_9](https://user-images.githubusercontent.com/79390131/141724740-e6a60fde-3140-4a32-8b81-9ab9c3cb6ffc.png)

**Comment by TheBroady** [comment]
Das müssten die Hashes der Fahrzeuge sein die seit dem "Bis hierhin DONE" von DonVito am 27 Juli gepostet wurden:

verus_engine_verus_24ps
verus_engine_verus_35ps

faction_engine_faction_101ps

glendale2_engine_glendale2_98ps
glendale2_engine_glendale2_103ps
glendale2_engine_glendale2_107ps
glendale2_engine_glendale2_113ps

rentalbus_engine_rentalbus_102ps

deathbike_engine_deathbike_53ps
deathbike_engine_deathbike_69ps

novak_engine_novak_176ps
novak_engine_novak_185ps
novak_engine_novak_199ps
novak_engine_novak_209ps

double_engine_double_122ps

speedo4_engine_speedo4_69ps
speedo4_engine_speedo4_82ps
speedo4_engine_speedo4_99ps

youga3_engine_youga3_122ps
youga3_engine_youga3_127ps
youga3_engine_youga3_133ps
youga3_engine_youga3_144ps

trailersmall_engine_trailersmall_0ps

impaler2_engine_impaler2_193ps
impaler2_engine_impaler2_178ps

dukes_engine_dukes_112ps
dukes_engine_dukes_115ps
dukes_engine_dukes_119ps
dukes_engine_dukes_123ps

yosemite3_engine_yosemite3_144ps
yosemite3_engine_yosemite3_149ps
yosemite3_engine_yosemite3_156ps
yosemite3_engine_yosemite3_164ps

**Comment by Statev-Bonsai** [comment]
Mesa Offroad
Brute Shuttle Bus
Benefactor Glendale Custom
Shitzu Hakuchou Drag

fehlen auch noch...

**Comment by RoyMckellar** [comment]
Pegassi FCR 1000 Custom
Brute Tour Bus/Rental Shuttle Bus

**Comment by TheBroady** [comment]
> Das müssten die Hashes der Fahrzeuge sein die seit dem "Bis hierhin DONE" von DonVito am 27 Juli gepostet wurden:
> 
> verus_engine_verus_24ps verus_engine_verus_35ps
> 
> faction_engine_faction_101ps
> 
> glendale2_engine_glendale2_98ps glendale2_engine_glendale2_103ps glendale2_engine_glendale2_107ps glendale2_engine_glendale2_113ps
> 
> rentalbus_engine_rentalbus_102ps
> 
> deathbike_engine_deathbike_53ps deathbike_engine_deathbike_69ps
> 
> novak_engine_novak_176ps novak_engine_novak_185ps novak_engine_novak_199ps novak_engine_novak_209ps
> 
> double_engine_double_122ps
> 
> speedo4_engine_speedo4_69ps speedo4_engine_speedo4_82ps speedo4_engine_speedo4_99ps
> 
> youga3_engine_youga3_122ps youga3_engine_youga3_127ps youga3_engine_youga3_133ps youga3_engine_youga3_144ps
> 
> trailersmall_engine_trailersmall_0ps
> 
> impaler2_engine_impaler2_193ps impaler2_engine_impaler2_178ps
> 
> dukes_engine_dukes_112ps dukes_engine_dukes_115ps dukes_engine_dukes_119ps dukes_engine_dukes_123ps
> 
> yosemite3_engine_yosemite3_144ps yosemite3_engine_yosemite3_149ps yosemite3_engine_yosemite3_156ps yosemite3_engine_yosemite3_164ps

Hier die Hashes der Fahrzeuge von @Statev-Bonsai und @RoyMckellar :

mesa3_engine_mesa3_89ps

rentalbus_engine_rentalbus_102ps

glendale2_engine_glendale2_98ps
glendale2_engine_glendale2_103ps
glendale2_engine_glendale2_107ps
glendale2_engine_glendale2_113ps

hakuchou2_engine_hakuchou2_152ps

fcr2_engine_fcr2_98ps

**Comment by Patrick-Snooze** [comment]
Dinka RT3000
Golf Caddy
Pfister Growler
Vapid Slamtruck

**Comment by Ekaz58** [comment]
Pegassi Speeder V2 auch, evtl das V1 ebenfalls.
![boot](https://user-images.githubusercontent.com/21086097/146273371-36c0069b-3796-4a18-8a1f-64c083b26b98.png)

**Comment by nox142** [comment]
Annis Euros

**Comment by ProgrammingFox** [comment]
Karin Rebel
![grafik](https://user-images.githubusercontent.com/48456305/148081911-eb51f4b8-8261-4924-9f0e-14d1176627b9.png)

**Comment by ShauniKT** [comment]
![chrome_f1Y8UbpZov](https://user-images.githubusercontent.com/74824266/148694627-e0ab97c7-bd67-4661-ba82-931e8b0a23e2.png)

**Comment by Ekaz58** [comment]
Pfister Comet S2 
![1](https://user-images.githubusercontent.com/21086097/149870196-fc4ec2a9-a74f-49ea-91b8-cbd2c600441c.png)

**Comment by Ekaz58** [comment]
Western Reever 99PS ebenfalls

![1](https://user-images.githubusercontent.com/21086097/153533369-8d1887de-a53c-4351-85de-3a409901421b.png)

**Comment by TheOutburst** [comment]
https://i.imgur.com/jIOYHmn.png

iwagen & comet6

**Comment by Ekaz58** [comment]
Pfister Comet S2 Cabrio

![11111](https://user-images.githubusercontent.com/21086097/158101729-73443cf4-e367-4cb9-8b04-e7307e39ec27.png)

**Comment by Patrick-Snooze** [comment]
Western Motorcycle Company Diabolus (Race)
Nagasaki Shinobi

**Comment by AdmiralState** [comment]
Astron Pfister 

![image](https://user-images.githubusercontent.com/103783836/164067453-5fd35cb9-dcc9-45bc-ac41-25480c664d75.png)

**Comment by KingMarcel** [comment]
--------- bis hier vervollständigt (im nächsten Update) ---------------

**Comment by eckbert58** [comment]
> Pegassi Speeder V2 auch, evtl das V1 ebenfalls. ![boot](https://user-images.githubusercontent.com/21086097/146273371-36c0069b-3796-4a18-8a1f-64c083b26b98.png)

speeder boot fehlt immernoch :(  🗡️ 

danke ürbigens!

**Comment by KingMarcel** [comment]
Speeder2 ergänzt.
Speeder ist drin

**Comment by epichalt** [comment]
Growler
Dominator ASP
Zeno
Buffalo STX
Cypher
Calico GTF

**Comment by Patrick-Snooze** [comment]
Karin Everon

**Comment by Statev-Bonsai** [comment]
Champion

![Screenshot_33](https://user-images.githubusercontent.com/70241137/203538312-9fd68232-80fb-40b6-9102-13c1d7f9d90e.jpg)

**Comment by epichalt** [comment]
Declasse Vamos
Western Motorcycle Gargoyle 
Willard Faction Custom Donk

**Comment by Statev-Bonsai** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/70241137/211065427-53180e83-0795-4deb-8f67-65c04fd44fa4.jpg)

![Screenshot_3](https://user-images.githubusercontent.com/70241137/211065444-2bff2685-3431-4912-a634-85b09cfea764.jpg)

![Screenshot_1](https://user-images.githubusercontent.com/70241137/211065468-44613d74-e47e-42fa-a592-7ec197ea74de.jpg)

**Comment by KingMarcel** [comment]
--------- bis hier vervollständigt (im nächsten Update) ---------------

**Comment by eckbert58** [comment]
Ski Doo 800R fehlt immernoch.

**Comment by KingMarcel** [comment]
--- für die Dokumentation, Ski Doo vor ein paar Updates auch ergänzt ---
