### ISSUE TITLE
Umlagerung Inventar bei bsp. Lager -> Fahrzeug

### ISSUE THREAD

**Issue by TheBroady** [eiksch/statev_v2_issues#1807]
**Character Name**
Max Broady

**Auftrittszeitpunkt (Datum / Uhrzeit)**
05.08.2021 - 19 Uhr

**Beobachtetes Verhalten**
Habe Benzin aus meinem Lagerhaus in meinen Phantom + Auflieger geladen.
Nach meinem Stand kann ich wenn ich bsp. 3000 Liter im Lager habe diese einfach in den LKW ziehen und es wird nur so viel eingeladen wie platz ist. Sprich wenn der LKW Leer ist, 1200 Liter.
Allerdings konnte ich nichts einladen, da ich die Meldung bekommen habe das ich nicht genug platz für die 3000 Liter habe.

**Erwartetes Verhalten**
Nicht wieder Q drücken müssen und eine genaue Menge angeben müssen.
Wenn man eine Menge rüber zieht, soll diese komplett rüber gelagert werden bis der Lagerplatz voll ist.
500 Liter Platz : von 1000 Liter die man rüber zieht werden dann nur 500 ins Fahrzeug gepackt ohne mit Q die genaue Menge angeben zu müssen.

**Schritte um den Fehler nachvollziehen zu können**
Probieren 2000 Liter von Lagerhaus in Fahrzeug zu ziehen. Ohne Q drücken um die genaue Menge festzulegen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by UNDRCVRR** [comment]
@DrGrizzlY17 Hab ich auf dem Dev getestet, ist immer noch so
