### ISSUE TITLE
Warenexport Bieten noch möglich nach Ablauf der Zeit

### ISSUE THREAD

**Issue by SatyriaDine** [eiksch/statev_v2_issues#1863]
**Character Name**
Sofia_Black // Ogi_Black

**Auftrittszeitpunkt (Datum / Uhrzeit)**
seit einiger Zeit

**Beobachtetes Verhalten**
Nachdem die Restzeit eines Warenexports abgelaufen ist, ist dieser noch ca eine Minute öffentlich in den Aufträgen zu sehen. In dieser Zeit kann noch geboten werden. Mehrfach beobachtet bei verschiedenen Exporten bei denen man zum Ablauf der Zeit der Bieter mit dem niedrigsten Gebot war.

**Erwartetes Verhalten**
Dass abgelaufene Exporte aus der Liste der verfügbaren Exporte schneller nach Ablauf der Zeit verschwinden und niemand mehr drauf bieten kann.

**Schritte um den Fehler nachvollziehen zu können**
Auf Exporte bieten und warten bis die Zeit abläuft.

**Comment by Stiefel911** [comment]
Das selbige ist auch im Import der Fall... die Null bleibt länger stehen als es vllt sollte...
Kann man ja auch mal drüber schauen vllt?

**Comment by ProgrammingFox** [comment]
Ist eure Uhrzeit des PCs auch synchronisiert? PCs haben die Angewohnheit nach einiger Zeit asychron zu laufen zur genormten Uhrzeit. Das kann von einige Sekunden sich bis zu Minuten ziehen. Macht mal rechtsklick auf eure Uhr unten rechts in Windows und dann auf "Datum/Uhrzeit ändern" und drückt dort mal auf "Jetzt sychronisieren" und schaut ob das immer noch passiert. Hab ich auf öfter das Problem.

**Comment by Bene-RonnyMoritz** [comment]
Das Problem liegt nicht an der Zeit vom PC denke ich. Auch am Handy tritt das Problem auf 🤔

**Comment by Erumeldor** [comment]
Heute war dieses Problem wieder. Ich hab den Motor für 24500$ ersteigert, Zeit war bei 0. Das war locker noch 20 Sekunden so. Dann hat nochmal jemand geboten - die Zeit blieb auf 0 (ist nicht mehr hoch gegangen). 
Schlussendlich dann auch nochmal geboten, und den Motor für 26000$ gekauft.

Das ist natürlich schade für mich (weil 1500$^^), aber auch irgendwie doof für die alle Bieter. Man muss quasi den Zeitpunkt abpassen, wann das Angebot auch wirklich aus der Liste verschwindet. Denn kurz vorher zu bieten sichert einem wirklich den Motor. Das ist irgendwie nicht so wirklich der Sinn dahinter tbh.

Konkret: Nagasaki Shinobi Motor / 142 PS - Datum 24.06.2022 - 20:48:16 - Satoru_Tsuyoshi

**Comment by Erumeldor** [comment]
Heute selbes Spiel nochmal.
Aber beim bieten ist aufgefallen:
Ich habe mal geboten kurz nachdem der Counter auf 0 war. Das Gebot ging rein und der Counter ist dann auf ein paar Sekunden. Aber nie auf 30s, was meines Wissens der Fall sein sollte, sondern eher so auf ~10-15.
Das ganze sogar mehrfach, weil immer wieder überboten gegenseitig.
Man hätte auch dann wieder so schätzungsweise bis 1min nach Ablauf bieten können (solange das Item eben noch in der Liste ist), und das Gebot wäre durch gegangen.

Vorschlag also ganz konkret: Timer bei 0? Gebot geht gar nicht mehr zum System. Auch wenn es erst später von der Liste entfernt wird. Vielleicht kann man ja die Eingabe lokal blockieren.
