### ISSUE TITLE
Dppelte Menge Eisen wenn 2 gleichzeitig ankaufen in einem Auto

### ISSUE THREAD

**Issue by QueenLuise** [eiksch/statev_v2_issues#1923]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Alexa_Woods

**Auftrittszeitpunkt (Datum / Uhrzeit)**
23.10.2021

**Beobachtetes Verhalten**
Wenn man mit einem Auto an einen ankaufpunkt steht und 2 Charaktere gleichzeitig ankauft hat man die doppelte menge im Auto. Quasi kauft einer 800 Eisen und der andere zur selben Zeit auch 800 am selben Auto hast du 1600 Eisen im Auto obwohl das Auto nur 800 KG platz hat.

**Erwartetes Verhalten**
Erm...Naja wollte es melden nicht das Spieler dies ausnutzen. Und eigentlich sollte es ja nicht so sein.

**Schritte um den Fehler nachvollziehen zu können**
Ein auto auf den Abledepunkt. Und 2 Spieler kaufen gleichzeitig Eisen an. sagen wir 800kg wie zb ein Punder fasst. Am ende hast du dann 1600 Eisen im Punder.

Ein auto auf den Abledepunkt. Und 2 Spieler kaufen gleichzeitig Eisen an. sagen wir 800kg wie zb ein Punder fasst. Am ende hast du dann 1600 Eisen im Punder.
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

Leider Kein video.

**Comment by TeubyDE** [comment]
Beim nächsten Update fix.
