### ISSUE TITLE
Waffen kleben an Hosen der Cops

### ISSUE THREAD

**Issue by PresLincoln** [eiksch/statev_v2_issues#1991]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**David_Lincoln**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seitdem ich als Cop spiele.

**Beobachtetes Verhalten**
Wenn man im Fraktionsdienst der Polizei eingestempelt ist, sieht der Koppel normal aus, auch sonst klebt **keine** Pistole oder Taser an der Hose. Wenn ich jedoch nicht im Dienst eingestempelt bin, kleben plötzlich Taser und Waffe an der Hose, was sehr komisch aussieht. Ergo - jeder der kein Cop ist, sieht die Waffen doppelt an unserer Hose kleben, das ist bissl doof.

**Erwartetes Verhalten**
Dass der Taser und die Pistole nicht zusätzlich an der Hose kleben.

**Optional: Video / Bilder des Fehlers**
Wenn man **im Diens**t ist:
![taserr2](https://user-images.githubusercontent.com/75540676/139879879-291e07be-7e3f-4131-b373-73e9d0c0c894.jpg)
![waffer1](https://user-images.githubusercontent.com/75540676/139879889-8bac6367-30f3-44ce-b76b-66ef71770128.jpg)

Wenn man **außer Dienst** ist:
![waffe1](https://user-images.githubusercontent.com/75540676/139880072-d57af482-fd4e-40de-afe9-782cedbd5efd.jpg)
![taser1](https://user-images.githubusercontent.com/75540676/139880092-6c76f802-c779-402c-a6b9-ecb5d806c5df.jpg)

**Comment by Gruntelicious** [comment]
Anmerkung:

Sobald die Waffe in die Hand genommen und wieder weggesteckt wird ist das weg. Ergo passiert das nur, wenn ich die Waffen ausrüste BEVOR ich das passende Copoutfit (eines mit Dutybelt) wähle. Darunter fällt auch ein "Außer Dienst und wieder in den Dienst gehen".

- Armstrong

**Comment by PresLincoln** [comment]
Nein, dachte ich auch als erstes. Bei Zivilisten funktioniert das nicht - der Taser und die Waffe kleben weiterhin an der Hose. Das habe ich jetzt schon bei drei Zivilisten ausprobiert. Da besteht definitiv ein bug!
