### ISSUE TITLE
Handy klingelt weiter obwohl wer auf anderem Handy den Anruf angenommen hat. (Friseur Nummer)

### ISSUE THREAD

**Issue by wichtTSV** [eiksch/statev_v2_issues#1996]
**Character Name**
Tom Spider

**Auftrittszeitpunkt (Datum / Uhrzeit)**
3.11.2021 14:30 Uhr

**Beobachtetes Verhalten**
Die Simkarte wurde angerufen die mehrer Leute drinne haben. Jemand anderes ist dran gegangen, wodurch bei mir mein Klingelton jetzt seit ca. 5 minuten in dauerschleife läuft.

**Erwartetes Verhalten**
Das wenn jemand anderes den Anruf annimmt der Klingelton aufhört zu Klingeln

**Schritte um den Fehler nachvollziehen zu können**
Mehrer Leute die gleiche Nummer einsetzten und Aktiv haben (z.b. Friseur nummer) anrufen lassen und jemand nimmt den Anruf an, bei anderen müsste dann wie in meinem Fall der Klingelton weiter laufen (obwohl angenommen wurden ist von einem anderen Handy)

**Optional: Video / Bilder des Fehlers**

**Comment by wichtTSV** [comment]
Ist ja aber auch keine dauerhafte lösung ^-^

**Comment by Dean-Gallagher** [comment]
Wiegesagt Workaround bis zum Fix :P
