### ISSUE TITLE
Charakter Bug nach Drogenkonsum

### ISSUE THREAD

**Issue by Lucky2406** [eiksch/statev_v2_issues#2171]
## WICHTIGE INFORMATION!!:

**Character Name**

Miguel Ashton

**Auftrittszeitpunkt (Datum / Uhrzeit)**

29.01.2021

**Beobachtetes Verhalten**

Gesichter werden sowohl vom eigenen Charakter, als auch von Umstehenden verunstaltet, sobald man einen "High" - Effekt hat.

**Erwartetes Verhalten**

Normales Aussehen der Charaktere trotz Dröhnung.

**Schritte um den Fehler nachvollziehen zu können**

Drogen Konsumieren (aufgefallen bei Weed in jeglicher Form)

**Bilder**
1. Auftreten (Miguel Ashton)
![Miguel](https://user-images.githubusercontent.com/66916316/147855896-48a9c886-2221-4592-92ff-71c9c98abe0a.png)

2. Auftreten (Carlie Tacus)
![Carlie](https://user-images.githubusercontent.com/66916316/147855897-44980a66-cde6-44c2-ab92-cbb06a551f5d.png)

3. Auftreten (Hanna Fields)
![Hannah](https://user-images.githubusercontent.com/66916316/147855948-877f350c-7ccd-43ce-b928-84d2c6addd1a.png)

PS: Es wurde mir angetragen, dass der Bug dadurch beseitigt wird, dass man ein Kleidungsstück kurz aus und wieder anzieht.

MfG
Lucky

**Comment by Saaria83** [comment]
Ich find ich bin voll den Hübschen :D

**Comment by its4l3x** [comment]
Auch bekannt als Tito Abendo Syndrom :D

**Comment by ShauniKT** [comment]
Uuh bei Bildern vom Tito Syndrom bin ich dabei!
War durch relogg wieder behebbar bei mir.

![GTA5_jlxAQnR2K3](https://user-images.githubusercontent.com/74824266/148690447-bd194a54-3812-43bb-8023-545f86a123ec.jpg)

**Comment by JasminHarper** [comment]
selbes Problem auch wenn man im Notfall MD gelandet ist.
