### ISSUE TITLE
Augen/Haar Animation beim Kiffen falsch?!

### ISSUE THREAD

**Issue by eckbert58** [eiksch/statev_v2_issues#2175]
**Character Name**
Rainer Kornn

**Auftrittszeitpunkt (Datum / Uhrzeit)**
02.01.2022 / 20:55

**Beobachtetes Verhalten**
Weiß nicht ob es an dem Update lag oder so aber beim anmachen des Joints verändert sich das Haartattoo in grün und die Augen bleiben normal.

**Erwartetes Verhalten**
Haare bleiben so und Augen werden rot. :D

**Schritte um den Fehler nachvollziehen zu können**
Joint anhauen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
Egal

**Optional: Video / Bilder des Fehlers**

![kiff](https://user-images.githubusercontent.com/21086097/147887919-a50c3d75-9b96-4310-90d5-efdaae56c64b.png)

**Comment by Ekaz58** [comment]
Andere sehen auch keine roten augen aber keine grünen haare, denke dass liegt dann an der Animation

**Comment by SHaagmann** [comment]
Augen werden nachdem man sich umgezogen hat richtig angezeigt. Haare könnten auch am Filter liegen, wenn es nur bei dir so ist.

**Comment by TeubyDE** [comment]
Müsste mit dem letzten drug use update fix sein
