### ISSUE TITLE
Eigene Rechnung ausstellen nicht möglich

### ISSUE THREAD

**Issue by Eve-Noxito** [eiksch/statev_v2_issues#2212]
## WICHTIGE INFORMATION!!:
```
Kann mir in der Werkstatt selbst keine Rechnung ausstellen. Weder für Reperatur noch Tuning noch Lackierung
```

**Character Name**
Eve_Noxito

**Auftrittszeitpunkt (Datum / Uhrzeit)**
<Fehler besteht schon seit Wochen, unabhängig von der Tageszeit bzw der Zeit die ich ic war

**Beobachtetes Verhalten**
<Wenn ich mir selbst eine Rechnung in der Werkstatt ausstellen möchte für zBsp. Reperatur, kommt das Fenster zum unterschreiben nicht. Charakter freezt an Ort und stelle fest und ich kann mich nicht mehr bewegen.. Da hilft dann nur ein Spielneustart

**Erwartetes Verhalten**
<Das ich mir selbst Rechnungen für Werkstattdienste ausstellen kann

**Schritte um den Fehler nachvollziehen zu können**
<!

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
<

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Welche Werkstatt?
Tritt der Fehler immer auf?
Haben auch andere Mitarbeiter diesen Fehler?

**Comment by Eve-Noxito** [comment]
Sludgie Customs. Also bei uns in der Werkstatt hab das Problem nur ich. Der Fehler tritt nicht immer auf aber von ca 10 versuchen 8 mal. Kann auch nicht ausmachen wann genau das auftritt. Weiß aber auch das ich wohl nicht die einzige mechanikerin bin die das Problem auf state hat oder hatte. Gab ja auch schon mal nen report im bugtracker deswegen

**Comment by Eve-Noxito** [comment]
Ja, tritt weiterhin auf :(

**Comment by Dean-Gallagher** [comment]
Bei Horizon auch, nicht bei allen aber immer den gleichen.

**Comment by TeubyDE** [comment]
Nach mehrmaligem Test auch auf dem Live Server ist das bisher nicht mehr aufgetreten. 
Bitte NEUEN Bugtracker eröffnen sollte das noch mal auftreten.
