### ISSUE TITLE
Telefon wird aufgelegt, wenn am Markplatz etwas mit n im Wort gesucht wird

### ISSUE THREAD

**Issue by hollyfizzu** [eiksch/statev_v2_issues#2214]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Jacques_Colombo

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Immer am Marktplatz

**Beobachtetes Verhalten**

Ist man am Telefon und will am Marktplatz etwas suchen, das ein N beinhaltet, beendet man den Anruf ungewollt.

**Erwartetes Verhalten**

Am Markplatz bei offenem UI wird das N zum Auflegen des Telefonats blockiert

**Schritte um den Fehler nachvollziehen zu können**

Am Marktplatz telefonieren und etwas mit N suchen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Falk-Alers** [comment]
auch bei werkstätten oä wenn man "N" drückt um zum auto zu laufen zb wegen tuning

**Comment by SimonPfeifferStateV** [comment]
Fehler besteht weiterhin
