### ISSUE TITLE
Fahrzeuge verschwinden nach Gamecrash, Ortung zeigt noch auf letzte Position

### ISSUE THREAD

**Issue by EricForster** [eiksch/statev_v2_issues#2248]
**Eric Forster**

**05.02.2022 / 00:30 Uhr**

**Alle Fahrzeuge an unserem Hotel (Postelcod 5072) sind unter die Map verschwunden. Orten der Fahrzeuge ergibt das die Fahrzeuge alle am Hotel stehen. 12 Fahrzeuge insgesamt. Die Fahrzeuge sind nur auf dem Grundstück verschwunden. Limousine die sich an der Straße befindet steht weiterhin dort.**

**Nach einer Aktion sind wir zum Hotel gefahren. Von dort aus sind wir umgestiegen auf einen Streiter, als wir uns vom Hotel entfernt haben und 3 min später wieder dorthin gefahren sind, waren alle Fahrzeuge verschwunden.**

**Comment by Donvito88** [comment]
Update: Ein weiteresmal an der selben Stelle passiert. Diesmal aber nicht nach relog sondern nach Besuch eines MLO's

**Comment by M4rvinLP** [comment]
Bei der HK ebenfalls heute Abend gewesen.

**Comment by Patrick-Snooze** [comment]
Hatte ich auch heute mit meinem Krieger, Barracks und Dock Trailer.

**Comment by Enemyaa** [comment]
Character Name
Jax Borrow

Auftrittszeitpunkt (Datum / Uhrzeit)
03.03.2022 um zirka 19:10Uhr

Beobachtetes Verhalten
Nach einem Gamecrash waren der von mir benutzte Barricks Semi sowie der daran angehängte Tanke 2 für mich nicht mehr sichtbar. Andere Spieler konnten beide Fahrzeuge sehen, aber nicht mit ihnen interargieren. Ein entfernen von dem Kartenbereich und anschließendes zurückkehren an den Ort hat auch keine Abhilfe schaffen können. Schlüssel konnte für einen weitern Lösungsansatz übergeben werden, hat aber leider auch nichts gebracht.

Erwartetes Verhalten
Das die Fahrzeuge nach Relog weiterhin sichtbar und nutzbar sind

Schritte um den Fehler nachvollziehen zu können
Es ist schwierig dies zu reproduzieren, da es nach einem Gamecrash war. Ist bei mir schon öfter aufgetreten in letzter Zeit.

Optional: Video / Bilder des Fehlers

    Crash und Relog
    https://drive.google.com/file/d/1bC84QOP_A9e_hFE_v0ccvkm2McxIGP_p/view?usp=sharing

    Rückkehr zum Ort des Geschehens + Test mit Schlüsselübergabe
    https://drive.google.com/file/d/1lkgv2-h3YxWZvcSw9Htik5rNtn7XUs1p/view?usp=sharing

**Comment by nox142** [comment]
Character Name
Jona Lindner

Auftrittszeitpunkt (Datum / Uhrzeit)
17.03.2022 um zirka 07:30Uhr (bzw zwischen 16.03. 21:15 Uhr und 07:30 Uhr am heutigen Tag)

Beobachtetes Verhalten
Nach dem Ausloggen gestern Abend sind anscheinend fast alle Fahrzeuge an der Werkstatt in Paleto in die andere Dimension gebuggt. Darunter zählen. 2x Slamtruck, Towtruck Large, Towtruck Small, Burrito, Shinobi, Tacovan, Sultan RS, Bison Standard, Trailer 200 und noch weitere.
Alle Fahrzeuge sind im Eigentum von verschiedenen Leuten. U.a. Jona Lindner, Sandy Miller, Marcello Valentine, Mike Ehrmanntraut, Besitz der Werkstatt und weiteren Leuten. Und nicht alle Besitzer waren gestern IC, sondern die Fahrzeuge wurden von uns ausgeparkt.

Erwartetes Verhalten
Fahrzeuge sollten nicht alle verschwinden

Schritte um den Fehler nachvollziehen zu können
Vermutlich nicht reproduzierbar?

Optional: Video / Bilder des Fehlers

**Comment by epichalt** [comment]
Heute auch den Fall gehabt im Autohaus, dass einer im Auto Kopfschmerzen hatte und für ihn das Fahrzeug nicht mehr sichtbar war. Für mich war es sichtbar, aber man konnte nicht einsteigen. Nachdem ich das Fahrzeug kurz auf den Flatbed geladen haben, war es wieder sichtbar und nutzbar. 
Allerdings sind gleichzeitig 20 andere Fahrzeuge im Autohaus verschwunden.

**Comment by TeubyDE** [comment]
alt:v Issue. Sollte das Problem auftreten bitte im Support melden. 

Wir geben bescheid wenn es von altv einen fix gibt.

**Comment by UNDRCVRR** [comment]
#2643

**Comment by TeubyDE** [comment]
Problem sollte mit dem altv Update 13 behoben sein
