### ISSUE TITLE
Passwort im Tablet nicht änderbar

### ISSUE THREAD

**Issue by powerswissi** [eiksch/statev_v2_issues#2270]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Roger Thickle

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Mittwoch 9 Februar

**Beobachtetes Verhalten**

Das Passwort lässt sich nicht ändern obwohl alle Kriterien erfüllt sind. Habe dies mit verschiedenen passwörtern probiert.

Passwort besteht aus mindestens 8 Zeichen /gross klein Schreibung, sonderzeichen und Zahlen

**Erwartetes Verhalten**

passwort sollte änderbar sein 

**Schritte um den Fehler nachvollziehen zu können**

versucht das passwort zu ändern 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Screenshot_32](https://user-images.githubusercontent.com/70152806/153137535-ccfad2cf-4f0b-4190-83ff-635f8d4ad08e.jpg)

**Comment by simplycach** [comment]
Fehler ist behoben.
