### ISSUE TITLE
Recycling Fabrik - Fahrzeug ausschlachten funktioniert nicht

### ISSUE THREAD

**Issue by ProgrammingFox** [eiksch/statev_v2_issues#2272]
**Character Name**
Daniel_Fox
Arthur_Pendragon

**Auftrittszeitpunkt (Datum / Uhrzeit)**
schon seit ein paar Wochen

**Beobachtetes Verhalten**
Beim Benutzen der Option "Fahrzeug ausschlachten" im Recycling Center passiert nichts. Dies passiert sowohl bei dem Inhaber Arthur Pendragon, als auch bei mir, einem Mitarbeiter mit allen Rechten. Wir haben dies jetzt über einige Tage/Wochen immer wieder erneut mit verschiedenen Fahrzeugen probiert. Passiert ist jedoch nichts.

Es hat am Anfang einmal funktioniert. Zu dem Zeitpunkt habe ich meinen "Karin Rebel" auf den Punkt gestellt. Als ich auf "Fahrzeug ausschlachten" ging öffnete sich auch entsprechend das Fenster mit der Übersicht, welche Teile man bekommt (interessanterweise war dieses allerdings leer). Dort hab ich dann wieder auf "Schließen" gedrückt und es ging zu.

Bei der Firma handelt es sich um das Objekt "LS Junkjard" mit Hash pfAkiyamaTextileCityRew_14

**Erwartetes Verhalten**
Das Fenster mit Übersicht der Teile geht auf und wir können wählen, dass wir das Fahrzeug ausschlachten wollen.

**Schritte um den Fehler nachvollziehen zu können**
Ich stelle mein eigenes Fahrzeug auf den Punkt.
![junkjard3](https://user-images.githubusercontent.com/48456305/153274130-5468b162-d682-4c2d-a584-82b60b15d459.PNG)

 Geh an die Türe und wähle dort "Fahrzeug ausschlachten".
![junkjard1](https://user-images.githubusercontent.com/48456305/153274186-909f1ade-ebaf-447b-bb5c-315bbfacf47b.PNG)

Es passiert nichts. Das Menü schließt sich einfach.

Das Fahrzeug wird auch registiert. Ich kann zB auf den Kofferraum zugreifen.
![junkjard2](https://user-images.githubusercontent.com/48456305/153274372-6d4b7d86-b2b3-4edd-913f-69a9fc6612d8.PNG)

**Comment by its4l3x** [comment]
@TheOutburst Bitte mal gegenprüfen

**Comment by TheOutburst** [comment]
UI öffnet sich aufm Dev, aber teilweise haben Fahrzeugen keine ausschlachtbaren Teile. Also erster Teil confirmed. Das nichts passiert konnte ich nicht nachweisen.

**Comment by ProgrammingFox** [comment]
@TheOutburst wenn du willst kann ich dir das morgen auch mal per Discord übertragen dann siehst das selbst mal

**Comment by Saaria83** [comment]
Ich kann bestätigen dass es alles funktionierte, als ich vor 2 Tagen eine Vortex recycelte

**Comment by ProgrammingFox** [comment]
@Saaria83 es geht hier speziell um das eine Gebäude. Dass es bei anderen funktioniert ist uns bewusst
