### ISSUE TITLE
Östliche Sisyphus Theater Strecke Bug/Problem

### ISSUE THREAD

**Issue by eckbert58** [eiksch/statev_v2_issues#2287]
*Character Name**
Rainer Kornn

**Auftrittszeitpunkt (Datum / Uhrzeit)**
17.02 / 00:40

**Beobachtetes Verhalten**
Beim annehmen des Rennens lässt sich weder das Inventar noch das X - Menu öffnen und somit ist einsteigen bzw aufschließen von Autos nicht möglich.

**Erwartetes Verhalten**
Inventar und X- Menu lassen sich bedienen

**Schritte um den Fehler nachvollziehen zu können**
mir selber ist es jetzt ein zweites mal aufgefallen, und nachdem ich es jetzt drei mal mit relog getestet habe dachte ich ich meld es mal

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
egal

**Comment by TheOutburst** [comment]
aber zuverlässig reproduziert bekommst du es nicht, oder?
Den Fehler kennen wir, haben ihn auch schon mal selbst hin bekommen, aber noch nicht genau herausgefunden wie es exakt passiert.

Kannst du hier einmal den client log von dem Tag hier hochladen? (altv Ordner -> Logs)

**Comment by Ekaz58** [comment]
[client_17-02-2022_00-28-10.log](https://github.com/mexyn/statev_v2_issues/files/8106120/client_17-02-2022_00-28-10.log)
[client_17-02-2022_00-42-11.log](https://github.com/mexyn/statev_v2_issues/files/8106121/client_17-02-2022_00-42-11.log)
[client_17-02-2022_00-44-39.log](https://github.com/mexyn/statev_v2_issues/files/8106122/client_17-02-2022_00-44-39.log)
