### ISSUE TITLE
Char wird nach Gamecrash immer wieder in die letzte Werkstatt zurückgesetzt in der ich war.

### ISSUE THREAD

**Issue by LadyLeo90** [eiksch/statev_v2_issues#2316]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Maria_Lopez**

**Auftrittszeitpunkt 15.03.2022/ 19:15)**

**Nach Gamecrashes wird mein Char wieder in die Werkstatt zurück geportet**

**Das mein Char an der Stelle steht wo ich den Crash hatte.**

**Immer während der Fahrt wenn ich einen Gamecrash bekomme und mich dann wieder einlogge, stehe ich an der Werkstatt in der ich zuletzt war.**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by TeubyDE** [comment]
Wie oft ist das vorgekommen? Is es aktuell immer noch so?

**Comment by LadyLeo90** [comment]
Also seit ich wieder da bin (ca. Mitte Februar) mindestens 8 mal gewesen und das letzte mal war gestern ca 19:15.

**Comment by TheOutburst** [comment]
Ich frag mal ganz doof:
wie oft ist das seit April aufgetreten?
1-10
20-50
50-X

@LadyLeo90 @cadpri
