### ISSUE TITLE
Bootswerkstatt - Tugboot passt nicht

### ISSUE THREAD

**Issue by Dean-Gallagher** [eiksch/statev_v2_issues#2319]
**Character Name**
Bootswerkstatt

**Beobachtetes Verhalten**
Tugs sind nicht Reparierbar

**Erwartetes Verhalten**
Tugs wieder Reparierbar

Huhu, ich weis nicht ob es daran liegt das der Punkt zu nahe am Steg ist oder obs am Tug liegt, aufjedenfall haben wirs Tug vorwärs und rückwärts probiert und es passt nicht. 

Grüße

**Comment by Dean-Gallagher** [comment]
Und wie schauts aus?

**Comment by TheOutburst** [comment]
Wurd wohl vergessen.
Hab den Punkt mal 2 Meter nach neben gepackt, jzt lüppts
https://i.imgur.com/7XL3TvL.jpeg
Referenzpunkt: https://i.imgur.com/twwIFFF.jpeg
