### ISSUE TITLE
[CASINO] Blackjack Tisch funktioniert nicht mehr ( Zeigt keine Auswahl mehr an, nur noch Restart möglich )

### ISSUE THREAD

**Issue by LukiiTime** [eiksch/statev_v2_issues#2364]
**Lukii_Time, Yuri_Greene**

**Auftrittszeitpunkt (17.04.2022 / 13.47 Uhr)**

**Beobachtetes Verhalten**
 Es war so, dass wir gesetzt hatten, aber es nach dem Karten legen des NPCs ging es nicht weiter. Man konnte keine Auswahl mehr treffen. Somit musste ein Neustart gemacht werden, nach Neustart habe ich mich wieder an den Tisch gesetzt, und bin All In gegangen und wieder das gleiche Problem. Ich denke auch, dass die nächsten Spieler die an die Tisch keine Möglichkeit haben dort zu spielen, da der NPC nichts mehr anzeigt und das Geld dann weg ist nach dem Relog. Als Orientierung welcher Tisch gemeint ist, sende ich ein Bild zu.

**Erwartetes Verhalten**

->

**Optional: Video / Bilder des Fehlers**

![20220417134653_1](https://user-images.githubusercontent.com/29608434/163713447-ad037450-08c2-405d-8ba0-ebff61af6f8c.jpg)

**Comment by TheOutburst** [comment]
mit diesem Update gefix
