### ISSUE TITLE
Chars stehen aus Sitzposition auf beim Handeln

### ISSUE THREAD

**Issue by onlyPASI** [eiksch/statev_v2_issues#2369]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Anthony_Chegwidden

Anthony_Chegwidden mit z.B. Ben_Hawkins

**Auftrittszeitpunkt (Datum / Uhrzeit)**

16.04.2022 17.00

**Beobachtetes Verhalten**
Wenn ein Char im Restaurant am Stuhl sitzt  (Y -> z.B. Sitzen Aufrecht) und man übergibt dem Char ein Item steht der Char automatisch nach erhalt des Items auf.

**Erwartetes Verhalten**

Um eine Bedienung durch einen Kellner in einem Restaurant zu ermöglichen müssen die Chars natürlich nach der Handelsaktion sitzen bleiben. Bei mehreren Chars an einem Tisch usw. entsteht dadurch jede Menge Chaos was den Spielspaß logischerweise kaputt macht.

**Schritte um den Fehler nachvollziehen zu können**

z.B. im Café Redemption auf einen Stugl sitzen (Y -> z.B. Sitzen Aufrecht) und dann dem Char ein Item übers X Menü (Handel) übergeben.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Hutstaender** [comment]
Ups hab ich lange Zeit übersehn. Ist nun fixed next Update.
