### ISSUE TITLE
Casino - F2/F3 Handy/Tablet rausholen funktioniert nicht mehr

### ISSUE THREAD

**Issue by flogut4e** [eiksch/statev_v2_issues#2374]
Character Name
Lars_Stromberg

Auftrittszeitpunkt (Datum / Uhrzeit)
18.04.2022 - 01:15

Beobachtetes Verhalten
Nachdem man am Tisch aktiv gespielt hat kann das Handy und Tablet mit F2/F3 nicht mehr rausgeholt werden.

Erwartetes Verhalten
F2/F3 funktionieren

Schritte um den Fehler nachvollziehen zu können
Blackjack spielen, danach versuchen das Handy/Tablet rauszuholen

**Comment by M4c-M4ni4c** [comment]
Ist mir auch schon passiert, glaube das kommt wenn man keine jetons mehr hat und vom tisch geschmissen wird. Zumindest war es bei mir so.

**Comment by foggel8** [comment]
Finde ich aber sogar gut. Kannst ja im Casino auch nich einfach mitten in der Runde dein iPad oder iPhone rausholen 😅

**Comment by flogut4e** [comment]
@foggel8 bin ich bei dir, geht aber darum dass das NACH dem zocken aufgetreten ist :)

**Comment by StateV-Jan** [comment]
bei mir auch

**Comment by TeubyDE** [comment]
Das Problem sollte mittlerweile behoben sein, wenn das nicht so ist gerne noch mal melden.

**Comment by Erumeldor** [comment]
Ist immer noch so. 
Todo: Solange verlieren bis keine Jetons. Man wird vom Tisch "geworfen". Danach geht Tablet und Handy nicht.
Man kann sich nochmal hinsetzen, steht automatisch wieder auf, dann gehts wieder.

**Comment by TheOutburst** [comment]
Ursprüngliche Meldung: nach beliebigem Blackjack spielen Handy versuchen rauszuholen, geht nicht
Neue Meldung: nur noch wenn man vom Tisch geworfen wird geht Handy / Tablet nichtmehr

Soweit richitg?

**Comment by Erumeldor** [comment]
Ich weiß leider nicht, wie es anfangs war.

Aber ja, aktuell geht es nur nicht, wenn man vom Tisch aufsteht weil man alle Jetons verloren hat.
Wenn man ohne Jetons hingeht und direkt wieder aufstehen muss, oder freiwillig aufsteht, ist alles okay.

**Comment by SimonPfeifferStateV** [comment]
Problem besteht immer noch...

**Comment by TheOutburst** [comment]
next update fixed! (dieses mal hoffentlich wirklich)
