### ISSUE TITLE
Casino Blackjack bekomm keine Karten

### ISSUE THREAD

**Issue by Teddyrules** [eiksch/statev_v2_issues#2381]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Alexander Hunter

<20.04.2022 00:50
[](url)
**Beobachtetes Verhalten**
Ich wollte n Casino Blackjack spielen konnte setzen bekam, aber keine Karten und habe trotzdem gewonnen, habe es danach auf einem anderen platz versucht alleine und bekam da auch keine Karten und konnte mich auch nicht mehr bewegen und musste Neustarten
![ddd](https://user-images.githubusercontent.com/104039091/164117267-6367a4a8-4926-4cd2-993c-6ea83d11f645.png)
.

**Comment by Marlisediefiese** [comment]
Ich schließe das Ticket, da ich das Problem nicht nachstellen konnte. Sollte aber das Problem wieder auftreten, dann mach gerne wieder einen neuen Bugtracker Eintrag am besten mit einem Clip von der Situation.
