### ISSUE TITLE
Fehler beim BlackJack spielen

### ISSUE THREAD

**Issue by Stiefel911** [eiksch/statev_v2_issues#2407]
**Auftrittszeitpunkt (Datum / Uhrzeit)**
28.04.2022 00:10-20 ca
**Beobachtetes Verhalten**
Am BJ Tisch direkt 4 Karten erhalten an stelle von 2 ... bei den Fünf Spielen waren drei so dabei immer direkt 4 karten bekommen.

**Erwartetes Verhalten**
Beim BJ zu beginn nur 2 Karten bekommen

**Schritte um den Fehler nachvollziehen zu können**
Ran setzten und spielen ;)

**Optional: Video / Bilder des Fehlers**
https://youtu.be/W1gev7IG7V8

**Comment by TheOutburst** [comment]
mit diesem Update gefixt
