### ISSUE TITLE
Ball Unendlich im Inventar.

### ISSUE THREAD

**Issue by TheBroady** [eiksch/statev_v2_issues#2437]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Noah Reese

**Auftrittszeitpunkt (Datum / Uhrzeit)**
13.05.22

**Beobachtetes Verhalten**
Ich kann den Ball unendlich werfen, allerdings geworfene nicht mehr aufheben.
Vor dem Server Crash ging es noch wie gehabt.
Trat erst bei Kiana auf, haben testweise den Ball gehandelt, bei mir gings auch

**Erwartetes Verhalten**
Ball nur 1x Werfen und aufheben können.

**Schritte um den Fehler nachvollziehen zu können**
Derzeit geht es bei Kiana Reese & mir immer.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://youtu.be/u7ac175hJik

**Comment by DonVitoDiangelo** [comment]
War das direkt nach dem Restart? Was hast du davor gemacht? Am besten so genau wie möglich beschreiben.

**Comment by TheBroady** [comment]
> War das direkt nach dem Restart? Was hast du vorm werfen gemacht? Am besten so genau wie möglich beschreiben.

Es war nicht direkt nach dem Restart. Wir haben den Ball ständig hin und her geworfen.
Irgendwann nach ca. 10x konnten wir ihn dann nicht mehr vom Boden aufheben.
teilweise haben wir dann Gegenstände in der Umgebung aufgehoben da wir diese platziert hatten.

Einige Minuten später ist uns dann aufgefallen das Kiana wieder einen Ball im Inventar hatte und haben dann weiter geworfen.
Dort ist dann der Fehler zustande gekommen.
Den Ball hat sie an mich gehandelt, und ich konnte diesen auch mehrfach werfen, ohne das er verschwindet. (siehe Video)

Probiert mal:
• Mit zwei Personen gleichzeitig den Ball aufheben zu wollen
• Nebendran Gegenstände zu Platzieren welche auch aufgehoben werden.

was anderes fällt mir gerade nicht ein.

LG
