### ISSUE TITLE
[SAMMEL-Ticket] Medical Bugs

### ISSUE THREAD

**Issue by DonVitoDiangelo** [eiksch/statev_v2_issues#2438]

**Comment by M4c-M4ni4c** [comment]
Hab das in einem Stream mitbekommen da es bis heute nicht im Bug Tracker gelandet ist, poste ich es mal hier rein.
**Character Name**
Alex Bold(Medic), Josh Korby(Cop)

**Auftrittszeitpunkt (Datum / Uhrzeit)**
14.05.2022 ca 17uhr

**Beobachtetes Verhalten**
Patient wird in einen Buffalo S Police ausversehen verladen

**Erwartetes Verhalten**
Das es nicht möglich ist in einem Buffalo S Police einen Patienten zu entladen

**Optional: Video / Bilder des Fehlers**
https://clips.twitch.tv/SpotlessDeliciousTarsierUWot-csBHL3h_Sjfnpc8E

**Comment by DrGrizzlY17** [comment]
#2547 2494

**Comment by NicoleWitt** [comment]
Vapid Saddler Medic Fahrzeug macht erneut wieder die Klappergeräusche und beim Ausparken vom Fahrzeug in der LSMD Garage von sehr weit oben runter fehlt Vielleicht kommt der schaden von da aus

**Comment by TeubyDE** [comment]
Sammeltickets werden abgeschafft. Sollte noch was offen sein -> neuer Eintrag verfassen
