### ISSUE TITLE
Anschnallstatus bei Hausgaragen

### ISSUE THREAD

**Issue by SHaagmann** [eiksch/statev_v2_issues#2445]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Sven_Rosenbach
**Auftrittszeitpunkt (Datum / Uhrzeit)**

Schon länger aber Clip ist vom 19.05 23:43 Uhr
**Beobachtetes Verhalten**

Wenn man ein fahrzeug in einer Hausgarage einparkt wird man nicht automatisch abgeschnallt
**Erwartetes Verhalten**

Man wird automatisch abgeschnallt wie bei Öffentlichen Garagen
**Schritte um den Fehler nachvollziehen zu können**

Angeschnallt in Hausgarage einparken und wieder ausparken
**Optional: Video / Bilder des Fehlers**

https://streamable.com/3juodw

**Comment by JaxBorrow** [comment]
Selbes gilt Garagen von Fraktionen. Ist problematisch, wenn man danach auf ein Motorrad steigt. Clip vom 30.05.

https://user-images.githubusercontent.com/100872532/171058638-a4f11e91-a485-4e85-a246-5b5abaf1b477.mp4

**Comment by TheOutburst** [comment]
Wurd mit dem letzen Update gefixt
