### ISSUE TITLE
[SAMMEL-Ticket] Tuning Probleme nach alt Update

### ISSUE THREAD

**Issue by MaxwellRicks** [eiksch/statev_v2_issues#2449]
Maxwell Ricks

**21.05.2022 / 02:30 Uhr (Datum / Uhrzeit)**

Nach dem AltV Update habe ich meinen Vapid GT Classic, Kennzeichen "JUDGE 4", aus der öffentlichen Garage am Gericht ausgeparkt und das Motorhaubentuning ist verschwunden.
Getuned wurde das Fahrzeug  am 16.05.2022.

**Erwartetes Verhalten**

Motorhaubentuning wieder so wie vor dem Update.

**Schritte um den Fehler nachvollziehen zu können**

Fahrzeug mehrfach ein und ausgeparkt, Tuning immer noch weg.

**Optional: Video / Bilder des Fehlers**

Tunung vor dem Update: https://pic.statev.de/image/gta5-2022-05-16-22-55-10.UHZ5w

Tuning nach dem Update: https://pic.statev.de/image/vapid-gt-classic-nach-dem-update.UHcrz

**Comment by epichalt** [comment]
Der Auspuff und die vordere Stoßstange sind auch weg oder?

**Comment by MaxwellRicks** [comment]
der Auspuff ändert sich automatisch mit dem Motorblock/Motorhaube.  Ja Front und Heckstoßstange sind auch weg

**Comment by PlayInc89** [comment]
Bevor ich was neues Aufmache beim Feltzer der Standard Spoiler ist weg und Tuning funktioniert bei dem nicht. 
Hier noch link zum Video wo man das fehlerhafte Tuning direkt sieht https://youtu.be/dqmxpfeOPOs

**Comment by SatyriaDine** [comment]
Mein Cypher Kennzeichen: S3RAPH1M hat plötzlich ein rotes Interieur


![20220522093427_1](https://user-images.githubusercontent.com/84275938/169684063-16c5e71f-52a6-49d8-8e51-6869f9410ca7.jpg)
![20220522093349_1](https://user-images.githubusercontent.com/84275938/169684064-c0816b34-13f5-4431-a62c-75b4443de9c1.jpg)

**Comment by powerswissi** [comment]
Kennzeichen TAMPA:

Haube wurde zurückgesetzt 
Frontspoiler
Heckspoiler
Auspuffanlage
Tieferlegung 
Dach


Kennzeichen: V8 Boys

Auspuffanlage
Käfig
Frontstosstange
Frontlippe

**Comment by CaleighRhodes** [comment]
Bravado Buffalo S, LS CR 28

- falsche Haube
- falsches Dach (aktuell: Sekundärfarbe, altes Tuning: Carbon)
- falscher Heckspoiler
- falsche Auspuffanlage
- Frontlippe fehlt

Grotti Carbonizarre, PB CR 19

- falsche Haube
- Außenspiegel nicht mehr in Wagenfarbe

BF Bifta, CALEIGH

- Dach fehlt
- Auspuffanlage falsch
- Spoiler fehlt
- Sportsitze fehlen

Vorher-Nachher-Bilder wären vorhanden.

**Comment by Maximilian63** [comment]
Dinka Blista (OPC) Schürze vorne, schürze Seite, Tieferlegung + huppe ? (hat eine Melodie wo abgespielt wird, glaube das sollte so nicht sein)
Benefactor schwarzer GZUZ187 Frontgrill u. Auspuff
Sandking MADMAX Tieferlegung und Stoßstange vorne

**Comment by nicnoc931** [comment]
**Character Name**
Nico Strunk

**Auftrittszeitpunkt (Datum / Uhrzeit)**
21.05.2022


**Beobachtetes Verhalten**
Tuning nach Altv Update verändert: Bodykit Front
Sand King: 
Kennzeichen: PRISMATO


**Erwartetes Verhalten**
Selbes Tuning wie vor dem Update


**Schritte um den Fehler nachvollziehen zu können**
Vorher nachher vergleich


**Optional: Video / Bilder des Fehlers**
Kann nur ein nachher Vergleichs Bild posten, aber die Überweisung an Gordons vom Tuning.

**Comment by JonnyHart** [comment]
Sandking Kennzeichen: Sandy JH

Front Bullenfänger fehlt

**Comment by RobMccoy** [comment]
Sandking- Kennzeichen: CANUCATCH

Bullenfänger vorn fehlt,Standardgrill wieder montiert,verdeckaufbau ladefläche fehlt-standard wieder montiert

**Comment by PlayInc89** [comment]
Fahrzeuge Mila Valdes
-  Grotti Carbonizzare Kennzeichen MIRYVA = Falsche Motorhaube sollte Serie sein und nicht Carboon
-  Buccaneer Custom Kennzeichen LSBEAUTY = Hat ein Dach hatte vorher kein Dach

**Comment by nox142** [comment]
Sandking: 
Kennzeichen: OFFK1NG
Folgendes Tuning fehlt:
- Frontstoßstange
- Aufbau von der Ladefläche
- Dachspoiler

Yosemite Rancher:
Kennzeichen: S4NDY
Folgendes Tuning fehlt:
- Frontstoßstange

**Comment by powerswissi** [comment]
Nachtrag: All meine Autos (Roger Thickle) haben Xenons verbaut bekommen . 
Diese waren nie montiert

**Comment by SatyriaDine** [comment]
nachtrag: 

Fahrzeug: Coil Cyclone
Kennzeichen: Wrack 18 
Eigentümer: James Ackles

Interieur ist seit dem Update blau und nicht mehr schwarz

**Comment by TamiGaming** [comment]
Fahrzeug: Dinka Jester
Kennzeichen: LS CT 05
Eigentümer: Carlie Tacus
Kein Tuning mehr.

Fahrzeug: Benefactor Schafter V12
Kennzeichen: BLACKY
Eigentümer: Carlie Tacus
Kein Bodykit vorne mehr.

Fahrzeug: Zentorno
Kennzeichen: LS T O6
Eigentümer: Carlie Tacus
Kein Tuning mehr.

Fahrzeug: Futo
Kennzeichen: T1TT3
Eigentümer: Hanna Fields
Kein Tuning mehr.

Fahrzeug: BF Surfer
Kennzeichen: ALOHA
Eigentümer: Carlie Tacus
Kein Tuning mehr.

Fahrzeug: Maibatsu Penumbra
Kennzeichen: LS FN 19
Eigentümer: Carlie Tacus
Schwarzes Dach (vorher weiß)

Fahrzeug: Bifta
Kennzeichen: LS KS 1
Eigentümer: Carlie Tacus
Kein Tuning mehr.

Fahrzeug: Pegassi Ruffian
Kennzeichen: SP 1
Eigentümer: Carlie Tacus
Kein Tuning mehr.

**Comment by JulianMa** [comment]
@its4l3x @DonVitoDiangelo vielleicht ist nur die `vehmods.bin` mal wieder kaputt. Sieht irgendwie danach aus.

**Comment by FarkasCian** [comment]
Sultan (Standard) ohne Kennzeichen
Besitzer: Farkas_Cian

Komplettes Tuning entweder anders oder weg
Zusatz: Clownshupe

**Comment by ProfDuebbi** [comment]
Fahrzeug: Albany Buccaneer
Kennzeichen: GENE LEE
Besitzer: Johnny Martens

Hat wheelie bar hinten, wo keine sein sollte.
Motorhauben tuning fehlt.

**Comment by its4l3x** [comment]
Problem wurde bereits vor ca. 2 Tagen gefunden, sind noch nicht aufgrund zeitlicher Probleme unserseits dazugegeben den Server zu updaten. Es kann noch vereinzelnd zu Problemen mit Interior Farben o.Ä. kommen, dass müssen wir nun aber separat angehen mit einem neuen System leider :/

Zeitlich gesehen wollen wir morgen um 15 Uhr den Fix bringen.

**Comment by cadpri** [comment]
auch wenn der Fehler offensichtlich gefunden ist:

Mein Bifta hat keinen Heckspoiler und Auspuff mehr

**Comment by TheMoonicorn** [comment]
Mamba mit dem Kennzeichen [MRS M] hat einen Überrollkäfig statt Kopfstützen.
Vorher/Nachher Fotos sind vorhanden.

Blista mit dem Kennzeichen [Freya] hat eine andere Hupe

**Comment by MisterGarry** [comment]
Servus, hier

Buffalo S Kennzeichen: SCORPION
Komplett anderes Tuning. (Felgen sind noch gleich)
Bilder vorhanden.

ZR350 Kennzeichen: keins
Bei Frontstoßstange Lippe weg

Asea Kennzeichen R4CE
Leicht anderes Tunning (Auspuff z.B.)

**Comment by simplycach** [comment]
Nach dem Update vom 26.05.2022 (16:53) - bisher anscheinend keine Änderung beim Cypher:

Sitze sind noch nicht aus Carbon und Interior ist noch nicht Schwarz

https://pic.statev.de/image/20220526165207-1.UofuV
https://pic.statev.de/image/20220526165215-1.Uo1Wg
https://pic.statev.de/image/20220526165217-1.UoCjS

**Comment by its4l3x** [comment]
Das wegen der Interior Farbe. Wir müssen da unser System umcoden und auch umbauen. Ihr müsst dann das Fahrzeug nochmal neu "tunen".

**Comment by its4l3x** [comment]
@PrimroseBloom Weißt du welchen Tuning Slot das Auto nutzt für das Dach?

**Comment by simplycach** [comment]
> Das wegen der Interior Farbe. Wir müssen da unser System umcoden und auch umbauen. Ihr müsst dann das Fahrzeug nochmal neu "tunen".

Ist dies schon geschehen oder passiert gerade ? Und denke mal wir werden das dann auch nochmal bezahlen müssen richtig ?

**Comment by l4m4rr224** [comment]
> Das wegen der Interior Farbe. Wir müssen da unser System umcoden und auch umbauen. Ihr müsst dann das Fahrzeug nochmal neu "tunen".

Lass mich raten und dazu zählt z.b der Schlagen GT auch? Weil der hatte auch mal schwarzes Interior

**Comment by PrimroseBloom** [comment]
> @PrimroseBloom Weißt du welchen Tuning Slot das Auto nutzt für das Dach?

Man kann an dem Dach nichts machen. Es war vorher in Sekundär Farbe und jetzt ist es aus Stoff und nicht Änderbar.

**Comment by thumbsucker** [comment]
Denke auch das zählt als folge Problem:

Beim tunen steht 1x Xenon auf der Rechnung obwohl nur das Dach bzw. Folie verändert wurde.

Beobachtet bei meiner Coquette (Kennzeichen: Coquette) und meinem Dominator GTT (Kennzeichen: Reckless)

Bei meinem Rapid GT Classic erschien allerdings kein Xenon auf der Rechnung als ich dort testweise die Folie weg machen wollte. Es scheint also nicht alle zu betreffen.

**Comment by SatyriaDine** [comment]
Pfister 811 

Kennzeichen: VIENETTA 
Eigentümer: James Ackles

hat immer noch nen Dach. 

![20220526201608_1](https://user-images.githubusercontent.com/84275938/170550908-eb6d097f-cd0a-43c3-99f0-dc1fe5b9e0cf.jpg)

**Comment by thumbsucker** [comment]
Nachtrag zum Thema Xenon: 

Wird leider auch beim tunen eines neuen PD Autos bei jedem Teil das man anbringen möchte auf der Rechnung angezeigt (und die Vergangenheit zeigt das es dann auch abgezogen wird). Somit ist es derzeit bei einigen Autos derzeit fast unmöglich zu tunen da der Verlust nur bis zu einem gewissen Punkt aufgefangen werden kann. (Man könnte nun alles am Stück tunen aber das löst das Problem auch nur dann wenn beim Tuning auch Xenon Lichter inbegriffen sind. Sonst hat man dennoch min 1x Xenons verloren)

**Comment by powerswissi** [comment]
Thema Xenon : 
Die Muscle Cars die ich habe sind wieder normal getuned

Bis auf eine Sache: Alle Fahrzeuge die ich besitze haben Xenons

**Comment by PlayInc89** [comment]
Nach dem Update
 
- Buccaneer Custom Kennzeichen LSBEAUTY = Hat immernoch ein Dach sollte eig. kein Dach haben !

**Comment by Dean-Gallagher** [comment]
Jester RR 
Tuning vertauscht -> Scheinwerfer <-> Kotflügel Extra 2

**Comment by PlayInc89** [comment]
Jester RR Interior ist Rot statt Schwarz
![falsches interrior](https://user-images.githubusercontent.com/70231715/171166468-e8360028-0e0e-4dca-8c90-a3b68c4ec741.jpg)

**Comment by JasminHarper** [comment]
Manana Custom
Kennzeichen: LS 420
Besitzer: Jacob Walker
Dach war vorher Sekundär Farbe Lackiert, ist jetzt mit dem Update nen schwarzes Stoff Dach (Fotos von vorher / nacher)

![G1eiq-lzTfqJz7-NaMpg0A](https://user-images.githubusercontent.com/74868934/172663650-bb1925b5-cd47-4248-a0f2-dfb1643a93dd.png)
![Grand Theft Auto V Screenshot 2022 06 08 - 17 16 01 49](https://user-images.githubusercontent.com/74868934/172663702-67be8107-118d-40dc-aa91-bb87b2cb26c8.png)

**Comment by Ekaz58** [comment]
Jester RR Kennzeichen " XXXXXX " 
 Vorher Schwarzes Interieur , jetzt ein Rotes.

**Comment by SatyriaDine** [comment]
Banshee 900R 

Kennzeichen: Wrack 31

Hat seit dem AltV Update kein Dach mehr

Jetzt Zustand:
![20220716131345_1](https://user-images.githubusercontent.com/84275938/179353187-ea0a5cd0-2833-4a0f-af4a-bed37bd827c6.jpg)

Zustand vorm AltV Update:
![20220207195218_12](https://user-images.githubusercontent.com/84275938/179353475-d81c3e78-e233-4de0-bb0c-560127591ac5.jpg)

Bei der normalen Banshee ist wie ich erfahren habe das Gleiche aufgetreten.

**Comment by PrimroseBloom** [comment]
@its4l3x Weiß man jetzt was beim Manana Custom los ist? Wird das noch behoben?

**Comment by TeubyDE** [comment]
Wir erarbeiten gerade noch eine nachhaltige Lösung. Das wir das alles zusammen in den Griff bekommen.

**Comment by PlayInc89** [comment]
Find ich gut... Vorallem die Roten Interrios sind halt nervig zumindest im Jester RR und Cypher. Naja mal schauen wie das Update von GTA selbst euch in die Suppe spuckt.

**Comment by TeubyDE** [comment]
Vielen Dank für den ganzen Input!

Wir könnten heute eine Lösung fertigstellen die beim nächsten Update kommen wird.
PS: Ist mmn nen cooles Feature geworden und nicht nur nen Bugfix. <3

**Comment by TheOutburst** [comment]
Durch Extra Tuning nun IC lösbar

**Comment by PrimroseBloom** [comment]
@TeubyDE @TheOutburst Beim Manana Custom ist das Dach immer noch nicht richtig und auch nicht veränderbar. Das Dach ist zwar nicht mehr schwarz aber in Primär Farbe und ursprünglich sollte es in Sekundär Farbe sein.
