### ISSUE TITLE
Mehr als drei kostenlose Schlüssel

### ISSUE THREAD

**Issue by JaxBorrow** [eiksch/statev_v2_issues#2460]
**Character Name**
Jax Borrow

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Leider weiß ich nicht mehr, wann ich den letzten Schlüssel vergeben habe aber mir ist es eben erst aufgefallen, dass da kein $-Symbol ist

**Beobachtetes Verhalten**
Es ist ein 4. Schlüssel für meinen Speeder vergeben, welcher keine Gebühren gekostet hat.

**Erwartetes Verhalten**
Dass ab dem 4. Schlüssel 150$ gezahlt werden müssen, und dies im Handy durch das Dollar-Symbol ersichtlich ist

**Schritte um den Fehler nachvollziehen zu können**
Möglicherweise bei einem Speeder mehrere Schlüssel vergeben. Wenn gewünscht kann ich gerne die Tage nochmal versuchen es zu reproduzieren (dann mit einem Video)

**Optional: Video / Bilder des Fehlers**

![Grand Theft Auto V Screenshot 2022 05 24 - 18 04 07 30](https://user-images.githubusercontent.com/100872532/170096158-75c58c26-d66d-40fa-a838-20dfe3f30742.png)

**Comment by TeubyDE** [comment]
Einzelfall, lässt sich weder reproduzieren noch nachvollziehen.
