### ISSUE TITLE
Einbruchsystem

### ISSUE THREAD

**Issue by WilliamWalles** [eiksch/statev_v2_issues#2476]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**William Walles**

 Mit dem oben genannten
**Auftrittszeitpunkt (Datum / Uhrzeit)**

07.06.2020 gegen 12 Uhr
**Beobachtetes Verhalten**

Auftrag bei little Toby angenommen aber keine push Benachrichtigung bekommen
**Erwartetes Verhalten**

Push Benachrichtigung hätte erfolgen müssen
**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by TeubyDE** [comment]
Ist das Problem einmalig aufgetreten oder bekommst du generell keine Benachrichtigung?
Wie lange hast du gewartet ?

**Comment by DonVitoDiangelo** [comment]
@WilliamWalles

**Comment by LautaroTesto** [comment]
Moin, 

ich hatte schon öfters auch das Problem.

Ich bekomme kein nach Auftragsannahme keine Push für ein Standort. Die Mission läuft aber noch und kann den Auftrag nicht abbrechen oder ein anderen wählen. Es muss bis Serverrestart gewartet werden.

Es ist bestimmt schon 4-5x aufgetreten

**Comment by WilliamWalles** [comment]
Das ist schon öfters passiert und nicht nur bei mir

**Comment by WilliamWalles** [comment]
Und gewartet hab ich 15min und normalerweise bekomme ich die benachrichtigung

**Comment by UNDRCVRR** [comment]
#2608

**Comment by UNDRCVRR** [comment]
#2637

**Comment by JohnRappStateV** [comment]
> tte schon öfters auch das Problem.
> 
> Ich bekomme kein nach Auftragsannahme keine Push für ein Standort. Die Mission läuft aber noch und kann den Auftrag nicht abbrechen oder ein anderen wählen. Es muss bis Serverrestart gewartet werden.
> 
> Es ist bestimmt schon 4-5x aufgetreten

ist bei mir genau so gestern und heute auch passiert.

**Comment by Parityisreal** [comment]
> 
Jup, bei mir heute auch. Vor dem 15 Uhr Restart und danach direkt beim Ersten Auftrag kam kein Push Standort.

**Comment by UNDRCVRR** [comment]
#2671

**Comment by JohnRappStateV** [comment]
Erneutes Problem mit Lil Toby :( Habe gestern Abend einen Auftrag erhalten: Ein Hausbesitzer ist gerade nichts zuhause, das solltest du ausnutzen!; Habe diesen abgearbeitet und erfolgreich erledigt. Ein bisschen später hat ein Kollege den gleichen Auftrag angenommen, es war das gleiche Haus - wir mussten 2x einbrechen, konnten aber beide nicht looten - es gab keine Marker, die Tür war aber offen
Der Job ist jetzt auch stuck beim Kollegen.

**Comment by Erumeldor** [comment]
Problem ist noch da. Keine Benachrichtigung bekommen, 30min später sagt er ich hab einen Auftrag offen.

**Comment by simplycach** [comment]
Ist der Fehler noch aktuell, wenn ja wäre gut zu wissen um welchen Auftrag es sich handelt ?

**Comment by Parityisreal** [comment]
@simplycach Ja der Fehler ist immer noch aktuell, bei mir kommt oft keine Push-Benachrichtigung bei folgenden Aufträgen:
-> Ein Hausbesitzer ist gerade nichts zuhause, das solltest du ausnutzen!
-> Ein Hausbesitzer hat Ware bei sich zuhause rumliegen, die ich benötige.

Von anderen habe ich aber gehört, dass sie dasselbe Problem mit ganz anderen Aufträgen haben.
Des Weiteren bekommt man auch keine Push-Benachrichtigung, wenn man den Auftrag annimmt und die Sim Karte wechselt.
