### ISSUE TITLE
kleine Friseur-Bugs

### ISSUE THREAD

**Issue by CaleighRhodes** [eiksch/statev_v2_issues#2480]
**Character Name**
Caleigh Rhodes

**Auftrittszeitpunkt (Datum / Uhrzeit)**
11.06.2022 - 11:28 Uhr

**Beobachtetes Verhalten**
Frisur Kurzer Bob:
- muss eine falsche Beschriftung sein, sind lange Locken mit Knubbeln auf dem Kopf
- ist zwei Mal drin (einmal recht weit vorne, einmal recht weit hinten)

![bob1](https://user-images.githubusercontent.com/74977218/173182611-515c9c6e-67fb-4e96-b7e4-ed5ee08ea02c.jpg)

Twintails wurden angezeigt ohne Materialverbrauch:

![cutted](https://user-images.githubusercontent.com/74977218/173182661-16c3048a-ca11-4105-a89c-0f8eb6ba726b.jpg)

Kundin hat eigentlich eine andere Frisur (kein Materialverbrauch wird ja immer nur bei der schon vorhandenen Frisur angezeigt). Nach dem Schneiden und wieder hinsetzen wurde aber wieder Materialverbrauch angezeigt.
Dafür wurde nach dem Schneiden dann auf einmal der Cornrow-Iro, der als aktuelle Frisur angezeigt wird obwohl die Kundin den Cleo Bun hat, wieder ohne Material angezeigt - zusätzlich zum Cleo Bun. Scheinbar "überlappen" sich hier Frisuren.

(Falls das komisch erklärt ist, sagt mir einfach Bescheid, kann das auch gern im TS erklären)

**Erwartetes Verhalten**
Kurzer Bob umbenennen und Dopplung entfernen oder entsprechende vorgesehene Frisur einfügen. Richtige Frisur bei Kunden hinterlegt und nicht zwei Frisuren in der Auswahl, die ohne Materialkosten geschnitten werden könnten.

**Schritte um den Fehler nachvollziehen zu können**
Friseurmenü öffnen und die entsprechenden Frisuren auswählen

**Comment by Enemyaa** [comment]
Mein Job hab ich hier erledigt @DrGrizzlY17 Es gibt nach wie vor immer 1-2 Frisuren die kein Material verbrauchen. Immer wieder neue

**Comment by DrGrizzlY17** [comment]
Hat etwas gedauert, aber fixed next Update.

Aber bitte beobachtet es weiter :)
