### ISSUE TITLE
Levi's Jeansjacke (der richtige Torso fehlt)

### ISSUE THREAD

**Issue by PaxPaxton** [eiksch/statev_v2_issues#2482]
**Character Name**
Jake_Paxton

**Auftrittszeitpunkt (Datum / Uhrzeit)**
15.06.2022 / 17:00 Uhr

**Beobachtetes Verhalten**
Wie man unten auf den Bildern sieht gibt es keinen passenden Torso bei der Levi's Jeansjacke. Hab jeden Torso ausgewählt aber keiner passt.

**Erwartetes Verhalten**
passender Torso.

**Schritte um den Fehler nachvollziehen zu können**
Torso-Menü öffnen und jeden Torso mal auswählen.

**Optional: Video / Bilder des Fehlers**

![pic 1](https://user-images.githubusercontent.com/107564967/173862801-6f9f05d1-4b4e-44c9-a432-b2c08e2f9453.png)

![pic 2](https://user-images.githubusercontent.com/107564967/173862831-65356e55-a558-4fcc-9eec-f52652eaae65.png)

**Comment by Stiefel911** [comment]
geht es dir um das dunkle an der Jacke links? Wenn ja liegt es aber nicht am Torso, sondern an der Jacke selber ;)
