### ISSUE TITLE
Vapid Saddler Medic Fahrzeug

### ISSUE THREAD

**Issue by NicoleWitt** [eiksch/statev_v2_issues#2487]
## WICHTIGE INFORMATION!!:
 
Bitte um Schnellen Hotfix da das sehr Nervig ist auf dauer 

**Nicole Witt **

**Auftrittszeitpunkt (Datum / Uhrzeit)**

16:24 21.06.22

**Beobachtetes Verhalten**

 Vapid Saddler beim Rollen lassen klimper-Geräusche als wäre der Motor oder irgendetwas Kaputt oder als würde das Blech irgendwo jedes mal gegen klappern
Nach dem Reparieren ist alles normal keine Geräusche aber sobald man ihn einmal eingeparkt hat und wieder rausholt wieder das selbe Problem 

**Erwartetes Verhalten**
Bei heilen zustand sollte der Vapid Saddler seine ganz normalen Ausroll geräusche machen bzw. nur das schalten und die normalen Motor geräusche

**Schritte um den Fehler nachvollziehen zu können**
Man versucht das Fahrzeug auf 60 std km oder mehr zu bringen und lässt ihn ganz normal ausrollen, beim Ausrollen kommen dann diese Knister oder Klapper geräusche ab und zu sehr Laut teils auch leiser aber hörbar

**Optional: Video / Bilder des Fehlers**
https://youtu.be/oBgma81Uvoo

**Comment by NicoleWitt** [comment]
Es war einmal Komplett weg und jetzt geht es wieder von vorne Los :/

**Comment by DrGrizzlY17** [comment]
#2438 schließe es erstmal und nehme es mit in den sammelthread auf
