### ISSUE TITLE
LSMD Tragesystem und Wasserunfälle

### ISSUE THREAD

**Issue by SvenPhoenix** [eiksch/statev_v2_issues#2489]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Sven Phoenix**

**22.06.2022 22 Uhr**

**Patient schwebt komisch in der Luft nach dem er ertrunken und auf die Trage geladen wurde.**

**Patient soll so´wie normal auch auf der Trage (und im Fahrzeug) liegen**

**Man benötigt eine Bewusstlose Person welche ertrunken ist. Dann zieht man die aus dem Wasser und stabilisiert sie. Anschliesend legt man sie auf die Trage (und dann ins Fahrzeug... In meinem Fall war es der Vapid Contender)**

**Bilder des Fehlers**

![Grand Theft Auto V Screenshot 2022 06 22 - 22 19 08 42](https://user-images.githubusercontent.com/78278616/175134527-35f9e47c-bd93-470d-aa2e-5a782811a9e2.png)
![Grand Theft Auto V Screenshot 2022 06 22 - 22 19 20 78](https://user-images.githubusercontent.com/78278616/175134645-63805a97-b137-473b-837f-f0d4a6015ca2.png)

**Comment by DrGrizzlY17** [comment]
#2438 ich schließe es erstmal und nehme es mit in den sammelthread
