### ISSUE TITLE
Casino - Karten liegen noch auf dem Tisch

### ISSUE THREAD

**Issue by Erumeldor** [eiksch/statev_v2_issues#2491]
**Character Name**
Satoru_Tsuyoshi

**Auftrittszeitpunkt (Datum / Uhrzeit)**
26.06 - 00:05

**Beobachtetes Verhalten**
Auf dem Tisch liegen sowohl an meinem Platz, als auch beim Dealer noch Karten. Diese gehen während dem Spiel, als auch danach auch nicht weg. Die "neuen" Karten werden einfach auf die selbe Position gelegt - Tisch ist quasi unbrauchbar.

**Erwartetes Verhalten**
Karten sind weg.

** Bilder des Fehlers**
![image](https://user-images.githubusercontent.com/21212905/175791819-308349e2-f14b-42c1-9786-b3e3f6646a05.png)

**Comment by TheOutburst** [comment]
mit diesem Update gefixt
