### ISSUE TITLE
Zu harter Kontakt zwischen MD Fahrzeugen und Patienten auf Tragen

### ISSUE THREAD

**Issue by Pregon** [eiksch/statev_v2_issues#2494]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Ronny Roberts

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Aufgefallen mit den neuen MD Fahrzeugen generell

**Beobachtetes Verhalten**
Patienten auf der Trage stoßen die MD Fahrzeuge weg

Zusatzinfo: Andere Leute sehen das nicht (Vermutung) und der schaden ist nur visuell bis man neu zum Fahrzeug läuft nachdem man aus dem Blickfeld entfernt hat

**Erwartetes Verhalten**
Fahrzeuge stehen stabil beim Beladen von Personen über die Trage

**Schritte um den Fehler nachvollziehen zu können**
Mit Trage vor dem MD-Fahrzeugen "hin und her wackeln"

**Optional: Video / Bilder des Fehlers**

https://user-images.githubusercontent.com/75855042/175829057-b4913f18-1654-4a4d-9d1e-db532c4cfedc.mp4

**Comment by quotenben** [comment]
@TeubyDE Nein, siehe https://www.youtube.com/watch?v=ZunwX0mjj94 . Patient war nicht bewusstlos und niemand saß im Helikopter.

**Comment by Pregon** [comment]
@TeubyDE Auch bei mir war nicht der Fall dass jemand mit im Fahrzeug saß.
Ich war zu dem Zeitpunkt allein Unterwegs.

**Comment by DrGrizzlY17** [comment]
@TeubyDE hab es jetzt mal getestet. Egal ob collision enable oder nicht, fixedrot an oder aus. Die collision entsteht trotzdem. Ich würd sagen das der attachTo die collision broke ist
