### ISSUE TITLE
R - Taste (Kinokamera) im Auto funktioniert nicht

### ISSUE THREAD

**Issue by SatyriaDine** [eiksch/statev_v2_issues#2505]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Sofia_Black

**Auftrittszeitpunkt (Datum / Uhrzeit)**
zuerst aufgefallen am: 08.07.2022

**Beobachtetes Verhalten**
Normalerweise kann man während der Fahrt in einem Fahrzeug R drücken, was die Kinokamera aktiviert.  Und so schöne Kamerafahrten während der Fahrt möglich macht. Siehe angehangenes Video.
Nun passiert beim drücken der R Taste nichts. 
(Bereits auf einem Sandbox AltV Server getestet dort funktioniert die R Taste) 

**Erwartetes Verhalten**
Dass beim Drücken der R Taste die Kinokamera aktiviert wird

**Schritte um den Fehler nachvollziehen zu können**
In ein Fahrzeug setzen. Als Fahrer oder Beifahrer und fahren und R drücken

**Optional: Video / Bilder des Fehlers**
https://www.youtube.com/watch?v=rl13hUzHHkE

**Comment by TeubyDE** [comment]
@TheOutburst bitte einmal gegen testen aufm dev.
