### ISSUE TITLE
Möbel bleiben optisch bestehen nach Abbau

### ISSUE THREAD

**Issue by CaleighRhodes** [eiksch/statev_v2_issues#2507]
**Character Name**
Caleigh Rhodes, Maxwell Ricks

**Auftrittszeitpunkt (Datum / Uhrzeit)**
11.07., ca. 19:30 Uhr
12.07., ca. 08:30 Uhr

**Beobachtetes Verhalten**
Platzierte Objekte sollten wieder abgebaut werden. Trotz mehrfachem Drücken von . UND der Tatsache, dass sich die Objekte dann schon im Inventar befanden, blieben diese stehen. In unserem Fall war es erst ein Camping-Tisch, dann ein Pavillon. Ein Objekt befand sich jeweils schon in unserem Inventar, stand faktisch im Spiel aber noch vor uns, inklusive Collision. Erst, wenn man die Range weeeeeeeeit verlassen hat und wieder zurück kommt, ist das Objekt weg.
Kurioserweise betrifft der Bug immer nur das erste Objekt von mehreren, das man platziert hat.

**Erwartetes Verhalten**
Objekt wird auch optisch abgebaut.

**Schritte um den Fehler nachvollziehen zu können**
Mehrere Objekte aufbauen, dann wieder abbauen, zuerst platziertes Objekt bleibt optisch stehen, wird faktisch aber abgebaut und in der Tasche angezeigt.

**Comment by TamiGaming** [comment]
Die Ansicht was das betrifft ist auch von Spieler zu Spieler unterschiedlich. 
Bei manchen ist das Objekt weg, bei anderen nicht.

**Comment by TeubyDE** [comment]
@CaleighRhodes ist das Problem nach dem heutigen Hotfix immer noch vorhanden?

**Comment by CaleighRhodes** [comment]
> @CaleighRhodes @TamiGaming ist das Problem nach dem heutigen Hotfix immer noch vorhanden?

Gucke nach, sobald ich mal wieder IC bin. Derzeit etwas schwierig wegen OOC-Kram, weißte ja, kennste ja. Ich informiere dich.

**Comment by CaleighRhodes** [comment]
@TheOutburst @TeubyDE Fehler besteht leider noch:

![20220814181044_1](https://user-images.githubusercontent.com/74977218/184545570-41efc126-30f3-438b-a535-a01141ad1190.jpg)

Wie zu sehen: Zelt ist im Inventar, aber leider auch noch optisch auf dem Berg.
