### ISSUE TITLE
Terrys Shop funktioniert nicht richtig

### ISSUE THREAD

**Issue by Humperrrt** [eiksch/statev_v2_issues#2510]
**Character Name**
Jaden_Pole

**Auftrittszeitpunkt (Datum / Uhrzeit)**
18.07.2022/17:10

**Beobachtetes Verhalten**
Terry zeigt keinen Job mehr an und bei abgeben einer Geldkassette kommt die Meldung, dass die Kosten (oder so) nicht korrekt berechnet werden konnten. 

**Erwartetes Verhalten**
Terrys Shop sollte immer angezeigt werden & die Kassetten sollten korrekt angerechnet werden.

**Schritte um den Fehler nachvollziehen zu können**
Terry eine Geldkassette abgeben, sollte kein Shop bei ihm zu sehen sein.

**Comment by UNDRCVRR** [comment]
@Humperrrt Sorry für die späte Antwort.

Ich habe versucht das Problem auf unserem Test-Server nachzustellen und konnte keine Probleme feststellen. Vielleicht handelte es sich hier bei um einen einmaligen Fehler. Sollte das Problem erneut auftreten, dann öffne dieses Ticket bitte wieder oder erstell ein neues. Es wäre schön, wenn du dann  eine Videoaufnahme dazu hättest, damit wir das besser nachstellen können.

Danke dir für's reporten!
