### ISSUE TITLE
Vapid Scout Police kann nicht verschrottet werden

### ISSUE THREAD

**Issue by flogut4e** [eiksch/statev_v2_issues#2513]
Character Name

Lars_Stromberg
Auftrittszeitpunkt (Datum / Uhrzeit)

20.07 21:35
Beobachtetes Verhalten

Der Vapid Scout Police kann nicht verschrottet werden. (Unknown Receipt)

Schritte um den Fehler nachvollziehen zu können

Scout am RC Hof versuchen zu verschrotten

**Comment by TheOutburst** [comment]
Greetings @flogut4e ,
was für ein Kennzeichen hat dieser Scout? Vermutlich war das einer der ersten produzierten neuen Scouts, da hatten wir ein kleineres Problem was bei den später produzierten Scouts gefixt ist. Wenn dem so ist müssen wir dieses Auto leider administrativ löschen, deswegen zur Versicherung das KZ

**Comment by flogut4e** [comment]
Hallo @TheOutburst 
SAPD S38 ist das aktuelle Kennzeichen. Kann aber leider nicht sagen welche Motorisierung das Teil hat, könnte durchaus noch einer mit 136 PS sein.

**Comment by TheOutburst** [comment]
@flogut4e 
Probierts nochmal bitte, haben evtl ne Lösung gefunden.
Bitte Feedback, obs geklappt hat

**Comment by flogut4e** [comment]
@TheOutburst sorry für die späte Rückmeldung - klappt jetzt!
