### ISSUE TITLE
Nutzbare Objekte schweben / werden falsch angezeigt

### ISSUE THREAD

**Issue by Domeex3** [eiksch/statev_v2_issues#2516]
Char: Domenik Sommer

Nach dem neuen AltV Update, wenn man das Tablet rausholt, wird dieses im rücken des Chars "gespawnt" und bleibt an der Position hängen, an der man F2 gedrückt hat, der Char hält ebenfalls kein Tablet in der Hand.

Selbes passiert mit Essen/Trinken/Fernglas etc.

![Download (4)](https://user-images.githubusercontent.com/70150715/181071233-a53da668-68f8-477e-8e6a-a01bcccc3146.png)

**Comment by Hutstaender** [comment]
Müssen leider abwarten und Tee trinken :)

**Comment by DrGrizzlY17** [comment]
Broken Attach native von altV

**Comment by TeubyDE** [comment]
mit dem heutigen Hotfix fixed
