### ISSUE TITLE
Autos Schieben Verbugt 

### ISSUE THREAD

**Issue by KendrickWhite1** [eiksch/statev_v2_issues#2517]
**Kendrick White**

 Maxwell Torrey 

**Auftrittszeitpunkt (Datum / Uhrzeit)**
 26.07 / 19.40 Uhr CA

**Beobachtetes Verhalten**
 Autos Schieben Person bleibt stehen Auto bewegt sich und kann nicht abgebrochen werden ( aufgefallen bei Schafter )

**Erwartetes Verhalten**
 das die Person das Auto ordentlich schiebt und auch abbrechen kann 

**Schritte um den Fehler nachvollziehen zu können**
 Schafter Komplett kaputt machen und dann Schieben

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
 ganz normal alles 

**Optional: Video / Bilder des Fehlers**
 leider keins zur verfügung

**Comment by Hutstaender** [comment]
Müssen leider abwarten und Tee trinken :)

**Comment by DrGrizzlY17** [comment]
Gleiches Problem wie bei #2516 somit mal als duplicate geschlossen. Sollte fixed sein wenn altV patched
