### ISSUE TITLE
Objecte stucken in der Luft (verschwindet bei Ausloggen)

### ISSUE THREAD

**Issue by EaselWeasel** [eiksch/statev_v2_issues#2518]
Hier das Bild:
https://pic.statev.de/image/schirme.dTfK0

Funktioniert mit sehr vielen Items, habe noch nicht getestet wie andere Spieler das sehen.
Funktioniert auch außerhalb der Firma.

Nach Relog waren die Objekte verschwunden, weiß nicht ob es nur eine Art "Sync Fehler" ist.

Replizierbar: Gegenstand nutzen, Weg legen, Schritt weiter, Neu Nutzen, Tada 2 Regenschirme.

PS: Sorry fürs etwas zu ausgiebige Testen

**Comment by Hutstaender** [comment]
Müssen leider abwarten und Tee trinken :)

**Comment by DrGrizzlY17** [comment]
#2516
