### ISSUE TITLE
Weiße Chucks Low haben Socken mit Hellblauer Skinny Jeans Männer

### ISSUE THREAD

**Issue by quotenben** [eiksch/statev_v2_issues#2519]
**Character Name**
Ben_Hawking

**Auftrittszeitpunkt (Datum / Uhrzeit)**
26.07.2022 22:00

**Beobachtetes Verhalten**
Weiße Chucks Low haben bei Hellblauer Skinny Jeans Socken

**Erwartetes Verhalten**
Weiße Chucks Low haben bei Hellblauer Skinny Jeans keine Socken

**Schritte um den Fehler nachvollziehen zu können**
Weiße Chucks Low und Hellblaue Skinny Jeans für Männer anziehen. Mit der blauen Skinny Jeans, used war es jedoch nicht so. Andere Hosen und andere Chucks Low Varianten konnte ich nicht testen.

**Optional: Video / Bilder des Fehlers**
![Screenshot_243](https://user-images.githubusercontent.com/66183993/181111206-302ac4c4-0970-4d7c-a1ea-00258c305469.png)

**Comment by Enemyaa** [comment]
Alle Chucks low haben Socken. So sieht das Modell aus. Wenn du das nicht sooo schön findest, wobei es echt schööön aussieht, kann ich nur die Converse High empfehlen. :)

**Comment by quotenben** [comment]
@Enemyaa Ja, ich habe gerade selber gemerkt, dass die Anfrage schlecht formuliert war. Es geht darum, dass bei dieser Kombination die Socken so weit hoch gehen, was ansonsten bei anderen Hosen bzw. vor dem altV Update nicht der Fall war.

**Comment by Enemyaa** [comment]
Dann liegts vielleicht auch an AltV. Ich kann da leider nichts mehr ändern.
