### ISSUE TITLE
Telefon und Tablet werden nicht richtig weggesteckt

### ISSUE THREAD

**Issue by Mondmadchen** [eiksch/statev_v2_issues#2520]
**Character Name**
Jenny Romeo

**Auftrittszeitpunkt (Datum / Uhrzeit)**
27.07.2022

**Beobachtetes Verhalten**
Beim wegstecken des Telefons und des Tablets verschwinden diese nicht sondern bugen sich in der Luft fest oder fallen zu Boden.

**Erwartetes Verhalten**
Telefon und Tablet  werden weggesteckt und verschwinden ohne runterzufallen oder in der Luft hängen zu bleiben.

**Schritte um den Fehler nachvollziehen zu können**
Telefon oder Tablet herausnehmen und wieder wegstecken

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
/

**Optional: Video / Bilder des Fehlers**
https://youtu.be/SLuuVV66jsk
https://youtu.be/sZ1VeS-aJT0

**Comment by DrGrizzlY17** [comment]
#2516
