### ISSUE TITLE
Trailer Large verschwindet, wird in Garage geortet und taucht plötzlich wieder auf

### ISSUE THREAD

**Issue by JaxBorrow** [eiksch/statev_v2_issues#2521]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Jax Borrow**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
27.07.2022 zirka 2:25Uhr

**Beobachtetes Verhalten**
Ich bin mit meinem Barricks nochmal zur Mine gefahren, wo mein Trailer Large auch noch stand. Einmal reingelaufen, um die letzten 50kg Kupfer zu machen. Beim wieder aus der Mine rauskommen war der Trailer weg, aber der Barricks noch da.
Eine Ortung über das Tablet ergab, dass der Trailer in der Harmony Garage geparkt sein sollte. Auf dem weg dorthin erschien der Trailer plötzlich hinter dem LKW und verursachte einen Unfall. (Im angehängten Video ersichtlich)

**Erwartetes Verhalten**
Dass der Trailer nicht verschwindet (ausgenommen Serverrestart) und wie gewohnt angehängt ist.

**Schritte um den Fehler nachvollziehen zu können**
Leider habe ich keine Idee, wie man dies reproduzieren kann

**Optional: Video / Bilder des Fehlers**
Video ist leider zu groß zum anhängen, deshalb hier der Link zu der Datei in meinem Drive:
https://drive.google.com/file/d/1RmranPW2oVQy-UeyzN1m8jeA_08e8Gut/view?usp=sharing

**Comment by TeubyDE** [comment]
Ich Close diesen Eintrag erst einmal. Der Eintrag ist aus Zeiten wo generell Probleme herrschten. Ist nicht nachstellbar für uns.
