### ISSUE TITLE
Canis Mesa Dach fehlt!

### ISSUE THREAD

**Issue by ManuelLadner** [eiksch/statev_v2_issues#2523]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Manuel_Ladner**

**Jederzeit**

**Canis Mesa hat kein vollständiges Dach mehr (Bilder anbei!)**

**sollte wie Vorher ein Dach haben**

**ausparken, anschauen = ) **

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![20220727194630_1](https://user-images.githubusercontent.com/77968842/181335281-ce9db76a-b903-414f-a560-353f03c7370f.jpg)
![20220727194635_1](https://user-images.githubusercontent.com/77968842/181335509-6afcfc34-b0d7-4aa2-84ed-e92bdc6edf23.jpg)
![20220727194641_1](https://user-images.githubusercontent.com/77968842/181335669-1a2a3254-9591-4fc4-869b-4f423884671c.jpg)

**Comment by TheMoonicorn** [comment]
Ich glaube, ich habe dein fehlendes Dach bei dem kleinen Mesa gefunden, der eigentlich kein Dach hat 😅

https://pic.statev.de/image/20220727200231-1.dtH4A

**Comment by ManuelLadner** [comment]
hahah jaaa krass! Hoff avber das das wieder geändert wird!

**Comment by TeubyDE** [comment]
Hat vermutlich mit diesem Fehler zu tun https://github.com/eiksch/statev_v2_issues/issues/2449
Wir sind hier dran, habe mittlerweile eine Lösung erarbeitet, muss noch finalisiert werden!
