### ISSUE TITLE
Bug IM Fahrzeug beim Verwenden des X- Menüs

### ISSUE THREAD

**Issue by LeTzIGameZz** [eiksch/statev_v2_issues#2524]
Jenny Milsa
Ich habe folgendes Problem mit meinem Char: Sobald ich IN einem Fahrzeug Sitze und das X- Menü nutzen möchte um ein Fahrzeug beispielweiße Ab zuschließen oder den Motor zu Starten,  fliege ich sofort aus dem Game. Von außen kann ich die Fahrzeuge ab sowie aufschließen.

Aufgefallen ist es mir nach dem Update am 26.07.2022 Abends gegen ca 21 Uhr.

**Comment by Stiefel911** [comment]
Ich häng das mal hier mit dran!

Wenn ins Fahrzeug eingestiegen wird, wird beim schließen der Tür von außen geschloßen. klingt komisch, genauso sieht es auch aus :D .auch seit dem Update aufgefallen

**Comment by JacobCrimson** [comment]
Ich geselle mich dazu. 
Wann kommt es zum Bug? 
Immer, wenn ich über das X-Menü ein privates KfZ (Cypher), welches zuvor automatisch eingeparkt war, öffnen oder schließen möchte.
Sowohl wenn ich im Auto sitze oder wenn ich daneben stehe und diese Aktion ausführen möchte.
Wie äußert sich der Bug?
Das spiel friert ein und wird nach kurzer Zeit automatisch geschlossen.
Seit wann?
Seit dem 28.07.2022, wobei ich am 27.07.2022 nicht online gewesen bin.

**Comment by TheOutburst** [comment]
@Timste2707 @LeTzIGameZz @Stiefel911 @JacobCrimson 

Wir kriegen das bei uns leider absolut nicht reproduziert und die Meldungen sind jetzt auch nicht soo viele, dass wir glauben, dass es nen flächendeckendes Problem ist. Könnt ihr hier mal die client logs & crashdumps hochladen? AltV Ordner -> logs bzw AltV Ordner -> crashdumps
Alternativ gerne in den Support -> allgemeine Fragen, dann helfen wir euch dabei

**Comment by Chandena** [comment]
Hallo, bei mir is gestern Abend, genau das gleiche passiert. Hab hier mal ein log hoch geladen.
https://filehorst.de/d/esBjwtdF

**Comment by nox142** [comment]
Habe auch das Problem, dass ich nicht in meinem Fahrzeug ( Semi Baracks) einsteigen kann, ohne dass das Game crashen tut. Problem besteht seit dem 28.07 bereits...

Anbei die ganzen Logs
[altv_12.7_Steam_0x82d33980c_01-08-2022_02-11-19.zip](https://github.com/eiksch/statev_v2_issues/files/9230032/altv_12.7_Steam_0x82d33980c_01-08-2022_02-11-19.zip)
[altv_12.7_Steam_0x82d33980c_01-08-2022_02-09-10.zip](https://github.com/eiksch/statev_v2_issues/files/9230033/altv_12.7_Steam_0x82d33980c_01-08-2022_02-09-10.zip)
[altv_12.7_Steam_0x82d33980c_01-08-2022_02-05-18.zip](https://github.com/eiksch/statev_v2_issues/files/9230034/altv_12.7_Steam_0x82d33980c_01-08-2022_02-05-18.zip)
[altv_12.5_Steam_0x71afa97dc_28-07-2022_16-07-12.zip](https://github.com/eiksch/statev_v2_issues/files/9230035/altv_12.5_Steam_0x71afa97dc_28-07-2022_16-07-12.zip)
[altv_12.5_Steam_0x71afa97dc_28-07-2022_16-04-48.zip](https://github.com/eiksch/statev_v2_issues/files/9230036/altv_12.5_Steam_0x71afa97dc_28-07-2022_16-04-48.zip)
[altv_12.5_Steam_0x71afa97dc_28-07-2022_16-01-35.zip](https://github.com/eiksch/statev_v2_issues/files/9230037/altv_12.5_Steam_0x71afa97dc_28-07-2022_16-01-35.zip)
[altv_12.5_Steam_0x71ac4964b_28-07-2022_15-58-53.zip](https://github.com/eiksch/statev_v2_issues/files/9230038/altv_12.5_Steam_0x71ac4964b_28-07-2022_15-58-53.zip)
[altv_12.5_Steam_0x7fb9697dc_28-07-2022_16-15-00.zip](https://github.com/eiksch/statev_v2_issues/files/9230039/altv_12.5_Steam_0x7fb9697dc_28-07-2022_16-15-00.zip)

**Comment by Chandena** [comment]
Also bei mir ging es wieder nachdem ich ALTV neu installt habe.

**Comment by TheOutburst** [comment]
Unsere Erfahrung ist bisher, dass jeder, der das Problem hatte und anschließend AltV neu installiert hat, anschließend kein Problem mehr hat. Die Logs lassen auch auf einen ganz normalen Client Crash schließen.
Gibt es jemanden, der auch nach einer komplett cleanen Neuinstallation von AltV (NICHT GTA) weiterhin Crash Probleme mit dem X Menü in einem Auto hat?

Wenn hier bis zum nächsten Update keine Antwort rein kommt würde ich es auf ein faulty Clientupdate schieben und den issue hier schließen.

**Comment by nox142** [comment]
Nach mehrmaligen neuinstallieren geht es bei mir jetzt auch

**Comment by DonVitoDiangelo** [comment]
:)
