### ISSUE TITLE
Spiel Crash auf dem Fahrersitz

### ISSUE THREAD

**Issue by Timste2707** [eiksch/statev_v2_issues#2525]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Alexis Mendoza**

**Auftrittszeitpunkt (27.07.2022/ 22 Uhr)**

**Beim Einsteigen auf den Fahrersitz egal ob es Cop Autos sind oder private Fahrzeuge, crashed mein Game direkt.Wenn ich auf dem Beifahrersitz einsteige ist alles ok und das Game crashed nicht**

**Normales Einsteigen und Autofahren ohne spielcrash beim einsteigen**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by TheOutburst** [comment]
#2524
