### ISSUE TITLE
Geld hat eine hitbox

### ISSUE THREAD

**Issue by MarcelloValentine** [eiksch/statev_v2_issues#2526]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Marcello Valentine

28.07.2022 um ca. 20 Uhr

Sobald man jemanden Geld gibt hat dieses Geld eine hitbox

Das es verschwindet und keine hitbox hat

Man gibt jemanden Geld das geld bleibt dann in der luft und man läuft gegen

**Comment by TheOutburst** [comment]
Auch wenn es sich anders äußert, im Kern ists der selbe Bug wie #2516
