### ISSUE TITLE
[F] Toronto Raptors - 1 McGrady Jersy Torso wird nicht richtig dargestellt

### ISSUE THREAD

**Issue by HuiBuh32** [eiksch/statev_v2_issues#2527]
Inge_Knesebeck

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer

**Beobachtetes Verhalten**
Beim dem Kleidungsstück [F] Toronto Raptors - 1 McGrady Jersy gibt es keine passende Anziehmöglichkeit. Der Torso wird in jeder Kombination nicht richtig dargestellt.
Diverse Shorts sieht man auch durch das Shirt, wenn man in Bewegung ist.

**Erwartetes Verhalten**
Es sollten keine Lücken o.ä. zu sehen sein

**Schritte um den Fehler nachvollziehen zu können**
Shirt gekauft und keine passende Kombi gefunden. Vermutlich tritt dieser "Fehler" auch bei anderen Shirts dieser Art auf aber hatte kein Geld mehr.
Magic Corsage auch verwendet

**Optional: Video / Bilder des Fehlers**
https://pic.statev.de/image/image.d9oIT

**Comment by Enemyaa** [comment]
Dake für die Info. Wir gucken mal ob wir da eine Torso Mölichkeit hinzufügen
