### ISSUE TITLE
Tuning Problem (Xenon licht beim Tunen obwohl nicht verändert)

### ISSUE THREAD

**Issue by baka708** [eiksch/statev_v2_issues#2528]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Ulli Schwadulek**

**30.07.2022 10:30 Uhr**

**Wenn man in der Werkstatt etwas am Fahrzeug unter dem Reiter 'tuning' verändern will, stehen auf der Rechnung am Ende immer Xenons mit drauf. Die Teile werden auch aus dem Lager entfernt. 
Es hilft auch nicht an der Einstellung der Xenon Scheinwerfer etwas zu verändern wie beim letzten mal als der Fehler ähnlich auftrat.**

**Xenons werden nur aus dem Lager entfernt wenn diese auch verändert werden.**

**Einfach in der WErkstatt etwas verändern am Fahrzeug und schon stehen auf der Rechnung die Xenon Scheinwerfer.**

****

****

**Comment by TeubyDE** [comment]
Hört sich super nach diesem Problem hier an https://github.com/eiksch/statev_v2_issues/issues/2466
Hatte das eigentlich Mitte Juni gefixed. Stichpunkt headlightColor. @TheOutburst  könntest du das bitte noch mal durchtesten?

**Comment by TheOutburst** [comment]
Ich kriege das sowohl mit bestehenden als auch neuen Autos nicht reproduziert. Egal was für Tunings bestehen, wenn etwas geändert wird, wird nur das abgezogen was auch angeklickt wurde - egal ob Xenon vorher bereits getuned ist oder nicht.

@baka708 tritt das bei dir wirklich bei jedem Fahrzeug auf? Weißt du noch bei welchen Autos konkret das war, was da getuned war und was für ein Tuning du geändert hast?

**Comment by baka708** [comment]
Ich hatte es zuerst beim Jester RR egal was ich daran verändert habe am Ende standen Xenons mit auf der Rechnung. 
Dann habe ich das ganze beim Tailgater S versucht da war das gleiche. 
Der Jester hatte nur eine Fronststoßstange dran war sonst komplett frisch aus der Fertigung. 
Der Tailgater S war schon komplett umgebaut fast alles was geht. 
Xenons hatten jedoch keine von beiden verbaut bisher.
Ich hatte dann mit einem Dev gesprochen der sagte was von Datenbankungleichheiten.
Danach funktionierte es plötzlich wieder. Bisher keine Probleme mehr damit.

**Comment by Dean-Gallagher** [comment]
@TheOutburst guck ma vll ist er in den hier gerannt https://github.com/eiksch/statev_v2_issues/issues/2465

**Comment by JaxBorrow** [comment]
Wir (Jax Borrow und Mila Valdes) hatten das Problem heute auch, dass beim Tunen eines Bucaneer Customs (Kennz. LSBEAUTY) die Xenons automatisch mit auf die Rechnung genommen wurden. Wir hatten aber lediglich das Heckablagen-Schild ändern.
