### ISSUE TITLE
TShirts falsch angezeigt

### ISSUE THREAD

**Issue by SHaagmann** [eiksch/statev_v2_issues#2529]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Sven Rosenbach & Larry Klein
**Auftrittszeitpunkt (Datum / Uhrzeit)**

31.07 ca 1 Uhr morgens
**Beobachtetes Verhalten**

Weißes TShirt [U] und Weißes StateV Tshirt haben sachen draufgedruck die normalerweise nicht da sind und auch von mehreren Personen so gesehen werden
**Erwartetes Verhalten**

Haben keine Fehlerhaften Texturen
**Schritte um den Fehler nachvollziehen zu können**

T-Shirts anhaben
**Optional: Video / Bilder des Fehlers**

![Screenshot_2](https://user-images.githubusercontent.com/58612983/182003383-dbebe9b7-da33-4874-8d39-cda6298e2382.png)
![unknown](https://user-images.githubusercontent.com/58612983/182003385-61628474-075f-4cff-8e45-87a6d59b5738.png)

**Comment by DonVitoDiangelo** [comment]
Tritt der Fehler noch immer auf? Konnte das auf dem DEV aktuell nicht reproduzieren.

**Comment by SHaagmann** [comment]
@DonVitoDiangelo Bis jetzt nicht mehr Aufgetreten. Falls doch nochmal gebe ich bescheid
