### ISSUE TITLE
NOS boost

### ISSUE THREAD

**Issue by AndoMalius** [eiksch/statev_v2_issues#2533]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Ando Malius 

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Beim Aktiveren vom NOS 

**Beobachtetes Verhalten**
wenn man das NOS zündet ist die Animation immer da. Jedoch ist der Boost nicht immer vorhanden. Wurde mit Jester Classic und Dominator ASP getestet

**Erwartetes Verhalten**
Boost sollte immer vorhanden sein 

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by TeubyDE** [comment]
@AndoMalius  Könntest du das bitte einmal genauer ausführen? bzw. ein Video anhängen.

**Comment by TheOutburst** [comment]
Known Issue: mit NVE bleibt der Bildschirmeffekt bestehen, sobald NOS in der Umgebung gezündet wurde
Fix: NVE deinstallieren

**Comment by AndoMalius** [comment]
wie es seien soll
https://medal.tv/games/gta-v/clips/v9SMbGR-_52_Y/d1337S94Azqg?invite=cr-MSxVRlgsODAxODc1NDks

Normal als vergleich
https://medal.tv/games/gta-v/clips/v9SkpZcaYHVTQ/d1337HRG3SxQ?invite=cr-MSxyUDMsODAxODc1NDks

Wie es hin und wieder nicht Funktioniert folgt, leider fehlen für weitere tests die ressourcen.

**Comment by AndoMalius** [comment]
https://medal.tv/games/gta-v/clips/va04fRXAzMG4N/d1337Vq40Wbz?invite=cr-MSw2MmYsODAxODc1NDks

**Comment by AndoMalius** [comment]
Mods habe ich keine

**Comment by UNDRCVRR** [comment]
@AndoMalius Ist dir das bisher wieder aufgefallen oder funktioniert das jetzt?

**Comment by AndoMalius** [comment]
Werde es testen und dann nochmal Rückmeldung geben. Kann allerdings bis Freitag dauern.

**Comment by AndoMalius** [comment]
Sorry für die späte Rückmeldung. Problem besteht noch immer. Passiert oft Random. Aber meist immer wenn man das NOS zündet wenn die Leistung vom Fahrzeug Umgebungstechnisch reduziert ist. Wie z.B Steigungen.

**Comment by Erumeldor** [comment]
Vor paar Tagen war das bei uns auch nochmal der Fall. Also einfach keine Wirkung.
https://medal.tv/games/gta-v/clips/K3na6ztAsxaFp/d1337E0Y6NRF?invite=cr-MSxOU2ssODIzMjY1NTMs
Sultan Classic, voll besetzt. Der fährt das ohne NOS genauso schnell.

**Comment by TeubyDE** [comment]
Mehrfache und unabhängige Test haben ergeben das dies leider in diesem speziellen Edge Cases durch die GTA engine verursacht wird. Somit leider kein Verhalten was wir beeinflussen können.
