### ISSUE TITLE
Golfball verschwindet nach Abschlag / nicht sichtbar, wo er liegen müsste

### ISSUE THREAD

**Issue by CaleighRhodes** [eiksch/statev_v2_issues#2534]
**Character Name**
Caleigh Rhodes

**Auftrittszeitpunkt (Datum / Uhrzeit)**
03.08., ca. 19:00 Uhr

**Beobachtetes Verhalten**
Beim Abschlag auf dem Golfplatz fliegt die Kamera dem Ball nur kurz hinterher. Dann kehrt sie zum Spieler zurück. Man sieht nicht, wie früher, wo der Ball gelandet ist, der Ball ist dann auch weg und nicht dort, wo man ihn vermuten würde.

**Erwartetes Verhalten**
Ball landet ordentlich und kann danach weiter bespielt werden.

**Schritte um den Fehler nachvollziehen zu können**
normal Golf spielen, passiert bei jedem Abschlag

**Comment by TeubyDE** [comment]
@TheOutburst Bitte einmal auf dem Dev nachstellen.

**Comment by TheOutburst** [comment]
next update fixed
