### ISSUE TITLE
S2 Cabrio - kein Sound beim Verdeck öffnen/schließen

### ISSUE THREAD

**Issue by CaleighRhodes** [eiksch/statev_v2_issues#2535]
**Character Name**
Caleigh Rhodes

**Auftrittszeitpunkt (Datum / Uhrzeit)**
seit gestern, 02.08. (ich war allerdings davor ein paar Tage nicht ic)

**Beobachtetes Verhalten**
Beim hoch- oder runterfahren des Cabrioverdecks des S2 wird kein Sound mehr abgespielt.

**Erwartetes Verhalten**
Sound sollte abgespielt werden

**Schritte um den Fehler nachvollziehen zu können**
Cabrio-Verdeck öffnen/schließen

**Comment by CaleighRhodes** [comment]
Habe es gerade mal mit einem anderen Cabrio versucht (Tornado Custom), da wird Sound abgespielt.

**Comment by TheOutburst** [comment]
Das isn gta oder altv Problem
Haben andere Server (selbst Freeroam Server) auch.
