### ISSUE TITLE
Beim 24/7 bei 6025 Fast unsichbares Objekt

### ISSUE THREAD

**Issue by NicoleWitt** [eiksch/statev_v2_issues#2536]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Nicole Witt **

**Auftrittszeitpunkt (Datum / Uhrzeit)**

(04.08.22 / 23:10 )
**Beobachtetes Verhalten**
Ein Kleines Objekt fast unsichtbar ist mitten in der Luft ungefähr Hüfthöhe

**Erwartetes Verhalten**
 Da sollte kein Objekt sein

**Schritte um den Fehler nachvollziehen zu können**
iehe Foto

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
<a href="https://ibb.co/cy7LBtK"><img src="https://i.ibb.co/cy7LBtK/Grand-Theft-Auto-V-Screenshot-2022-08-04-23-09-41-48.png" alt="Grand-Theft-Auto-V-Screenshot-2022-08-04-23-09-41-48" border="0"></a>

**Comment by WoahJeesus** [comment]
Wird mal wieder die Lichterkette vor dem Laden sein (24/7 Postal 6025)

**Comment by TheOutburst** [comment]
Das was WoahJeesus sagt, das liegt an der Lichterkette, da wird über den Bürgersteig jmd mitm Auto gefahren sein, was dann diese Spuren hinterlassen hat.
