### ISSUE TITLE
 Haushash	paletobay20

### ISSUE THREAD

**Issue by DrCassado** [eiksch/statev_v2_issues#2537]
Moin moin wie mit William Walles im Support besprochen nun hier das Ticket

es geht um 2 Anliegen.

Punkt nummer 1.
Die anfrage für eine Hausgarage.
![Screenshot_202](https://user-images.githubusercontent.com/102039945/183121259-0d1613ba-a1f9-450c-9f88-602861c4c687.png)
![Screenshot_201](https://user-images.githubusercontent.com/102039945/183121280-a76eed15-1205-42f3-a2b8-9a21f54f31ea.png)
![Screenshot_5](https://user-images.githubusercontent.com/102039945/183121415-5b2bfa15-25e9-43c2-8e18-d167f7cd0747.png)
Wie man an den Bildern Erkennen kann habe ich eine Sehr sehr große Einfahrt. (platz für bis zu 6 Autos und dan noch Motorräder)
Deswegen stelle ich nun die Anfrage für einen Garagen punkt (ich weis das nichts gemappt wird aber zumindestens der Punkt zum Bee und Entladen währe sehr sehr wünschenswert. Dieser könnte am Ende der Einfahrt Angebracht werden (dort wo das Zelt steht)

Diese anfrage hatte ich im support gestellt und gesagt bekommen das ich für das Gamedesign nen Ticket erstellen solle.

Anfrage nummer 2
Diese ist etwas ungewöhnlicher.
Mir wurde anfags gesagt das sich die Interiör größen nach art des Hauses orientieren. Nun ist mir aufgefallen das ich eines der größeren häuser in Paleto und Sandy shores habe und das haus Allerdings auf die Klasse 1 gesetzt ist. An sich fdand ich das ja noch ok weil ich dachte gut das liegt an Paleto die in der stadt sind dan alle 2 oder höher aber inzwischen weis ich das ettliche auch viel kleinere (und ich rede da schon von wirklichen wohnwagen oder kleien bruchbuden) Wohnungen auf klasse 2 gesetzt wurden.

Deswegen würde ich darum bitten das man schaut ob das haus vl nicht einfach nur falsch eingestuft wurde.
Ich habe aktuell das Low End Apartment in meinen Klasse 1 haus und würde  gerne auf das Girlys apartment von klasse 2 wechseln.
Dies hatt den Hintergrund das ich finde das das Design viel besser zum Grundriss des Hauses Passt und dies auch besser meinen char wiederspiegeln würde (keines der klasse 1 interieurs passt wirklich zu den Char.

Ich würde mich deswegen über eine Kurze Überprüfung freuen (sollten dafür kosten anfallen werde ich die selbstredend übernehmen)

MfG
Ricardo Cassado

**Comment by TheOutburst** [comment]
Hellole,

unsere (gelockerten) Bedingungen für Hausgaragen treffen leider nicht auf dein Haus zu. Du hast weder eine Garage, noch ein Carport. Eine Einfahrt legitimiert derzeit leider keinen Garagenpunkt.

Die Klasse ist tatsächlich schon auf 2, das Interieur richtet sich jedoch nach der Größe, die war auf 1. Hab die bei deinem und deinem Nachbarhaus mal auf 2 angehoben.

**Comment by DrCassado** [comment]
ok vielen dank für die schnelle bearbeitung
