### ISSUE TITLE
Drehrad am Casino geht nicht mehr 

### ISSUE THREAD

**Issue by NicoleWitt** [eiksch/statev_v2_issues#2538]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Nicole Witt **

Nicole und andere Personen

**Auftrittszeitpunkt (Datum / Uhrzeit)**

06.08.22 / 11:41

**Beobachtetes Verhalten**

Die Person Vor mir hatte gedreht, Nun steht die ganze zeit Aktuell dreht bereits eine Person

**Erwartetes Verhalten**

Das es wieder wie vorher ist, dass man nach der Person auch drehen kann

**Comment by NicoleWitt** [comment]
Geht auf eine Unerklärliche weise wieder

**Comment by DrGrizzlY17** [comment]
Ging dann doch wieder oder warum closed?

**Comment by NicoleWitt** [comment]
Irgendwie ja aber irgendwie auch nicht hab länger mir das noch angeguckt ab und zu kommt die meldung dann doch noch wenn man zu schnell ans drehrad will
