### ISSUE TITLE
Extras wie Färbung der Inneneinrichtung wird als Reparatur in Finanzen deklariert

### ISSUE THREAD

**Issue by CatherineGallagher** [eiksch/statev_v2_issues#2539]
**Character Name**
Catherine Gallagher

**Auftrittszeitpunkt (Datum / Uhrzeit)**
06.08.22 // 13:30 Uhr

**Beobachtetes Verhalten**

Es wird in den Finanzen das Färbung der Inneneinrichtung  unter Extra als "Reparatur" deklariert, wäre schön, wenn dies auch unter Tuning fallen würde.

**Erwartetes Verhalten**
Das es als Tuning in den Finanzen auftaucht

**Comment by CatherineGallagher** [comment]
Nevermind, hab mich verguckt sind ja Farbtuben , keine Lackdosen :D Fail, aber das mit der Deklarierung bleibt noch xD

**Comment by TeubyDE** [comment]
@CatherineGallagher  Kannst du das bitte kurz spezifizieren? ggf. mit Screenshot. Ich komm gerade nicht drauf was genau du meinst.

**Comment by CatherineGallagher** [comment]
https://prnt.sc/A8yw4u57PUnn

So sehen ja die Finanzen aus, die färbung der Inneinrichtung ist ja ein Tuning, wird aber in den Finanzen als Reparatur verzeichnet.
