### ISSUE TITLE
Klamotten Bugs

### ISSUE THREAD

**Issue by PlayInc89** [eiksch/statev_v2_issues#2540]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Ryan_Valdes**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

13:00Uhr

**Beobachtetes Verhalten**

Folgende Klamotten werden im Fashion Killa falsch angezeigt !

[F] Grüne Camo Slipper
[F] Orange-Gelbe Slipper mit Muster
[F] Hellgrüne Slipper
Nike Pants Sports & Streetwear
[M] Schwarze Nike Sagged Joggers
[M] Graue Nike Sagged Joggers
[M] Weiße Nike Sagged Joggers

Und für die Lounge Hemden gibt es bei Männern keinen Passenden Torso !

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by TheMoonicorn** [comment]
Bow Tie Tops haben teilweise falsche Beschriftungen

**Comment by PlayInc89** [comment]
Ich glaube da stimmt was nicht

![image](https://user-images.githubusercontent.com/70231715/183264930-cfaea42f-5912-4bee-86b4-2cca0cb1395e.png)
