### ISSUE TITLE
Packer kann Ölanhänger nicht mehr ankoppeln

### ISSUE THREAD

**Issue by cadpri** [eiksch/statev_v2_issues#2544]
**Character Name**
Fabian_Picard

**Auftrittszeitpunkt (Datum / Uhrzeit)**
06.08.2022 17:38

**Beobachtetes Verhalten**
Packer kann seit dem Update heute Mittag den Ölanhänger nicht mehr ankoppeln.

**Erwartetes Verhalten**
Packer kann den Ölanhänger ankoppeln

**Schritte um den Fehler nachvollziehen zu können**
Packer versuche unten einen Ölanhänger zu fahren

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080

**Optional: Video / Bilder des Fehlers**
[Youtube Link](https://youtu.be/RKvHGIYYwuo)

**Comment by Stiefel911** [comment]
Ich kann es auf dem Video schlecht erkennen. Aber kann es sein das die Stützen im Boden sind? Irgendwie sehe ich die Stützensohle nicht. ;)

**Comment by cadpri** [comment]
Doch da ist alles so wies soll.
Phantom Custom kann da ganz normal drunter fahren

**Comment by DonVitoDiangelo** [comment]
Also das geht wunderbar. Bei sieht man das der vermutlich bisschen tief hängt und den halt schiebst und somit nicht drunter kommst. Am besten mal etwas drehen, dann passt das irgendwann. :)
