### ISSUE TITLE
lightbar (Blaulicht) verschwindet nach einparken

### ISSUE THREAD

**Issue by Daniel-Meister-508** [eiksch/statev_v2_issues#2545]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Daniel_Meister**

**Auftrittszeitpunkt 06.08.2022 / 19:50)**

Beobachtetes Verhalten
nach Einparken des Scoutes Verschwindet das Blaulicht auf dem Dach. Nach Ausparken kein Blaulicht mehr auf dem Scout**

Schritte um den Fehler nachvollziehen zu können
**Karre mit Blaulicht Einparken und Ausparken**

**Optional: Video / Bilder des Fehlers**
https://pic.statev.de/image/screenshot-27.wWVZD

**Comment by TeubyDE** [comment]
Danke für den Hinweis, habe das Problem bereits finden können. Morgen Vormittag kommt der bereits angekündigt Hotfix.
