### ISSUE TITLE
Drift Tampa Geschwindigkeit

### ISSUE THREAD

**Issue by Michi993** [eiksch/statev_v2_issues#2546]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Luke Hammer

**Auftrittszeitpunkt (Datum / Uhrzeit)**
06.08.2022 13 Uhr

**Beobachtetes Verhalten**
Drift Tampa ist um einiges langsamer, als vor dem GTA update, also ist schon seit ca. 1 woche so.
Fährt nur noch ca. 200-210 km/h (mit Driftreifen)

**Erwartetes Verhalten**
Fahrzeug fähr im regelfall ca. 260 - 280km/h (mit Driftreifen)

**Schritte um den Fehler nachvollziehen zu können**
Fahrzeug fahren

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Fahre erst einmal in die Werkstatt und lass das Fahrzeug checken. ;)

**Comment by Michi993** [comment]
wurde gemacht, da passt alles, sonst hätte ich ja kein bug report geschrieben ;)

**Comment by DonVitoDiangelo** [comment]
Also wenn der nur noch 210 bei dir fährt ist an dem was. Wieviel Kilometer hat der schon runter?

**Comment by DonVitoDiangelo** [comment]
Gib mal auch dein Kennzeichen durch.

**Comment by Michi993** [comment]
ca. 1980km und ohne kennzeichen

**Comment by Michi993** [comment]
gibt es vielleicht probleme mit der drift Bereifung, dass die fahrzeuge mit dieser eventuell langsamer werden?

**Comment by Michi993** [comment]
Aktuell: https://medal.tv/de/games/gta-v/clips/wobqdqFweHFgF/d1337k9UHTqE?invite=cr-MSxWcTIsOTI2NjAwNTks

Damals (leider nur dieser clip verfügbar, am besten auf die beschleunigung achten): https://www.youtube.com/watch?v=qQwv-6VHglo

**Comment by DonVitoDiangelo** [comment]
So, also das sieht alles fine aus. Ja klar bist du zwangsläufig mit den Drift in der Beschleunigung langsamer.
"mehr Wheelspin = weniger Grip". Die Speed auf deinem ersten Video ist nicht repräsentativ für deine 260 - 280km/h Angabe.
Die 260 sind absolute max. Werte bei entsprechendem Untergrund. Hier sieht alles aus wie es sein soll, daher closed.

**Comment by Michi993** [comment]
wie gesagt, das fahrzeug ist langsamer als vorher, das merkt man und sieht man ebenfalls an den geschwindigkeitswerten, kp wo der fehler liegt, aber er besteht, deswegen wäre es cool, wenn sich darum gekümmert werden könnte, dass das fahrzeug wieder so fährt, wie vorher, danke
