### ISSUE TITLE
Piercing buggt durch Jerseykleid

### ISSUE THREAD

**Issue by Saaria83** [eiksch/statev_v2_issues#2547]
```

<!-- Bitte die Vorlage unten vollständig ausfüllen -->
**Character Name**
 
 Hanna Fields

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Seit 06.08.2022

**Beobachtetes Verhalten**

Piercing buggt beim Jerseykleid durch

**Erwartetes Verhalten**

Dass es nicht durch buggt :p 


Bild siehe unten :D

**Comment by TamiGaming** [comment]
![image](https://user-images.githubusercontent.com/40512639/183269905-aabbbc9b-3a7e-4183-be94-1ea29b89b036.png)

**Comment by CatherineGallagher** [comment]
https://github.com/eiksch/statev_v2_issues/issues/2094

dieses Problem exisitiert schon sehr lange.

**Comment by DrGrizzlY17** [comment]
Wie bereits in dem anderen BT Eintrag, is das ein viel zu großer Aufwand für Klamotten Check bei nem Piercing. Muss man sich halt entschieden. Sorry
