### ISSUE TITLE
Hautfarbe ändert sich

### ISSUE THREAD

**Issue by halloheyleon** [eiksch/statev_v2_issues#2548]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Grezzer Morgan

Grezzer Morgan
**Auftrittszeitpunkt (Datum / Uhrzeit)**

07.08.2022 19Uhr
**Beobachtetes Verhalten**

ich habe mich ganz normal eingeloggt und habe gesehen das mein Char auf einmal eine andere Hautfarbe hatte
**Erwartetes Verhalten**

eigentlich sollten die Hautfarbe des Chars immer gleich bleiben und sich nicht über ein Neustart verändern
**Schritte um den Fehler nachvollziehen zu können**

ich weiß es nicht wie das passieren kann
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

Monitor Auflösung ist 1920 x 1080 und ich habe auch nix dran verändert oder einen neuen angeschlossen
**Optional: Video / Bilder des Fehlers**

https://pic.statev.de/image/alt-v-multiplayer-31052022-19-20-02.wgoKq
https://pic.statev.de/image/alt-v-multiplayer-07082022-22-12-05.wx44B  (Frisur ich gewollt verändert)
https://pic.statev.de/image/alt-v-multiplayer-07082022-18-50-44.wxWWA
https://pic.statev.de/image/alt-v-multiplayer-07082022-18-53-11.wxgmy

Orte an dem der Bug auffällig ist/war:
gegenüber von Bahamas am Horizon in Hotel.
in verschiedenen Hotelzimmern.

**Comment by epichalt** [comment]
wäre vlt vorteilhafter, wenn du die Bilder an der selben Stelle machst. So könnte man meinen es ist nur die Belichtung

**Comment by DrGrizzlY17** [comment]
Also ich hätte jetzt auch gesagt das ist eher die Belichtung. Hast du den Settings geändert oder grafik mods oder reshade installiert/deinstalliert?

**Comment by halloheyleon** [comment]
Kleine Zusatz Info anscheinen gibt es diesen Bug nur an bestimmten orten also kann es doch an der Belichtung liegen aber dennoch sollte das mal beobachtet werden

**Comment by DrGrizzlY17** [comment]
Notier mal so ein paar Gegenden wo dir das auffällt

**Comment by DonVitoDiangelo** [comment]
Bei weiteren Infos hier reinschreiben, ansonsten erstmal closed. Ist nach den Bildern zu urteilen halt schlicht  die Belichtung. :)
