### ISSUE TITLE
Kette und Cord Bracelet werden nicht zusammen angezeigt beim ausrüsten

### ISSUE THREAD

**Issue by JaxBorrow** [eiksch/statev_v2_issues#2550]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Jax Borrow

**Auftrittszeitpunkt (Datum / Uhrzeit)**
07.08.2022 um zirka 22:10

**Beobachtetes Verhalten**
Wenn man eine Kette (in meinem fall die [M][Neck] Silberne Kordelkette 10mm) und ein Armband (in meinem Fall [M][A] Gold-Schwarzes Cord Bracelet) anzieht wird immer nur das angezeigt, welches man zuletzt angezogen hat. Das andere Schmuckstück wird ausgeblendet, ist aber noch ausgerüstet.

Ich weiß leider nicht ob es alle Kombinationen aus Kette und Armband betrifft.

**Erwartetes Verhalten**
Das beide Schmuckstücke angezeigt werden

**Schritte um den Fehler nachvollziehen zu können**
Die oben genannten Schmuckstücke nacheinander anlegen.

**Optional: Video / Bilder des Fehlers**

![Grand Theft Auto V Screenshot 2022 08 07 - 22 10 16 76](https://user-images.githubusercontent.com/100872532/183309566-02d04cd9-5690-472a-9373-3a7b60af3011.png)
![Grand Theft Auto V Screenshot 2022 08 07 - 22 23 54 56](https://user-images.githubusercontent.com/100872532/183309758-36b2b87c-2a97-4fd7-9e57-7e4728be0e13.png)

**Comment by Enemyaa** [comment]
Hi, die liegen auf dem selben Slot. Die kann man nicht zusammen tragen.
