### ISSUE TITLE
Scheibentönung Police Cruiser CVPI

### ISSUE THREAD

**Issue by stormbreaker22** [eiksch/statev_v2_issues#2551]
## WICHTIGE INFORMATION!!:

**Character Name**
Kilian_Smith

**Auftrittszeitpunkt (Datum / Uhrzeit)**
8.8.22 17:30

**Beobachtetes Verhalten**
Beim Tunen des Police Cruisers lässt sich die Scheibentönung nicht richtig auftragen. Diese ist falschrum so das man von aussen nach innen aber von innen nicht nach aussen sehen kann.
Auch fehlt ein teil der Scheibentönung komplett.
**Erwartetes Verhalten**
Die Scheibentönung sollte wie gewohnt angebracht sein.

**Schritte um den Fehler nachvollziehen zu können**
Beim Tunen in der Werkstatt die Scheibentönung anbringen.

**Optional: Video / Bilder des Fehlers**
![Scheibentönung_CVPI](https://user-images.githubusercontent.com/61292701/183457584-aa51043f-0bc3-449e-90b0-9f383753648f.png)
![Scheibentönung_CVPI_innen](https://user-images.githubusercontent.com/61292701/183458342-534f339e-ad58-4242-9775-a51cdd169477.png)

**Comment by TheOutburst** [comment]
Das Problem ist eines von Rockstar (bzw hat der Modersteller das Problem von Rockstar kopiert - wie auch immer das geht)
Da können wir nicht viel dran machen.
