### ISSUE TITLE
Stealth Hoodies fixen an den Haaren

### ISSUE THREAD

**Issue by Luuperr** [eiksch/statev_v2_issues#2552]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Mikey Joyce**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by TeubyDE** [comment]
@Luuperr  könntest du bitte ein wenig mehr Input liefern?
WAs ist den genau kaputt bei den Stealth Hoodies?

**Comment by DonVitoDiangelo** [comment]
Bitte mehr Infos, wenn Ihr einen Bugtracker eröffnet
