### ISSUE TITLE
Casino Glücksrad Bug

### ISSUE THREAD

**Issue by franzjosef27** [eiksch/statev_v2_issues#2553]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Franz Josef**

**08.08.22 21.40**

**Man will drehen am Glücksrad und es gibt eine Fehlermeldung "Es dreht schon jemand"**

**EDass diese Fehlermeldung nicht auftaucht, obwohl auch keiner dreht.**

**geh ins casino, dreh am rad und schau dann was passiert.**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by elaaar** [comment]
Ich hatte gestern das erlebniss, das man 100dollar gezahlt hat, erfolgreich gedreht und als Gewinn nochmal drehen bekommen hatte. Nach mit war dann direkt jemand  am Rad zum drehen und danach musste ich weitere 100dollar für den Dreh zahlen. Sprich der gratis Dreh war weg und ob ich hätte nochmal zahlen müssen kann ich nicht beantworten.
