### ISSUE TITLE
Stühle Unsichtbar bei Underground Ink

### ISSUE THREAD

**Issue by CreminddJayo** [eiksch/statev_v2_issues#2554]
Hey, bei Underground Ink sind normalerweise neben dem Kaugummi Automaten 2-3 Stühle. Diese tauchen nur auf, wenn man durch "y" sich auf diese Stühle hinsetzen möchte. Wäre cool wenn die auch so sichtbar wären.

Danke euch <3

**Comment by TeubyDE** [comment]
@TheOutburst  Sind das Probs die wir ggf. entfernt haben?

**Comment by TheOutburst** [comment]
Seit 3 Jahren hat sich niemand dran gestört :D 
Next update habt ihr da "wieder" 2 Stühle stehen
