### ISSUE TITLE
Fahrzeug wird beim Ausparken beschädigt

### ISSUE THREAD

**Issue by baka708** [eiksch/statev_v2_issues#2555]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Ulli Schwadulek*

**09.08. ca. 20:00 Uhr**

**Beim ausparken von meinem youga 4x4 buggt dieser etwas herum und fällt dann ca. einen halben meter herab auf die Straße.
Danach braucht der Wagen eine Reperatur da er deutliche Geräusche macht. Nach einer Reperatur macht der wagen beim ein und wieder ausparken wieder Geräusche. **

**Fahrzeug wird beim ausparken nicht beschädigt.**

**Fahrzeug reparieren dann ein und ausparken und auf Beschädigung prüfen.**

****

****

**Comment by Saaria83** [comment]
Kann ich so bestätigen. Ist mir aber nur bei der Rancho Garage aufgefallen. Das gleiche auch bei dem Hotrod Blazer

**Comment by DonVitoDiangelo** [comment]
next update fixed
