### ISSUE TITLE
Müllentfernung am Haus

### ISSUE THREAD

**Issue by SHaagmann** [eiksch/statev_v2_issues#2556]
Ich wollte einfach mal anfragen, ob es möglich wäre die Kartons und den Müllsack vor meinem Haus zu entfernen, da es doch leider den Anblick des eigentlich recht edlen Hauses herunterzieht.

![20220807202926_1](https://user-images.githubusercontent.com/58612983/183977346-6ad7f380-fc42-4775-afd8-3248a2f430e7.jpg)

![20220809214909_1](https://user-images.githubusercontent.com/58612983/183977378-bde9d98d-9b7b-4039-956f-5f8914dca9b7.jpg)

**Comment by TheOutburst** [comment]
Bewegliche Mapobjekte können wir nicht entfernen, da sie beim "berühren" wieder sichtbar werden - was noch schlimmer ist als Müll vor der Türe
