### ISSUE TITLE
Gegenstände

### ISSUE THREAD

**Issue by KnauserHB** [eiksch/statev_v2_issues#2558]

**Comment by SvenPhoenix** [comment]
Das ist ein Feature... du wurdest ausgeraubt. Alles so gewollt. Vermutlich hast du es schon selber gemerkt. Deswegen ist das Ticket leer...

**Comment by DonVitoDiangelo** [comment]
? Kann hier jemand aufklären. Worum geht es hier genau? @KnauserHB

**Comment by Stiefel911** [comment]
ich schließe mich mal mit ein, da im Discord der Text noch zu lesen ist. Wenn du am 02.08. den Kleiderschrank befüllt hast, und am 06.08. aber ein update ins Spiel eingebracht wurde wo du in der Wohnung eine Nutzung von Kühlschrank für essen und trinken hast, so wie eine Abstell möglichkeit für andere Dinge " Abstellkammer" wurde zu diesem Zeitpunkt nämlich alles was im Kleiderschrank sich befunden hat, in die "Abstellkammer" verlagert, so das logischerweise der Kleiderschrank leer ist! Und du selbst nun sortieren solltest was du wo haben möchtest . ;)

hoffe DonVitoDiangelo kann es jetzt auch nachvollziehen ;)

So long

**Comment by DonVitoDiangelo** [comment]
ah ok, jup alles klar, dann closed :)
