### ISSUE TITLE
Falsche Dimmension

### ISSUE THREAD

**Issue by elaaar** [eiksch/statev_v2_issues#2559]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Jack_Jackson

**Auftrittszeitpunkt (Datum / Uhrzeit)**
12.08.2022 18:50

**Beobachtetes Verhalten**
Char wird in Falsche Dimension geportet und nicht in das Interior

**Erwartetes Verhalten**
Charakter wird in das Interior geportet

**Schritte um den Fehler nachvollziehen zu können**
Schiebe ein Fahrzeug das nicht mehr startet zum Portalpunkt der Werkstatt, dann E Drücken um mit dem Auto geportet zu werden. Das Auto blieb draußen stehen, der Char wurde in die falsche Dimension geportet, stand weiterhin draußen und nicht im Interior

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by TeubyDE** [comment]
@elaaar hast du ein Video davon?

**Comment by elaaar** [comment]
Nein Leider nicht. ist das nicht Reproduzierbar?

**Comment by DonVitoDiangelo** [comment]
> @elaaar hast du ein Video davon?

In der schiebe-anim am Auto und betätigst dann den port marker. 100% reproduzierbar
Bist ja attached am car und das portet zwar auch in die Werkstatt rein ,du der char aber selbst nicht, aber dim wird gesettet.
