### ISSUE TITLE
Bart auswahl verbugt

### ISSUE THREAD

**Issue by StateV2Marie** [eiksch/statev_v2_issues#2560]
ich hab leider nich gesehen obs da schon was gibt obs jemand gemeldet hat drum mach ichs mal bei der bart auswahl im frisur is beim hin und her machen aufeinmal nen grüner bart ich weiß nich worans liegt aber das sieht man auch als aussenstehender haben es extra mal getestet.

**Comment by Saaria83** [comment]
Das haben wir auch manchmal. Aber das Menü zu schließen und erneut zu öffnen "fixt" das. Also man sieht wieder alles normal

**Comment by TeubyDE** [comment]
Nicht game breaking. Bisher keine Lösung für gefunden. Hat vermutlich mit dem Mod zu tun.
