### ISSUE TITLE
IC Tablet Invalid Token

### ISSUE THREAD

**Issue by cadpri** [eiksch/statev_v2_issues#2561]
**Character Name**
Fabian_Picard

**Auftrittszeitpunkt (Datum / Uhrzeit)**
13.08.2022 15 Uhr irgendwas

**Beobachtetes Verhalten**
Wenn ich IC das Tablet aufmache steht dort Invalid Token und ich muss mich jedes mal wieder neu anmelden.

**Erwartetes Verhalten**
Früher war es so, dass man IC sich nicht jedes mal neu anmelden musste

**Schritte um den Fehler nachvollziehen zu können**
IC F3 drücken

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080

**Optional: Video / Bilder des Fehlers**
Es ist kein Video oder Bild vorhanden

**Comment by TheOutburst** [comment]
bereits seit einigen Tagen gefixt
