### ISSUE TITLE
Item verliert keine Haltbarkeit

### ISSUE THREAD

**Issue by Icceetea** [eiksch/statev_v2_issues#2562]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Tommy_Tatum

14.08.22 10:00

Erntemesser verliert keine Haltbarkeit

Das Messer verliert beim Benutzen Haltbarkeit

Ich habe mit dem Messer auf dem Kautschukfeld in der Westside gearbeitet, da hat es noch richtig funktioniert und ein paar Stunden später habe ich mit dem selben Messer Baumwolle auf dem Feld in Harmony gefarmt. Dort hat es keine Haltbarkeit mehr verloren.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by CaleighRhodes** [comment]
Könnte daran liegen, dass man für Baumwolle pflücken kein Werkzeug braucht… ;)

**Comment by TeubyDE** [comment]
Wie @CaleighRhodes  schon richtig geschrieben hat. Wird Baumwolle einfach gepflückt.
