### ISSUE TITLE
Es ist nicht möglich, aus einem Fahrzeug heraus Ressourcen zu sammeln!

### ISSUE THREAD

**Issue by cadpri** [eiksch/statev_v2_issues#2563]
**Character Name**
Fabian_Picard

**Auftrittszeitpunkt (Datum / Uhrzeit)**
15.08.2022 16:56:57

**Beobachtetes Verhalten**
Kleines Ölfeld, zweite Pumpe, bin die Treppe hoch gegangen und oben E gedrückt und hab folgende Fehlermeldung bekommen:
"Es ist nicht möglich, aus einem Fahrzeug heraus Ressourcen zu sammeln!"
Nachdem ich die Treppe runter und wieder rauf gegangen bin gings dann.

**Erwartetes Verhalten**
Hochgehen, E drücken, Pumpen

**Schritte um den Fehler nachvollziehen zu können**
Puh ja gute Frage. Das kommt so selten vor, dass ich nicht weiss wie ich das reproduzieren soll.
Ist auch eher nur als kleiner Reminder gedacht, falls mal wer zufällig im Code über was stolpern sollte.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920 x 1080

**Optional: Video / Bilder des Fehlers**
[Bildchen](https://pic.statev.de/i/wRYrD.jpg)

**Comment by TeubyDE** [comment]
Wie oft ist das bisher vorgekommen?
1/100, 10/100 oder 50/100 mal das du auf dem Ölfeld farmst?

**Comment by DonVitoDiangelo** [comment]
@cadpri
