### ISSUE TITLE
Brecheisen nach Verwendung als Waffe nicht mehr für Einbrüche nutzbar

### ISSUE THREAD

**Issue by Humperrrt** [eiksch/statev_v2_issues#2564]
Character Name
Jaden_Pole

Auftrittszeitpunkt (Datum / Uhrzeit)
Immer

Beobachtetes Verhalten
Sobald man ein Brecheisen als Waffe ausrüstet, kann man dieses **NACH ABRÜSTUNG** nicht mehr für Hauseinbrüche nutzen

Erwartetes Verhalten
Man sollte das Brecheisen dennoch für Hauseinbrüche nutzen können.

Schritte um den Fehler nachvollziehen zu können

    Brecheisen als Waffe ausrüsten
    Brecheisen wieder abrüsten und versuchen damit in ein Haus einzubrechen.

Da mein letzter Issue scheinbar geschlossen wurde, weil nicht richtig gelesen wurde, reposte ich diesen hier nochmal. Es kam keine Reaktion mehr auf die Nachricht, die ich unter den geschlossenen Issue geschrieben habe.

**Comment by Erumeldor** [comment]
Ich würde mich freuen wenn das "low prio" vielleicht nochmal überdacht wird. 
Das Problem besteht, und bremst das Hauseinbruchs-System wenn man jedes mal ein neues Brecheisen kaufen gehen kann.

**Comment by Erumeldor** [comment]
Hab das gerade übrigens mal getestet:
Das ganze geht dann auch nicht mehr für ATMs. (also mit an und abgerüstetem Brecheisen)
Da gibt es ein anderes Ticket bzw. ein Eintrag irgendwo, das die Items sich auch nicht mehr im 24/7 stacken lassen. Ich denke das Item bekommt einfach eine Art "benutzt" Flag - denke das "andere" Item müsste man denke ich "einfach" für beide Crime-Sachen auch noch freischalten.
