### ISSUE TITLE
Drift Reifen ohne Wirkung

### ISSUE THREAD

**Issue by 48619** [eiksch/statev_v2_issues#2565]
**Character Name**
Magdalena Kurowska

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Verstärkt seit den letzten alt:V/StateV Updates

**Beobachtetes Verhalten**
Mein Dukes Custom, bestückt mit Drift Reifen, zeigt ein deutlich geändertes Fahrverhalten als zuvor.
Drifts, Burnouts und das Ausbrechen des Hecks bei niedrigen sowie hohen Geschwindigkeiten sind aktuell nicht mehr zu beobachten.

Das Tuning des Fahrzeugs wurde bewusst so gewählt, um eine "gesteigerte" Motorleistung auszuspielen, allerdings fährt sich das Fahrzeug aktuell sehr zäh.

Das Fahrzeug war bereits in zwei Werkstätten, ein Service hat keine Fehlermeldungen ausgeworfen und eine Reparatur hat auch keine Besserung gebracht. Das Ein- und Ausparken wurde auch bereits mehrmals probiert, ohne Erfolg.

Ein "Feature" war unter anderem auch, den Geschwindigkeitsbegrenzer auf 80 kmh zu stellen und daduch durchgehend durchdrehende Räder in Kurven zu haben.
Durch die nun anscheinend geänderte Fahrphysik der Reifen hat sich auch die Endgeschwindigkeit geändert und beträgt bei dem Fahrzeug aktuell 205 kmh (gemessen Fort Zancudo).

**Erwartetes Verhalten**
Mein Dukes Custom hatte vor den Updates ein sehr aggressives Ausbrechverhalten, vor allem bei niedrigen Geschwindigkeiten in der Stadt, mit der Möglichkeit die Drifts durch Vollgas in der Kurve schön zu halten.
Das unkontrollierte Ausbrechen des Hecks begann auf dem Highway bereits ab einer Geschwindigkeit von 150 kmh.

Beim Festsetzen der Geschwindigkeit auf 80 kmh wieder durchgehend durchdrehenden Reifen in Kurven haben.

Die Endgeschwindigkeit von 240 kmh die sonst bei 1/2 Meile Rennen (gemessen Fort Zancudo), mit dem genannten Setup, erreicht wurde, wieder zu erreichen.

**Daten zum Fahrzeug**
Dukes Custom / "124PS"
Kennzeichen: "YEEE HAA"
Kilometer: ~3300 km
Bereifung: Drift
1/4 und 1/2 Zeiten werden noch als Vergleich nachgereicht oder sind dem Racing System selbst zu entnehmen.

**Comment by Michi993** [comment]
ich kann nach mehreren versuchen mit und ohne drift bereifung bestätigen, dass diese aktuell zu leistungsverlusten bei den fahrzeugen führen, langsamere beschläunigung und weniger höchstgeschwindigkeit, obwohl es genau andersrum sein sollte

**Comment by DonVitoDiangelo** [comment]
Nein, Driftreifen sind nicht für schnellere Geschwindigkeiten und/oder bessere Beschleunigung gedacht.
Der Reifen dient lediglich dem Effekt des Drifts. Was dann bei den Speeds etc. exakt passiert ist durch GTA gesteuert.
Das Fahrzeug wurde auch in der DB geprüft und hier sind die Werte alle soweit ok.

**Comment by Michi993** [comment]
naja, aber ohne leistung kann man im grunde auch nicht driften und dass die fahrzeuge weniger leistung haben, ist halt einfach trash, da kann man ja gleich auf der felge fahren... meine meinung

**Comment by 48619** [comment]
> Nein, Driftreifen sind nicht für schnellere Geschwindigkeiten und/oder bessere Beschleunigung gedacht. Der Reifen dient lediglich dem Effekt des Drifts. Was dann bei den Speeds etc. exakt passiert ist durch GTA gesteuert. Das Fahrzeug wurde auch in der DB geprüft und hier sind die Werte alle soweit ok.

@DonVitoDiangelo Korrent, dennoch fährt sich das Fahrzeug seit den letzten Updates komplett anders und hat, trotz Drift Reifen, viel mehr Grip als vorher. Eine offizielle StateV Änderung an den Reifen/Fahrzeugen gab es keine, daher auch der Bug Report.

**Comment by DonVitoDiangelo** [comment]
> @DonVitoDiangelo Korrent, dennoch fährt sich das Fahrzeug seit den letzten Updates komplett anders und hat, trotz Drift Reifen, viel mehr Grip als vorher. Eine offizielle StateV Änderung an den Reifen/Fahrzeugen gab es keine, daher auch der Bug Report.

Also auf dem Dev passt das alles soweit und auch das Anstellen des Fahrzeugs, Burnouts und Drifts funktionieren wie es soll. 
Von uns gab es in der Hinsicht auch keine Änderung, weder an Multiplier des Reifens, noch am Fahrzeug selbst oder am Mode. Es fährt sich für mich "logisch" wie ein Drift Car. Es ist ja im Grunde auch nur der Drift Mode der aktiviert wird, ohne weitere Beeinflussung. Mach mir mal bitte ein Video, wie du mit Driftreifen anfährst und durch Kurven fährst.

**Comment by 48619** [comment]
> Also auf dem Dev passt das alles soweit und auch das Anstellen des Fahrzeugs, Burnouts und Drifts funktionieren wie es soll. Von uns gab es in der Hinsicht auch keine Änderung, weder an Multiplier des Reifens, noch am Fahrzeug selbst oder am Mode. Es fährt sich für mich "logisch" wie ein Drift Car. Es ist ja im Grunde auch nur der Drift Mode der aktiviert wird, ohne weitere Beeinflussung. Mach mir mal bitte ein Video, wie du mit Driftreifen anfährst und durch Kurven fährst.

@DonVitoDiangelo versteh mich bitte nicht falsch aber mir geht es rein um den Punkt dass sich das Fahrzeug seit den letzten Updates einfach komplett anders fährt als vorher. Natürlich kann man immer noch "irgendwie" driften aber nicht mehr so wie vorher, natürlich gehen Burnouts noch aber eben nicht mehr so wie vor den Updates, das zickige und unkontrolierte Ausbrechen des Fahrzeugs in Kurven fehlt auch total.

Und da bringen jetzt aktuelle Videos wie ich fahre auch nix weil ich keine Aufnahmen zum Vergleich habe.

Wenn du sagst, ihr habt keine Änderungen gemacht, dann müssen wir gemeinsam gucken wodurch der Bug entstanden ist.

**Comment by TeubyDE** [comment]
Um das hier einfach abzukürzen. Das Fahrzeug Thema führt bei mir regelmäßig zu enormen Kopfschmerzen.
Ja wir können bei den Fahrzeugen viel einstellen und viele Veränderungen am Handling vornehmen.
Ja wir nutzen hierfür viele Mechaniken vom Reifen Wechsel bis hin zum Drift/Race Mode.
Ja wir haben ein System das sich auf das Fahrverhalten auswirkt wenn das Fahrzeug viel in Verwendung/beschädigt ist.

Hier spielen ca. 18 verschiedene Faktoren hinein. 
Aber bei allen Standard GTA Fahrzeugen liegt hier RG's normale Fahrzeug config als Basis. Gibt's da ne Änderung von RG dann verhält sich dieses Fahrzeug einfach anders als zuvor. 
Was wir prüfen können ist, haben State Systeme sich bei diesem Fahrzeug verändert?
Dies wurde geprüft, hier gab es keine Änderungen. 

Aussagen wie "Fahrzeug XYZ ist nun langsamer, als zum Datum XX.XX.XXXX" oder noch viel schlimmer "Fahrzeuge mit Drift Reifen sind nun langsamer" Bringen absolut Garnichts, null, noch viel weniger als Garnichts. 
Es spielen wie oben erwähnt so viele Faktoren eine Rolle. (Wetter, Reifen, Tuning, Verschleiß, Km, ...)
In 90% der Fällen würde ich euch empfehlen einmal nach New York zu fliegen und hier bei RG nachzufragen warum weshalb und wieso. (Wenn das einer von euch machen will, melde euch bei mir. Ich hätte da auch die ein oder andere Frage an RG....)

Spaß bei Seite.

Wir haben die Möglichkeit das betroffene Fahrzeug auf dem Dev Server einmal zu testen und zu schauen ob das von uns gewollte Verhalten der Drift Reifen an diesem Fahrzeug vorliegt. So wie ich Vito kenne, hat er das auch gemacht und vermutlich nicht nur einmal.

Aus diesem Grund tut es mir leid wenn sich das Fahrzeug nun anders fährt, aber die Zeit die ich in diesen Beitrag und die internen Diskussionen hierfür verwendet habe, hätte ich lieben gerne in andere System gesteckt. Die aktuellen Resourcen lassen es nicht zu hier jede Änderung von RG via State Mittel noch anzupassen das es eben wie zuvor gewesen ist.

Zum Schluss, die Vermutung das hier RG etwas an diesem Fahrzeug verändert hat ist auch nur eine Vermutung.
Als logische Schlussfolgerung da wir nichts daran verändert haben.

In diesem Sinne.

**Comment by TeubyDE** [comment]
Bevor ich es vergesse. Wenn es hier von irgendjemanden noch Gesprächsbedarf gibt. Meldet euch gerne per Discord bei mir!
Das gilt generelle, gibt es Gesprächsbedarf dann meldet euch gerne bei der jeweiligen Person. Ich kann es nur immer wieder betonen!
