### ISSUE TITLE
Alle Schränke in Hotelzimmern plötzlich leer. Was nun?

### ISSUE THREAD

**Issue by GekkoLilly** [eiksch/statev_v2_issues#2566]
**Character Name**
Susi_Wagenhorst

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Bemerkt am 14.8. um 23:20. Kontrolliert am 15.8 um 5:00 und 18.8 um 7:00. 

**Beobachtetes Verhalten**
Alle Schränke in meinen drei Hotelzimmern im Little Havana (JunAltaRew_Hotel_1) sind komplett leer.
Da ich zurzeit in Kanada leben und die Zeitverschiebung sowie andere Gründe dazu führen, dass ich weniger Zeit für RP habe, war ich davor zu letzt am 27.7 gegen 6-8 online. In der Zeit dazwischen müssen sich alle meine Besitztümer, die ich in fast 1,5 Jahren RP angesammelt habe, in Luft aufgelöst haben. 
Ich habe nur noch, was in meinen Inventar und meinen Autos war. In dem Zeitraum war auch das Hotelzimmer-Update, vllt hat das was mit dem Verschwinden zu tun.

**Erwartetes Verhalten**
Die Sachen im Schrank wieder finden. Also da, wo ich sie abgelegt habe.

**Schritte um den Fehler nachvollziehen zu können**
Ich hab mich eingeloggt, mich mega erschreckt, dass ich "nicht im gewohnten Hotelzimmer" aufgewacht bin. Dann rausgelaufen, um zu gucken, wo ich bin. Hab gesehen, dass das mein Hotel ist, bin zurück aufs Zimmer. Wollte mir ein anderes Outfit anziehen und bin zum Schrank. Hab mich wieder erschreckt.
Ich habe dann in allen Zimmern nachgeguckt und mich sofort im Support gemeldet. Dann noch mehrfach nachgeschaut und überprüft, ob meine Autos auch leer sind. Glücklicherweise sind nur die Hotelzimmer betroffen.
Da meine Sachen noch immer weg sind, melde ich mich nun hier.

**Optional: Video / Bilder des Fehlers**
Hier Bilder von den leeren Schränken. Ich kann aber nicht sagen, wer zu welchem Zimmer gehört.
https://pic.statev.de/image/w2NJc

![Grand Theft Auto V Screenshot 2022 08 14 - 20 03 52 79](https://user-images.githubusercontent.com/111252190/185344245-d4097fe5-3293-400a-8079-1c5a8ed9516b.png)

**Comment by Dean-Gallagher** [comment]
Blende mal marker ein. Es gab ein Update vor kurzem. Du hast nun 3 Lager im Zimmer/Haus.

**Comment by GekkoLilly** [comment]
> Blende mal marker ein. Es gab ein Update vor kurzem. Du hast nun 3 Lager im Zimmer/Haus.
> 
> Kleiderschrank und Kühlschrank wie du zeigst sind die neuen, diese sind standartmässig leer. Du must im eigendlichen lager nachsehen. Dieses ist unter dem TV.

Das hört sich einfach an. Lustigerweise hat das keiner gesagt oder gefragt. Hatte mich da schon mit ner Hand voll Leuten drüber unterhalten x`D

**Comment by GekkoLilly** [comment]
Dann ist das Problem behoben.
