### ISSUE TITLE
Mule Buggt beim auspacken im boden fest 

### ISSUE THREAD

**Issue by NitroDog119** [eiksch/statev_v2_issues#2568]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Bernd Shoemaker

**Auftrittszeitpunkt (Datum / Uhrzeit)**

23:45 am 18.08.2022
**Beobachtetes Verhalten**

Beim ausparken meiner mule buggt sie im boden fest und kippt auf die seite und mann kann sie nicht mehr aufstellen es ist am flughafen die garage 
**Erwartetes Verhalten**

sie soll normal auf den rädern landen 
**Schritte um den Fehler nachvollziehen zu können**

ich gehe zum park wächter wähle die mule aus parke sie aus und im anschluss buggt sie im boden fest und kippt um 
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
](url)

**Comment by TeubyDE** [comment]
Hast du nen Video davon? @NitroDog119

**Comment by DrGrizzlY17** [comment]
einfach die höhe bissel hoch setzen

**Comment by NitroDog119** [comment]
#2568 ich soll noch mal drauf verweisen das es wieder passiert ist sie ist wieder in den boden gebuggt das mein video nur noch ton hat bringt es hier leider nicht weiter
