### ISSUE TITLE
Kann nurnoch 2 Seeds einpflanzen (egal welche Sorte)

### ISSUE THREAD

**Issue by deehoe** [eiksch/statev_v2_issues#2569]
Character Name
Jayden Down

Auftrittszeitpunkt (Datum / Uhrzeit)
vor ein paar Wochen

Beobachtetes Verhalten
Ich habe 3 Seeds eingepflanzt, 2 davon waren Aloe Vera und einer Hanf. Diese hab ich über Nacht wachsen lassen und am nächsten Tag war die Hanfpflanze verschwunden. 
Daraufhin wollte ich neue Seeds einpflanzen, aber ich kann seitdem nurnoch 2 Seeds einpflanzen.

**Comment by DonVitoDiangelo** [comment]
Ok, kannst du dann nochmal versuchen. Wir haben die Dritte alte Pflanze mal rausgenommen. Wenn du auch mal vergessen hast wo die war, kannst du auch gern in den Support kommen. Aber am besten immer merken, wo genau :)

**Comment by deehoe** [comment]
Okei danke euch. 

also bei der Pflanze wusste ich zu 100% wo sie steht, da war sie eben nicht mehr :o 
Im Support war ich schon die haben mich hier her verwiesen.

**Comment by DonVitoDiangelo** [comment]
Ah ok, danke für die Info. Aber dann haben wir das geklärt. :)
