### ISSUE TITLE
Werkstatt -> selbst keine Rechnung ausstellbar

### ISSUE THREAD

**Issue by Dean-Gallagher** [eiksch/statev_v2_issues#2570]
**Auftrittszeitpunkt (Datum / Uhrzeit)**
Random

**Beobachtetes Verhalten**
Spieler möchten sich selbst eine Rechnung ausstellen, können es aber nicht bzw das feld wo sie unterschreiben müssen taucht nicht auf. 
Da hilft nur ein Relog. 

**Erwartetes Verhalten**
Rechnung zum unterschreiben kommt an. 

**Schritte um den Fehler nachvollziehen zu können**
Random aber nur bestimmten Personen.

**Comment by SHaagmann** [comment]
Ist bei mir in letzter Zeit auch häufiger vorgekommen Char: Sven_Rosenbach Wekstatt: North Customs

**Comment by SHaagmann** [comment]
Gerade gesehen Dopplung mit #2212

**Comment by Dean-Gallagher** [comment]
closed doppel
