### ISSUE TITLE
Falsche Animation beim einsteigen / aufsitzen

### ISSUE THREAD

**Issue by Stiefel911** [eiksch/statev_v2_issues#2573]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Auftrittszeitpunkt (Datum / Uhrzeit)**
immer wenn die Waffe angelegt ist (Pistole)

**Beobachtetes Verhalten**
Beim einsteigen und aufsitzen von Fahrzeugen wird an Stelle des Tür schließen/ Lenker halten
die Waffe erst weggesteckt. Obwohl sie nicht ausgewählt wurde.

https://github.com/eiksch/statev_v2_issues/issues/2524#issuecomment-1198317658 <- dort hab ich es erst falsch erkannt

**Erwartetes Verhalten**
normales Türen schließen, einfaches aufsitzen ohne Verrenkung
so wie es ohne geholsterte Waffe der fall ist

**Schritte um den Fehler nachvollziehen zu können**
Pistole holstern einsteigen, und auf Bike setzten.

**Comment by Derison** [comment]
Das Problem ist (endlich) ab dem nächsten Update behoben.

Vielen Dank fürs Melden! :)
