### ISSUE TITLE
Außenbereich Luxury House Modern Design Art 

### ISSUE THREAD

**Issue by Knippsa** [eiksch/statev_v2_issues#2574]
Sicher bekannt und sicher auch aus Gründen gewollt, dass o.g. Einrichtung nun nicht mehr nach Außen hin betreten werden kann. Dennoch für alle Besitzer die ich meine es waren 50k oder mehr ausgegeben haben, weil es schliesslich auch mit Pool etc. angeteasert wird, nun eine echte Enttäuschung. 
Vor einer Woche noch einen schönen Bingo Abend dort machen können, nun geschlossen. 

Sofern es etwas mit dem Zugang zur gesamten 2. Dimension zu tun hat, wären andere unsichtbare Hürden o.ä. sicher auch eine Möglichkeit. So mindert es nun die Immobilien erheblich. 

Mir persönlich, der sein Haus eigentlich gerade verkaufen will, fehlt nunmehr einiges an Argumentation.

Daher wäre ich über eine Info bzgl. der Zukunft dieses Interieurs sehr froh.

**Comment by Statev-Bonsai** [comment]
schau hier mal rein.. https://github.com/eiksch/statev_v2_issues/issues/2458

**Comment by Dean-Gallagher** [comment]
[Changed] Man kann das Luxury House Modern Design Art nichtmehr verlassen

https://statev.de/forum/thread/13777-v2-3-11-19-08-2022/?postID=127001#post127001

**Comment by CaleighRhodes** [comment]
Naja, Knippsa, uns Besitzer des Luxury House Rustikal Design Art hat das Ganze schon vor ein paar Monaten getroffen. Finden wir auch nicht so pralle, da unsere Ausstattung gleich mal 100 k kostet (oder 80, ich glaube aber 100), aber somit ist jetzt wenigstens ausgleichende Gerechtigkeit drin.

In dem von Bonsai angegebenen Ticket wurde das mit Abuse-Gefahr begründet - die war bei meinem Interior nicht gegeben, da man weder per Tor, noch per Tür das Grundstück verlassen konnte.

Bei eurem Interior konnte man aber, wenn man wollte, in einer zweiten Dimension durch die ganze Stadt wandern.

**Comment by TeubyDE** [comment]
Lieber @Knippsa 
Wie @Dean-Gallagher  schon korrekt verlinkt hat, ist dies ein gewollter Change. Der Bug Tracker ist nur für Bugs.
Für einen Vorschlag würde ich dich bitte das Forum zu nutzen.

Ich bin mir nicht sicher was genau du für eine Info bezüglich dieses Interieurs dir erhoffst.
Jedoch kann ich dir sagen das es nicht mehr gewollt ist in einem Innenraum eines Hauses einen Garten mit blick auf 
eine komplett andere Nachbarschaft zu haben. Andere unsichtbare Hürden, würde diesen Anspruch nicht erfüllen.
