### ISSUE TITLE
Per E-Mail an Handy Nr. Schreiben

### ISSUE THREAD

**Issue by SHaagmann** [eiksch/statev_v2_issues#2575]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Sven Rosenbach
**Auftrittszeitpunkt (Datum / Uhrzeit)**

Immer
**Beobachtetes Verhalten**

Man kann eine Konversation zwischen einer Email Adresse und einer Telefonnummer erstellen und nutzen.
**Erwartetes Verhalten**

Es sollte nicht möglich sein
**Schritte um den Fehler nachvollziehen zu können**

Die Handy Nr. in den Kontakten bei der Email speichern und eine Konversation öffnen
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![image](https://user-images.githubusercontent.com/58612983/186145270-51b4362a-e89a-4cbd-ab8d-eadcb38aa9b0.png)

**Comment by epichalt** [comment]
Was soll denn daran ein Bug sein?? Es ist zwar nicht gängig, aber auch in Echt möglich.
IC ist es oft ein Ersatz für Verträge zw. 3 Personen, da es keine Mail Konversationen für mehr als 2 Personen gibt.

**Comment by DonVitoDiangelo** [comment]
jupp, alles fine
