### ISSUE TITLE
Motorrad Wester Reever Direkt Totalschaden beim Umfallen

### ISSUE THREAD

**Issue by DrCassado** [eiksch/statev_v2_issues#2576]
Ricardo Cassado

**Auftrittszeitpunkt (Datum / Uhrzeit)**
23.08.2022 ca 22 Uhr

**Beobachtetes Verhaltenn**

Die Wester Reever ist zum 2 mal ungefallen und hatte direkt wieder nen Rotes Motor Symbol

**Erwartetes Verhalten**
Fahrzeug ist beschädigt aber kein totalschaden nach reperatur (wurde direkt davor repariert und ausgelesen durch Dean bei der Werkstadt)

**Schritte um den Fehler nachvollziehen zu können**
Motorrad aufschleießen wen man daneben steht es fällt um und ist kaputt

**Comment by PlayInc89** [comment]
Ist auch bei der Shinobi so

**Comment by DrCassado** [comment]
gegen 0 uhr ist einer leicht vorbei gerrannt und es fing wieder an zu rauchen (motorrad hatte sich leicht gedreht aber ist nicht umgefallen) heißt hatte 3 reperaturen ohne einen einzigen wirklichen unfall. das kann es doch nicht sein

**Comment by DonVitoDiangelo** [comment]
shinobi reever fixed next update

**Comment by DrCassado** [comment]
danke für die schnelle Problemlösung :)
