### ISSUE TITLE
Einbruch kann nicht abgeschlossen werden

### ISSUE THREAD

**Issue by Derison** [eiksch/statev_v2_issues#2578]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**: Drake_Price

**Auftrittszeitpunkt (Datum / Uhrzeit)**: 27.08.2022, ca. 00:40 Uhr

**Beobachtetes Verhalten**: Bei dem Einbruch in ein bestimmtes Interior kann man den Auftrag nicht abschließen, da sich ein bestimmter Punkt nicht abarbeiten lässt, da dieser mit dem Lager kollidiert. Siehe dazu das Bild.

**Erwartetes Verhalten**: Der Punkt kann abgearbeitet werden, damit man den Auftrag abschließen kann.

**Schritte um den Fehler nachvollziehen zu können**: Einbruch in das entsprechende Interior. Kann leider nicht genau nachvollziehen welche Stufe. Es handelt sich aber um die Wohnung von Lester in der GTA-Story.

**Optional: Video / Bilder des Fehlers**

![GTA5_k94DI4ihUh](https://user-images.githubusercontent.com/40345051/187000699-ae22ea7d-33db-4148-bc60-c820683ec5d9.png)

**Comment by DrGrizzlY17** [comment]
Hatte ich gestern auch, hab schon gefixed :) fixed next update
