### ISSUE TITLE
Motorrad Tuning benötigt zu viele Felgen

### ISSUE THREAD

**Issue by 48619** [eiksch/statev_v2_issues#2579]
**Beobachtetes Verhalten**
Das Tuning am Motorrad benötigt 4 Felgen statt 2.

**Erwartetes Verhalten**
Da am Motorrad nur 2 Räder vorhanden sind, dass auch nur zwei Felgen benötigt werden.
Bei der Bereifung werden auch nur 2 benötigt, was das ganze noch verwirrender macht.

**Schritte um den Fehler nachvollziehen zu können**
Werkstatt aufsuchen und im Tuning unter Felgen und Bereifung schauen.

**Comment by TeubyDE** [comment]
Wird beim nächsten update dann korrekt berechnet.
