### ISSUE TITLE
alte Hypercars nicht möglich zu bauen

### ISSUE THREAD

**Issue by epichalt** [eiksch/statev_v2_issues#2580]
Santito Quintero

**Auftrittszeitpunkt (Datum / Uhrzeit)**
seit dem Fahrzeugherstellungs/Verschleiß Update

**Beobachtetes Verhalten**
die alten Hypercars, RSX, D10 und Tigon benötigen so viel Materialien welche gar nicht in die Maschine passen. Ein Bau kann daher nicht stattfinden.  1500 Rollen Stoff und 4000 Gummi sind bereits 6500kg, während nur 5000 Kilogramm in die Maschine passen. 

**Erwartetes Verhalten**
Fahrzeuge sollten möglich zu bauen sein. 

![image](https://user-images.githubusercontent.com/16436981/187054952-6bc5c5eb-1fc5-4733-b55a-c1d7db608f5e.png)

**Comment by TheOutburst** [comment]
ich würd das gerne als Legacy Bug einstufen, das ist jetzt ein Jahr lang nicht aufgefallen :D
Fixed next update

**Comment by Statev-Bonsai** [comment]
> ich würd das gerne als Legacy Bug einstufen, das ist jetzt ein Jahr lang nicht aufgefallen :D Fixed next update

den bug gibt es noch nicht ein jahr... das muss mit den letzten patches passiert sein..
wenn ihr das ändert dann macht den bauplan UNBEDINGT wie er vorher war, sonst verlieren die bereits gebauten 1,5 millionen hypercars enorm an wert!

**Comment by epichalt** [comment]
@Statev-Bonsai 
Habe eben mal meine Listen verglichen. Den Bug gibt es auf jeden Fall seit der Produktionsumstellung zum Verschleiß Update. 
Es ist wohl nur keinem aufgefallen weil kein Hypercar mehr gebaut wurde. 
Der letzte RSX wurde am 08.09.2021 ersteigert
D10 am 20.06.2021
Tigon noch nie. 
Fahrzeugverschleiß kam am 25.10.2021

Ausnahme ist der Ignus, dessen Herstellung ist aber allgemein günstiger und es hat alles in die Maschine gepasst :D
