### ISSUE TITLE
Shinobi Probleme 

### ISSUE THREAD

**Issue by MarkusKumala** [eiksch/statev_v2_issues#2581]
Hi, ich fahre mit meinem Char Miguel Rivera unter anderem eine Shinobi. Derzeit besteht meiner Meinung nach das Problem das diese gefühlt aus Glas ist. Man läuft am Bike entlang ein Glas oder Blinker springt und sofort geht die Gelbe Lampe an Stellenweiße die Rote und das Bike brennt. Oftmals passiert das auch beim aufsteigen. Bin derzeit mit der Shinobi mindestens 1-2 mal am Tag in der Werkstatt. Denke hier müssten vielleicht mal die Werte angepasst werden. Am Anfang war dies definitiv nicht so besitze das Motorrad jetzt seit ca 3-4 Wochen. 

Liebe Grüße Miguel (Tobi)

**Comment by DonVitoDiangelo** [comment]
https://github.com/eiksch/statev_v2_issues/issues/2576
