### ISSUE TITLE
Bravado Rumpo nach ausparken aus Del Perro Garage kaputt(Motorkontrollleuchte an)

### ISSUE THREAD

**Issue by Wothor22** [eiksch/statev_v2_issues#2582]
Wothor Akori

Wothor Akori
**Auftrittszeitpunkt (Datum / Uhrzeit)**

nahezu bei jedem ausparken aus dieser Garage
**Beobachtetes Verhalten**

Motorkontrollleuchte nach ausparken an
**Erwartetes Verhalten**

normales ausparken ohne das das Fahrzeug schaden nimmt
**Schritte um den Fehler nachvollziehen zu können**

Fahrzeug aus dieser Garage ausparken
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by PlayInc89** [comment]
Was mir halt aufgefallen ist das die Fahrzeuge an sämtlichen Garagen schaden beim Ausparken bekommen, z.B. mein Hellion steckte beim Spawnen kurz im Boden und Stand dann da, mit Gelber Leuchte.

**Comment by TheOutburst** [comment]
mit letztem Update gefixt
