### ISSUE TITLE
Man kann sich im neu verschlossenen Interior durch ein Fenster wieder nach draussen buggen

### ISSUE THREAD

**Issue by WaDuTv** [eiksch/statev_v2_issues#2584]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Klaus_Kevin

**Auftrittszeitpunkt (Datum / Uhrzeit)**
02.09.2022 ca 21:15

**Beobachtetes Verhalten**
Im Interior "Luxury House Modern Design Art" befindet sich im unteren Geschoss im Ankleideraum ein Hocker. Vor dem Fenster stehen zwei Stühle. Wenn man am Fenster steht, hat man die Möglichkeit mit Y das "Hinsetzmenü" zu öffnen und sich auf die beiden äußeren Stühle zu setzen. Somit kann man sich durch das Fenster buggen und weiterhin den Garten benutzen. Ich denke, das sollte nicht möglich sein :)

**Erwartetes Verhalten**
Die beiden äußeren Stühle vor dem Fenster sollten keine Interaktionsmöglichkeit haben, so dass man sich nicht nach draussen buggen kann.

**Schritte um den Fehler nachvollziehen zu können**
Im Ankleideraum ans Fenster gehen, Y drücken und hinsetzen wählen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://gyazo.com/a3ef433b4be81771d2d313d138ca8c11

**Comment by TheOutburst** [comment]
Joa...
Wer für Bugusing gebannt werden möchte, nur weil er in ner eigenen Instanz in ner leeren Map rumrennen will, go for it.

Danke fürs Melden, aber das werden wir nicht fixen

**Comment by WaDuTv** [comment]
Es ging mir beim Melden tatsächlich weniger um das Bugusing, sondern dass das ungewollt passiert, weil der Hocker drinnen und die Stühle draussen eine zu geringe Entfernung zueinander haben. So ist es mir ja auch passiert, ich wollte mich drinnen auf den Hocker setzen, saß dann aber plötzlich draussen auf dem Stuhl. Und wenn man mal dort draussen ist, kommt man eben auch nicht mehr rein. Das nur als Klarstellung, weil dieses Problem in meiner Schilderung eventuell zu kurz kam. LG

**Comment by TheOutburst** [comment]
das versehentliche draufsetzen verstehe ich, den Würfel da drin hab ich gar nicht gesehen
Hab den mal nen halben Meter von der Fensterscheibe weg gedreht, ich denke das sollte reichen
