### ISSUE TITLE
Marker fürs Durchsuchen nicht gut platziert

### ISSUE THREAD

**Issue by Naaki6** [eiksch/statev_v2_issues#2585]
Owen Carter

**Auftrittszeitpunkt (Datum / Uhrzeit)**
22:20 Uhr 05.09.2022

**Beobachtetes Verhalten**

Letzter Marker beim Einbruch unglücklich platziert.

**Erwartetes Verhalten**

Bei dem Interior ist der letzte Marker genau bei dem Hausinventar Marker und dadurch kann man den letzten Punkt nicht durchsuchen und den Auftrag nicht abschließen.

**Optional: Video / Bilder des Fehlers**

![Grand Theft Auto V Screenshot 2022 09 05 - 22 23 54 44](https://user-images.githubusercontent.com/74776926/188509950-88da6009-5a7f-4cd7-b463-00092e88dc83.png)

**Comment by DrGrizzlY17** [comment]
Bereits fixed im nächsten Update und schon reported. Danke trotzdem :)
