### ISSUE TITLE
Fahrzeuge schliessen sich in Werkstatt beim Tuning

### ISSUE THREAD

**Issue by SgtTukiTuki** [eiksch/statev_v2_issues#2586]
Beobachtet mit Sandy Folk
in Gordon Customs

Wir können ja beim Tuning nun den Innenraum auch umgestalten. Seitdem das drin ist, schließen sich aber alle Türen des Fahrzeuges, wenn man in das Menü zum Tunen geht, … ist natürlich zum Gucken etwas schwierig, zumal es auch Fahrzeuge gibt, bei denen man den Motorraum umgestalten könnte!

**Comment by DonVitoDiangelo** [comment]
Das ist ganz normal und schon immer so :)

**Comment by Dean-Gallagher** [comment]
@DonVitoDiangelo nein ist neu, war früher nicht so.
