### ISSUE TITLE
Kanjo SJ lässt sich nicht überschreiben

### ISSUE THREAD

**Issue by epichalt** [eiksch/statev_v2_issues#2588]
Santito Quintero

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit dem Update heute. Vor paar Tagen funktionierte es noch

**Beobachtetes Verhalten**
Der Kanjo SJ im Autohaus bei Vinewood Cars lässt sich nicht mehr anmelden. 
Es kommt keine Fehlermeldung und nichts.

Andere Fahrzeuge wurden getestet da ging es. Ein-Ausparken hat nicht geholfen. Getestet mit 2 unterschiedlichen  Personen. 
Der andere Marker zum Überschreiben aufs Autohaus funktioniert, da spuckt er immerhin eine Fehlermeldung aus, dass das Fahrzeug bereits aufs Autohaus angemeldet ist (was es auch ist). 

**Erwartetes Verhalten**
Fahrzeug sollte man anmelden können

**Optional: Video / Bilder des Fehlers**
![image](https://user-images.githubusercontent.com/16436981/189400530-90c6f135-5fda-4104-8fcb-038b5231bb8a.png)

**Comment by epichalt** [comment]
Auch nach Serverneustart. Selbes Problem

**Comment by flogut4e** [comment]
Hatte eben selbiges Problem mit dem Rhinehart, kann nicht überschrieben werden. Corsita ebenfalls...

**Comment by Nuuki900** [comment]
Selbes Problem mit dem Vigero bei mir im Autohaus

**Comment by DonVitoDiangelo** [comment]
Sollte behoben sein, bitte erneut testen :)

**Comment by flogut4e** [comment]
@DonVitoDiangelo negativ, rhinehart klappt nicht

**Comment by epichalt** [comment]
ebenfalls negativ
