### ISSUE TITLE
Werbetafel Petrolstation20 nicht von Straße aus sichtbar

### ISSUE THREAD

**Issue by ChrisBranth** [eiksch/statev_v2_issues#2589]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

ChrisBranth

ChrisBranth
**Auftrittszeitpunkt (Datum / Uhrzeit)**

10.09.2022 01:26
**Beobachtetes Verhalten**
Die Werbung von der petrolstation20 in Paleto Bay ist nicht von der Straße aus sichtbar. 
Erst wenn man hinter die Zapfsäulen am Gebäude ankommt erscheint die Werbetafel.
Daher meine Frage: Könnt Ihr dies so ändern, dass man die Werbetafel bereits von der Straße aus sieht? Die Tankstelle ist ja relativ groß. So wie es jetzt ist, verfehlt die Werbetafel an dieser Tankstelle leider deren Zweck.

**Erwartetes Verhalten**
Werbetafel von der Straße aus sichtbar

**Schritte um den Fehler nachvollziehen zu können**
Hinfahren

**Comment by DonVitoDiangelo** [comment]
fürs nächste update gefixt

**Comment by ChrisBranth** [comment]
Hallo,

leider konnte ich keine Änderung feststellen. Die Werbetafel wird immer noch erst kurz vorm Gebäude sichtbar.
Selbst an den Zapfsäulen sieht man die Werbetafel nicht.
