### ISSUE TITLE
Doppelte Hauptkonten / doppelte Abbuchung Gebühr

### ISSUE THREAD

**Issue by VictorCorticera** [eiksch/statev_v2_issues#2591]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Gustavo Luciano

10.09.2022 / 12:50

Bei zwei meiner Firmen ist mir aufgefallen, dass es komischerweise nicht nur ein Hauptkonto, sondern mehrere gibt. Dementsprechend wird von jedem dieser Konten die Betriebsgebühr abgebucht.

Betriebsgebühr sollte nur einmal abgebucht werden / Es sollte nur ein Hauptkonto geben

Firmen prüfen:
cypressflats38
cypressflats29

![D1DC7C21-C560-49E0-80D2-338662676AF2](https://user-images.githubusercontent.com/28830176/189496662-cd96afbd-2c51-401b-a12f-bd581914a589.jpeg)
![AEF851CB-5FA6-455A-9C5C-DE4578C59C8A](https://user-images.githubusercontent.com/28830176/189496668-2233ba00-fad1-4a1d-8de5-e6e9eca008f0.jpeg)

**Comment by KingMarcel** [comment]
Fixed. Je ein Hauptkonto als HPT Konto entfernt
