### ISSUE TITLE
Wassserfz. einparken

### ISSUE THREAD

**Issue by Stiefel911** [eiksch/statev_v2_issues#2592]
Wasserfahrzeug nicht möglich einzuparken.

Siehe https://youtu.be/5yP6HXPX0e8

Denke es liegt an der Range.... so bald der Type am Land verschwindet ist ein einparken nicht mehr möglich.
Mit Dinghi besteht das Problem nicht.

**Comment by TheOutburst** [comment]
NPC & Marker spawnen dann next Update ein paar Meter früher rein
