### ISSUE TITLE
Golfbälle verschwinden, bleiben aber noch als platzierte Gegenstände liegen.

### ISSUE THREAD

**Issue by DepeaceDrey** [eiksch/statev_v2_issues#2593]
Depeace Drey

Auftreten:
Mehrfach, möchte ich jetzt aber nicht nochmal nachbilden, da ich sonst das selbe Problem wieder habe.

Beschreibung:
Wenn man Golf spielt und dabei der Ball in einen Baum gerät oder ins aus, verschwindet dieser (ist ja auch okay).
Das Problem ist, dass diese dann als platzierte Objekte liegen bleiben und ich dann keine anderen mehr platzieren kann und demensprechend das Golfspielen dann auch einfach nicht mehr möglich ist irgendwann.
(Ich habe kürzlich alle meine platzierten Golfbälle löschen lassen, entsprechend findet ihr diese bei mir nicht mehr)

Richtiger Ablauf:
Richtig sollte sein (meiner Meinung nach), dass die Bälle, die verschwinden und nicht mehr aufhebbar sind, gelöscht werden automatischen oder zumindest nicht mehr meinem Charakter zugeordnet werden.

Fehler nachbilden:
Ball ins die äußersten Hecken am Zaun schießen oder in die Baumkronen.

**Comment by CaleighRhodes** [comment]
Ist mir leider auch passiert, dadurch fehlen mir 2 von 10 Platzierungsplätzen. Könnte man diese via Support wieder erlangen? (Bei mir trat das allerdings beim Golf-Bug vor einiger Zeit auf, ist aber gestern beim Haus dekorieren aufgefallen).

**Comment by Hutstaender** [comment]
Hab ne Tutorial Nachricht eingefügt, das sollte es zukünftig beheben.

Wenn der Ball weg ist, einfach den nächsten anspielen.
