### ISSUE TITLE
Casino KartenBug

### ISSUE THREAD

**Issue by RizzolieHawk** [eiksch/statev_v2_issues#2595]
Rizzolie_Hawk

11.09.2022 / 22:55

Beim  Blackjack wurden mir die verdeckte 2. und 3. Karte durch einen Bug angezeigt.

Die folgenden Karten sollten nicht ersichtlich sein.

Blackjack im Casino spielen

Normale Auflösung

![20220911225501_1](https://user-images.githubusercontent.com/113313498/189549708-b6f8a158-6377-4e32-8dc0-d9ee37f7812d.jpg)

**Comment by KingMarcel** [comment]
https://gyazo.com/26b5701bd44ab230fb0d19ecc589fe7c

**Comment by TheOutburst** [comment]
mit diesem Update gefixt
