### ISSUE TITLE
Obey Omnis e-GT - Überschreiben funktioniert nicht

### ISSUE THREAD

**Issue by VictorCorticera** [eiksch/statev_v2_issues#2596]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Gustavo Luciano

11.09.2022 / 20:00

Obey Omnis e-GT lässt sich im Autohaus nicht auf eine Person überschreiben, bei anderen Fahrzeugen funktioniert es.

Fahrzeug lässt sich überschreiben.

Obey Omnis e-GT in Autohaus entpacken und anschließend versuchen auf einen Spieler zu schreiben. 
Wurde in diesem getestet: carShop17

**Comment by epichalt** [comment]
https://github.com/eiksch/statev_v2_issues/issues/2588
ist bei allen neuen Fahrzeugen aktuell so

**Comment by TheOutburst** [comment]
exakt, ist auch mitm nächsten Update gefixt
ich schließ das mal, weils so gesehen nen duplikat ist
