### ISSUE TITLE
New Era Caps Namensfehler 

### ISSUE THREAD

**Issue by epichalt** [eiksch/statev_v2_issues#2598]
Santito Quintero 

Vermutlich nicht sooo relevant, aber Caps Nummer 7,8 und 9 sind die Oakland A´s und nicht die Atalanta Braves. 
Zudem ist da noch das alte Logo der Cleveland Indians, welche jetzt Cleveland Guardians heißen. Das Team musste/wollte den Namen und das Logo, ähnlich wie die Washington Redskins, ändern. Da die Namen für viele rassistisch waren. 

Mich persönlich störts nicht und kein Plan ob es in Deutschland überhaupt wen interessiert :D 
![image](https://user-images.githubusercontent.com/16436981/190028085-3d4ed531-1cb1-4b38-b915-ef0200869893.png)

**Comment by Enemyaa** [comment]
Alles klar. DANKE. Habs geändert.
