### ISSUE TITLE
Abladepunkte zusammen legen 

### ISSUE THREAD

**Issue by epichalt** [eiksch/statev_v2_issues#2599]
Santito Quintero 

Vortec Industries  pfGroupAllRew_14
📦 Vinewood Cars Depot 📦 pfGroupAllRew_6

Bitte die Abladepunkte zusammen legen, da es beim linken Abladepunkt ständig zu Problemen mit der engen Straße dort kommt. Zudem steht man auch immer im Parkverbot, wenn man auf dem Abladepunkt ist.  Einfach nach rechts zu dem Abladepunkt von der Firma 📦 Vinewood Cars Depot 📦 pfGroupAllRew_6 würde auch QoL für mich bedeuten :D 

![image](https://user-images.githubusercontent.com/16436981/190035295-85c7662d-bc86-4979-a71a-3103a7f4053c.png)

**Comment by TheOutburst** [comment]
linker Abladepunkt ist dann next update zur Nebenstraße verschoben
