### ISSUE TITLE
Zugang Balkon & Dach

### ISSUE THREAD

**Issue by SCARFACEEEE** [eiksch/statev_v2_issues#2600]
Charakter Name:
Justin_Gering

Gibt es die Möglichkeit einen Teleportpunkt, von der Tür an der rechten Seite des Hauses,  zum ersten Stock zu bekommen und von dort aus aufs Dach ? Bei beiden Ebenen ist der Außen sowie der Innenbereich begehbar und mit Möbeln durch AltV ausgestattet.

Haushash:
SamsonCountryRew_Hous_18

Bild 1 : https://pic.statev.de/image/99bef6e3-eef9-4592-b02c-692ec7d6a57c.Ql6rs
Bild 2 : https://pic.statev.de/image/d40430c6-cf93-46f1-b9df-641049eb2d0b.QlH1t

**Comment by TheOutburst** [comment]
1. Danke für den Haushash, aber wenn der falsch geschrieben ist bringt der leider nur noch halb so viel

2. Das Haus ist nicht durch AltV mit Möbeln ausgestattet sondern durch den GTA Singleplayer. 

3. Wäre dort nur eine Dachterasse wäre ein Portpunkt kein Problem, aber durch das Singleplayer Snipermission Backdrop hättest du ein Haus, was einmal durch einen Hausmarker mit interieur und zusätzlich durch 1-2 Portmarker auch noch in der normalen Spielwelt mit einer anderen Ausstattung und Raumaufteilung bespielbar ist. Sowas ergibt im RP ja gar keinen Sinn
