### ISSUE TITLE
Fenster Bug

### ISSUE THREAD

**Issue by powerswissi** [eiksch/statev_v2_issues#2601]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Roger Thickle / Autonummer: STINGRAY

**Auftrittszeitpunkt (Datum / Uhrzeit)**

13.9.2022 19 Uhr + 14.9.2022 19,40

**Beobachtetes Verhalten**

Fenster sind unten obwohl Sie NICHT geöffnet worden sind 

Fenster kann man auch nicht zumachen .

**Erwartetes Verhalten**

Das die scheiben zugehen

**Schritte um den Fehler nachvollziehen zu können**

Coquette spawnen (STINGRAY) und ausprobieren 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Screenshot_9](https://user-images.githubusercontent.com/70152806/190225780-1d0929cc-1d69-40cf-a96e-1afdf7e563d4.jpg)

**Comment by SHaagmann** [comment]
Haste n paar mehr Informationen, was du vorher gemacht hast?

**Comment by powerswissi** [comment]
Ich hab das Auto gekauft

Die Fenster runtergemacht.. 

Wieder hochgemacht

Eingeparkt

Ausgeparkt - und dann war der "bug" da

die vorderen fensterscheiben bleiben nicht zu egal was ich tue..

**Comment by powerswissi** [comment]
https://clips.twitch.tv/OptimisticLuckyBurritoPeteZarollTie-rL-PBlmAcnmEsMgb


hier sieht mans auch

**Comment by UNDRCVRR** [comment]
@TeubyDE  @SHaagmann Ich habe das bei mehreren Fahrzeugen beobachtet. Generell scheint das Fenster runter/oben nicht sync zu sein. Bei mir sind teilweise die Fenster unten, obwohl sie oben sind für alle anderen.

**Comment by SHaagmann** [comment]
@UNDRCVRR Habe da selber schon aufm Liveserver und auf dem Dev Server rumprobiert bei mir ist's noch nie aufgetreten 🤔

@powerswissi @UNDRCVRR habt ihr irgendwelche Modifikationen drin?

**Comment by UNDRCVRR** [comment]
@SHaagmann Ich habe mit verschiedenen Modifkikationen gespielt, aber das spielt keine Rolle. Aktuell spiele ich auf Vanilla und hatte das Problem heute erst wieder, dass das bei mir nicht sync war. Das war keine Coquette, sondern ein SUV. Aber es betrifft tatsächlich mehrere Fahrzeuge. Idk wie man das reproduzieren kann, ich saß bisher immer mit mehreren Leuten im Auto und dachte, dass die Scheiben unten waren. Beim Regen wollte ich diese dann hochmachen und hab gemerkt, dass sie technisch schon oben waren. Das hin und her schalten hat auch nichts verändert - optisch blieben sie unten.

**Comment by powerswissi** [comment]
@UNDRCVRR nur reshade

**Comment by TeubyDE** [comment]
Ich bin der Meinung die Fenster in altv sind so lange sync bis jemand diesen einschlägt oder durch Schaden am Fahrzeug diese kaputt gehen. Die Frage ist aber, ob sich die Fenster gar nicht öffnen bzw. schließen lassen frisch nach dem ausparken.

wenn dies nicht der Fall ist. Können wir hier nichts machen.

**Comment by UNDRCVRR** [comment]
@TeubyDE Die Fenster lassen sich frisch nach dem Ausparken normal öffnen und schließen.

**Comment by powerswissi** [comment]
check kann ich bestätigen .. gerade getestet

**Comment by powerswissi** [comment]
Heute nach Serverrestart und das Auto ist draussen gestanden 
Fenster wieder auf!

![Screenshot_19](https://user-images.githubusercontent.com/70152806/203132274-4feda8d0-4062-4e5e-9a9e-279df0a2c5a1.png)

**Comment by SHaagmann** [comment]
Sobald man das Fenster aufgemacht hat kann man es zwar für sich zu machen aber sobald man in nem Interrior drinnen war ists wieder offen. Ist mir gerade nebenbei aufm Live Server aufgefallen

**Comment by powerswissi** [comment]
Ist mir heute aufgefallen.. Die Fenster waren zu.. aber man hört trotzdem die Windgeräusche.
Also ist zu auch nicht "zu"..

Also klingt komisch ist aber so

**Comment by TeubyDE** [comment]
Die Scheiben sind vermutlich von Grund auf nicht richtig gesynced. Müssten wir uns was custom einfallen lassen wie wir diese Syncen.

**Comment by TeubyDE** [comment]
Ist von altv nicht gesynced. Somit außerhalb unserer Möglichkeiten.
