### ISSUE TITLE
Klamottenbug

### ISSUE THREAD

**Issue by SatyriaDine** [eiksch/statev_v2_issues#2602]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Sofia_Black

**Auftrittszeitpunkt (Datum / Uhrzeit)**
15.09.2022

**Beobachtetes Verhalten**
Jede Leggings die ich meinem Char anziehe hat hinten links einen kleinen Texturfehler. Sieht so aus als würde die Textur der Leggings in den Char hineingehen. Besonders störend wenn man Bauchfrei tragen möchte. 

**Erwartetes Verhalten**
keine Texturenfehler

**Schritte um den Fehler nachvollziehen zu können**
Weiblichen Char eine Leggings (Beispiel: [F] Schwarze Leggings V2) anziehen. Hinten Links auf Höhe des Leggings-Bundes sieht man dann den Texturfehler

**Optional: Video / Bilder des Fehlers**
Leggings mit denen ich es unteranderem getestet habe:

![Screenshot_757](https://user-images.githubusercontent.com/84275938/190500453-6793f080-599f-4fc0-bf4d-eaed48182c55.jpg)

Beispiel mit schwarzer Leggings (V2)

![Screenshot_752](https://user-images.githubusercontent.com/84275938/190500695-fd4312c4-52d4-4626-bae5-13da48084c05.jpg)

Beispiel 2 mit Anime Leggings

![Screenshot_749](https://user-images.githubusercontent.com/84275938/190500815-61357d71-1974-42a4-baff-8b25601ac67f.jpg)

**Comment by CaleighRhodes** [comment]
Kann ich bestätigen, die einzige Leggings, bei der das nicht passiert, ist die von Adidas.

**Comment by Enemyaa** [comment]
Hi, ich kann das so bestätigen, aber ich weiß nicht richtig wieso. Gerade wenn du sagst, dass die Adidas Leggings noch gehen. Das Modell dahinter ist 1zu1 das selbe. 

Mal schauen... Danke für die Info

**Comment by Enemyaa** [comment]
Also auf GTA Online besteht das Problem aktuell auch. Einfach mal abwarten, ansonsten nehme ich sie vielleicht raus.

**Comment by CaleighRhodes** [comment]
Mittlerweile buggen an der selben Stelle, aber sehr viel kleiner, auch die Skinny-Jeans. Nur so zur Information.
