### ISSUE TITLE
Licht desync

### ISSUE THREAD

**Issue by JannikDatsch** [eiksch/statev_v2_issues#2603]
**Auftrittszeitpunkt (Datum / Uhrzeit)**
In den letzten Tagen

**Beobachtetes Verhalten**
Immer wieder wird bei fremden Fahrzeugen keine Beleuchtung gesynct, obwohl sie Licht anhaben.

Hatte es jetzt in den letzten Tagen mehrmals, dass ich Leute rausgezogen habe die aus meiner Sicht ohne Licht gefahren sind, obwohl sie Licht anhatten. Gabs früher ned und schon gar ned in der Häufigkeit.

**Comment by DonVitoDiangelo** [comment]
https://github.com/eiksch/statev_v2_issues/issues/2116
