### ISSUE TITLE
Fehlendes Fahrzeug Everon ?

### ISSUE THREAD

**Issue by KingMarcel** [eiksch/statev_v2_issues#2604]
Aus Ticket 0136 übernommen:

hätte ne Frage zu einem Auto, Wieso wird der Everon nicht auf State angebot? Hat das irgendwelche gründe? Der wagen selber ist ja schon etwas älter soweit ich weiss. 

Prüfen ob es Gründe für das nicht vorhanden sein gibt.

**Comment by DrCassado** [comment]
würde mich persönlich auch einmal interessieren. Der everon ist ein sehr schönes fahrzeug mit sehr viel tuning potential
