### ISSUE TITLE
Vapid Saddler Ich bitte um ein schnellen Fix

### ISSUE THREAD

**Issue by NicoleWitt** [eiksch/statev_v2_issues#2605]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Nicole Witt**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Am 17.09.22 14 Uhr nochwas 
**Beobachtetes Verhalten**

Klappert sehe Video 

**Erwartetes Verhalten**

Das sowas nach dem Ausparken oder generel weniger oder garnicht mehr auftaucht wenn man das Fahrzeug nichtmal beschädigt

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://youtu.be/ZqOcyP6UHrw

**Comment by NicoleWitt** [comment]
Eventuell was mir noch einfallen würde und aufgefallen ist,  das er ein zu harten kontakt zur Straße bekommt gerade bei Schlaglöchern oder Gullideckeln haut der ordentlich drauf

**Comment by TeubyDE** [comment]
Dann solltest du eventuell nicht mit 200 durch Schlaglöcher rasen ;)

**Comment by NicoleWitt** [comment]
Das war eine demontration damit man das hört ^^

**Comment by TheOutburst** [comment]
Ich hab mir das Video jetzt 3x angeschaut, was genau ist der Fehler?

**Comment by NicoleWitt** [comment]
https://youtu.be/vSX7Wo74zwg Hier hört er sich normal Heile an  :::: Und hier wiederum ist er Kaputt und Klappert wenn man ihn ausrollen lässt https://youtu.be/ZqOcyP6UHrw

**Comment by NicoleWitt** [comment]
Quasi im Heilen Zustand nirgendwo gegengeditsch und alles aber sobalt ich ihn heile einparke kommt er mit Klappern wieder raus versteh da nicht die logik und auf dauer weil wir ja damit stunden rumfahren ist es keine lösung jedemal nach dem ausparken in die werkstatt zu fahren

**Comment by DonVitoDiangelo** [comment]
Du hattest dazu bereits eine Antwort: https://github.com/eiksch/statev_v2_issues/issues/2487
