### ISSUE TITLE
Klamotten Bug, Aufschriften

### ISSUE THREAD

**Issue by TheBroady** [eiksch/statev_v2_issues#2606]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Noah Reese & Tom Barnaby

**Auftrittszeitpunkt (Datum / Uhrzeit)**
19.09.2022

**Beobachtetes Verhalten**
Wenn ich kleidung anziehe, sieht Tom Barnaby als auch ich bei ihm, immer andere Symbole auf der Kleidung.
 Das betrifft die Markenklamotten als auch normale GTA Kleidung

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
Meine Sicht:
![image](https://user-images.githubusercontent.com/70150887/190972297-766a64c8-17f0-41e0-913d-2bc94b35578c.png)
![image](https://user-images.githubusercontent.com/70150887/190972442-8407b636-d22b-4412-92a4-84648f7ffa98.png)

Sicht Tom:
![image](https://user-images.githubusercontent.com/70150887/190972410-8b07f58d-54e5-40c6-9db7-cba1c5dc5f4a.png)
![image](https://user-images.githubusercontent.com/70150887/190972528-eb0dd495-7b42-4cdb-bacb-b93a31ad9bce.png)

**Comment by Enemyaa** [comment]
Hi,

immer mal wieder hat das "EIN" Spieler. Wir wissen selber nicht richtig wieso, aber ich denke eine komplette Neuinstallation und der Verzicht auf mods hat anderen damit schon geholfen.

**Comment by Stiefel911** [comment]
es gibt ein Kleider-bug in GTA selbst, denke hat damit auch was zu tun. Dort wird das Tattoo was eigentlich unter dem Hemd ist, auf das Hemd projektiert, an stelle drunter zu lassen. ;)

**Comment by Enemyaa** [comment]
Ja, aber das haben ja sonst andere Spieler nicht. Es gibt das Problem auf jeden Fall auch durch NVE. Wir können da auf jeden Fall nicht nachhelfen.
