### ISSUE TITLE
Antrag auf Fixierung oder Entfernung der Möbel im Garten

### ISSUE THREAD

**Issue by eckbert58** [eiksch/statev_v2_issues#2609]
**Character Name**
Hector Cortez

**Ort/Lage**
Dunstable Lane 163
Haushash:  house_VinewoodHills_155

Guten Abend, ich wollte fragen ob es möglich ist die Objekte die auf dem Grundstück stehen zu fixieren. Man muss jedes mal genau aufpassen dass man keinen Stuhl zu weit verschiebt weil man sonst aus Sicht anderer direkt versetzt sitzt oder sogar wie im Bild zu sehen Möbel aus versehen zu weit schiebt und sie landen im Pool. Ist dies möglich oder gibt es da eine andere Möglichkeit?

Grüßee :)

**Optional: Video / Bilder des Fehlers**
![1333](https://user-images.githubusercontent.com/21086097/192115887-343d5818-a949-4471-b05b-41f143fc5c07.png)
![14](https://user-images.githubusercontent.com/21086097/192115892-8a93c14f-e6d7-4606-893a-a9bcede8bf15.png)

**Comment by DonVitoDiangelo** [comment]
Nein, wenn dann können wir dir diese nur entfernen und du setzt diese dann selbst.

**Comment by eckbert58** [comment]
Guten Morgen, das wäre perfekt! Dann stell ich mir da selber. 

Grüße!

**Comment by TheOutburst** [comment]
Aaaalso
Den Tisch kann ich dir wegmachen
Aber alles was eine Y Interaktion hat können wir zwar entfernen, aber sobald da jemand Y dran drückt ist das wieder sichtbar, das wäre im RP Sinn halt eher weniger Sinnvoll

**Comment by eckbert58** [comment]
okay ne dann macht das mit dem tisch entfernen keinen sinn. aber trotzdem danke!

**Comment by TheOutburst** [comment]
Danke fürs Verständnis, die beiden sind dann zum nächsten Update entfernt

**Comment by eckbert58** [comment]
> Danke fürs Verständnis, die beiden sind dann zum nächsten Update entfernt

Ich weiß ich bin mega nervig, kannst du bitte beide sonnenschirme entfernen? dann ist auch gut :-D

Grüße!

**Comment by TheOutburst** [comment]
geschlossener Schirm ist schon weg, der andere Schirm kommt dann next Update auch weg, ich schließe aber schonmal an der Stelle

**Comment by eckbert58** [comment]
<3 danke
