### ISSUE TITLE
Helmbug bei LSMD Kleidung

### ISSUE THREAD

**Issue by SvenPhoenix** [eiksch/statev_v2_issues#2611]
## WICHTIGE INFORMATION!!:
```
Ein Bugfix zum Mitnehmen bitte! 
```

**Sven Phoenix**

**24.09.2022 ca. 22 Uhr**

**Wenn man zum Beispiel die SAR oder TRU Kleidung trägt und anschliesend auf eine andere ,,normale" Kleidung ohne Helm wechselt sehen viele andere Spieler dann denn Helm der vorherigen Kleidung beim neuen Outfit.**

**Helme sollten sich Problemlos ohne Bug wechseln lassen. Kurzzeitig hilft es ne Mütze zu tragen aber leider nicht immer.**

**Hier ein Bild von der guten Anna Luna beim Tanzen mit Helmbug**

![grafik](https://user-images.githubusercontent.com/78278616/192122415-798e4483-db71-4b14-9bd7-dd4363431eb1.png)

**Comment by Enemyaa** [comment]
Wenn man sich über den Oufitter anzieht, sollte man keine normale Kleidung tragen. Ich denke mal wenn ihr einfach aus den Dienst geht oder das Oufit wechselt im Outfitter, gibt es dieses Problem gar nicht.

**Comment by Enemyaa** [comment]
Lässt sich nicht nachstellen auf dem DEV. Vielleicht mal außer Dienst gehen und rumspielen. Wüsste jetzt keinen Anhaltspunkt, wenn wir es nicht mal bestätigen können.

**Comment by DrCassado** [comment]
selbiges problem mit den taser, wen man einen taser vor den sar getragen hatt ist man nach den sar resporn wieder mit einen an der hüfte, und ich kann aus eigener erfahrung sagen das es mega weird ist wen man keinen taser mehr dabei hatt aber in die zellen muss weil man ja einen taser an der hüfte sieht und man den nicht wegbekommt.
