### ISSUE TITLE
Tankstellen Ausblendung

### ISSUE THREAD

**Issue by Esry84** [eiksch/statev_v2_issues#2612]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Esry Grafenhorst

**Auftrittszeitpunkt (Datum / Uhrzeit)**
25.09.2022

**Beobachtetes Verhalten**
Tankstelle wird bei nichtbetrieb immernoch auf der Karte angezeigt, ich dachte alle Spezialobjekte werden ausgeblendet auf der Karte.

![Grand Theft Auto V Screenshot 2022 09 25 - 13 34 37 37](https://user-images.githubusercontent.com/93259918/192141586-bbe891c3-0d8a-41a6-9a02-a711256e69c8.png)

**Comment by KingMarcel** [comment]
Wir blenden die Objekte je nach Bedarf manuell aus.
Da diese Tankstelle aber wieder in Betrieb genommen werden soll, wurde sie wieder eingeblendet.

**Comment by Esry84** [comment]
Ah ok, wollt es nur anmerken, damit die User nicht leere Tankstellen anfahren ;)

**Comment by KingMarcel** [comment]
Passt. Danke für die Info
