### ISSUE TITLE
Kofferrauminhalt wird nicht angezeigt

### ISSUE THREAD

**Issue by RudiRanger** [eiksch/statev_v2_issues#2613]
**Character Name**
Rudi Ranger

**Auftrittszeitpunkt (Datum / Uhrzeit)**
seit 25.09.2022, 23 Uhr, immer noch

**Beobachtetes Verhalten**
Eine andere Spielerin ist in mein geparktes Auto gefahren, vermutlich wurde es ihr nichts angezeigt.
Ich konnte bis zum Restart am 26.09 um 15 Uhr nicht ins Auto einsteigen, oder den Kofferrauminhalt aufrufen.
Nach dem Restart kann ich wieder einsteigen aber den Kofferrauminhalt kann ich weiterhin nicht einsehen.

**Erwartetes Verhalten**
Kofferraum geöffnet -> Taste "I", Kofferrauminhalt wird angezeigt

**Schritte um den Fehler nachvollziehen zu können**
Geht bei mit bei allen Fahrzeugen bis auf meinen Elegy RH8

**Comment by NDRCVRR** [comment]
@TeubyDE Ist nicht reproduzierbar auf dem DEV, hab's getestet mit zwei Fahrzeugen. Hab bisher auch von niemand anderem gehört, dass dieses Problem existiert. Denke mal, dass es sich hierbei eher um ein Positions/Desync Bug handelt, dass das Fahrzeug eventuell Server-Side woanders steht als Client-Side und deswegen kein Zugriff auf den Kofferraum möglich ist. Any other ideas?

**Comment by TeubyDE** [comment]
jein. denke is ne einmalige sache.
