### ISSUE TITLE
Truffade Thrax Geschwindigkeit/ Beschleunigung im Vergleich 

### ISSUE THREAD

**Issue by eckbert58** [eiksch/statev_v2_issues#2615]
**Character Name**
Hector Cortez

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Jederzeit

**Beobachtetes Verhalten**
Der Truffade Thrax schafft es kaum bis garnicht bei den gängigen Supersportlern mitzuhalten, selbst die die zum teil "nur" 320 PS
haben lassen den Thrax spätestens im dritten gang stehen. Getestet gegen T20, Entity XXR, Infernus, Truffade Nero. Ohne Bodenwellen ist meist bei 248 Schluss wo andere mit selber Bereifung (UHP) nochmal mit Schub vorbei ziehen. Ich frage mich ob das beim Thrax gewollt ist, da dieser mit einem Motorpreis von über 240 Tausend und 419PS doch eigentlich mindestens genauso sportlich fahren sollte.

**Erwartetes Verhalten**
Der Thrax fährt genauso schnell wie andere Supersportler in seiner Preisklasse (ähnlich wie Emerus, Autarch, Krieger).

**Schritte um den Fehler nachvollziehen zu können**
Thrax gegen andere Supersportler testen. 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
Kein NVE oder andere Mods.

**Optional: Video / Bilder des Fehlers**
-

Beste Grüße!

**Comment by epichalt** [comment]
https://github.com/eiksch/statev_v2_issues/issues/1803
https://github.com/eiksch/statev_v2_issues/issues/1837

**Comment by eckbert58** [comment]
> #1803 #1837

Oh stimmt, da war ja was. Naja schade einen versuch wars wert.
