### ISSUE TITLE
Entlade/Belade Punkt verschieben

### ISSUE THREAD

**Issue by MrsPxtn** [eiksch/statev_v2_issues#2616]
Mila Paxton

**Auftrittszeitpunkt (Datum / Uhrzeit)**
24/7 :D 

**Beobachtetes Verhalten**
An 3 Firmen nervt mich der entlade bzw belade Punkt. Man fährt mit den Fahrzeugen gegen Bäume oder Strom und Briefkästen.

**Erwartetes Verhalten**
Punkte verschieben :3 

**Schritte um den Fehler nachvollziehen zu können**
Firma 1. > Hash pfJunRockFordHillsRew_14   |  Morningwood Blvd. 5087
Entladepunkt nach Links verschieben, so dass der Riesenbaum kein Schaden an Pounder oder Achsen verursacht.
[https://gyazo.com/74a95f429c0b95f46fe66eaad95d3ae7](url)
Könnte man den Hydranten auch entfernen ? Falls ja, bei der Gießerei bitte auch.. > Hash  pfEveMorningwoodRew_2

Firma 2. > Hash pfJunRockFordHillsRew_13 | Morningwood Blvd. 5086 
Entladepunkt nach Links verschieben ( auch die Einfahrt Möglich )
[https://gyazo.com/88cdb36d41f988d4352f1dc4dd3e7a69](url)

Firma 3. > Hash pfEveMorningwoodRew_7  | Morningwood Blvd. 24
Entladepunkt nach Rechts verschieben, so dass der Riesenbaum kein Schaden an Pounder oder Achsen verursacht.
[https://gyazo.com/ccfc561180487e75882e7e138926a7b3](url)

**Optional: Video / Bilder des Fehlers**
![ccfc561180487e75882e7e138926a7b3](https://user-images.githubusercontent.com/87946968/193413983-5131a126-dd8e-4aa3-80ec-76b8b9a0a3bc.jpg)
![74a95f429c0b95f46fe66eaad95d3ae7](https://user-images.githubusercontent.com/87946968/193414006-0f577a71-6461-40dc-8448-48e10048fe86.jpg)
![88cdb36d41f988d4352f1dc4dd3e7a69](https://user-images.githubusercontent.com/87946968/193414012-a8e8934f-98cf-4484-9e5a-2a55bfe21f16.jpg)

**Comment by TheOutburst** [comment]
Ich hab Firma 1 & 2 auf den selben Punkt in die Gasse gepackt, ich würde recht ungerne nur für nen Abladepunkt nen Hydranten weg machen.
Firma 3 ist der Punkt next Update auf Höhe der Stühle, ich hoffe das reicht.
