### ISSUE TITLE
Interaction nach Fahrzeug schieben nicht mehr möglich

### ISSUE THREAD

**Issue by ManuelLadner** [eiksch/statev_v2_issues#2620]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Manuel_Ladner**

**Täglich beim Ausführen!**

**kann keine Marker mehr anwählen oder durch Türen porten --- e taste funkt nicht mehr wenn man vorher ein Fahrzeug geschoben hat**

**nachdem wir die Fahrzeuge auf den reparierpunkt schieben , sollte man auch reparieren können! leider muss man sich immer ausloggen und wieder einloggen**

**fahrzeug schieben danach versuchen zu reparieren oder eine tür zu betreten**

**normal**

**keine weiteren**

**Comment by UNDRCVRR** [comment]
@ManuelLadner Ich kann den Bug bestätigen. Für den Moment hilft nur ein Relog als Workaround, aber wir werden uns das anschauen und zeitnah sicherlich einen Hotfix bereitstellen. Danke dir fürs melden.

**Comment by ManuelLadner** [comment]
vielen Dank für die schnelle lösung!
