### ISSUE TITLE
Werbeschild am 24/7 sieht man nicht

### ISSUE THREAD

**Issue by LanabobanaTTV** [eiksch/statev_v2_issues#2621]
Lana Winters

✨🛒 SPÄTI 🛒✨ - Prosperity Street 12
Firmenhash  ''shop6''

Man sieht das Werbeschild oben links nicht obwohl man direkt vor dem Laden steht, es ploppt auf der Straße nur im Hinterhof auf (aber da sehen es die Kunden nicht )

Bitte das Werbeschild so machen, dass es angezeigt wird, wenn man vor dem Laden ist

![vierundzwanzigsieben](https://user-images.githubusercontent.com/86558691/193874994-7ef821b0-0de9-4615-b81e-79e5f5787a5d.jpg)

dankeschön :)

**Comment by TheOutburst** [comment]
Das Werbeschild hängt technisch an dem An-/Verkaufspunkt des Stores, der ist nunmal am hinteren Ende des sehr tiefen Gebäudes.
Ich habe den Punkt + Abladepunkt mal nach vorne Verschoben (siehe Screen)

https://i.imgur.com/j9TxEnQ.jpeg

Außerdem hat es mich schon immer getriggert, dass die Mapicons nicht am 24/7 Eingang sind, hab das mal bei allen 24/7 angepasst.

Kommt dann zum nächsten Update.
