### ISSUE TITLE
Shitzu Longfin (Boot) keine Neuanmeldung möglich

### ISSUE THREAD

**Issue by epichalt** [eiksch/statev_v2_issues#2622]
Santito Quintero

**Beobachtetes Verhalten**
Shitzu Longfin (Boot) im Autohaus nicht möglich zu überschreiben.

**Erwartetes Verhalten**
neues Boot ins Autohaus Lager packen. Anschließend sollte es normal überschrieben werden können. 
Dies ist allerdings nicht möglich. Boot konnte nur wie ein normales Fahrzeug ausgeparkt werden.

**Comment by Dean-Gallagher** [comment]
https://pic.statev.de/i/QDskc.png

**Comment by JonnyHart** [comment]
Muss man nicht den Flatbed auf dem Punkt stehen haben? (Nur bei Booten)

**Comment by epichalt** [comment]
nein

**Comment by TeubyDE** [comment]
Ich bin der der Meinung es gibt einen extra NPC um das mit den Booten zu handeln. Das sollte nicht über das Autohaus laufen.
@UNDRCVRR Kannst du das bitte einmal prüfen?

Details in Discord PN

**Comment by epichalt** [comment]
jaein

Neue Boote werden zunächst im Container ins Autohaus Lager gelegt. Dann kann man oben an der Kasse das Boot auf eine Person schreiben.  Anschließend packt man den Container wieder auf den Flatbed und fährt zum NPC. Dort wird das Boot zu Wasser gelassen. 

Der andere NPC macht Boots Überschreibungen.

**Comment by TeubyDE** [comment]
Schein ein Problem mit der longfin zu sein. Das system is nicht bruch.

Danke @Dean-Gallagher und @epichalt  für die Erklärung, wusste selbst nicht wie das genau geht.

**Comment by TheOutburst** [comment]
Ich sag mal so: man lernt nie aus. Bug ist gefixt, der Longfin wird jetzt wie jedes andere Boot als Boot gehandhabt
