### ISSUE TITLE
Schmink Stuhl defekt???

### ISSUE THREAD

**Issue by StateV2Marie** [eiksch/statev_v2_issues#2624]
Nach besuch von einen kunden merkte ich das der schminkstuhl nich funktionierte weder kunde noch ich sahen die schminke im gesicht bei ihm trotzdem beide relog gemacht haben blieb die schminke denoch aus ist vll der stuhl defekt? oder woran kann es liegen?? gestern abend c.a 23 uhr rum ging noch alles.

mfg: von O Sheas Barber Shop in Sandy Shoes

**Comment by Enemyaa** [comment]
@StateV2Marie haste mal geguckt wie hoch die Transparenz eingestellt war?

**Comment by StateV2Marie** [comment]
Haben Fest gestellt das es an Logan Martinez liegt bei anderen kunden funktioniert es und die transparent stand bei ihm auf max hab da nix verändert

**Comment by Enemyaa** [comment]
Ja gut, kannst halt nochmal bei ihm mit der Transparenz spielen. Ansonsten ist hier nichts defekt und deswegen schließ ich den Eintrag wieder.
