### ISSUE TITLE
In der Mühle auf die Stühle setzen geht nicht

### ISSUE THREAD

**Issue by Beartox** [eiksch/statev_v2_issues#2625]
**Character Name**
Tobias_Schlueter

**Auftrittszeitpunkt 
16.10.2022 / 12:09

**Beobachtetes Verhalten**
Kann mich in der Mühle nicht mehr auf die Stühle setzen

**Erwartetes Verhalten**
Das ich mich in der Mühle auf denn Stuhl setze

**Schritte um den Fehler nachvollziehen zu können**
an denn Stuhl stellen und dann y drücken kommt aber dann keine anzeige das man sich setzen kann

**Comment by Stiefel911** [comment]
https://github.com/eiksch/statev_v2_issues/issues/2597 doppelt
