### ISSUE TITLE
Verladepunkt verschieben

### ISSUE THREAD

**Issue by PinkyDog** [eiksch/statev_v2_issues#2626]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Henri_Dogg
**Auftrittszeitpunkt (Datum / Uhrzeit)**

Immer
**Beobachtetes Verhalten**

Verladepunk zwischen den Palmen
**Erwartetes Verhalten**

Bitte auf die Strasse verlegen
**Schritte um den Fehler nachvollziehen zu können**

man kann nicht endladen ohne sich das auto zu beschädigen
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![20221017090531_1](https://user-images.githubusercontent.com/96830992/196166403-72723822-8d5c-430b-b23b-06d2f92b2671.jpg)
![20221010201158_1](https://user-images.githubusercontent.com/96830992/196166471-e05fd05a-4033-4a38-9dfc-d2ae0aa0f504.jpg)

**Comment by PinkyDog** [comment]
Upps hab ich vergessen Nikola Ave.30   Hash   pfGroupAllRew_19

**Comment by epichalt** [comment]
Finds Wahnsinn, dass das jetzt erst bemängelt wird. Frage mich schon seit Monaten wie das dort betrieben wird^^
