### ISSUE TITLE
Bauantrag

### ISSUE THREAD

**Issue by Silkester0815** [eiksch/statev_v2_issues#2627]
Wie gewünscht überreiche ich hier noch einmal die Bauanträge ein.

https://docs.google.com/document/d/17T4QkzxKJ-bgLwxLeQH076OvjKnyd0ff-VT7bly42Q0/edit

https://docs.google.com/document/d/1FxuUF5aSG2BLSMHIAgxw_a09n-f6TMWpazsBew5LFAI/edit

mfg Klaus_Werner

**Comment by Enemyaa** [comment]
Nr.1 ist schon mal genehmigt

**Comment by Enemyaa** [comment]
Nr.2 muss ich leider ablehnen. Wir haben gar keine Hotelgaragen.
