### ISSUE TITLE
Laptop Verbauch bei ATM Raub

### ISSUE THREAD

**Issue by eckbert58** [eiksch/statev_v2_issues#2628]
**Character Name**
Hector Cortez

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Jederzeit

**Beobachtetes Verhalten**
ich brauche auf 8 Geldkassetten mittlerweile 3 Laptops und ein Brecheisen, und bekomme zum teil nicht mal eine Kassette wo andere mit einem Laptop bis zu 12 Kassetten rausholen. Das die Werte schwanken ist mir bewusst, aber ich verbrauche zum Teil einen Laptop pro ATM und frage mich was ich falsch mache? Ich hab jetzt vermehrt drauf geachtet wie mein Laptop verbrauch ist, und ich komme bei 10 Laptops auf nicht mal 48 Kassetten. Wäre echt schön wenn ihr euch das mal angucken könntet.
Mfg! 

**Erwartetes Verhalten**
Weniger Laptops auf mehr ATM´s? =D

**Schritte um den Fehler nachvollziehen zu können**
Da andere Spieler das Problem nicht so extrem wie ich haben keine Ahnung um ehrlich zu sein.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
egal

**Optional: Video / Bilder des Fehlers**
-

**Comment by DrGrizzlY17** [comment]
Hi Hector,
das Verbrauchen der Laptops hat keinen bestimmten Faktor, es ist einfach random. Manchmal hast du Glück und manchmal halt pech. Ging glaub jedem schonmal so, das ein Laptop einfach Gold war und man damit ewigkeiten knacken konnte und dann hat man an 2 ATMs 2 Laptops verbraucht. Das ist einfach random

Somit kein Fehler
