### ISSUE TITLE
Stacking von Taschenlampen

### ISSUE THREAD

**Issue by TheBroady** [eiksch/statev_v2_issues#2629]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Aiden Baxter

**Auftrittszeitpunkt (Datum / Uhrzeit)**
21.10.22

**Beobachtetes Verhalten**
Ich habe 5 Taschenlampen gekauft. Diese werden als 5er Stack im Inventar abgebildet.
Sobald man eine davon ausrüstet und wieder abrüstet, wird diese nicht mehr gestackt sondern einzeln angezeigt.
Es ist keine Alte Taschenlampe (mit Seriennummer wie früher)

**Erwartetes Verhalten**
Das sie dann wieder gestackt wird, oder von Anfang an nicht im Stack angezeigt werden.

**Schritte um den Fehler nachvollziehen zu können**
3 Taschenlampen kaufen, eine ausrüsten, wieder abrüsten.
-> 2 im Stack, eine einzeln.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![image](https://user-images.githubusercontent.com/70150887/197196316-085c44f1-47b0-4935-b257-15664c4c4db3.png)

**Comment by TheBroady** [comment]
Nachtrag:
Ich kann das Stack vom Ammunation splitten und dann fügt sich das wieder zusammen.
aber sobald ich eine ausrüste, ist es ein "eigen" Objekt und kann nicht gestacked werden.

**Comment by Stiefel911** [comment]
ja weil sie in diesem Moment als benutzt gilt ;)

**Comment by TheBroady** [comment]
Ja, Taschenlampen nutzen sich aber nicht ab.
Wieso dann also eine "benutzte" anders behandeln als eine neue.
ohne Sinn

**Comment by epichalt** [comment]
ist bei Fallschirmen übrigens genauso. Vermutlich bei allen Sachen, die man ausrüsten kann.

**Comment by SHaagmann** [comment]
genau so Reproduzierbar wie Broady es geschrieben hatte

**Comment by Erumeldor** [comment]
Um das hier auch zu erwähnen:
Das Problem hier ist denke ich dasselbe Problem wie auch mit den Brecheisen für die Hauseinbrüche.
https://github.com/eiksch/statev_v2_issues/issues/2564

**Comment by TeubyDE** [comment]
Weapon Items sind ab einem bestimmten Zeitpunkt unique.  Wie @Erumeldor schon geschreiben hat, ist das gleiche wie in #2564
