### ISSUE TITLE
Betriebskosten wurden nicht abgebucht.

### ISSUE THREAD

**Issue by PlexerPG** [eiksch/statev_v2_issues#2630]
**Character Name**
Paul Graham

**Auftrittszeitpunkt (Datum / Uhrzeit)**
24.10.2022 (normalerweise 3:30 Uhr)

**Beobachtetes Verhalten**
Bei allen Firmen, in denen ich Einsicht habe, wurden die Betriebskosten nicht abgebucht.

**Erwartetes Verhalten**
Betriebskosten werden automatisch abgebucht.

**Schritte um den Fehler nachvollziehen zu können**
Einsicht auf den Kontoauszug^^

**Comment by epichalt** [comment]
Gibt ja auch kein Strom und die HK liegt in Schutt und Asche. also naja :D

**Comment by Silkester0815** [comment]
Wegen event wird nix abgebucht. Alles gut :)

**Comment by KingMarcel** [comment]
Korrekt, kein Strom und fließend Wasser, keine Kosten ;)
