### ISSUE TITLE
Pattern not found bei kfz reperatur und game crash 

### ISSUE THREAD

**Issue by DaAlki** [eiksch/statev_v2_issues#2633]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Jack_Spooner

**Auftrittszeitpunkt (Datum / Uhrzeit)**
11:37 am 26.10.2022
 
**Beobachtetes Verhalten**
Klicke in der werkstatt auf reperatur und kästchen erscheint (pattern not found )  zahlen code please contact developers ink came crash 

**Erwartetes Verhalten**
Sollte normale reperatur möglich sein ohne game crash 

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://cdn.discordapp.com/attachments/411925103048392724/1034767301133742170/20221026_114746.jpg

**Comment by SHaagmann** [comment]
Habe mal die Sachen die du aus versehen auskommentiert hast anzeigen lassen, könntest du dennoch noch n paar mehr Informationen geben? Ist es dir erst einmal passiert oder schon mehrfach und was hast du genau gemacht als das aufgetreten ist?  Bist du selber dort angestellt und wolltest dich selber reparieren oder hat dir wer anders die Rechnung ausgestellt?

**Comment by DaAlki** [comment]
also ich bin dort angestellt! habe heute um 7:14 schon mal ein Fahrzeug repariert ! hatte diesen Fehler noch nie und ich habe mir die rechnung selber ausgestellt!  7:14 habe ich die sanchez repariert und danach ging ich dem rätsel wieder nach! und um 11:37 wollte ich den patriot reparieren! wenn ich hin gehe und quasi die rechnung ausstellen möchte kommt das bild was ich schon community support gebostet habe und spiel crasht! hat sich von alleine dann beendet

**Comment by SHaagmann** [comment]
Sollte eigentlich mit dem letzten AltV update (27.10 Mittag/Abend) gefixed worden sein. Falls es doch nochmal auftritt einfach wieder eröffnen oder einen neuen Erstellen.
