### ISSUE TITLE
Waffe ziehen bei MDler ohne Animation (Taurus)

### ISSUE THREAD

**Issue by Pregon** [eiksch/statev_v2_issues#2635]
**Character Name**
Ronny Roberts

**Auftrittszeitpunkt (Datum / Uhrzeit)**
27.10.2022 21:50

**Beobachtetes Verhalten**
Waffe ziehen bei MDler ohne Animation (Taurus)

**Erwartetes Verhalten**
Waffe ziehen bei MDler mit Animation (Taurus)

**Schritte um den Fehler nachvollziehen zu können**
Als Medic in den Dienst und Waffe ziehen (Taurus)

**Comment by Derison** [comment]
Vielen Dank fürs reporten! 🙂
Wird mit dem nächsten Update behoben
