### ISSUE TITLE
Fahrzeuge teleportieren sich weg

### ISSUE THREAD

**Issue by Erumeldor** [eiksch/statev_v2_issues#2636]
**Character Name**
Satoru_Tsuyoshi

**Auftrittszeitpunkt (Datum / Uhrzeit)**
28.10 ~14:05 (paar Minuten danach vielleicht)

**Beobachtetes Verhalten**
Auto am Würfelpark abgestellt. Kurz zum Würfelpark, danach zum MRPD, dann zurück zum "Auto", was dann aber nicht mehr da war.
Kennzeichen vom Auto (Bodhi): 46FIH689
Das Fahrzeug steht nun nach GPS an einem Punkt wo ich vor 20 Minuten etwa war und kurz ins Hotel rein und raus bin.

**Erwartetes Verhalten**
Auto soll sich nicht teleportieren

Ist wohl schon häufiger die Tage vorgekommen nach Erzählungen.

**Comment by Enemyaa** [comment]
@Erumeldor 

Ist das immer noch aktuell?

**Comment by Erumeldor** [comment]
@Enemyaa
Kann ich dir leider schlecht sagen. 
Bei mir war es während dem Event 1x, ich war die letzten Tage nach dem Event wenig online, da ist es aber nicht passiert.
Kann mich gerne nochmal hier melden falls es nochmal auftritt.

**Comment by TeubyDE** [comment]
Sollte das reproduzierbar sein und häufiger vorkommen kann gerne noch einmal ein eintrag erstellt werden.
