### ISSUE TITLE
Hauseinbruchsmarker an Position von Hausinventar

### ISSUE THREAD

**Issue by Erumeldor** [eiksch/statev_v2_issues#2638]
**Character Name**
Satoru_Tsuyoshi

**Auftrittszeitpunkt (Datum / Uhrzeit)**
31.10 - 11:00Uhr

**Beobachtetes Verhalten**
Hauseinbruch kann nicht abgeschlossen werden, der Schrank ist genau über dem letzten Sammelpunkt.

**Erwartetes Verhalten**
Punkt verschieben.

**Optional: Video / Bilder des Fehlers**
Bild des Hauses:
![image](https://user-images.githubusercontent.com/21212905/198982474-e13bf742-cf18-4f0b-8ee7-51792998179b.png)

Bild des falschen Punkts:
![image](https://user-images.githubusercontent.com/21212905/198982504-79a4053a-4a7d-4800-856c-d330dbc247c9.png)

**Comment by Dean-Gallagher** [comment]
https://github.com/eiksch/statev_v2_issues/issues/2585
