### ISSUE TITLE
Hausgarage hinzufügen

### ISSUE THREAD

**Issue by Knippsa** [eiksch/statev_v2_issues#2639]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Kalle Knutsen**

**Hallo zusammen, könnt ihr bei der Einfahrt vom Haus Carson Ave.32 eine Garage einrichten?
Sollte nicht zu weit hinten sein, da dort einige Haus-Elemente im Weg sein könnten.**

**Comment by SHaagmann** [comment]
Könntest du noch den Haushash hinzufügen?

**Comment by Knippsa** [comment]
Natürlich, sorry
house_EastLS_34
