### ISSUE TITLE
The North Face Jacken werden nicht richtig angezeigt.

### ISSUE THREAD

**Issue by Naaki6** [eiksch/statev_v2_issues#2641]
**Character Name**

Jalen Park

**Auftrittszeitpunkt (Datum / Uhrzeit)**

2.11.22 10:30 ca.
**Beobachtetes Verhalten**

Wie auf dem Bild zu sehen ist, werden einige der North Face Jacken nicht richtig angezeigt.
**Erwartetes Verhalten**

Werden richtig angezeigt.

**Optional: Video / Bilder des Fehlers**

![Grand Theft Auto V Screenshot 2022 11 02 - 10 25 22 11](https://user-images.githubusercontent.com/74776926/199459931-6c8bf777-3a50-4ed7-b6ab-1b89cf407582.png)
![Grand Theft Auto V Screenshot 2022 11 02 - 10 41 14 72](https://user-images.githubusercontent.com/74776926/199459950-d3add390-32e2-4897-9eef-52789bf542ae.png)

**Comment by SHaagmann** [comment]
Die werden richtig angezeigt. Sie sind so gedacht, dass sie in der Hose stecken (Frag nicht warum ist irgendwie so) und sehen nur noch weirder aus, durch deine Hosenwahl.

**Comment by Naaki6** [comment]
> Die werden richtig angezeigt. Sie sind so gedacht, dass sie in der Hose stecken (Frag nicht warum ist irgendwie so) und sehen nur noch weirder aus, durch deine Hosenwahl.

Die anderen werden aber ganz normal angezeigt das sind auch nur 2-3 Stück die so aussehen :D

**Comment by CaleighRhodes** [comment]
Ja, es gibt ja auch 3 verschiedene Modelle (zumindest bei den Frauen). Die mit der Bezeichnung Fleece im Namen werden alle so dargestellt, wie auf deinem Bild. Alle anderen sind "über der Hose"-Jacken. Oder cropped, bei den Frauenjacken.

**Comment by SHaagmann** [comment]
Das was @CaleighRhodes sagt 👌
