### ISSUE TITLE
HalloweenKeycard nicht wegwerfbar

### ISSUE THREAD

**Issue by SgtTukiTuki** [eiksch/statev_v2_issues#2642]
Sandy Folk

Sandy Folk und Alvaro Alvarez
**Auftrittszeitpunkt (Datum / Uhrzeit)**

02.011.2022 um 15.27Uhr
**Beobachtetes Verhalten**
HalloweenKeycard lässt sich nicht aus dem Inventar entfernen und ist nirgends hin verschiebbar

**Erwartetes Verhalten**
Das ich es in den Müll werfen könnte....

**Comment by SHaagmann** [comment]
Ist bekannt und wird heute mit dem Hotfix gefixxed
