### ISSUE TITLE
Fahrzeuge verschwinden beim Ein- Ausparken

### ISSUE THREAD

**Issue by epichalt** [eiksch/statev_v2_issues#2643]
Santito Quintero

In letzter Zeit nimmt es leider überhand, dass die Autos beim Ein- und Ausparken aus Autohäusern oder Werkstätten einfach verschwinden. Beim Einparken steht man dann einfach ohne Auto im Gebäude. Beim Ausparken ohne Auto vor dem Gebäude. 

Zudem ist der Ausparkpunkt dann jedes Mal blockiert. Manchmal bis zum Serverneustart, selten auch bis zum übernächsten Serverneustart (falls das Auto vorher bewegt wurde)

Es gibt einen ähnlichen Bugtracker, welcher allerdings mit Gamecrashes zusammen hängt. Hier gehts lediglich um den Teleportpunkt, dass das Fahrzeug in der falschen Dimension landet.

**Comment by UNDRCVRR** [comment]
@TheOutburst Das Problem hatten wir doch vor Ewigkeiten schon mal, erinnerst du dich noch woran das damals lag?

**Comment by epichalt** [comment]
> John Wright
> 
> Ich habe es in letzter Zeit sehr häufig, dass meine Nightblade mit dem Kennzeichen JOHN nicht mehr sichtbar ist. Heute logge ich mich ein und alle Fahrzeuge auf dem Los Malvados Place sind weg. Laut Ortung stehen sie aber noch genau dort.

das hat damit leider nix zu tun, sondern ist ein Atlv problem. Siehe
https://github.com/eiksch/statev_v2_issues/issues/2248
