### ISSUE TITLE
Event Ende aber sichtbare spuren

### ISSUE THREAD

**Issue by StateV2Marie** [eiksch/statev_v2_issues#2644]
Huhu das Event war mega doch leider hats spuren hinterlassen da einige ja alles makieren musten nur schwebt es leider noch in der luft 

[Bild](https://pic.statev.de/image/eventende.Tix6c)

einmal das bild das ihr seht wie es aktuell ausschaut.

**Comment by TeubyDE** [comment]
Zeug ist weg Danke
