### ISSUE TITLE
Bestimmte Klamotten nicht Herstellbar

### ISSUE THREAD

**Issue by PlayInc89** [eiksch/statev_v2_issues#2645]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Ryan_Valdes

**Auftrittszeitpunkt (Datum / Uhrzeit)**

04.11.22

**Beobachtetes Verhalten**

Die Weiblichen Boyfriend Jacken sowie die College Jacket w. Shirt für Männer sind zwar im Fashionkilla erhalten aber nicht mehr sichtbar im Produktion PC 
**Erwartetes Verhalten**

Klamotten sollten Herstellbar sein !
**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by PlayInc89** [comment]
Combat Oberteile sind auch nicht Produzierbar genau wie der [M] Juice WRLD † Hoodie

**Comment by Clawdie** [comment]
Gilt auch für die "Braune Fliegerkappe" und College Jackets w. Shirt für Frauen (Hobo Jacket, Prayer Jacket).
