### ISSUE TITLE
Spawnpunkte etwas tiefer setzten

### ISSUE THREAD

**Issue by Stiefel911** [eiksch/statev_v2_issues#2646]
Dem ein oder anderem ist es gewiss auch aufgefallen und da ich nicht weiß ob ihr evtl schon daran seid.

Beim rein und raus gehen von Gebäuden ( extrem bei Restaurants) spawnd man nicht wie gewohnt auf dem Boden, sondern so weit oben, daß man erstmal eine kleinen "Art" Sprung macht. Wenn man zu zweit raus geht steht man bei dem anderem auf der Schulter.

Irgendwie haben sich die Spawnpunkte nach oben verschoben.

;)

**Comment by Enemyaa** [comment]
@Stiefel911 @SHaagmann Ist das noch aktuell? Ich kann das gar nicht nachstellen, weil jede Landung voll smooth ist.

**Comment by SHaagmann** [comment]
@Enemyaa die letzten Tage nicht wirklich drauf geachtet, beobachte es die nächsten Tage nochmal und gebe dann nochmal rückmeldung.

**Comment by Stiefel911** [comment]
Es kann natürlich Zufall gewesen sein, jedenfalls nach einem Restart des Servers war dieses nicht mehr auf getaucht... Wollte es dir ganze Zeit bereits geschrieben haben, aber voll vergessen 😔 sorry

**Comment by Enemyaa** [comment]
OK, dann scheint ja wieder alles tutti zu sein.
