### ISSUE TITLE
Falscher Hersteller des Motorrads "Wolfsbane" im Import

### ISSUE THREAD

**Issue by theSiixx** [eiksch/statev_v2_issues#2647]
**Character Name**
//

**Auftrittszeitpunkt (Datum / Uhrzeit)**
//

**Beobachtetes Verhalten**
Das Motorrad "Wolfsbane" ist (zumindest) im Import als Fahrzeug der Marke "Enus" gelistet

**Erwartetes Verhalten**
Gemäß GTA Fandom ist der/die/das Wolfsbane vom Hersteller "Western Motorcycle Company"
Link zum GTA Fandom Eintrag: [https://gta.fandom.com/de/wiki/Wolfsbane_(V)](https://gta.fandom.com/de/wiki/Wolfsbane_(V))

**Schritte um den Fehler nachvollziehen zu können**
//

**Comment by SHaagmann** [comment]
Generelle Übersetzung des Hashes ist mit Enus angegeben

**Comment by Enemyaa** [comment]
Danke für die Info!
