### ISSUE TITLE
Be und entlade Marker möglich zu versetzen?

### ISSUE THREAD

**Issue by LiljaMorningstar** [eiksch/statev_v2_issues#2648]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Lilja Teller

**Auftrittszeitpunkt (Datum / Uhrzeit)**

04.11.2022

**Beobachtetes Verhalten**

Unser Marker für die Be& Entladezone befindet sich in einem engen Bereich zwischen vielen Metallstreben. Mit einer Achse ist es äußerst kompliziert Ort Schadensfrei rein und raus zu manövrieren.

Firmenname: HooVer Warehouse V3
Adresse: Orchardvile Ave.6
Postalcode: 6007

**Erwartetes Verhalten**
 Wir würden uns freuen wenn der Marker einfach an den Straßenrand gesetzt werden könnte. wie bei den Nachbarn auch. Mögliche Position wenn umsetzbar habe ich per Bild mitgeschickt . Jetzige Position habe ich auch noch einmal anbei gefügt zur leichteren Übersicht

Vielen Dank im Voraus und für die Aufmerksamkeit 

Lilja Teller

**Optional: Video / Bilder des Fehlers**

![Jetziger marker](https://user-images.githubusercontent.com/76446293/200066327-455a184f-c236-4895-b162-d0a6801be90d.PNG)
![umsetzen neu](https://user-images.githubusercontent.com/76446293/200066343-6de4fe9c-8586-4fde-992b-09941ce7c16e.png)

**Comment by SHaagmann** [comment]
Könntest du noch einmal den Firmenhash für die Schnellere Suche hinzufügen? Den findest du im StateNET über dem Firmennamen bei der Übersicht.

**Comment by LiljaMorningstar** [comment]
Hier einmal der gewünschte Firmenhash : <html>
<body>


cypressflats6
--



</body>
</html>
