### ISSUE TITLE
Fahrzeuge drehen sich im Autohaus 

### ISSUE THREAD

**Issue by epichalt** [eiksch/statev_v2_issues#2650]
Woran liegt es, dass etwa 1x im Monat oder alle 2 Monate fast alle Fahrzeuge im Autohaus sich teilweise um 180° drehen und verkehrt rum stehen oder sich wie hinten auf dem Bild um 90° drehen und ineinander buggen. 

Mir gehts nicht mal um die 2-3000$, aber es ist super nervig 12-13 Repkästen zu holen, dann alle Fahrzeuge jeweils anzumelden, mit jedem einzeln zur Werkstatt zu fahren und anschließend wieder alle umzumelden^^
Wenn die Autos sich etwas verstellen und vor und zurück geschoben werden müssen ist das ja ok, aber dass die sich komplett drehen und man teils eine Achse mit Gewalt aus einer Ecke holen muss weil man die sonst nicht mehr von der Wand weg bekommt, dann wirds schwierig :D 

![029749038c1d5220d70034bb7fec1e42](https://user-images.githubusercontent.com/16436981/200179192-6cdb52bf-e76a-4889-9d1d-f29cf8747f84.jpg)

**Comment by h3adbang3r** [comment]
Es scheint sich dabei um ein generelles Problem zu handeln, denn auf der Straße sieht es ähnlich aus.
![2022_1121-125945](https://user-images.githubusercontent.com/15799077/203047841-d4bf17f2-e377-40dc-8cca-250c8de842bd.png)

**Comment by TheOutburst** [comment]
Das ist seit Monaten ein aktives AltV Problem, was jeder Server hat
AltV weiß davon auch schon bescheid, ob und wann sie eine Lösung davon haben bleibt abzuwarten, ich schließe hier aber mal an der Stelle, weil wir daran leider nichts ändern können.
