### ISSUE TITLE
Durags/Caps nicht in Schneiderei produzierbar

### ISSUE THREAD

**Issue by TamiGaming** [eiksch/statev_v2_issues#2651]
**Character Name**
Carlie Tacus

**Auftrittszeitpunkt (Datum / Uhrzeit)**
06.11.2022 18:00 Uhr

**Beobachtetes Verhalten**
Neu hinzugefügte Items, wie Weißes/Orangef./Grünes/Lila Durag und die MLB Caps lassen sich nicht in der Schneiderei produzieren. 
Ansicht Schneiderei:
![image](https://user-images.githubusercontent.com/40512639/200187089-327d9db6-ba07-42b7-9cc6-ea66230c53c5.png)

Ansicht HATers:
![image](https://user-images.githubusercontent.com/40512639/200187157-6be42a90-11be-44bf-8da1-edda495e1453.png)

**Erwartetes Verhalten**
Items lassen sich wie gewohnt, verpackt in der Schneiderei herstellen,

**Schritte um den Fehler nachvollziehen zu können**
In Weberei gehen und nach z.B. White Sox suchen.

**Comment by PlayInc89** [comment]
Ich denk mal das der selbe Fehler wie #2645

**Comment by TamiGaming** [comment]
> Ich denk mal das der selbe Fehler wie #2645

Im Klamottenladen könntet ihr die Sachen wie gewohnt "auspacken" ?
Dann denk ich ja ^^
