### ISSUE TITLE
Schmuck nicht sichtbar.

### ISSUE THREAD

**Issue by Naaki6** [eiksch/statev_v2_issues#2652]
Jalen_Park
**Auftrittszeitpunkt (Datum / Uhrzeit)**

07.11 ca. 19 Uhr
**Beobachtetes Verhalten**

Sobald ich eine Kette und ein Armband anziehe verschwindet je eins von den Items und ist nicht mehr sichtbar.
**Erwartetes Verhalten**

Beides Sichtbar.

**Schritte um den Fehler nachvollziehen zu können**

Armband anziehen und danach die Kette, oder andersrum.

**Optional: Video / Bilder des Fehlers**

https://streamable.com/roy31r

**Comment by SHaagmann** [comment]
Duplikat von #2550
Die beiden Sachen liegen auf dem gleichen Slot und können daher nicht zusammen getragen werden
