### ISSUE TITLE
Crop Lederjacken - nur ein passendes Undershirt

### ISSUE THREAD

**Issue by CaleighRhodes** [eiksch/statev_v2_issues#2655]
**Character Name**
Caleigh_Rhodes

**Auftrittszeitpunkt (Datum / Uhrzeit)**
immer

**Beobachtetes Verhalten**
die neuen Crop-Lederjacken für Damen lassen sich leider nicht richtig anpassen über das Kleidungsmenü. Auch die Undershirts, die speziell für Jackets sind, können mit keiner Langarm-Einstellung die Ränder links und rechts unter der Jacke entfernen. Das einzige Kleidungsstück, das man unter der Lederjacke tragen kann, ohne dass die Löcher auftauchen, sind hoch geschlossene Blusen.

**Erwartetes Verhalten**
Lücken sind gefüllt (wie bei den Anzugsjacken) oder werden anderweitig gefixt, sodass man nicht durch den Char durchgucken kann.

**Schritte um den Fehler nachvollziehen zu können**
Crop-Lederjacke anziehen, beliebiges Unterteil drunter ziehen, Löcher entdecken

**Optional: Video / Bilder des Fehlers**
Lederjacke mit Shirt für Jackets:
![cropleder](https://user-images.githubusercontent.com/74977218/201351910-cf32eb42-3a77-4887-9a92-69baee4da1e4.jpg)

![leder3](https://user-images.githubusercontent.com/74977218/201351928-dbc330a9-42f1-4cc0-92ff-8e6612fdc9ca.jpg)

Lederjacke mit Bluse:
![leder2](https://user-images.githubusercontent.com/74977218/201351955-aa0701a4-cecc-4ad8-8986-3bd1197993ca.jpg)

Gegebenenfalls könnte man, wenn möglich, es so anpassen, dass die Lücken gefüllt werden, wie bei der Anzugjacke:
![füllung](https://user-images.githubusercontent.com/74977218/201352498-d369c89d-94b1-4e2b-a368-eda19b668022.jpg)

**Comment by Stiefel911** [comment]
Liegt in dem Fall an der "Unterbekleidung", sie sind nicht für so weit geöffnete Oberbekleidung geskinnt.
Das Transparente ist das ende des Skins vom Shirt ;)

**Comment by CaleighRhodes** [comment]
Joa, das ist mir schon klar. Aber da es keine passende Unterbekleidung, ausser den Blusen, gibt, dieses Issue.

Entweder muss die Jacke wieder raus, ein Undershirt her, das keine Bluse ist, oder wir müssen damit leben, dass es nur die Blusen gibt, was ich halt schade fände. 
aber: wer nicht wagt, der nicht gewinnt. Fragen kann man ja mal.

**Comment by Stiefel911** [comment]
Dann, sorry. wollte nur etwas behilflich sein. Nicht jeder sieht das offensichtliche und kann / muss sich mit der Materie auskennen. :~

**Comment by StateV2Marie** [comment]
wieso ich eins auf gemacht hab weil ich nich gesehen habe das du schon eins auf gemacht hast und ich nich auf einer englischen seite zurecht komme sorry dafür.......... aber gut dann wissen se es ja schon wolte nur helfen........
