### ISSUE TITLE
neue lederjacke

### ISSUE THREAD

**Issue by StateV2Marie** [eiksch/statev_v2_issues#2656]
Huhu haben fest gestellt das keine passenden unterteile für die neue croop leder jacke gibt und es auch keine größe gibt wo passt es sind immer löcher zu sehen oder die hupen schauen raus kann man da was machen???

**Comment by CaleighRhodes** [comment]
Warum machst du nen Issue auf, was ich vor 3 Stunden schon eröffnet habe? #2655

**Comment by SHaagmann** [comment]
Das was @CaleighRhodes sagt
