### ISSUE TITLE
[M][U] Weißes Hemd mit hellgrauer Weste, aufgekn. anscheinend nicht funktioanl

### ISSUE THREAD

**Issue by Lucky2406** [eiksch/statev_v2_issues#2660]
**Character Name**
Miguel Ashton

**Auftrittszeitpunkt (Datum / Uhrzeit)**

14:55 Uhr am 12.11.2022

**Beobachtetes Verhalten**

Beim Kaufen von Klamotten ein T-Shirt gefunden, welches beim Auswahlmenü Leder Handschuhe ungewollt hinzufügt.
Um für den Bugtracker weiter zu ermitteln habe ich mir besagtes gekauft: "[M][U] Weißes Hemd mit hellgrauer Weste, aufgekn.". Sobald man dieses angezogen hat, hat man erwartet, dass auch hier die Handschuhe einfach angezogen werden. Dies passierte zwar auch, jedoch viel vor Allem auf, dass es möglicherweise bei Minusgraden sehr kalt werden könnte.

**Erwartetes Verhalten**

Klamotten ohne Handschuhe und sichtbar.

**Schritte um den Fehler nachvollziehen zu können**

Das Richtige "unter" Shirt kaufen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

Zwar nicht von Nöten, aber für den Flex 4k.

**Optional: Video / Bilder des Fehlers**

![image](https://user-images.githubusercontent.com/66916316/201477789-68ba3cac-5ab0-432e-b2a6-f6623e756ae0.png)

**Comment by Lucky2406** [comment]
Scheint wohl mehrere Klamotten zu betreffen -> alles was anscheinend der Gattung aufgeknöpft zugehört

**Comment by SHaagmann** [comment]
Gerade n bisschen Rumgetestet manche Funktionieren andere nicht wirklich würde mir morgen mal alle geben lassen und ne Liste machen, bei welchen es nicht klappt

**Comment by PlayInc89** [comment]
[F][U] Helllblaues kurzes V-Shirt verpackt muss man beim Produzieren mit 3 l schreiben und wenn es ausgepackt ist ist es wieder richtig mit 2 ll [F][U] Hellblaues kurzes V-Shirt
