### ISSUE TITLE
Unsichtbarer Pfosten

### ISSUE THREAD

**Issue by Havati** [eiksch/statev_v2_issues#2662]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Jackson_Sawyer**

Mit Jackson_Sawyer und Naomi_Foley
**Auftrittszeitpunkt (Datum / Uhrzeit)**

13.11.2022 um 8.45Uhr
**Beobachtetes Verhalten**

Es ist ein unsichtbare Pfosten oder ein Teil davon vor dem 24/7 bei 6025 wo man dagegen fährt und laufen kann
**Erwartetes Verhalten**

Das dort nichts vorhanden ist
**Schritte um den Fehler nachvollziehen zu können**

Wenn man vor dem Laden steht links am Bürgersteigrand ungefähr 8-9 Schritte und dann läuft man dagegen
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![grafik](https://user-images.githubusercontent.com/118099424/201511691-633f6f9d-298a-434d-83d9-0c0b1ceaa6e0.png)
![grafik](https://user-images.githubusercontent.com/118099424/201511725-4667d8f2-c27f-4bf2-97e6-f31a3fcc6af8.png)

**Comment by SHaagmann** [comment]
@TeubyDE ist das nicht der unsichtbare Pfosten der Lichterkette?

**Comment by CatherineGallagher** [comment]
https://github.com/eiksch/statev_v2_issues/issues/2536

ja es ist und bleibt die Lichterkette ^^

**Comment by TheOutburst** [comment]
das was Catherine sagt
Vielleicht arbeitet der 24/7 Betreiber ja in der Werkstatt nebenan und geht so auf Kundenfang?
