### ISSUE TITLE
Casino - Crash Game

### ISSUE THREAD

**Issue by Chandena** [eiksch/statev_v2_issues#2663]
Chandena_Mascarponi

**Auftrittszeitpunkt (Datum / Uhrzeit)**
11;00Uhr/ 13.11.22

**Beobachtetes Verhalten**
Das Spiel Crash Game im Casino hat ab und an ein paar Fehler, entweder es erscheint kein Crash Button oder  oben links die Ui? bleibt stehn bzw reagiert nicht wie sie sollte. Ich kann das nicht richtig erklären, siehe Bilder.

![bug2](https://user-images.githubusercontent.com/74984579/201516824-ecc20e66-ed18-42cf-b961-77f0ce3fda73.jpg)
![bug](https://user-images.githubusercontent.com/74984579/201516827-4820f8ac-2452-4fbe-a17a-15c269758657.jpg)

**Erwartetes Verhalten**
Das es wieder spielbar ist.

**Comment by TheOutburst** [comment]
ich würde das von den Screenshots folgendermaßen erklären:

1. obwohl auf der Leinwand "next Game in X" steht das UI das Spiel noch als laufend erkennt
2. obwohl auf der Leinwand das Spiel bereits läuft wartet das UI noch auf den Spielbeginn
