### ISSUE TITLE
Fahrzeug fährt nach dem Reloggen eines Gamecrachs ohne Fahrer weiter.

### ISSUE THREAD

**Issue by xeni2401** [eiksch/statev_v2_issues#2665]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Alan_Carter
**Auftrittszeitpunkt (Datum / Uhrzeit)**

14.11.2022 c.a 10:30
**Beobachtetes Verhalten**

Ich bin vom Marktplatz in der Stadt in meinem Bobcat Xl auf der Carson Ave Richtung 6001 gefahren.
Ungefähr auf der höhe des Friseurs habe ich einen Gamecrash bekommen, ich habe wieder eingeloogt
und bin liegend auf der ladefläche meines Bobcats wachgeworden der nach meinem Spawn mit c.a 20 kmh einfach weitergefahren ist.
ich konnte mich auf der Ladefläche auch nicht bewegen hatte "glück" dass das Fahrzeug gebremst wurde es ist allerdings ausgebrannt.
**Erwartetes Verhalten**

Normalerweise sollte das Fahrzeug nach einem Gamecrash stehen bleiben beim relog und nicht ohne Fahrer einfach losfahren.
**Schritte um den Fehler nachvollziehen zu können**

Ich wüsste nicht ob man einen gamecrash triggern kann.
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Screenshot 2022-11-14 104207](https://user-images.githubusercontent.com/118171829/201629528-b36d0b1e-cf17-4ab3-9ef3-526563a6e211.png)

**Comment by JohnRappStateV** [comment]
Ist bei mir ebenfalls passiert, auf dem Osthighway von der Stadt in Richtung Sandy Shores. Heute gegen 10:00 Uhr. Gestern hatte ich diesen Fall auch 2x.

**Comment by TheOutburst** [comment]
Ich meine das ist AltV behavior, wo wir nicht sonderlich viel dran ändern können
Du als Spieler bist aber immerhin beim einloggen kurz unverwundbar, damit dein eigenes Auto dich nicht tötet

**Comment by JohnRappStateV** [comment]
Ist korrekt denke ich, habe es gestern "anderweitig" auch noch gesehen - kann dir hierzu gerne im Discord nen Clip schicken.

Wie gehen wir damit um, falls unseren Fahrzeugen durch sowas Schäden entstehen / Sachen abbrennen? Kann der Support da unterstützen?

**Comment by TheOutburst** [comment]
jo, leider nen AltV Problem was wir mit der Unsterblichkeit für ein paar Sekunden überlebbar gestalten.
Ich schließe dann hier, können wir nicht mehr machen als erneut weitergeben.
