### ISSUE TITLE
Fahrzeug-Sync vor dem Restart zu langsam

### ISSUE THREAD

**Issue by Erumeldor** [eiksch/statev_v2_issues#2667]
**Character Name**
Satoru_Tsuyoshi

**Auftrittszeitpunkt (Datum / Uhrzeit)**
14.11 - 14:56

**Beobachtetes Verhalten**
Fahrzeug bei der Ankündigung zum Restart nochmal "umbeladen" - also wirklich nicht 2 Sekunden vor Restart sondern eher 2 Minuten. Gefarmte Sachen rein, private Sachen raus. 
Dann losgefahren, Auto geparkt. Sogar noch einige Sekunden vor dem Restart ausgeloggt.
Nach dem Restart ist das Inventar vom Auto "resettet". Heißt die gefarmten Sachen sind weg, die privaten Sachen wieder drin - und nun natürlich doppelt da ich sie ja rausgenommen habe.
Bild dazu nach Restart:
![image](https://user-images.githubusercontent.com/21212905/201683389-5bc575fa-ba4f-461b-86a8-4b37a5429fed.png)

**Erwartetes Verhalten**
Fahrzeugsync muss später oder separat bei Restart gemacht werden. Oder die "Kick"-Zeit deutlich höher, aber das sind hier ja fast 2-3 Minuten gewesen.
So kann man wenn man es drauf anlegt Items duplizieren.

**Schritte um den Fehler nachvollziehen zu können**
Kurz vor dem Restart Sachen umlagern.

**Comment by Erumeldor** [comment]
Ahja, Fahrzeugkennzeichen "OKINA"

**Comment by TeubyDE** [comment]
Mit dem letzten Update gefixed. Wenn es noch besteht, bitte bei mir noch mal melden.
