### ISSUE TITLE
Bug beim Gewinn ausschuss bei Crash-Game

### ISSUE THREAD

**Issue by Marcus-Pierce** [eiksch/statev_v2_issues#2668]
Marcus Pierce

15.11.2022 19:35 

Habe bei Crash- game 150$ gesetzt und den multiplikator auf 10 gesetzt, der Multiplikator ging über 10 aber bei der Auszahlung habe ich das geld nicht bekommen und als nachricht kamm auszahlung nicht möglich (C3)

**Erwartetes Verhalten**
Das durch das übersteigen des 10 multiplikator meine gesetztes geld ver 10 facht wirt.

Wenn es Log gibt wo man sowas nachgucken kann dort.

**Comment by eiksch** [comment]
Hallo Marcus,

C3 bedeutet, dass du entweder zu langsam auf Cash-Out gedrückt hast, oder kein Gebot in dieser Runde von dir vorhanden war. In beiden Fällen ist kein Fehler auf unserer Seite festzustellen. Dein letztes Gebot ist um 19:30Uhr eingegangen und nicht wie beschrieben um 19:35Uhr.

Gruß,

Tito
