### ISSUE TITLE
Geht um Zigarrenboxen weiß nich ob da nen beitrag zu offen is hab kein gefunden sry

### ISSUE THREAD

**Issue by StateV2Marie** [eiksch/statev_v2_issues#2669]
Hallo hab die neuen Montecristo Zigarrenpackung machen wollen aber es sind die falschen boxen die gebraucht werden oder ist es gewollt das man Cohiba boxen brauch??? [https://pic.statev.de/image/fehler-bei-den-zigarren.Z4EXU](https://pic.statev.de/image/fehler-bei-den-zigarren.Z4EXU)

**Comment by UNDRCVRR** [comment]
Next Update!
