### ISSUE TITLE
Zigarettenstummel reproduktions Bug

### ISSUE THREAD

**Issue by NoXCtic** [eiksch/statev_v2_issues#2673]
Wenn man bei Zigaretten ohne Feuerzeug eine rauche will dann kann man dies wie normal nicht jedoch werden Zigarettenstummel ins Inventar gelegt ohne das die Verpackung verbraucht wird. Hab des nur bei den Debonaire Zigaretten getestet bei den anderen weiß ichs nicht.

**Comment by GonzoMenendez** [comment]
Selbiges passiert auch bei den Zigaretten mit denen man sich bewegen kann (name grad unbekannt :S)
