### ISSUE TITLE
Klamotten im Klamottenladen als Hash angezeigt

### ISSUE THREAD

**Issue by MrsPxtn** [eiksch/statev_v2_issues#2674]
Mila Paxton

Hallöchen! Ich habe eben Klamotten Produziert, die wir nicht im Laden hatten. Ich weiß nicht, ob diese neu sind - oder älter. 
In der Schneiderei ist die Produktion komplett in Ordnung. Sobald die Klamotten entpackt werden im Klamottenladen, wird in der Produktionsloste "maleundershirt817812" angezeigt. Hat man die Kleidung im Inventar, ist es wieder normal beschriftet. Stellt man diese in den Klamottenladen zum Verkauf, werden diese wieder mit dem Hash angezeigt. Es geht um die komplette Kollektion von Fitted Business Shirts
Fitted Business Shirts, aufgeknöpft

Falls dies normal ist und sich von alleine beheben sollte, tut es mir leid für die unnötige Meldung. 
Liebe Grüße! 
![51d98cd4c08cfbec85f0c7ca8a142d4d](https://user-images.githubusercontent.com/87946968/202870595-faa3b4e6-35d4-4e39-84c3-fd111ee925cc.png)
( sind noch paar mehr )

**Comment by PlayInc89** [comment]
[F][U] Weiße Bluse, aufgeknöpft.  könnte man zwar Auspacken im Laden aber nicht Herstellen in der Schneiderei

**Comment by TeubyDE** [comment]
Mit dem letzten Update sollte das alles behoben sein.
