### ISSUE TITLE
Falsche Zigarrenboxen für die neue Zigarrenpackungen.

### ISSUE THREAD

**Issue by DepeaceDrey** [eiksch/statev_v2_issues#2675]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Depeace Drey

Seit dem Update mit den neuen nikotinhaltigen Waren.

Motegcristo Zigarrenpackungen werden aus Cohiba Zigarrenboxen hergestellt.

Motegcristo Zigarrenpackungen werden aus Motegcristo Zigarrenboxen

Ab in nen 24/7! ;-) Ggf. auch in einer Verpackung.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

https://pic.statev.de/i/ZM1ek.png

**Comment by UNDRCVRR** [comment]
#2669
