### ISSUE TITLE
Hausgarage hinzufügen

### ISSUE THREAD

**Issue by Tyson0211** [eiksch/statev_v2_issues#2676]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Hallo zusammen,

kann man bei dem Haus (Haushash: EveZone3Rew_House_27) vlt. eine Garage anbauen?
Die Voraussetzungen dafür sind gegeben (Carport) und man müsste dann nicht unendlich weit bis zur nächsten öffentlichen laufen.
Vielen lieben Dank schonmal.

LG
Tyson

**Comment by TheOutburst** [comment]
kommt dann nächstes Update!

**Comment by Tyson0211** [comment]
Supi, vielen Dank!
