### ISSUE TITLE
Antrag auf Entfernung der Gartenmöbel

### ISSUE THREAD

**Issue by Parityisreal** [eiksch/statev_v2_issues#2677]
Character Name
Parity Corleone

Ort/Lage
North Rockford Drive 1000
Haushash: house_VinewoodHills_205

Guten Morgen währe es möglich, die beiden Verkaufsschilder in der Einfahrt zu entfernen und die Gartenmöbel hinter dem Haus.
Diese sind leider leicht zu verschieben und fliegen gerne in den Pool oder die Sitzanimation bugt wenn sie verschoben werden.
Vielen Dank im Voraus!
Lg. Parity

Bilder : 
![Screenshot_108](https://user-images.githubusercontent.com/44527538/204261409-94692232-1a22-41bb-b4e5-158f123589e9.png)

![Screenshot_109](https://user-images.githubusercontent.com/44527538/204261399-046ba9cc-e5cd-4995-8065-57c26205e8cd.png)

![Screenshot_110](https://user-images.githubusercontent.com/44527538/204261419-b1260a0d-178a-459a-871c-0703e2d17894.png)

**Comment by TheOutburst** [comment]
Die Verkaufsschilder sind jetzt weg.

Die Liegen und Stühle haben eine Y Interaktion und würden wieder sichtbar werden, sobald jmd dort Y drückt. Bewegliche Objekte werden auch gerne mal so sichtbar, wenn man dagegen rennt, wo sie stehen würden. Das ist absolut nicht RP getreu und machen wir deswegen nicht.

**Comment by Parityisreal** [comment]
Edit: Die Schilder sind leider immer noch da.

**Comment by TheOutburst** [comment]
Richitg, die Änderungen werden immer erst nach dem nächsten Update
