### ISSUE TITLE
Antrag auf Versetzung des Verladepunktes

### ISSUE THREAD

**Issue by SgtTukiTuki** [eiksch/statev_v2_issues#2680]
Sandy_Folk

Sandy_Folk und Sven_Weber

28.11.2022 18.00 Uhr

Der Abladepunkt der Fertigung "Weber´s Fertigung - Bay City Ave. 3330" befindet sich zur Zeit hinter dem Gebäude im Innenhof. Dieser ist mit Zugmaschine und Anhänger sehr schwer zu erreichen. Daher würde es sich Anbieten diesen Punkt nach vorne an die Straße vor die Fertigung zu setzen! Anbei schicke ich 2 Fotos mit. Der Besitzer der Fertigung ist damit Einverstanden, dass ich mich um die Versetzung kümmere, sollte dennoch von ihm etwas benötigt werden, einfach Bescheid geben.

![Fertigung Ladepunkt Aktuell](https://user-images.githubusercontent.com/87803938/204338199-08780d29-b3b9-466d-baca-c1989c5993dd.png)

![Fertigung Ladepunkt Neu](https://user-images.githubusercontent.com/87803938/204338256-82370347-00f1-4003-afc7-cb2f1432b0ec.png)

**Comment by TheOutburst** [comment]
Abladepunkt next Update auf Parkplatz vor der Türe verschoben
Nächstes mal gerne mit Firmenhash (StateNET oder über Dreifachpunkte bei Firmennamen hovern)
