### ISSUE TITLE
Müll entfernen

### ISSUE THREAD

**Issue by AceJohnson2** [eiksch/statev_v2_issues#2681]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Ace Johnson/Eric Forster**

Lage:
house_VinewoodHills_194 - North Rockford Drive 1009

Löschung von Pleps die auf den nachfolgenden Bildern zu erkennen sind.

![20221128232956_2](https://user-images.githubusercontent.com/119367621/204399712-03968389-7c3b-41ce-813f-2e9de935d57f.jpg)

![20221128233014_1](https://user-images.githubusercontent.com/119367621/204399726-c269d150-113d-4e0e-946f-a50fd0d40cf1.jpg)

Vielen Dank im Voraus

Ace Johnson und Eric Forster

**Comment by TheOutburst** [comment]
Tachchen,

da man alle Objekte beweden kann kriegen wir die nicht ressourcensparend entfernt, ohne dass man sie durch "entgegenlaufen" wieder sichtbar bekommt, deswegen kann ich euch leider nichts davon entfernen.
