### ISSUE TITLE
Antrag auf Versetzung des Verladepunktes

### ISSUE THREAD

**Issue by RickoSanchez** [eiksch/statev_v2_issues#2682]
Firma: REH Weapon Inc - Algonquin Blvd. 33 

Der Abladepunkt der Waffenfertigung "REH Weapon Inc - Algonquin Blvd. 33 " befindet sich zur Zeit direkt vorm Gebäude und kann nicht mit einer Trailer Large Achse angefahren werden daher meine bitte den Verladepunkt auf die Straße zu versetzen .
Lg R.Sanchez

<img src="https://pic.statev.de/i/Zdri6.jpg" alt="Zdri6.jpg" border="0" />
<img src="https://pic.statev.de/i/ZdN9s.jpg" alt="ZdN9s.jpg" border="0" />
<img src="https://pic.statev.de/i/Zd2JJ.jpg" alt="Zd2JJ.jpg" border="0" />

**Comment by TheOutburst** [comment]
Abladepunkt next Update auf "Grünfläche" vor dem Zaun verschoben
Nächstes mal gerne mit Firmenhash (StateNET oder über Dreifachpunkte bei Firmennamen hovern)
