### ISSUE TITLE
Impaler Zukunftsschock Optisches Tuning

### ISSUE THREAD

**Issue by Michi993** [eiksch/statev_v2_issues#2685]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Luke Hammer

**Auftrittszeitpunkt (Datum / Uhrzeit)**
29.11.2022 21:40

**Beobachtetes Verhalten**
Viele Tuiningmöglichkeiten beim Impaler Zukunftsschock nicht verfügbar (z.B. Motorhauben oder Spoiler, die das Fahrzeug nur optisch ändern, dass sachen wie MG´s entfernt wurden, ist selbstverständlich, wäre cool, wenn optische Tuningmöglichkeiten wieder hinzugefügt werden würden)

**Erwartetes Verhalten**
Es sollten mehr Tuningmöglichkeiten zur Verfügung stehen

**Schritte um den Fehler nachvollziehen zu können**
Im Tuningmenü bei diesem Fahrzeug nachschauen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by TheOutburst** [comment]
Jeder von uns geblockter Slot, das Auto ist eines von denen, wo auf jedem Slot etwas absolut RP ungeeignetes drauf liegt.
Symbolbild:
https://i.imgur.com/aim2Het.jpeg
