### ISSUE TITLE
Canis Mesa (Offroad) Dachtuning

### ISSUE THREAD

**Issue by MaCaR23** [eiksch/statev_v2_issues#2686]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
 Harami Jaxson 

**Auftrittszeitpunkt (Datum / Uhrzeit)**
 29.11.2022 ca. 22;30 Uhr

**Beobachtetes Verhalten**
Das Tuning bot deutlich weniger Möglichkeit als vor geraumer Zeit, dabei war nicht Möglich das Dach zu verändern obwohl das Fahrzeug noch vor wenigen Monaten über ein Dach verfügte. Das Dach verschwand nach einem Fahrzeug Update und wurde bis Gestern nicht im Tuning angerührt.

**Erwartetes Verhalten**
Eine Möglichkeit via Tuning das Dach zu verändern.

**Schritte um den Fehler nachvollziehen zu können**
Im Tuningmenü überprüfen

**Comment by Domeex3** [comment]
Schau einfach nochmal mit deiner Werkstatt des Vertrauens drüber :)

**Comment by MaCaR23** [comment]
> Schau einfach nochmal mit deiner Werkstatt des Vertrauens drüber :)

also https://i.gyazo.com/1e0e47b02817dd10ccf05d8b59409218.png die zweite Werkstatt und insgesamt der vierte Spieler der mir nicht weiterhelfen konnte. Glaube es stimmt einfach nur etwas mit meinem Wagen nicht dunno

**Comment by Domeex3** [comment]
Mit "Anwenderfehler" Abgeschlossen
