### ISSUE TITLE
" Deko Reh Klein" nicht aufstellbar

### ISSUE THREAD

**Issue by Saaria83** [eiksch/statev_v2_issues#2688]
**Character Name**

Hanna Fields

**Auftrittszeitpunkt (Datum / Uhrzeit)**

00:10 Uhr ~ 01.12

**Beobachtetes Verhalten**

Ich habe beim Adventskalender ein aufstellbares Reh bekommen und wollte das aufstellen.  Als ich es mit E usen wollte, war es nicht mehr im Inventar und konnte es auch nicht aufstellen. Als ich ein wenig mit "." rumgespamt habe, war es auch wieder im Inventar

**Erwartetes Verhalten**

Das sich das Objekt aufstellen lässt

**Optional: Video / Bilder des Fehlers**

Hier ist das Objekt was gemeint ist: https://prnt.sc/h61ibGayBN1f

**Comment by epichalt** [comment]
MIt der Deko Zuckerstange genauso. Beim ersten Mal gings. Danach verschwindet es einfach aus dem Inventar und taucht erst wieder auf, wenn man etwas anderes platziert. Lässt sich anschließend nicht mehr aufstellen,

**Comment by Domeex3** [comment]
@epichalt @Saaria83 Wo habt ihr versucht die Items zu platzieren?

**Comment by Saaria83** [comment]
house_VinewoodHills_34  <-- Da auf dem Grundstück.

**Comment by Domeex3** [comment]
Ist mit dem nächsten Update gefixt :)
