### ISSUE TITLE
Verdopplung der Adventstürchen

### ISSUE THREAD

**Issue by RIT-FR** [eiksch/statev_v2_issues#2690]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Jim_Manolo

01.12.2022 / ca. 18:20

Nach dem Einloggen existierte ein Zweites Türchen im Inventar, habe es dann aus Reflex in das Portmonee gezogen

Ich habe mich nur eingeloggt

![Screenshot_105](https://user-images.githubusercontent.com/77400784/205120623-a3e00173-eea5-4287-b986-b2b34acacd75.png)

**Comment by DonVitoDiangelo** [comment]
Also Türchen gibt es 2 mal. Einmal beim einloggen und einmal am Weihnachtsbaum.

**Comment by TeubyDE** [comment]
Kein Bug.
