### ISSUE TITLE
Deko Reh klein - Wunderschön aber nicht jeder kann es bewundern.

### ISSUE THREAD

**Issue by Saaria83** [eiksch/statev_v2_issues#2691]
**Character Name**

Hanna Fields

**Auftrittszeitpunkt (Datum / Uhrzeit)**
18:20 Uhr ~ Nach dem Update

**Beobachtetes Verhalten**

Ich habe voller Vorfreude dieses Reh ausgepackt und hab es aufgestellt. Bin leuchtenden Augen ergötze ich mich an dem Funkeln aber musste mit Entsetzen feststellen, dass nur ich dieses Wunderwerk betrachten kann. 

**Erwartetes Verhalten**

Es sollte die Augen aller Mitmenschen zum glänzen bringen

**Optional: Video / Bilder des Fehlers**

Heute habe ich leider kein Bild für sie :c

**Comment by Domeex3** [comment]
Bei wie vielen Spielern ist das Problem denn aufgetreten?
Können diese Spieler nochmal Reloggen und sicherstellen, dass ihre Clientdaten aktuell sind?

**Comment by Saaria83** [comment]
Ich habe nun extra noch mal nachgefragt und auch die, die den vorher nicht sehen konnte, sieht es. Also vll war das nur n kurzer Bug D:

**Comment by Domeex3** [comment]
Ja hier und da kommt es zu kleinen Hickups nach den Restarts. Freut mich das sich jetzt alle am Funkeln erfreuen können :)
