### ISSUE TITLE
LSPD Cruiser - zweiter Suchscheinwerfer nach Werkstatt-Besuch

### ISSUE THREAD

**Issue by shoxmox** [eiksch/statev_v2_issues#2692]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Antonio Knauff

**Auftrittszeitpunkt (Datum / Uhrzeit)**
01.12.2022 - 21.00 Uhr round-about

**Beobachtetes Verhalten**
Nach Auslesen vom Fahrzeug oder gestern nach dem Reifen wechseln wird am LSPD Fahrzeug ein zweiter Suchscheinwerfer angezeigt. Sichtbar nur von vorn. Fahrzeug einparken - ausparken löst das Problem.

**Erwartetes Verhalten**
Kein zweiter Suchscheinwerfer

**Schritte um den Fehler nachvollziehen zu können**
LSPD Cruiser (bspw. LSPD 124) zur Werkstatt bringen, Reifen wechseln oder Fz auslesen, Fahrzeug von vorne anschauen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
Hinten: https://pic.statev.de/image/gta5-2022-12-01-21-02-13.ZZ9B6
Vorne: https://pic.statev.de/image/gta5-2022-12-01-21-02-11.ZZcTJ

**Comment by TeubyDE** [comment]
Hier wurde wohl von der Werkstatt an den Extras rumgespielt. Gibt dafür aktuell keine Lösung. Hat etwas mit der "komplexen" extra Struktur der Cop Autos zutun die teilweise aufeinander aufbauen.
