### ISSUE TITLE
Kein ducken mit ^ im betrunkenem Zustand

### ISSUE THREAD

**Issue by TheFish789** [eiksch/statev_v2_issues#2693]
Charakter Name
Benjamin Wells

**Auftrittszeitpunkt (Datum / Uhrzeit)**
immer im betrunkenem Zustand (dem des Charakters, nicht meinem)

**Beobachtetes Verhalten**
In der geforcten Betrunkenenanimation kann man sich mit ^ nicht mehr hinhocken. Außerdem ändert sich nach dem Betrunkeneneffekt die Laufanimation wieder zu normal, statt zu dem vorher ausgewähltem.

**Erwartetes Verhalten**
Ja, bücken will ich mich halt.

**Schritte um den Fehler nachvollziehen zu können**
Trink n Bier, warte den Effekt hab und versuch Dich mit ^ hin zu hocken.

**Comment by TeubyDE** [comment]
Kein Bug, der geforced "betrunken" Walkingstyle darf nicht überschrieben werden.
Somit ist der "geduckte" Walkingstyle nicht auslösbar.
