### ISSUE TITLE
Telefon klingelt weiter bei mehreren Usern 

### ISSUE THREAD

**Issue by powerswissi** [eiksch/statev_v2_issues#2694]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Roger Thickle, Johanna Roesler, Ronny McLeod

**Auftrittszeitpunkt (Datum / Uhrzeit)**

1.12.2022 ca 22 uhr 30 

**Beobachtetes Verhalten**

Werkstattnummer klingelt bei den Anderen Weiter obwohl Ich bereits telefoniere. 
Klingelsound kann auch nicht abgeschalten werden. Auch wenn man taste N drückt klingelt das telefon weiter. Der rote Knopf am telefon beendet auch nicht den Klingelton 
Es hilft da auch nur ein neustart wenn man einen eigenen Klingelton eingespeichert hat und dieser sehr lang ist 

Gleicher Fehler: https://github.com/eiksch/statev_v2_issues/issues/1996

**Erwartetes Verhalten**

Wenn jemand ans Telefon geht wo mehrere die gleiche Nummer  haben sollte wenn jemand rangeht , bei den anderen das telefon aufhören zu klingeln

**Schritte um den Fehler nachvollziehen zu können**

Sim Karte klonen - angerufen weren- einer geht ran und die anderen "legen" auf !

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by CaleighRhodes** [comment]
Dafür gibt es ein Issue, das ist leider schon ne Weile so. Der Workaround ist, einfach jemand anderen anzurufen, dann hört das Klingeln auf.
Haben wir bei der Fraktionssim "leider" auch. #1996

**Comment by epichalt** [comment]
Man kann auch einfach kurz den Klingelton wechseln. 

Weiß auch nicht wieso du einen zweiten Bugtracker aufmachst und sagst es sei der gleiche Fehler während der andere nicht geschlossen ist :D

**Comment by powerswissi** [comment]
> Man kann auch einfach kurz den Klingelton wechseln.
> 
> Weiß auch nicht wieso du einen zweiten Bugtracker aufmachst und sagst es sei der gleiche Fehler während der andere nicht geschlossen ist :D

weil ich den nicht gesehen habe und erst dann aufmerksam gemacht worden wurde das der noch offen ist ;)

**Comment by TeubyDE** [comment]
https://github.com/eiksch/statev_v2_issues/issues/1996
