### ISSUE TITLE
Sägewerk Produktion Verpackte Halfpipe

### ISSUE THREAD

**Issue by CoreForceee** [eiksch/statev_v2_issues#2695]
**Character Name**
Kevin Grover

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Jederzeit

**Beobachtetes Verhalten**
Verpackte Halfpipe benötigt 1500 Holzbretter und alleine dies würde 4500KG in der Maschine benötigen welche aber nur 3000KG hat

**Erwartetes Verhalten**
Maschine im Sägewerk auf 5000KG erhöhen oder Produktionsformel ändern

**Schritte um den Fehler nachvollziehen zu können**
1500 Holzbretter benötigen mehr Platz in der Maschine als vorhanden

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
egal welche auflösung

**Optional: Video / Bilder des Fehlers**

**Comment by TheOutburst** [comment]
Next Update ist die Produktion auf die verkleinerten Lagergrößen angepasst
