### ISSUE TITLE
Gamecrash

### ISSUE THREAD

**Issue by Schu1z1909** [eiksch/statev_v2_issues#2697]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Julius Walker

**Auftrittszeitpunkt (Datum / Uhrzeit)**
03.12.2022 - 15:10

**Beobachtetes Verhalten**
Game crashed unterhalb vom See beim Mount Gordo

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by CaleighRhodes** [comment]
Das ist eigentlich nichts für den Bugtracker. Random Crashes sind "normal".
Bugtracker nur dann, wenn du zusätzlich dazu eine Fehlermeldung angezeigt bekommst.
