### ISSUE TITLE
MTL Reifenwechseln falscher Reifenverbrauch beim wechseln

### ISSUE THREAD

**Issue by M4c-M4ni4c** [eiksch/statev_v2_issues#2700]
**Character Name**
Ronny Mcleod

**Auftrittszeitpunkt (Datum / Uhrzeit)**
04.12.2022 21:13
Werkstatt: Truck and Shine (carWorkshop10)

**Beobachtetes Verhalten**
MTL Reifentausch gibt nur vier Reife zurück und verbraucht auch nur 4 Reifen, obwohl im Overlay Reifenwechsel 6xReifen steht

**Erwartetes Verhalten**
Das der MTL wie andere LKW's mit sechs achsen auch 6 Reifen verbraucht

**Schritte um den Fehler nachvollziehen zu können**
MTL auf Werkstattpunkt setzen und reifen Wechseln

**Optional: Video / Bilder des Fehlers**
![image](https://user-images.githubusercontent.com/52389841/205514497-20638fcd-d951-4386-a301-a8e5fa30beca.png)
![image](https://user-images.githubusercontent.com/52389841/205514502-ff91b7a9-09d0-40f2-9850-eb6d07fe9837.png)
![image](https://user-images.githubusercontent.com/52389841/205514537-9a8d5b5f-1926-4c1d-9aae-e43204564b83.png)

**Comment by TeubyDE** [comment]
Liegt leider am Mod. Sind dran.
