### ISSUE TITLE
Questgeber Weihnachtsevent unsichtbar?

### ISSUE THREAD

**Issue by Statev-Bonsai** [eiksch/statev_v2_issues#2701]
Das Gerät schlägt komplett aus und piept an einer bestimmten Stelle, jedoch kein Questgeber vor Ort...
Es dreht sich um Dixi VIII, ist das ein Bug?
![Screenshot_5](https://user-images.githubusercontent.com/70241137/205529999-90b3c089-f631-49cd-805b-c92aaf1c1165.jpg)

**Comment by CaleighRhodes** [comment]
Gut, dass du fragst - wir sind an dieser Stelle gestern auch verzweifelt 😅

**Comment by JohnRappStateV** [comment]
Hab exakt das gleiche Szenario.
