### ISSUE TITLE
Gegenstände/Müll auf dem Grundstück.

### ISSUE THREAD

**Issue by Looper-L** [eiksch/statev_v2_issues#2703]
**Character Name**
Gerold Langberg

**Haus:**
PLZ: 826
Genau: [Sandy Shores] - Niland Ave. 32

**Beobachtetes Verhalten**
Gegenstände/Müll auf dem Boden eines Grundstückes. (Nicht aufhebbar.) 

**Erwartetes Verhalten**
Gegenstande entfernen oder selber entfernbar.

**Schritte um den Fehler nachvollziehen zu können**
Bilder im Anhang

**Optional: Video / Bilder des Fehlers**
Im Anhang

![#1](https://user-images.githubusercontent.com/103857358/206295650-c870608b-6354-4e70-b455-8ade29c13bda.PNG)
![#2](https://user-images.githubusercontent.com/103857358/206295660-60ca723e-ba2b-4f3b-94c1-4467885bf60d.PNG)
![#3](https://user-images.githubusercontent.com/103857358/206295669-900d6b78-c112-4716-add8-aa360ab315cc.PNG)

**Comment by SHaagmann** [comment]
Kannst du bitte noch den Haushash hinzufügen?

**Comment by Looper-L** [comment]
Ist beigefügt.

**Comment by TheOutburst** [comment]
Die Ölfässer sind sobald man da gegen läuft wieder sichtbar, die müssen also da bleiben
Der Rest ist beim nächsten Update weg
