### ISSUE TITLE
Werkstatt felgen tuning fehler

### ISSUE THREAD

**Issue by Sielentpain6** [eiksch/statev_v2_issues#2706]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**FriedrichArnold**

**Auftrittszeitpunkt (08.12.22 / 5 uhr)**

**Beobachtetes Verhalten**
Es werden im Werkstatt System beim Tuning nur 1 felge und 1 felgenbereifung angezeigt Es werden aber 4-4 benötigt und nach der Anzeige das Resourcen fehlen wird eine felge sowohl eine felgenbereifung ausm Lager entfernt aber nicht verbaut das heißt sie sind weg, beim Xenon ist es auch schon aufgefallen wenn du nur schauen möchtest wie es aussehen tut und es wieder auf serie stellst musst du das Fahrzeug erstmal einparken davor du etwas anderes tunen möchtest da er sonst 2x xenon ausm Lager nehmen tut es aber nicht verbaut wird so habe ich schon 4 xenon verloren xD 😆 

**Erwartetes Verhalten**
Das es nichts ausm Lager nimmt wen es nicht verbaut wird. Bzw das die Anzeige richtig funktioniert 

Ich bedanke mich schon um Voraus für eure Mühe. 

Mit freundlichen Grüßen 
Julien aka Friedrich Arnold

**Comment by Domeex3** [comment]
Das Problem das nur 1x Felge und 1x Felgenbereifung im UI angezeigt wird ist korrekt, der Fehler das jeweils 1x aus dem Lager verschwindet trat bislang nicht auf.

**Comment by TeubyDE** [comment]
Bei welchem Fahrzeug tritt das auf?
Die Xenon Thematik ist ein anderes Thema.
