### ISSUE TITLE
Werbungen gehen nicht mehr weg

### ISSUE THREAD

**Issue by Erumeldor** [eiksch/statev_v2_issues#2708]
**Character Name**
Satoru_Tsuyoshi

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit dem AltV Update - 08.12

**Beobachtetes Verhalten**
Werbungen gehen nicht mehr weg.

**Erwartetes Verhalten**
Verschwindet wieder außerhalb der Range

**Schritte um den Fehler nachvollziehen zu können**
Werbung an, bisschen rumlaufen/fahren. Auf dem Bild unten sieht man wie das selbst in der Firma noch.

**Optional: Video / Bilder des Fehlers**
![image](https://user-images.githubusercontent.com/21212905/206459821-5f7730a1-d503-4c7f-872c-b05bad3897c1.png)

**Comment by CaleighRhodes** [comment]
Habe denselben Fehler:

![20221208151535_1](https://user-images.githubusercontent.com/74977218/206469022-edcdc6ca-95ea-4240-bac1-5af60735c83c.jpg)

**Comment by CaleighRhodes** [comment]
Habe  festgestellt, wenn man wo hin kommt, wo ebenfalls an gleicher Stelle Werbungen erscheinen, dann geht die gefreezte wieder weg.

**Comment by simplycach** [comment]
Tritt der Fehler noch auf ?

**Comment by Erumeldor** [comment]
> Tritt der Fehler noch auf ?

Ich hab seit dem die Werbung aus (und vermisse nichts). Kann morgen Abend mal wieder anmachen und beobachten, falls es bis dahin noch niemand getestet hat.

**Comment by Erumeldor** [comment]
![image](https://user-images.githubusercontent.com/21212905/223316522-f0a1a23b-4e14-4c8c-abf9-69ece8f64a10.png)
Immer noch das selbe Problem @simplycach
