### ISSUE TITLE
Flatbed Fahrzeuge schweben in der Luft

### ISSUE THREAD

**Issue by Sielentpain6** [eiksch/statev_v2_issues#2709]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Friedrich Arnold**

**Liam Kane**

**Auftrittszeitpunkt (08.12.2022 / 15.30 Uhr)**

**Beobachtetes Verhalten**
Die Fahrzeuge Fliegen in der Luft also die Position des Fahrzeugs ist zu weit oben und zu weit hinten siehe Bild

**Erwartetes Verhalten**
das sie Normal aufm Flatbed beladen sind ^^

**Optional: Video / Bilder des Fehlers**

![WhatsApp Image 2022-12-08 at 15 59 15](https://user-images.githubusercontent.com/52214992/206479718-d2221d79-057f-4723-8a3d-53661ea84cb0.jpeg)

**Comment by Derison** [comment]
Ist beim Slamtruck ebenfalls der Fall.
https://github.com/eiksch/statev_v2_issues/issues/2707
