### ISSUE TITLE
Gesprächsdauer am Telefon resettet sich

### ISSUE THREAD

**Issue by SatyriaDine** [eiksch/statev_v2_issues#2710]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Sofia_Black // Ogi_Black
**Auftrittszeitpunkt (Datum / Uhrzeit)**
seit dem AltV Update. Aufgefallen am 08.12.2022

**Beobachtetes Verhalten**
Wenn man telefoniert geht der Gesprächstimer bis 00:59 und fängt dann wieder bei 00:00 an

**Erwartetes Verhalten**
dass der timer normal zählt

**Schritte um den Fehler nachvollziehen zu können**
jemanden anrufen und auf die Gesprächszeit achten

**Comment by Derison** [comment]
@SatyriaDine Wird beim nächsten Update behoben sein. Vielen Dank fürs Melden! :)
