### ISSUE TITLE
Slamtruck Problemme beim Abschleppen 

### ISSUE THREAD

**Issue by Reggi257** [eiksch/statev_v2_issues#2711]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Reggi Stone**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Jedes mal beim abschleppen mit dem slam truck
**Beobachtetes Verhalten**

wenn man mit dem slamtruck abschleppt schwebt das abgeschleppte auto ein paar meter hinter dem abschlepper in der luft, denke wagen müssen neu gesetzt werden für auf dem wagen 
**Erwartetes Verhalten**

eigentlich sollte der abgeschleppte wagen auf dem schlepper sein 
**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by M4c-M4ni4c** [comment]
Duplikat zu 
#2707

**Comment by SHaagmann** [comment]
Das was @M4c-M4ni4c sagt
