### ISSUE TITLE
Diesel Verschwunden

### ISSUE THREAD

**Issue by Michi993** [eiksch/statev_v2_issues#2712]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Luke Hammer

**Auftrittszeitpunkt (Datum / Uhrzeit)**
 ca. 14.53 Uhr - 09.12.2022

**Beobachtetes Verhalten**
Diesel in Tanker-Achse umgeladen (1200 Ltr.) ca. 3 min später Servercrash -> Diesel nicht mehr im Lager und auch nicht im Tanker

**Erwartetes Verhalten**
Diesel sollte im Tanker sein

**Schritte um den Fehler nachvollziehen zu können**
schwer nachzuvollziehen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Bitte im Discord Ticket aufmachen bei weiteren Fragen. Ist bedingt durch den Crash. Kein Bug in dem Sinne.
