### ISSUE TITLE
Animationen werden nicht beendet/Items nicht mehr abgelegt

### ISSUE THREAD

**Issue by Clawdie** [eiksch/statev_v2_issues#2714]
**Character Name**
Glinda Leverstone

**Auftrittszeitpunkt (Datum / Uhrzeit)**
seit ca. 2 Wochen, immer

**Beobachtetes Verhalten**
keine Animationen mehr abbrechen können und auch kein Item in der Hand mehr weglegen können bzw. nur durch Griff zu Handy oder Tablet.

**Erwartetes Verhalten**
Animationen können beendet und Items wieder abgelegt werden

**Schritte um den Fehler nachvollziehen zu können**
beliebige Animation ausführen, Blumenstrauß oder Fernglas z.B. in die Hand nehmen

**Comment by SHaagmann** [comment]
Klingt blöd aber: Ist dein Numpad aktiv?

**Comment by Hutstaender** [comment]
Nachdem es generell funktioniert, würde ich auf Software Probleme tippen. Probier bitte mal folgendes:
-Gta Tastenbelegung auf Standard zurücksetzen
-In den gta Einstellungen -> Mauseinstellungen -> Input Typen durchwechseln z.B. Raw Input
-Antivierenprogramm ausschalten (falls es Kaspersky ist, deinstallieren, sonst lässt es sich nicht ausschalten)
-GtaV auf Fehler überprüfen
-Altv neuinstallieren

**Comment by SHaagmann** [comment]
@Clawdie Tritt es weiterhin auf, nachdem du die vorherigen Tipps ausprobiert hast?

**Comment by TeubyDE** [comment]
No response.
