### ISSUE TITLE
Bitte um eine Hausgarage #2679 (Nachtrag)

### ISSUE THREAD

**Issue by MatzeColeman** [eiksch/statev_v2_issues#2715]
Hallo zusammen,
da sich an dem beantragten Haus keine Garage/Carport befindet, ist mit bewusst, dass ich hier keine 6 Garagenplätze bekomme. 
Jedoch wäre ich sehr glücklich darüber, wenn wenigstens ein Stellplatz freigegeben werden könnte. Ich parke mein Auto in der Hofeinfahrt, welche auch dafür vorgesehen ist. Das Problem beim parken in der Hofeinfahrt ist nur, dass das Auto nach einem Restart krumm respawnt wird. Dadurch habe ich immer wieder Probleme das Auto aus der Einfahrt raus zu bekommen und muss es fast täglich reparieren lassen.

Grüße und danke für eure Antwort :)

_Originally posted by @MatzeColeman in https://github.com/eiksch/statev_v2_issues/issues/2679#issuecomment-1341945449_

**Comment by TeubyDE** [comment]
Wenn an dem Haus keine Garage und/oder Carport vorhanden ist werden wir dort keine Haus Garage hinzufügen.
