### ISSUE TITLE
Motorschaden LowRider

### ISSUE THREAD

**Issue by avoid-0001** [eiksch/statev_v2_issues#2718]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Hiwidar_Deoliveira
**Auftrittszeitpunkt (Datum / Uhrzeit)**
jeder Zeit wen man die Hydraulische Funktion der LowLows nutzt

**Beobachtetes Verhalten**
Man nutzt die Hydraulik der LowLows und Zack leuchtet die Kontrollleuchte

**Erwartetes Verhalten**
Sollte eventuell nicht direkt Gelb oder Rot leuchten ???

**Schritte um den Fehler nachvollziehen zu können**
 LowLow nehmen und kurz jumpen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Derison** [comment]
Hey @avoid-0001, mit welchem genauen Fahrzeugmodell hast du das Problem?

**Comment by avoid-0001** [comment]
Buccanner custom ich denke aber das Problem gilt für alle LowLows

**Comment by DonVitoDiangelo** [comment]
Also ja, sie können kaputt gehen, das aber etwas instant rot gelb/rot ist, kann nicht nachgestellt werden.
Kannst du uns dazu ein Video schicken?

**Comment by simplycach** [comment]
@avoid-0001 Ist dieser Fehler noch aktuell, wenn ja bitte wie @DonVitoDiangelo gebeten hat ein Video einsenden.
