### ISSUE TITLE
Casino Tische Funktionieren nicht mehr

### ISSUE THREAD

**Issue by Shishko96** [eiksch/statev_v2_issues#2719]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Mas_Jackson

**Auftrittszeitpunkt (Datum / Uhrzeit)**

16Uhr 12.12.22

**Beobachtetes Verhalten**
Beim Casino Spiel konnte man aufeinmal nicht mehr Halten oder Karte Ziehen Spiel hängt sich auf Karten und Chips bleiben auf dem Tisch und man kann sich nicht mehr dran setzten

**Erwartetes Verhalten**
/

**Schritte um den Fehler nachvollziehen zu können**
Habe eine Karte bekommen 
Danach die 2 Karte hatte eine 19 auf der Hand musste H Drücken zum Halten oder L zum ziehen
konnte nix mehr drücken
Spiel musste ich mit Task Manager schließen
Spiel Neustart Karten und Chips liegen auf dem Tisch
man kann sich nicht mehr hinsetzten

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
/

**Optional: Video / Bilder des Fehlers**
![20221212164156_1](https://user-images.githubusercontent.com/120399543/207090987-0a255e3b-b6ab-496e-9cb4-ae602ad38a46.jpg)
![20221212163506_1](https://user-images.githubusercontent.com/120399543/207090996-7be961bc-3222-4f1e-80bd-ec9e5f4ede5d.jpg)
![20221212163515_1](https://user-images.githubusercontent.com/120399543/207091004-bb27d53e-137d-4e7e-ada3-b96f8bf90bff.jpg)
![20221212163520_1](https://user-images.githubusercontent.com/120399543/207091010-33b48d8d-fa77-4e11-a674-2ebb674cecba.jpg)

**Comment by its4l3x** [comment]
Bitte nochmal erneut prüfen. Konnte keinen Fehler feststellen

**Comment by TheOutburst** [comment]
wir haben mit diesem Update einige Bugs die ein sehr ähnliches Verhalten verursachen konnten gefixt, falls das nochmals auftaucht neuen Bugtracker öffnen und ggf. auf diesen verweisen.
