### ISSUE TITLE
Animationsabbruch im Fahrzeug führt zu Unsichtbarkeit

### ISSUE THREAD

**Issue by Marlisediefiese** [eiksch/statev_v2_issues#2720]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Amara_Petrov

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Gestern (12.12.22) und am 09.12.22 (nach AltV update)

**Beobachtetes Verhalten**
Sobald man eine Animation ausführt und mit dieser ins Auto steigt und dann im Auto beendet fällt man quasi runter? bzw. man fällt aus dem Auto aber man ist noch zum Fahrzeug attached nur für sich und andere unsichtbar.

**Erwartetes Verhalten**
Animation während man im Auto sitzt abbrechen zu können und nicht unsichtbar werden oder wo anders zu landen.

**Schritte um den Fehler nachvollziehen zu können**
Ich hatte bei beiden fällen die Animation Hände an der Weste 2 aktiv. Bin dann ins Fahrzeug gestiegen und habe die Animation abgebrochen.

**Optional: Video / Bilder des Fehlers**
Hier zwei kurze Clips: https://youtu.be/9qsiRGKHCRw und  https://youtu.be/CsV25Z-VuZg

**Comment by SHaagmann** [comment]
Mit verschiedenen Animationen Ausprobiert und nur beim Westengriff (Kragen) nachstellbar gewesen
