### ISSUE TITLE
Essentials Hoddie mit Duffle Bag geht nicht

### ISSUE THREAD

**Issue by btwDeamon** [eiksch/statev_v2_issues#2721]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```
**Charakter Name:**
Karl Reis

**Auftrittszeitpunkt:**
Gemerkt habe ich es heute den 14.12.2022 um Ca. 5 Uhr. Ich gehe aber davon aus es den Bug schon länger gibt aber ihn halt noch keiner reportet hat.

**Beobachtetes Verhalten:**
Mit dem Essentials Hoodie wird Duffle Bag nicht angezeigt. Wenn ich den Hoddie ausziehe ist die Tasche zu sehen wenn ich ihn aber wieder anziehe ist sie wieder weg.

**Erwartetes Verhalten:**
Das der Duffle Bag mit dem Hoodie zu erkennen ist, denn im Moment kann man 30kg mehr mitnehmen ohne das es jemand sieht.

**Schritte um den Fehler nachvollziehen zu können:**
Einfach den  Hoodie anziehen und dann die Duffle Bag anziehen. Dann sieht man das die Duffle Bag nicht zu sehen ist. Dann könnt ihr den Hoddie die ganze Zeit an und aus ziehen und seht wie die Tasche da ist und wieder weg ist.

**Optional: Video / Bilder des Fehlers**
https://www.youtube.com/watch?v=20oRil3qp8k

**Comment by CaleighRhodes** [comment]
Doch, der Bug wurde schon öfter reportet, ist mit vielen gemoddeten Klamotten so.

**Comment by SHaagmann** [comment]
das was @CaleighRhodes sagt
