### ISSUE TITLE
Entfernung der Mülltonnen

### ISSUE THREAD

**Issue by Saaria83** [eiksch/statev_v2_issues#2722]
Hallöchen, 

wir wollten mal nachfragen ob es möglich ist, die Mülltonnen auf unserem Grundstück entfernen zu lassen?
Wenn man ein Auto davor parkt, kommt es manchmal vor, dass sich dieses ein Stück nach hinten buggt und das Auto dann kaputt geht. Was auf Dauer wirklich ärgerlich ist.

Haushash ist: house_VinewoodHills_34

![Mülltonnen](https://user-images.githubusercontent.com/70151476/207813474-3816817b-1474-437f-ad09-8abeba3ce7fd.png)

LG Hanna & Carlie

**Optional: Video / Bilder des Fehlers**

**Comment by TheOutburst** [comment]
Bei den Mültonnen verhält es sich leider so, dass die trotzdem wieder auftauchen sobald sie bewegt werden würden, da bringt das wegmachen leider nichts
