### ISSUE TITLE
Werkstatt Tuning verändert/durcheinander

### ISSUE THREAD

**Issue by nox142** [eiksch/statev_v2_issues#2724]
**Character Name**
Jona Lindner

**Auftrittszeitpunkt (Datum / Uhrzeit)**
16.12.2022 11 Uhr

**Beobachtetes Verhalten**
Tuning bei Weevil Custom wurde verändert nach dem Update:
https://prnt.sc/yaJFC1at5zUY
Leider habe ich gerade kein Bild vom vorherigen Zustand des Fahrzeugs

Wenn ich jetzt Tuning verändere, stimmen die Bezeichnungen vom TuningPC und dem angezeigten nicht mehr überein. ZUdem verändert es plötzlich das gesamte Angezeigte optische tuning, nur weil zum beispiel das Dach verändert wurde
https://prnt.sc/tA3ETaks_21G

**Erwartetes Verhalten**
Korrekt eingezeigtes Tuning vom PC und dem angezeigten

**Schritte um den Fehler nachvollziehen zu können**
Fahrzeuge die man kennt, kontrollieren ob das Tuning noch stimmt und dann am Tuning PC schauen, was passiert wenn man was am Tuning verändert

**Comment by nox142** [comment]
Eventuell handelt es sich um einen Fehler bei neueren Fahrzeugen, bei einem älteren Fahrzeug stimmt alles

**Comment by nox142** [comment]
https://prnt.sc/E7OfH1mqyJpA
Felgenverbrauch wird wieder falsch angezeigt beim PKW

**Comment by TheOutburst** [comment]
Siehe
https://discord.com/channels/365251792679862292/461460992287571988/1053723168075939870

**Comment by DonVitoDiangelo** [comment]
Bitte auch darauf achten, keinerlei Mods aktiv zu haben,.

**Comment by nox142** [comment]
Keine Mods derzeit drauf und der Tuningrechner passt nicht überein. Auch bei anderen Mitarbeitern
