### ISSUE TITLE
Brioso 300 Widebody Tuning Bug

### ISSUE THREAD

**Issue by SHaagmann** [eiksch/statev_v2_issues#2725]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Sven Rosenbach
**Auftrittszeitpunkt (Datum / Uhrzeit)**

Nachm AltV Update
**Beobachtetes Verhalten**

Beim Brioso 300 Widebody hat sich das Tuning geänder
**Erwartetes Verhalten**

sollte ja nicht so sein 
**Schritte um den Fehler nachvollziehen zu können**

Mein Auto Ausparekn
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

so siehts jetzt aus:
![image](https://user-images.githubusercontent.com/58612983/208166242-255cb230-6e11-46bd-8f15-e76546dc0fa8.png)
und so vorher (fands besser)
![image](https://user-images.githubusercontent.com/58612983/208166269-55ef9756-db59-44da-9275-1c0c98987a6e.png)

**Comment by TheOutburst** [comment]
#2724
