### ISSUE TITLE
Klamotten werden bei anderen Spielern anders angezeigt

### ISSUE THREAD

**Issue by JaxBorrow** [eiksch/statev_v2_issues#2726]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Jax Borrow 

**Auftrittszeitpunkt (Datum / Uhrzeit)**
16.12. zirka 21:10

**Beobachtetes Verhalten**
Habe mich gerade zum ersten mal mit dem neuen AltV Patch eingeloggt und wurde darauf hingewiesen, dass meine New Era NFL Raiders Bomber neue Badges hat. Für mich wird alles normal angezeigt

**Erwartetes Verhalten**
Dass die Klamotten für alle gleich angezeigt werden

**Schritte um den Fehler nachvollziehen zu können**
zu zweit einloggen und einen Spieler die Raiders Bomber anziehen lassen

**Optional: Video / Bilder des Fehlers**

![1](https://user-images.githubusercontent.com/100872532/208182324-01781c0a-a897-4773-bfd8-ab5629d1cc64.jpg)
![2](https://user-images.githubusercontent.com/100872532/208182339-7f1df944-cb26-4d31-89f0-7f4e731a6b60.jpg)
![3meineSicht](https://user-images.githubusercontent.com/100872532/208182347-15d63c77-94f8-44f4-b447-cd3b67f8414c.jpg)
![4meineSicht](https://user-images.githubusercontent.com/100872532/208182354-c52ba38a-596a-4cb0-a4c2-e4fcaeccbe19.jpg)

**Comment by DonVitoDiangelo** [comment]
Entweder bei dir selbst oder der andere soll seine Mods entfernen, dann ist wieder alles fine.
