### ISSUE TITLE
Westengriff Animation immernoch nutzbar

### ISSUE THREAD

**Issue by FoxXxyLive** [eiksch/statev_v2_issues#2728]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Mit verschiedenen Charakteren

**Auftrittszeitpunkt (Datum / Uhrzeit)**

17.12.2022 13:40

**Beobachtetes Verhalten**

gelöschte Animation, "Westengriff - Hände unter Weste #1"
"Westengriff - Hände unter Weste #2", können, wenn man sie vorher als Favorit hinterlegt hatte, immernoch abgespielt  und benutzt werden
**Erwartetes Verhalten**

Animationen sollten nicht mehr verwendbar sein, da sie ja Serverseitig entfernt wurden
**Schritte um den Fehler nachvollziehen zu können**

genannte Animation als Favorit abgespeichert haben 
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Screenshot_35](https://user-images.githubusercontent.com/79162546/208243032-be7a23ae-d755-4754-ad75-25a2e6040663.png)

**Comment by DonVitoDiangelo** [comment]
next update solved
