### ISSUE TITLE
Problem neustart server und respawn

### ISSUE THREAD

**Issue by RayDudikov** [eiksch/statev_v2_issues#2732]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Ray_Dudikov**

Ray_Dudikov
**Auftrittszeitpunkt (Datum / Uhrzeit)**
14:58 bei neustart und auch allen anderen neustarts vom server

**Beobachtetes Verhalten**

Hallo ich habe ein problem und zwar nach jedem neustart oder auch respawn ist mein fahrzeig in irgendeiner garage eingeparkt, allerdings nur bei mir den anderen ihre fahreuge bleiben stehen .Woran kann das liegen?

**Erwartetes Verhalten**

Fahrzeuge sollte stehen bleiben wo sie abgestellt wurden 

**Schritte um den Fehler nachvollziehen zu können**

Einfachste weise mein fahrzeug mit dem kennzeichen Dudikov irgendwo hinstellen und server neustarten 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by SHaagmann** [comment]
Vllt bewegst du es einfach zu wenig wenn du es kurz vorher ausparkst und kaum bewegst dann wird es eingeparkt. Wenn du es schon viel benutzt hast dann bleibt es draußen.

**Comment by RayDudikov** [comment]
also das ding hat 5000 km drauf und fahre täglich mehrmals zur mine , kann ich mir nicht vorstellen

**Comment by SHaagmann** [comment]
Es muss halt aktiv vor dem Restart bewegt worden sein. Dafür reicht halt nicht mal zur Mine und zurück

**Comment by RayDudikov** [comment]
ok das werde ich mal versuchen, aber wie gesagt meine frau ihr Fahrzeug fährt selbe strecke und ihres bleibt stehen , irgendwie mach ich da ein fehler

**Comment by SHaagmann** [comment]
Da spielen mehrere Faktoren rein genaueres kann ich dir auch nicht sagen, würde das Ticket erstmal schließen. Wenn doch noch was ist kannst du dich gerne Melden

**Comment by RayDudikov** [comment]
ja denke ich auch , ich kann es auch nicht nachvollziehen :-)
