### ISSUE TITLE
Gegenstand/Müll entfernen vom Grundstück.

### ISSUE THREAD

**Issue by Looper-L** [eiksch/statev_v2_issues#2733]
Character Name
Gerold Langberg

Haus:
PLZ: 826
Genau: [Sandy Shores] - Niland Ave. 32
Haushash: SandyShores32

Beobachtetes Verhalten
Gegenstand/Müll auf dem Boden eines Grundstückes. (Nicht aufhebbar.)

Erwartetes Verhalten
Gegenstand entfernen.

Schritte um den Fehler nachvollziehen zu können
Bilder im Anhang

Optional: Video / Bilder des Fehlers
Im Anhang

![1](https://user-images.githubusercontent.com/103857358/208530997-1d9848cf-f05f-45f1-8b19-660b45fa57ff.PNG)

**Comment by TheOutburst** [comment]
Moin,
ich fasse meine Antwort mal auch von #2723 hier rein.
Das ist jetzt in Summe der dritte Bugtracker für das selbe Haus. Nichts von dem was ihr wollt ist zwingend unmöglich, aber es ist kein Verbrechen mehrere Sachen in einen Eintrag zu packen, solange es das selbe Gebäude betrifft / die selbe Aktion ist.

So ists es einfach nur verwirrend, ob das was im Eintrag C angemerkt wird nicht schon in Eintrag A erledigt wurde.

_______

Änderungen sind dann next update live

**Comment by Looper-L** [comment]
Moin,
ich danke Dir für die Antwort und entschuldige mich für die 3 verschiedenen Beiträge.
Ich hatte das alles im Kopf aber nur einzeln täglich daran gedacht. Wird nicht wieder vorkommen. Danke nochmal!

Grüße.
