### ISSUE TITLE
Casino Games broken 

### ISSUE THREAD

**Issue by FoxXxyLive** [eiksch/statev_v2_issues#2734]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Samy Nustrajev - Lina Marino
**Auftrittszeitpunkt (Datum / Uhrzeit)**

ab 18:40 Uhr 20.12.2022
**Beobachtetes Verhalten**

Alle Casino Games sind broke 

Das Rad kann gedreht werden aber dreht nicht, der Croupier teilt keine Karten aus, Crash Game kann auch am Eingang gestartet werden 
**Erwartetes Verhalten**

Casino Games sollten funktionieren 
**Schritte um den Fehler nachvollziehen zu können**

ins Casino an die Tische oder an das Rad gehen 
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by FoxXxyLive** [comment]
Edit: Sobald man am Black Jack Tisch sitzt, kann man nicht mehr aufstehen, wenn man reloggt wird der Platz auch als belegt angezeigt.

**Comment by SHaagmann** [comment]
#2719 Duplikat
