### ISSUE TITLE
Fahrzeug und Charakter glitcht in den boden und fällt durch!

### ISSUE THREAD

**Issue by RimiKaru** [eiksch/statev_v2_issues#2735]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Rimi Karu  /  Rumpo Costum

20.12.2022  ca.22:00 - 22:30 

Fahrzeug und Char Glitchen und fallen durch den boden, 2x an der gleichen Stelle

Nicht durch fallen

Vom NSA gebäude (garage) per "GPS" zum Restaurant Haute bei 5017 fahren! Genau beim Gericht!

2K

https://www.youtube.com/watch?v=ygvRri2SP2w  sieht man bei ca. 1:30

![Screenshot 2022-12-20 233653](https://user-images.githubusercontent.com/121135271/208780067-42f1b503-9468-46b5-8aa0-6f1fbe31acbd.jpg)

**Comment by Derison** [comment]
Wie vorhin schon im Teamspeak besprochen, ist der Grund hierfür wahrscheinlich ein installierter Grafikmod. Daher für uns an der Steller meiner Meinung nach kein Handlungsbedarf.

**Comment by RimiKaru** [comment]
Ja, das kann ich nun bestätigen! mit dem neuen ALTV update und dem NVE+ENB update, werden wohl die shader falsch berechnet und man fällt durch die texturen durch! Das Problem, ist nach dem entfernen von NVE+ENB, nicht mehr vorhanden!
