### ISSUE TITLE
Fahrzeug komplett umgetuned

### ISSUE THREAD

**Issue by Michi993** [eiksch/statev_v2_issues#2737]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Luke Hammer

**Auftrittszeitpunkt (Datum / Uhrzeit)**
21.12.2022

**Beobachtetes Verhalten**
Fahrzeugtunings sind komplett verschieden, ich denke, das lag am alt:v update, habe seit dem das Fahrzeug nicht mehr ausgeparkt

**Erwartetes Verhalten**
Tuning sollte nicht verändert sein

**Schritte um den Fehler nachvollziehen zu können**
X

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehler
Bilder in der Garage ist das aktuelle Tuning:
https://ibb.co/WsXBtpV
https://ibb.co/C2PjzdP
https://ibb.co/pLT9yTr
https://ibb.co/CvRBYt7

**Comment by CaleighRhodes** [comment]
#2731 
#2725 
#2724 

schon mehrfach gemeldet.

**Comment by SHaagmann** [comment]
Das was @CaleighRhodes sagt
