### ISSUE TITLE
Teleporter am Haus zur Terrasse 

### ISSUE THREAD

**Issue by FoxXxyLive** [eiksch/statev_v2_issues#2738]
Charakter: Samy Nustrajev

Haus: Ineseno Road 65 
Haushash: SamsonCountryRew_House_22

Hey Ihr tollen Teamler, ich hätte eine Bitte und zwar hätte ich ganz gerne an meinem Haus einen Teleporter, sodass wir die bisher zu Fuß nicht erreichbare Terrasse nutzen und im RP bespielen können. 
Wäre lieb von euch, wenn Ihr das für uns umsetzen würdet. 

(NUR ALS BEISPIEL)
Der Teleporter könnte hier
![Screenshot_37](https://user-images.githubusercontent.com/79162546/209359818-adaa3a85-9267-4ce8-abec-28a2b877972d.png)
oder hier 
![Screenshot_38](https://user-images.githubusercontent.com/79162546/209359865-2811803f-38a5-44c3-b70d-d3166542840b.png)
an die Tür gesetzt werden, damit wir 
Hier auf die Terrasse hochkommen.
![Screenshot_39](https://user-images.githubusercontent.com/79162546/209359901-396a8dcc-ffbf-400e-accb-3746416f2d27.png)

Danke schonmal im vorraus! <3

**Comment by TheOutburst** [comment]
Du hast da vorne 4 Balkone die allesamt voneinander abgetrennt sind, hab dir mal nen Portmarker bei "oder hier" zu dem größten davon gemacht
Das for Sale Schild geht auch weg, ist dann beides beim nächsten Update drin.

**Comment by FoxXxyLive** [comment]
Perfekt, ich danke dir! 
Kannst du dir eventuell nochmal den Müll anschauen, wir haben ja hinter dem Haus bei den "oder hier" schon Mülltonnen, vielleicht können die dann vorne bei der Garage weg? Und diese doofe Kiste die da immer rumfliegt. :D

**Comment by FoxXxyLive** [comment]
![Screenshot_44](https://user-images.githubusercontent.com/79162546/209479600-7fe2bfba-bbfb-4e47-8d6e-5ab29723a87a.png)
![Screenshot_45](https://user-images.githubusercontent.com/79162546/209479601-9ed27e18-ffa5-4243-8994-c03473222df8.png)
also diese Kiste und die Mülltonnen

**Comment by TheOutburst** [comment]
Moin,
die Mülltonnen würden unter gewissen Umständen aus dem Nix wieder auftauchen, deswegen kann ich dir die nicht RP getreu entfernen
Der Karton und die Müllsäcke gehen, sind dann auch weg

**Comment by TheOutburst** [comment]
#dopellsolved
