### ISSUE TITLE
Harter Gamecrash in bestimmten Läden

### ISSUE THREAD

**Issue by SgtTukiTuki** [eiksch/statev_v2_issues#2740]
Sandy Folk

Aufgetreten aktuell heute gegen 00.00Uhr (kam schon mehrfach vor)

Ich habe folgendes Problem und zwar jedesmal Abends wenn ich den Friseur bei 4008 betrete um dort zu Arbeiten sich das Spiel komplett verabschiedet so das ich einen Neustart erzwingen muss... das kommt nur in diesem Laden vor und immer erst zu später Stunde. 
Das ganze passiert auch bei Bennys. Ich hab das nirgendswo anders und an den Einstellungen kann es auch nicht liegen hab schon einiges ausprobiert.

**Comment by DonVitoDiangelo** [comment]
Hast du schon versucht dein GTA neu zu Installieren und vor allem auch frei von sämtlichen Mods zu halten?
Weiterhin solltest du uns deinen Crash Log, wenn das Spiel frisch gecrasht ist, zukommen lassen. Den findest du dann direkt in deinem altv/logs Ordner.

**Comment by SgtTukiTuki** [comment]
War auch nach Neuinstallation... werd das nächste Mal die Logs raussuchen
