### ISSUE TITLE
Hakuchou Drag Tuning Problem

### ISSUE THREAD

**Issue by prinzenbude** [eiksch/statev_v2_issues#2741]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Johny_Koenig

27.12.2022 / 22-22:45

Verbauung von Tuningteilen mehrfach fehlgeschlagen 
Fahrzeug = Hakuchou Drag
Tuningteil = Turbo und Schalthebel

Erhöhte Leistung

Man nehme dieses Motorrad und versucht diese Bauteile einzubauen, Jeweils die Letzte Stufe (3) 
Es wird leider nichts verbaut obwohl Geld sowie Bauteile entnommen werden.

![Bezahlung](https://user-images.githubusercontent.com/61855112/209725908-40e36579-d636-400b-a7ac-84c4df4ad33d.PNG)

**Comment by SHaagmann** [comment]
Unter welche Reiter ist denn der Turbo und der Schalthebel? Gibt es bei mir garnicht zur Auswahl.
![image](https://user-images.githubusercontent.com/58612983/209825730-44de0929-3e43-4923-9fd8-afd287905810.png)
![image](https://user-images.githubusercontent.com/58612983/209825778-fed72be7-a1a9-4a11-93f3-ff88bb1732bb.png)

**Comment by prinzenbude** [comment]
Moin, das eine ist unter Bremshebel und das andere unter Lautsprecher



Von: ***@***.***>
Gesendet: Mittwoch, 28. Dezember 2022 15:18
An: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Betreff: Re: [eiksch/statev_v2_issues] Hakuchou Drag Tuning Problem (Issue #2741)


Unter welche Reiter ist denn der Turbo und der Schalthebel? Gibt es bei mir garnicht zur Auswahl.
[image]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F58612983%2F209825730-44de0929-3e43-4923-9fd8-afd287905810.png&data=05%7C01%7C%7Cdedb7da895d34550b50f08dae8de67fd%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638078339165305599%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=V6Pe0rJxO8ATeq8wxMfB%2F6jB%2Frew9aZAeHWNDgiLFUE%3D&reserved=0>
[image]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F58612983%2F209825778-fed72be7-a1a9-4a11-93f3-ff88bb1732bb.png&data=05%7C01%7C%7Cdedb7da895d34550b50f08dae8de67fd%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638078339165305599%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2dcQIokQhXZEGF0N2ymmqxLEPZWvyY%2Bsk8UFKM%2BEZmY%3D&reserved=0>

**Comment by prinzenbude** [comment]
Wir haben das ganze zwei mal getestet einmal in der Bennys Werkstatt und noch einmal in einer anderen

**Comment by TheOutburst** [comment]
Moin
Turbo und HSW Leistungsverbesserung unterstützen wir nicht, weswegen es keine Änderung gab und die Tuningoption bei Fahrzeugen idr. deaktiviert ist.
Außerdem hat es Konflikte mit NVE, wie man bei Sven sieht.

Ob es beim rein nehmen der hakuchou2 vergessen wurde oder die Tunings erst in der Zwischenzeit dazukamen ist jetzt nichtmehr festzustellen, jedenfalls habe ich die Slots jetzt geblockt, kommt nächstes Update, danke fürs melden!

Solltest du das Gefühl haben das Geld sollte dir erstattet werden kannst du die gewohnten Supportwege nutzen
