### ISSUE TITLE
Fahrzeug taucht nicht in der Garage auf

### ISSUE THREAD

**Issue by Xymena** [eiksch/statev_v2_issues#2744]
**Character Name**
Anna_Luna

**Auftrittszeitpunkt (Datum / Uhrzeit)**
etwa 30-31.12.2022

**Beobachtetes Verhalten**
Es steht ein Declasse Granger und  Pfister Coment S2 in der Garage Ace Jones Drive 174  (house_VinewoodHills_166) allerdings taucht nur der Pfister in der Garage auf. Der Granger wird nicht aufgelistet. 

**Erwartetes Verhalten**
Pfister und Comet S2 Tauchen in der Garage auf, und lassen sich ausparken 

**Schritte um den Fehler nachvollziehen zu können**
Mit E an Tür auf Garage nur ein Fahrzeug taucht auf, abgleich mit Statenet / Handy zwei fahrzeuge sind dort geparkt 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![image](https://user-images.githubusercontent.com/76626768/210175566-58167243-32c0-4548-a5b9-93c2938b433f.png)
![image](https://user-images.githubusercontent.com/76626768/210175580-3bddec84-fd86-41c5-92c7-f4432200c1b8.png)
![image](https://user-images.githubusercontent.com/76626768/210175598-1b79e153-4a45-41ef-bfb8-f7b0a1e3dc0a.png)

**Comment by TeubyDE** [comment]
Bitte über den Support umparken lassen.
