### ISSUE TITLE
Kart Bahn defekt

### ISSUE THREAD

**Issue by nox142** [eiksch/statev_v2_issues#2745]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Jona Lindner

**Auftrittszeitpunkt (Datum / Uhrzeit)**
01.01.2023 22:40 Uhr

**Beobachtetes Verhalten**
Auf der Kartbahn steht derzeit nur Kart und das springt nicht an, wenn ein Rennen gestartet wird. Letztes Rennen war angeblich am 15.12.

**Erwartetes Verhalten**
Dass dort mehrere Karts stehen und anspringen, wenn ein Rennen gestartet wird

**Schritte um den Fehler nachvollziehen zu können**
Auf die Kartbahn gehen und rennen starten

https://prnt.sc/XYO_v38wWdna

**Comment by TeubyDE** [comment]
nächstes Update fixed.
