### ISSUE TITLE
Fehler beim Lackiercomputer

### ISSUE THREAD

**Issue by DepeaceDrey** [eiksch/statev_v2_issues#2746]
Depeace Drey

01.01.2023 (ist aber reproduzierbar)

Sobald man beim Lackieren von Fahrzeugen die gleiche Sekundärfarbe hinzu nimmt, wird der Gesamtverbrauch an Dosen verringert. Beispiel:
Ich möchte etwas Lackieren:
Primär 7600$
inkl. Sekundär 6500$

Ich würde erwarten, dass durch die zusätzliche Sekundärfarbe mehr Lacke verbraucht werden.

Siehe Video.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

https://youtu.be/7z32OaTU2go
**Optional: Video / Bilder des Fehlers**

**Comment by M4c-M4ni4c** [comment]
Man lackiert immer beide farben und da bei sekundär nunmal der Speziallack 12 drin steht(der relativ teuer ist) ist es natürlich günstiger wenn man eine andere sekundär farbe nimmt die weniger dosen verwendet(schwarze lack dosen sind nunmal teuer).

**Comment by DepeaceDrey** [comment]
Deine Antwort macht keinen Sinn. @M4c-M4ni4c 
Hast du dir mein Video überhaupt angeschaut?

**Comment by Dean-Gallagher** [comment]
Sobald du das lackier Terminal öffnest zeigt er dir die aktuelle Primär und Sekundär farbe an die auf dem Fahrzeug ist. 
Der Lackverbrauch ist dabei derer welche diese Farbe braucht. In deinem Falle die Speziallfarbe 12 Matte Black. 

Änderst du nun entweder die Primär oder Sekundär farbe so ändert sich der verbrauch von dieser mit. 
In deinem Falle wäre das 1x Speziallackierung Matte Black (folgend MB) sowie RGB Schwarz.
Diese Rechnung kannst du bei Primär/Sekundär machen oder Sekundär/Primär (MB/RGB Black oder RGB Black/MB)

RGB Schwarz braucht 1x Schwarzen Lack und 2 Basis lack, man MUSS immer Haupt und Sekundärfarbe lackieren 
Also 2 Schwarze Dose und 4 Basis Lack für die billigste Lackierung die es gibt. 

Färbst du also die Hauptfarbe Gold und lässt die Sekundär Schwarz wie in deinem Falle Matte Black so haut die Rechnung auch wieder hin da 
Matte Black aus 2 Dose Basislack 6 Dose Schwatz und 20 Kohlestaub besteht. 
Für Primär und Sekundär also 4 Dose Basis, 12 Dose Schwarz und 40 Kohlestaub. 
Ändert man also Hauptfarbe auf Gold + Sekundär Natte Black
So wird Hauptfarbe 2 Dose Basis, 1 Dose Schwarz. 5 Dose Weiß, 50 Goldstaub + Sekundär 2 Dose Basis, 6 Dose Schwarz, 20 Kohlestaub. 

Du kannst Spezial sowie RGB kombinieren dadurch kommen so extrem komische verbräuche zustande.

Ich sehe keinen Fehler in deinem Video.

**Comment by TeubyDE** [comment]
Es handelt sich hierbei um die beiden Gegenläufigen Systeme RGB und GTA Color.
Diese beiden System berechnen die benötigten Farbdosen dynmisch. Daher kommt dieser Verhalten zustande.

Wie @Dean-Gallagher schon geschrieben hat, ist das kein Fehler.
