### ISSUE TITLE
Frage ob das Schild weg geht 

### ISSUE THREAD

**Issue by einhornpupsii** [eiksch/statev_v2_issues#2750]
Hallo mein Name ist Anna Gambino 
Ich wohne im Mirrorpark und würde gerne das Schild vor dem Haus weg haben würde das gehen ? 

HausHash: house_MirrorPark_20

**Comment by TheOutburst** [comment]
Moin,

diese großen Schilder sind keine eigenständigen Objekte sondern hängen mit am gesamten Boden der anliegenden Grundstücke. Deswegen können wir die leider nicht Ressourcensparend entfernen
![grafik](https://user-images.githubusercontent.com/70150675/212482466-a9cdf3b1-c135-4a53-9127-935fbdfa00a0.png)
