### ISSUE TITLE
UI - Tablet-Screen öffnet sich Vollbild bei mittlerer Maustaste

### ISSUE THREAD

**Issue by Erumeldor** [eiksch/statev_v2_issues#2751]
**Character Name**
Satoru_Tsuyoshi

**Auftrittszeitpunkt (Datum / Uhrzeit)**
05.01 - 14:30

**Beobachtetes Verhalten**
Am Tablet Ingame Statenet öffnet, und dann irgendwo ein Menüpunkt mit mittlerer Maustaste anklicken, hat darin geendet das der Tablet-Screen Vollbild wurde und nicht mehr geschlossen werden konnte. (Alt+F4 und Neustarten ist der einzige Ausweg)

**Schritte um den Fehler nachvollziehen zu können**
Mittlere Maustaste auf ein Menüpunkt im Tablet-Satenet

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
FullHD

**Optional: Video / Bilder des Fehlers**
![image](https://user-images.githubusercontent.com/21212905/210791542-c4ce0559-7169-44a5-bf0b-01568203bbc5.png)

https://user-images.githubusercontent.com/21212905/210792164-caaa2d47-1aa1-4b60-ab8c-1abed6e1d719.mp4

**Comment by TeubyDE** [comment]
Leider ein Verhalten was wir nicht beeinflussen können.
