### ISSUE TITLE
Abladepunkt & Eingang Verschieben

### ISSUE THREAD

**Issue by ManuelLadner** [eiksch/statev_v2_issues#2752]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Manuel Ladner**

**Jederzeit!**

**Eingang / Abladepunkt / Ausgang**

**Bitte diese Punkte nach vorn versetzten da man mit einem großen Fahrzeug schwer rann kommt und Betreten wird das Gebäude von hinten und beim verlassen steht man vorne!**

**Punkte und Eingang nach vorn an die Straße versetzen. Der Platz und die Möglichkeit ist da. Auch die Nachbar Gebäude haben die Punkte vorne an der Straße (siehe Fotos)**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![20230105200204_1](https://user-images.githubusercontent.com/77968842/210869690-287c2477-9513-4cd4-8b88-1667e5520520.jpg)
![20230105200213_1](https://user-images.githubusercontent.com/77968842/210869740-2c205fa0-305d-4247-90d4-03a75e9a813c.jpg)
![20230105200228_1](https://user-images.githubusercontent.com/77968842/210869750-d178525f-4114-478c-8a3e-576c1db4110b.jpg)
![20230105200239_1](https://user-images.githubusercontent.com/77968842/210869757-16cb02ff-3f17-47ba-8cbb-b7b659a2889d.jpg)

 Vielen Dank im Voraus!

**Comment by TheOutburst** [comment]
Moin @ManuelLadner 
Ich kann dir nicht einfach die gesamte Firma verschieben, die muss da an der Hinterseite bleiben. Ist nunmal auch nicht die einzige Firma da hinten und auch der Abladepunkt wird noch von ner anderen Firma genutzt. Aber ich hab mal den Ausgangspunkt zum Eingang gelegt, ich hoffe das ist zu deiner Zufriedenheit
