### ISSUE TITLE
Garage zu Haus hinzufügen

### ISSUE THREAD

**Issue by JeremyKloeckl** [eiksch/statev_v2_issues#2753]
Hi,

es wäre toll, wenn das Haus mit dem Haushash: house_VinewoodHills_50 
eine Garage bekommen könnte.

Dankeschön. :)

**Comment by TheOutburst** [comment]
Glückwunsch zum Hauskauf, mitm nächsten Update hat dein Haus dann sogar eine Garage unterm "Carport"
