### ISSUE TITLE
Parkpunkt, Müll, Balkon. Ineseno Road 60a

### ISSUE THREAD

**Issue by WunderBaum9** [eiksch/statev_v2_issues#2754]
**Character Name**
David Ostrowski

**Ort**
Ineseno Road 60a - SamsonCountryRew_House_16

**Beobachtetes Verhalten**
Ich hätte die Bitte, den Einparkpunkt weiter nach vorn zu versetzen. Wenn man rückwärts einparken möchte, ist dies sehr schwer, weil der Punkt so nahe vor der Garage liegt. Außerdem würde ich gerne hin und wieder mit größeren Fahrzeugen den Punkt anfahren können.
Der Ausparkpunkt müsste auch etwas weiter nach vorne, weil größere Fahrzeuge (Granger) in dem Müll spawnen.

Zudem wollte ich fragen, ob die Müllsäcke und die Tonnen entfernt werden könnten, da sie wie gesagt beim Ein- und Ausparken stören.

Last, but not Least: Gäbe es die Möglichkeit, wie bei einigen anderen Häusern am Westhighway, am Garagentor einen Portpunkt für die Balkone an der Rückseite des Hauses zu erhalten? Ich würde diese gerne nutzen. Würde mich freuen, wenn es klappen würde.

**Optional: Video / Bilder des Fehlers**
![park](https://user-images.githubusercontent.com/122064578/210906136-58021d69-6a24-4b24-a837-0e8087088c62.png)

**Comment by TheOutburst** [comment]
- Garagenpunkt 1.5 Meter nach vorne verschoben (das ist auch der Ausparkpunkt)
- Die Müllsäcke erscheinen leider wieder wenn man "über sie drüber" läuft und die Mülltonnen haben ein ähnliches Verhalten, zusätzlich gibt es Bugs in Kombination mit der Y Interaktion von entfernten Objekten, deswegen gehen die auch nicht weg
- Wenn du mir eine Stelle an deinem Haus zeigst, wo man RP Konform "auf den Balkon" gelangen könnte ja, ich sehe nur das Garagentor und die Türe wo der Hauseingangsmarker ist, deswegen wird das eher nichts.

**Comment by WunderBaum9** [comment]
Okay, ja gut. Dachte, es würde so gehen. Hab gesehen das paar Häuser das auch so haben. Die Garage als Tür. Aber wenn es nicht geht. Würde ich mich freuen wenn der Einparkpunkt versetzt wird.
