### ISSUE TITLE
Verschieben von Garage

### ISSUE THREAD

**Issue by rodistic** [eiksch/statev_v2_issues#2755]
Hallo StateV Team,

ich wollte mal anfragen ob es möglich ist beim Haushash
house_VinewoodHills_51
die Garage zu verschieben da dieses Haus 2 Einfahrten hat von dem eine der beiden sehr unkomfortable ist.

Derzeitiger Garage Punkt
![Screenshot (1591)](https://user-images.githubusercontent.com/53124324/210990099-aa400e87-6753-47ed-9c69-16378db51aa0.png)

Angefragter Garage Punkt
![Screenshot (160)](https://user-images.githubusercontent.com/53124324/210990077-c13ae715-5c79-438a-aaa3-1f5e1637c550.png)

**Comment by TheOutburst** [comment]
Garage ist zum nächsten Serverupdate an der oberen Einfahrt

**Comment by rodistic** [comment]
Danke!
