### ISSUE TITLE
Motorhaubentuning vom Stirling GT wurde über Nacht zurückgesetzt

### ISSUE THREAD

**Issue by VitoCastellano** [eiksch/statev_v2_issues#2757]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
 Vito Castellano

**Auftrittszeitpunkt (Datum / Uhrzeit)**
 06.01.2023 - ca. 17:30

**Beobachtetes Verhalten**
 Von gestern auf heute wurde das Tuning der Motorhaube wieder "zurückgesetzt." War gestern bei Sludgie Customs (Mechaniker hieß Terry) und dort wurde die Motorhaube und Felgen getauscht, sowie eine Scheibentönung angebracht. Das Tuning der Motorhaube wurde von über Nacht "zurückgesetzt"

**Erwartetes Verhalten**
 -

**Schritte um den Fehler nachvollziehen zu können**
 Tunen -> eine Nacht warten -> Tuning weg

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
 -

**Optional: Video / Bilder des Fehlers**
 Leider kein Bild vom Auto gemacht, lediglich Zeugen vorhanden, falls diese wichtig sind, dann gerne Bescheid geben :)

**Comment by TeubyDE** [comment]
Können wir leider nichts machen, wurde getuned als die IDs noch verschoben waren.

**Comment by VitoCastellano** [comment]
Hi!

War kurz danach nochmal bei Sludgies. Tuning war nicht möglich, da nur noch eine Motorhaube angezeigt wird. Scheibentönung wohl auch nicht mehr die stärkste. Man kann also legit nichts mehr tunen, dementsprechend hier nochmal der push :)

Aussage vom Mechaniker, warte paar Tagen und komm dann nochmal wieder. Heute nochmal probiert. Nichts geht.

Hoffe ihr könnt den Fehler bald beheben, dankeschön!
