### ISSUE TITLE
NVE Bug

### ISSUE THREAD

**Issue by SimonCasitelo** [eiksch/statev_v2_issues#2758]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Simon Casitelo**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

06.01.23     ca. 23:30

**Beobachtetes Verhalten**

Aufgrund von NVE Buggt man durch die Map an gewissen stellen
**Erwartetes Verhalten**

Man sollte eigentlich nicht durch die Map buggen

**Comment by PlayInc89** [comment]
In diesem Sinne ist es kein Server Bug sondern einer von NVE. Das einzige was dir da Hilft NVE runterschmeißen. Dann haste auch keine Probleme.

**Comment by DonVitoDiangelo** [comment]
So ist es, runter mit NVE.

**Comment by 48619** [comment]
@SimonCasitelo bitte einmal mitteilen in welchen Bereichen der Map das passiert ist und welche Settings du in GTA/NVE verwendest.

**Comment by SimonCasitelo** [comment]
Die Probleme befanden sich am Gerichtsgebäude sowie im Umkreis von ca. 500 Metern um das Gebäude herum. Es waren einige verschiedene Positionen wo dies aufgetreten ist. Ich habe die NVE Settings aus dem StateV Forum genutzt.
Sry für die späte Antwort ich war im Urlaub und deswegen erst gestern Quasi das erste mal wieder richtig ic.

MFG

Simon aka Nico

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows

Von: ***@***.***>
Gesendet: Sonntag, 8. Januar 2023 19:13
An: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Betreff: Re: [eiksch/statev_v2_issues] NVE Bug (Issue #2758)


@SimonCasitelo<https://github.com/SimonCasitelo> bitte einmal mitteilen in welchen Bereichen der Map das passiert ist und welche Settings du in GTA/NVE verwendest.
