### ISSUE TITLE
Parkbank Sitzen (Becher) "nur teils" mit Kaffee verwendbar

### ISSUE THREAD

**Issue by Knippsa** [eiksch/statev_v2_issues#2759]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Kalle Knutsen**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Dauerhaft

**Beobachtetes Verhalten**
Man kann sich mit einem Kaffeebecher im Inventar seltsamerweise manchmal nicht auf die gesetzte Parkbank hinsetzen. Nach Einloggen geht es. Sobald man aufsteht funktioniert es darauf hin nicht mehr und im HUD erscheint der Hinweis nach anderen Artikeln.

**Comment by DonVitoDiangelo** [comment]
Liegt an unserem LOS check. Bitte sicher gehen, das nichts zwischen deiner Sicht und der Bank ist. Oder diese z.B. auch nicht so nah an andere Objekte geplaced wurde.
