### ISSUE TITLE
durch paletzieren einer stehlampe in die luft geschleudert geworden 

### ISSUE THREAD

**Issue by DaAlki** [eiksch/statev_v2_issues#2760]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Jack Spooner 

**Auftrittszeitpunkt (Datum / Uhrzeit)**
14:55

**Beobachtetes Verhalten**
durch paletzieren der stehlampe gefühlt 2 km in die luft geschleudert geworden 

**Erwartetes Verhalten**
es sollte das objekt platziert werden und nicht dadurch sterben

**Schritte um den Fehler nachvollziehen zu können**
eine lampe (wegweiser) neben einem stein mit Sträucher zu platzieren! vl liegt es auch am gebäude in harmony??? 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DaAlki** [comment]
ein kollege hatte auch das problem und man sollte nicht zu nah an die gebäude kommen  dann ist man entweder unter der map oder wird in die höhe geschleudert! konnte die ganze map sehen von oben

**Comment by SHaagmann** [comment]
Hast du eventuell nen Video davon? Und welches Gebäude ist gemeint? Gibt ein oder zwei mehr in Harmony

**Comment by DaAlki** [comment]
ne leider hatte da aufnahme nicht an! hätte ich selber gerne als Erinnerung xD und zwar ist das in harmony an der brismatic schmelze passiert habe da rechts vom eingang ein stein v2 ist das glaube ich platziert und wollte du in der ecke beim stein und Haus Mauer eine Wegweiser Lampe platzieren! habe die ganze map von oben gesehen soviel kann ich sagen xD

**Comment by DaAlki** [comment]
drückte zuerst das Objekt an was ich Platzieren wollte und ging dann dort in die ecke! zuerst war ich in der Haus Mauer drinnen und dann wurde ich in die Luft geschleudert!  Ein Kumpel hatt ähnliches bei einem Haus! nur das er in der Map war und nicht hoch geschleudert wurde https://www.youtube.com/watch?v=mpeBfrALLhM

**Comment by simplycach** [comment]
Konnte nicht reproduziert werden, auf nachfrage bei Alki meinte er, er konnte ihn auch nicht erneut durchführen.
