### ISSUE TITLE
Zaun entfernen möglich?

### ISSUE THREAD

**Issue by Patrick-Snooze** [eiksch/statev_v2_issues#2761]
**Character Name**
Patrick Snooze

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Jederzeit

**Anliegen/Frage:**
Könnte man vorne bei meinem Lager "Snooze Bunker" die Zäune entfernen?

**Firmenhash**
FabriklagerhausRancho - Jamestown Street 21

**Screenshot**
https://pic.statev.de/i/9s2F2.th.jpg

gr33tz
Snooze

**Comment by TheOutburst** [comment]
Beide beweglichen Zauntore sind zum nächsten Serverupdate wech

**Comment by Patrick-Snooze** [comment]
Mir fällt gerade ein, würde das selber auch bei der Firma mit dem Hash: TanklagerRancho klappen?
Das Tor reagiert leider nie wenn man ran fährt, man muss es immer erst mit dem Fahrzeug leicht berühren.

**Comment by Patrick-Snooze** [comment]
Meistens mit dem Pounder oder Barracks, aber ich werde es mal testen mit ~40km/h.
Bin vielleicht dann wohl immer nur zu schnell.

Melde mich...

**Comment by Patrick-Snooze** [comment]
> Bei dem Rolltor scheint der Sound zu bleiben, was im RP bisschen strange wäre Mit welchem Auto fährst du denn dran? Ich hab paar LKWs ausprobiert, wenn man da mit ~40km/h anfährt geht das Tor angenehme 5 Meter vor einem auf

Habe das nun eben mal ausprobiert und der Rollzaun geht nicht auf und ich war unter ~40km/h nicht von weiten und nicht mal als ich Direkt da vor stand kannst Dir ja mal das Video anschauen und auf dem Server selber mal testen.

[https://youtu.be/D7lcGV-vSD4](url)

**Comment by TheOutburst** [comment]
Das Video ist ja interessant, wenn ich hier mit nem frischen HVY Barracks Semi mich davor stelle reagiert das Tor viel früher
![grafik](https://user-images.githubusercontent.com/70150675/213258174-b7a260a1-e71d-4026-9749-be6f40ee2e17.png)

Zu den Serverupdates: das waren "nur" Updates um ggf den Crashes entgegenzuwirken, kein "content" Update mit Changelog die sowas hier updaten. Wir differenzieren da, hatte es nicht für nötig gehalten das zu erwähnen.

**Comment by Patrick-Snooze** [comment]
Aso ok kein Problem, aber was können wir bzw. du/ihr da jetzt mit dem Zaun machen... den egalmit welchen Fahrzeug ich vor dem Zaun fahre es öffnet sich nicht erst wenn ich diesen leicht berühre.
