### ISSUE TITLE
Aufstellbare Objekte

### ISSUE THREAD

**Issue by ChapWinchester** [eiksch/statev_v2_issues#2763]
Name:
Clayton_Wells

Fehler:
Jederzeit vorhanden

Beobachtetes Verhalten:
Ich kann nur 9 von 10 Objekten aufstellen. Mit F7 Einstellung zeigt es mir jedoch 10 / 10 an aber die ist nicht korrekt
Da wo ich mal ein Grill aufgestellt hatte ist nach dem aufheben nicht mehr Platzierbar.

Gruß Chap

**Comment by TheOutburst** [comment]
Moin,

Ich verstehe den Satz mit dem Grill nicht ganz, aber wenn du nach einschalten der F7 Funktion auf der Map 10 "Platzierbares Objet" Icons hast, hast du da auch wirklich was platziert. Wenn es einen Ort gibt, wo trotz Serverneustart mit der Einstellung eingeschalten ein Icon, aber kein Objekt auffindbar ist, müsstest du einmal mit dieser Position in den Ts Support gehen / ein Discord Ticket machen, aber das ist so an sich kein genereller Bug für den Bugtracker, weswegen ich hier zu mache.
