### ISSUE TITLE
Fahrzeug kann nicht getuned/umgebaut werden

### ISSUE THREAD

**Issue by Looper-L** [eiksch/statev_v2_issues#2764]
**Character Name**
Gerold Langberg

**Auftrittszeitpunkt (Datum / Uhrzeit)**
10.01.2023 | 22:00 Uhr

**Beobachtetes Verhalten**
Ich wollte die Sitze in meinen Auto ändern bei der Werkstatt, allerdings hat mein Auto anscheinend seit gestern ein Fehler da man davor noch (Den Tag davor) die Scheinwerfer umbauen konnte. Jetzt wird egal, was getuned wird angezeigt das "Xeon Lichter" eingebaut werden und das tritt leider bei jedem Tune mit dem Auto seit gestern auf.

(Xeon Lichter werden zur Rechnung hinzugefügt.)

**Erwartetes Verhalten**
Das die ausgewählten Teile auch verbaut werden und nicht "Xeon Lichter".

**Schritte um den Fehler nachvollziehen zu können**
- Auto ausparken, zur Werkstatt fahren & irgendetwas tunen und Rechnung anzeigen lassen, dort steht das. 
(Kein Anzeige Fehler, wurde getestet, die "Xeon Lichter" werden auch tatsächlich dann verbaut.

Auto: Imponte Duke Custom
Kennzeichen: L4NGB3RG

**Comment by Erumeldor** [comment]
Ich hatte vor einiger Zeit dasselbe Problem.
Jester RR, noch kein Kennzeichen. Beim Tunen vom Kotflügel immer Xenon Scheinwerfer auf der Rechnung und auch im Verbrauch.

Wenn man sie aus dem Lager nimmt wird dann gemeckert das keine im Lager sind.

**Comment by PlayInc89** [comment]
2528
