### ISSUE TITLE
Abladepunkt an die Straße schieben

### ISSUE THREAD

**Issue by epichalt** [eiksch/statev_v2_issues#2765]
Firmenhash
pfJunAbschnitt2Rew_4

https://i.gyazo.com/1cc6ba8be7ba514aac6d5cd2157bedd0.jpg

Aktueller Abladepunkt ist da etwas unglücklich zwischen den beiden Gebäuden. Zusätzlich ist dieser Felsbrocken noch im Weg.
Bitte einfach vors Gebäude setzen

**Comment by TheOutburst** [comment]
Moin,

ist in der Tat etwas unglücklich.
Neuer Punkt ist dann hier wo ich stehe
![grafik](https://user-images.githubusercontent.com/70150675/212482621-55f2920f-78cc-4498-b22d-575f8576959a.png)
