### ISSUE TITLE
Declasse Tulip M-100 lässt sich nicht schieben

### ISSUE THREAD

**Issue by M4c-M4ni4c** [eiksch/statev_v2_issues#2767]
**Character Name**
Ronny Mcleod

**Auftrittszeitpunkt (Datum / Uhrzeit)**
14.01.2023 22:30

**Beobachtetes Verhalten**
Das Fahrzeug "Declasse Tulip M-100" lässt sich nicht schieben

**Erwartetes Verhalten**
Da es ein PKW ist erwartet man eigentlich, dass er geschoben werden kann wie andere PKW's

**Schritte um den Fehler nachvollziehen zu können**
Declasse Tulip M-100 ausparken und versuchen zu schieben

**Optional: Video / Bilder des Fehlers**
![image](https://user-images.githubusercontent.com/52389841/212501487-5bb7b87c-9762-417b-b9ca-38c54cc49196.png)

**Comment by TheOutburst** [comment]
Das ist richtig, Grund ist ein technischer, die "bones" (also die technsiche Grundstruktur) von dem speziellen Fahrzeuges sind sehr komisch, wir müssten da sehr stark eingreifen was wiederum weitere bugs / ungewolltes Verhalten hervorrufen könnte.
Deswegen bleibt das leider so
