### ISSUE TITLE
Simkarten Sortierung bei Antwort auf Dashboard Anzeigen

### ISSUE THREAD

**Issue by eckbert58** [eiksch/statev_v2_issues#2768]
**Character Name**
Hector Cortez

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Jederzeit

**Beobachtetes Verhalten**
Jedes mal wenn ich auf eine Dashboard Anzeige antworten will wird automatisch die älteste Simkarte (die älteste wird immer ganz oben angezeigt) benutzt und hinterlegt, welche in dem fall leider eine Werkstatt Simkarte ist. Das ist natürlich nicht so gut da man jedes mal erst die Simkarte rausnehmen müsste. Gibt es eine Möglichkeit dass zu ändern, das quasi die Haupt-Simkarte bestimmt werden kann?

Grüße!

**Comment by epichalt** [comment]
anderen Sim Karten rausnehmen, sonst gibt es da keine Möglichkeit, Vielleicht ändert sich das durch das neue StateNet evtl :D

**Comment by TeubyDE** [comment]
Kannst du das bitte als Vorschlag ins Forum posten?
