### ISSUE TITLE
Trage des SAMS hat Kollision und zerstört Fahrzeuge und Helikopter

### ISSUE THREAD

**Issue by SvenPhoenix** [eiksch/statev_v2_issues#2769]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Sven Phoenix**

**18.01.2023 21 Uhr**

**Die Krankentrage des SAMS beschädigt mti den Patienten die Fahrzeuge des SAMS und zerstört Regelmäßig den Helikopter**

**Keine Kollision der Trage**

**Mensch auf Trage --> Mensch mit Trage zum Heli oder MRU schieben. Und versuchen Pat. einzuladen**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Reiche ich nach**

**Comment by SvenPhoenix** [comment]
Hier einmal ein kleines Video
https://youtu.be/tuQtGyQNQfU

**Comment by simplycach** [comment]
Ist das noch vermehrt wieder vorgekommen ?

**Comment by SvenPhoenix** [comment]
Ja... gestern erst wieder gesehen. Da wurde ein ganzer Ambu durch die Gegend geschoben

**Comment by simplycach** [comment]
Alles klar, gebe ich so weiter.
