### ISSUE TITLE
Kollision zwischen Trage und Fahrzeug wieder extrem

### ISSUE THREAD

**Issue by Pregon** [eiksch/statev_v2_issues#2772]
**Character Name**
Ronny Roberts

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit mehreren Wochen wieder vermehrt, aber generell schon seitdem ich es schonmal gepostet habe

**Beobachtetes Verhalten**
Trage haut das Fahrzeug kaputt

**Erwartetes Verhalten**
Trage beeinflusst das Auto nicht (hat keine solche Kollision)

**Schritte um den Fehler nachvollziehen zu können**
Trage nehmen und in MRU/AMBU schieben)

**Optional: Video / Bilder des Fehlers**
https://user-images.githubusercontent.com/75855042/213826865-20c2e282-7510-40c9-9d3d-e72063c0a6da.mp4
https://user-images.githubusercontent.com/75855042/213826947-8b5ed7aa-d9a8-45dd-82e6-49a41c10c9f0.mp4

**Comment by SHaagmann** [comment]
Duplikat #2769
