### ISSUE TITLE
Kein Tuning mehr am Cheval Picador vorhanden / Karin Previon Drift Modus ohne Funktion bzw kein Unterschied zum normalen Modus

### ISSUE THREAD

**Issue by kingrobtv** [eiksch/statev_v2_issues#2773]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Brian Diesel**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Cheval Picador hat kein verbautes Tuning mehr. Alles an Tuning ist verschwunden, Fahrzeug sieht aus wie ab Werk.
Karin Previon verändert nicht das Fahrverhalten im Drift Modus.**

**Picador= ausparken und Tuning ist wieder vorhanden.
Previon= Drift Modus aktivieren und Fahrzeug verändert Fahrverhalten (beisp. Beschleunigung/Endgeschwindigkeit usw).**

**Picador ausparken und bestaunen das kein Tuning mehr vorhanden ist.
Previon ausparken, fahren, Modus ändern, fahren und keinen Unterschied merken.**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Ist der Fehler noch aktuell, oder hat sich das Problem bereits behoben durch ein Update von alt:v?

**Comment by kingrobtv** [comment]
Ist noch aktuell. Picador kein Tuning mehr, Previon kein Drift Modus unterschied und beim Benefactor Schwartzer fehlt auch Tuning.

**Comment by kingrobtv** [comment]
Beim Picador sowie Schwartzer ist das Tuning wieder da.
