### ISSUE TITLE
starke Rotation bugs

### ISSUE THREAD

**Issue by FoxXxyLive** [eiksch/statev_v2_issues#2776]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit 2-3 Tagen 

**Beobachtetes Verhalten**
Fahrzeuge an der Zentralmine clitchen ständig hin und her oder rollen nach unten bzw buggen in andere Fahrzeuge (trotz Handbremse)

**Erwartetes Verhalten**
Korrekter Fahrzeugsync

**Schritte um den Fehler nachvollziehen zu können**
Einfach an die Zentralmine schauen bzw Fahrzeuge nebeneinander stellen

![IMG_3524](https://user-images.githubusercontent.com/79162546/213884463-2f63d0ed-69f1-4a52-b7db-aa93787688ce.jpeg)
![IMG_3525](https://user-images.githubusercontent.com/79162546/213884469-0758d956-083f-471b-88cb-496ef2131830.jpeg)

**Comment by simplycach** [comment]
Ist ein Altv Bug, muss auf ein Update seitens AltV gewartet werden.
