### ISSUE TITLE
Ausparken -Fahrzeug auf der seite

### ISSUE THREAD

**Issue by Nordlys12** [eiksch/statev_v2_issues#2778]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name** Abby Anderson

Abby Anderson
**Auftrittszeitpunkt (Datum / Uhrzeit)**

ca.9.25
**Beobachtetes Verhalten**
Mule sollte ausgeparkt werden , wurde ausgeparkt , aber seitlich 

**Erwartetes Verhalten**

richtiges ausparken des  Fahrzeug 
**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
 
[Bild](https://pic.statev.de/image/90BGA)

**Comment by DonVitoDiangelo** [comment]
Kann nicht reproduziert werden. Kann aber in ganz seltenen Fällen mal passieren. Ist dann im RP auszuspielen.
