### ISSUE TITLE
Anfrage auf feste Gegenstandplatzierung für das Tequi-La-La

### ISSUE THREAD

**Issue by SauerkirscheJM** [eiksch/statev_v2_issues#2780]
Azula Rise
10.01.2023

Tequi-La-La Aufbau

Wir wollten vom Tequi-La-La fragen ob es möglich wäre unsenren Aufbau vor der Bar fest auf dem Server zu verankern.
Aktuell könnn wir grade so alles aufbauen aber dann auch nciht mehr für Partys oder in der Bar selbst dekorieren.

Ich kann verstehen, wen ndas nicht möglich wäre, wollte nur einmal nachfragen. Anbei die Bilder von unserem Aufbau.

8 Absperrgitter
4 Glaswände
1 Parkbank
1 Fass
1 blauer Strahler
1 roter Strahler
1 Aschenbecher Outdoor
1 Bartresen
1 Wegleuter Warm

Bei Fragen gerne bescheid geben.

Vielen Dank,
viele Grüße

Azula Rise

![GTA5 2023-01-23 18-59-29](https://user-images.githubusercontent.com/123385988/214115606-a9e23619-0d11-497e-bd3a-cc0e2dfc8488.png)
![GTA5 2023-01-23 18-58-51](https://user-images.githubusercontent.com/123385988/214115560-9fc69eb4-c342-4b1e-b973-7be4250df678.png)
![GTA5 2023-01-23 16-53-18](https://user-images.githubusercontent.com/123385988/214115535-2e66c26e-48e8-4b4f-8120-fa3e4c5615e8.png)
![GTA5 2023-01-23 18-59-11](https://user-images.githubusercontent.com/123385988/214115570-2c401560-2f51-4fc5-888b-5ac4772f6587.png)
![GTA5 2023-01-23 18-59-23](https://user-images.githubusercontent.com/123385988/214115591-f6539ad7-866c-4489-b482-192e6a4e00ef.png)
![GTA5 2023-01-23 19-00-40](https://user-images.githubusercontent.com/123385988/214115501-779c0794-cab5-4e9c-ba7b-795b2b758c54.png)
![GTA5 2023-01-23 16-51-35](https://user-images.githubusercontent.com/123385988/214115506-f1a532b9-9e52-4c0c-9f1f-1ab48085537b.png)

**Comment by DonVitoDiangelo** [comment]
Leuchten und Glaswände würden wir der Umgebung so nicht antun wollen. Da müsstet Ihr dann weiterhin eure Slots für "opfern".
Absperrgitter, Bank und Aschenbecher wären aber fine.

**Comment by SauerkirscheJM** [comment]
Besser als nichts! Danke <3
