### ISSUE TITLE
Daueraufträge

### ISSUE THREAD

**Issue by ingo-lorenz** [eiksch/statev_v2_issues#2781]
Hallo liebes Entwicklungsteam,

es wäre wirklich gut und sehr hilreich, wenn man Daueraufträge erstellen könnte. Diese könnte man, damit es nicht zu komplex wird,  auf die Wochentage beschränken.

So könnte ich mir das vorstellen:

Betreff: **XYZ**
Quellkonto: **456 456**
Zielkonto: **123 123**
Betrag: **9999999 $**
Mehrfachauswahl der Tage zur Ausführung: **MO, DI, MI, DO, FR, SA, SO**
Ende der Ausführung; **DATUM**

Das würde sicherlich auch bei vielen anderen Mitspielern gut ankommen. So kann man Pachtbeträge und Kredite besser pünklich bezahlen. Wenn das Konto nicht gedeckt ist, schlägt der Auftrag fehl und wird deaktiert.

Danke und Grüße
Ingo Lorenz

**Comment by SHaagmann** [comment]
Vorschläge bitte ins Forum. Hier bitte nur Bugs melden 👍
