### ISSUE TITLE
NOS-Flaschen Nutzung bei Schlagen GT und Verlierer nicht möglich

### ISSUE THREAD

**Issue by SatyriaDine** [eiksch/statev_v2_issues#2782]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Sofia_Black

**Auftrittszeitpunkt (Datum / Uhrzeit)**
seit Einführung von NOS bis jetzt 

**Beobachtetes Verhalten**
in den Fahrzeugen Benefactor Schlagen GT sowie Bravado Verlierer ist die Nutzung von NOS nicht möglich

**Erwartetes Verhalten**
Dass NOS nutzbar ist

**Schritte um den Fehler nachvollziehen zu können**
Autos spawnen und versuchen eine NOS-Flasche einzubauen

**Optional: Video / Bilder des Fehlers**

![Screenshot_341](https://user-images.githubusercontent.com/84275938/215064623-04c0b9bf-c1be-45cd-83f9-0903def9a7f0.jpg)
![Screenshot_342](https://user-images.githubusercontent.com/84275938/215064699-3343788e-5a24-4858-8b36-d91bf4195ed8.jpg)

**Comment by DonVitoDiangelo** [comment]
NOS ist bis dato nur für die speziellen Tuner Cars vorbehalten, daher besitzen diese Fahrzeuge auch keine NOS Option.
Eventuell lassen wir uns hier zukünftig ein Feature einfallen, für die Einrichtung einer entsprechenden "Vorbereitung für NOS".
Aber wenn, dann werdet ihr es über den Changelog erfahren.
