### ISSUE TITLE
Drafter / Vamos legt sich auf die Seite

### ISSUE THREAD

**Issue by powerswissi** [eiksch/statev_v2_issues#2784]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Alex Faith (im auftrag)

Roger Thickle

**Auftrittszeitpunkt (Datum / Uhrzeit)**

28.1.2023 Irgendwann am Abend

**Beobachtetes Verhalten**

Drafter legt sich auf die Seite mit Typ 1 Tieferlegung 

Das gleiche geschieht auch mit dem Vamos und der typ 2 tieferlegung

Nachdem das Auto wieder auf Normal gestellt ist passierte nichts mehr

**Erwartetes Verhalten**

Das man das Auto tieferlegen kann Ohne das es Umkippt!

**Schritte um den Fehler nachvollziehen zu können**

Drafter / vamos spawnen, tieferlegen und zackig ums eck fahren 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://clips.twitch.tv/SpineyLivelyCurlewFreakinStinkin-XsQGFb7N3h5qZPM5

https://clips.twitch.tv/HungryBusyMangetoutPhilosoraptor-FQDZyGglwPvnuu6J

**Comment by TeubyDE** [comment]
Ich gehe hier von aus das wir hier nichts dran ändern könne ohne das komplette balancing zu erneuern. Einfach nicht die tiefste Variante verwenden.
