### ISSUE TITLE
Abladepunkt verschieben

### ISSUE THREAD

**Issue by FoxXxyLive** [eiksch/statev_v2_issues#2785]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Samy Nustrajev

**Beobachtetes Verhalten**
Abladepunkt zu nah an der Firma, Be und Entladen mit Achse und Pounder kaum/gar nicht möglich 

**Erwartetes Verhalten**
Abladepunkt so verschieben, dass man leichter Be und Entladen kann auch mit größeren Fahrzeugen

**Schritte um den Fehler nachvollziehen zu können**
an die Firma schauen 

Firmenhash: pfEveMorningwoodRew_17

Abladenpunkt derzeit: 
![Screenshot_60](https://user-images.githubusercontent.com/79162546/215283577-4051a832-6150-4e1f-8e9e-afffb567a367.png)

Abladepunkt gewünscht: (Irgendwo da auf dem Parkplatz, damit es für die Achse leichter ist)
![Screenshot_61](https://user-images.githubusercontent.com/79162546/215283595-11dc9277-b28b-4dad-a83a-fa72e3fd0390.png)
t: 
oder an der Straße: 
![Screenshot_62](https://user-images.githubusercontent.com/79162546/215283640-25721a00-b43a-4877-bddd-3c01f59bfc42.png)

Danke :)

**Comment by FoxXxyLive** [comment]
Hey, ich wollte mal nachfragen, wann wir mit der Änderung des Abladepunkts rechnen können?

**Comment by TheOutburst** [comment]
Der Abladepunkt wird zum nächsten Update 3 Meter weg vom gelben Bordstein geschoben, das sollte auch für Achsen reichen.

So wie alle hier noch offenen aber mit "solved" markierten Änderungen kommt auch diese zum nächsten Update
