### ISSUE TITLE
Sirene Polizeifahrzeuge fehlerhaft

### ISSUE THREAD

**Issue by PresLincoln** [eiksch/statev_v2_issues#2786]
**David_Lincoln**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Unterschiedlich, ab und zu. Um den Fehler zu beheben muss man kurz neu ein- und aussteigen. Kein Muster erkennbar

**Beobachtetes Verhalten**
Wenn man in (irgendeinem) Police Fahrzeug sitzt und die Sirene+Beleuchtung anschalten möchte, kommt es häufiger vor, dass das Fahrzeug nur hupt und die Sirene/Beleuchtung sich nicht anschaltet. Wenn das der Fall ist muss man "E" gedrückt halten um die Sirene und Beleuchtung anzuschalten, dies gilt auch für das Abschalten. Wenn man E kurz drückt, wie es eigentlich sein sollte, hupt der Wagen lediglich.

**Erwartetes Verhalten**
Kurzes E drücken und zack, Sirene und Beleuchtung sollten eingeschaltet sein

**Schritte um den Fehler nachvollziehen zu können**
In irgendein Police Fahrzeug eingsteigen und E drücken, bis es irgendwann mal nicht funktioniert und die Hupe anspringt

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by simplycach** [comment]
Konnte bisher nicht reproduziert werden, wenn es dir nochmal auffällt bitte ein Video machen.

**Comment by DonVitoDiangelo** [comment]
Wird nicht weiter verfolgt. Manchmal ist nen Schalter halt etwas störrig.
