### ISSUE TITLE
Buffalo Fahrerscheibe flackert 

### ISSUE THREAD

**Issue by PresLincoln** [eiksch/statev_v2_issues#2787]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**David_Lincoln*

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Seit dem Einfügen der neuen PD Buffalos

**Beobachtetes Verhalten**

Seitenscheibe auf der Fahrerseite flackert in der First Person.

**Erwartetes Verhalten**

Scheibe sollte nicht flackern,

**Schritte um den Fehler nachvollziehen zu können**

Einsteigen, First Person gehen und auf dem Fahrersitz nach links rausschauen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by TeubyDE** [comment]
@TheOutburst @DonVitoDiangelo vermutlich nur am mod selbst zu fixen.

**Comment by DonVitoDiangelo** [comment]
Ein Umstand mit dem wir wohl leben müssen, da wir keine Fahrzeugmodelle editieren.
