### ISSUE TITLE
Entity MT Tuning

### ISSUE THREAD

**Issue by Koray5858** [eiksch/statev_v2_issues#2788]
Das Tuning vom Entity MT ist fehlerhaft bei gefühlt der hälfte vom verfügbaren Tuning ist hinterm Fahrzeug nur ein weißes Quadrat (Siehe Bild)
Es würde mich auch freuen wenn man bei diesem Fahrzeug nochmal die Beschleunigung und Endgeschwindigkeit testet, da es meiner Meinung nach nicht zum Preis passt.
![Unbenannt123124444](https://user-images.githubusercontent.com/75127724/215443071-23f5253b-ef14-4a00-bc57-b7ead4c98c72.PNG)

**Comment by SHaagmann** [comment]
Die tuning optionen sind einfach noch nicht in GTA verfügbar. Sobald dies der Fall ist sollten diese auch normal auf dem Server verfügbar sein.
