### ISSUE TITLE
Musiklautstärke vor Clubs

### ISSUE THREAD

**Issue by LeaBrandt** [eiksch/statev_v2_issues#2789]
Schon seit längerer Zeit können DJ's in Clubs Musik über den Club quasi abspielen. Ich kenne mich mit der Spielmechanik nicht aus, aber ich glaube das hat mit virtuellen Wänden usw. zu tun. Das ist eine super Idee...Leider funtioniert es seit dem nicht mehr, dass ich den DJ in Teamspeak suche und seine Lautstärke verringere. Sobald man vor der Tür eines Clubs steht bleibt mir also nur die Lautstärke insgesamt runter zu stellen und alle anderen lauter zu machen. Das ist allerdings sehr schwierig, wenn ständig neue Leute hinzukommen. 
Als regelmäßige Clubgängerin ist es mir auch schon vermehrt aufgefallen, dass keine Gespräche mehr vorm Club möglich sind, weil die Leute sich untereinander nicht verstehen. 
Speziell im Tequi-La-La hört man den DJ in der oberen Etage, wenn man am Geländer steht "normal" und wenn man weiter hinten steht Richtung zweiter Bar in der oberen Etage ist es wie draußen (ohne Möglichkeit den DJ leiser zu stellen)...
Mein Vorschlag wäre: Entweder wenn möglich die "draußen"-Lautstärke deutlich zu reduzieren oder dass die eigene Einstellung der Lautstärke des DJ aus Teamspeak greift....
P.s.: Beim rein und raus laufen ist es auch etwas nervig, dass ich den DJ bei jedem rein kommen wieder neu runterregeln muss, aber daran gewöhnt man sich ja irgendwann...

P.p.s.: Danke an das ganze Team und eure Arbeit...Mega!

**Comment by TeubyDE** [comment]
Kein bug. Vorschläge bitte ins Forum. Mach dir da aber bitte keine großen Hoffnungen.
