### ISSUE TITLE
Nich alle Tassen auf dem Markt.

### ISSUE THREAD

**Issue by StateV2Marie** [eiksch/statev_v2_issues#2792]
Hallöchen es geht um die Weißen Tassen die kann man leider nicht auf den markt zum verkauf stellen wäre lieb wenn ihr das ändern könntet.

mfg: Dat Mariechen

**Comment by TheOutburst** [comment]
Du redest von der "Tasse", die man hinstellen kann?
Solche Items gehen nicht über den Marktplatz da sie über einen 24/7 gekauft werden sollen und für den restlichen Markt nicht relevant sind
