### ISSUE TITLE
Tuning Bug?

### ISSUE THREAD

**Issue by xMucki86x** [eiksch/statev_v2_issues#2793]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Isaac_Dawson

**Auftrittszeitpunkt (Datum / Uhrzeit)**
07.02.23 / ca 20:50

**Beobachtetes Verhalten**
Nachdem ich bei meinem Jester Classic Xenon in ICE Green einbauen lassen habe ist mein komplettes Tuning fast zurück gesetzt auf Serie bzw falsch.

**Erwartetes Verhalten**
Das mein Tuning was ich bis jetzt alles gekauft und verbaut habe, alles wieder dran ist oder ich Geld bekomme damit ich alles neu anbauen kann. 

**Schritte um den Fehler nachvollziehen zu können**
beim Tuning von Xenon ist es passiert.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
So soll er wieder sein wie auf dem Foto:
Es gibt auch nen VOD dazu auf meinem Twitch Kanal! 
https://www.twitch.tv/videos/1731241170
In dem Stream ist quch alles zu sehen. Vor dem Tuning und nach dem Tuning. Denn habe ich ihn noch eingepackt und wieder aus geparkt und denn war alles weg...
![20230207212940_1](https://user-images.githubusercontent.com/124738214/217373601-f791eac1-4d0f-4ee2-84ce-4285d899c267.jpg)

**Comment by simplycach** [comment]
Den Tuning Bug konnte ich jetzt nicht nachvollziehen bzw. reproduzieren.
