### ISSUE TITLE
Fehler bei der fahrzeugrückgabe 

### ISSUE THREAD

**Issue by robert0509** [eiksch/statev_v2_issues#2794]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Robert_Duck

Robert_Duck
**Auftrittszeitpunkt (Datum / Uhrzeit)**

11.2.2023 22:25
**Beobachtetes Verhalten**

wollte mein öl tanker den ich damals geliehen habe zurück geben da stand dann er ist zu stark beschädigt ( keine motorkontrollleuchte) macht 500$ strafe und die kosten für die km haben die kosten für die km bezahlt und dann habe ich den wagen repariert und wollte ihn abgeben und dann sollte ich die kosten nochmal bezahlen obwohl sie schon abgezogen worden 
**Erwartetes Verhalten**

kosten nur einmal abziehen 
**Schritte um den Fehler nachvollziehen zu können**

fahrzeug abgeben mit den bargeld dann in der werkstatt reparieren und dann nochmal zurück geben 
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

fahrzeug abgeben mit den bargeld dann in der werkstatt reparieren und dann nochmal zurück geben 
**Optional: Video / Bilder des Fehlers**

hab leider keins

**Comment by simplycach** [comment]
Ist ein bekannter Bug, einmal bitte genügend Geld mitnehmen für Reparatur und KM-Pauschale, dann kannst du es abgeben und wenn du der Meinung bist, dass du es Erstattet haben möchtest bitte im Support melden.

**Comment by robert0509** [comment]
ok danke für die info mich hat das nur gewundert weil mir nicht angezeigt wurde das er einen schaden hat weil keine leuchte an war     Am Samstag, 11. Februar 2023 um 22:49:37 MEZ hat simplycach ***@***.***> Folgendes geschrieben:  
 
 


Ist ein bekannter Bug, einmal bitte genügend Geld mitnehmen für Reparatur und KM-Pauschale, dann kannst du es abgeben und wenn du der Meinung bist, dass du es Erstattet haben möchtest bitte im Support melden.

**Comment by simplycach** [comment]
Wir nehmen uns der Sache an, es wird Zeitnah nach einer Lösung gesucht.
