### ISSUE TITLE
Behälter mit Kerosin fehlt im Marktplatz

### ISSUE THREAD

**Issue by SimonPfeifferStateV** [eiksch/statev_v2_issues#2795]
Character Name: Simon Pfeiffer

Auftrittszeitpunkt (Datum / Uhrzeit): dauerhaft

Beobachtetes Verhalten: Behälter mit Kerosin kann man nicht am Marktplatz kaufen/verkaufen, obwohl es im Labor hergestellt werden kann

Erwartetes Verhalten: Möglichkeit von An- und Verkauf von Behälter mit Kerosin 

Schritte um den Fehler nachvollziehen zu können: Zum Marktplatz gehen und danach suchen

**Comment by TheOutburst** [comment]
Das ist richitg, das kann zwar im Labor hergestellt werden, ist aber nicht für den Firmenkreislauf benötigt und um das zu bekommen soll rp gespielt werden. Dementsprechend ist das gewollt und das Item wird es nicht im Marktplatz geben.
