### ISSUE TITLE
Motor-/ Turbotuning bei Issi Rally? / Spoilertuning fehlerhaft

### ISSUE THREAD

**Issue by Michi993** [eiksch/statev_v2_issues#2796]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Luke Hammer

**Auftrittszeitpunkt (Datum / Uhrzeit)**
19.02.2023

**Beobachtetes Verhalten**
Turbo Tuning und Motortuning im Tuningmenü einbaubar. Bei Spoilertuning baut man eine Weiße fläche ausserhalb vom Fahrzeug an

**Erwartetes Verhalten**
Dies sollte nicht verbaut werden können 

**Schritte um den Fehler nachvollziehen zu können**
Ins Tuningmenü schauen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)*

**Optional: Video / Bilder des Fehlers**

![GTA5 2023-02-19 19-32-23](https://user-images.githubusercontent.com/75136157/219967995-0a294dcb-0576-4be8-9a25-15423ffc2a6b.png)
![GTA5 2023-02-19 19-30-51](https://user-images.githubusercontent.com/75136157/219968003-4e0374ef-dc0b-407a-bd1e-51063d77ee9b.png)

**Comment by TheOutburst** [comment]
Die Weiße Fläche kommt davon, dass das Auto aus dem letzten GTA DLC ist und das Tuning in GTA Online noch nicht freigeschalten wurde. Einfach nicht tunen, nicht anspielen, irgendwann wird das von R* aus verfügbar sein

Das man Leistungsverbesserung & Turbo tunen kann ist nicht gewollt, ist next update fixed
