### ISSUE TITLE
Antrag auf Verlegung/Zusammenführung von Be-/Entladepunkt

### ISSUE THREAD

**Issue by hollyfizzu** [eiksch/statev_v2_issues#2797]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Charname: Jacques_Colombo
Firmenhash: pfJunAltaRew_9

Hallo Zusammen,
Der Be-/Entladepunkt unseres Labors befindet sich direkt auf den Parkplätzen des Friseurs, der relativ viel besucht ist, was ja auch toll ist. Der Nachteil ist, dass unser Be-/Entladepunkt immer öfters besetzt/blockiert ist. Auch nach mehreren Versuchen das IC zu klären ist es nahezu unmöglich, weil halt auch immer wieder Leute da parkieren, die nichts davon wissen. Da relativ viel Umlagerung passiert am Labor würde ich es sehr begrüssen den Punkt zu verlegen.

Ich sehe 2 Möglichkeiten:
Den Ladepunkt entweder genügend weit auf die Strasse ziehen, damit der Parkplatz besetzt sein kann und wir den trotzdem nutzen können (auch mit einer Achse) oder den Ladepunkt mit dem anderen kombinieren (siehe Bild) oder zumindest weiter weg auf die Sperrfläche ziehen.

Vielen Dank

![Screenshot 2023-02-20 103134](https://user-images.githubusercontent.com/98158374/220067040-9b2be4a3-025b-4bac-842f-b3950283a956.png)

**Comment by TheOutburst** [comment]
Hab mal den Parkplatz frei gemacht und auf den Platz wo schon die 2 Firmen rechts von euch den Punkt haben verlegt.
Den Punkt auf die Straße zu legen würde zu echt vielen Chartoden durch Autounfällen führen :D

**Comment by hollyfizzu** [comment]
Perfekt, thx
