### ISSUE TITLE
Instandsetzung (Beantragung) Garage Westmirror Drive

### ISSUE THREAD

**Issue by shoxmox** [eiksch/statev_v2_issues#2798]
Dear Mrs. or Mr.,

ich wende mich schriftlich an Sie um die Beantragung der Instandsetzung des maroden Carports am Objekt Westmirror Drive 27, Mirror Park (house_Vinewood_27) 

bei Ihnen zu beantragen.
Dass der Carport bei Abrissarbeiten des nebenstehenden Gebäudes in Mitleidenschaft gezogen wurde wird durch das angehängte Gutachten der Firma "Miller & Carter" bestätigt.

Ich würde Sie entsprechend um eine Stellungnahme bitten. In der Zwischenzeit werde ich eine ausführende Firma mit den nötigen Abstützarbeiten suchen und mit dem Wiederaufbau des Carports beauftragen, sobald Sie ihre Genehmigung erteilt haben.

mit freundlichen Grüßen
Antonio Knauff

Anhang:
[Baugutachten.pdf](https://github.com/eiksch/statev_v2_issues/files/10786954/Baugutachten.pdf)

**Comment by shoxmox** [comment]
_(Ich würde mich auch riesig freuen wenn das "For Sale" Schild am Straßenrand verschwinden würde, weil es ja genau genommen nicht mehr im Verkauf ist ;) )
Is that possible?_

**Comment by TheOutburst** [comment]
Bevor ich jetzt wieder Wochenlang IC Anträge bekomme:

- Garage Hinzugefügt
- For Sale Schild entfernt
