### ISSUE TITLE
Falsche Frisur

### ISSUE THREAD

**Issue by Marlisediefiese** [eiksch/statev_v2_issues#2801]
Amara_Petrov

**Auftrittszeitpunkt (Datum / Uhrzeit)**
24.02.2023 nach dem Update

**Beobachtetes Verhalten**
Mein Char hat eine andere Frisur als davor. War jedoch nicht beim Friseur 

**Erwartetes Verhalten**
selbe Frisur wie vor dem Update zu haben 

**Optional: Video / Bilder des Fehlers**
Frisur nach dem Update: https://pic.statev.de/image/20230224200458-1.csZ8i

Frisur vor dem Update: https://pic.statev.de/image/0000000000000000000000000000001.cstY6

**Comment by TheOutburst** [comment]
Ja, das ist leider so, aber gefixt bekommen wir das auch nichtmehr ohne an anderer Stelle Schaden anzurichten, bitte einfach IC zum Friseur gehen
