### ISSUE TITLE
Sprachradius verbuggt

### ISSUE THREAD

**Issue by ShoxqZ1312** [eiksch/statev_v2_issues#2802]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**Ace Kings
Ace Kings 

**Auftrittszeitpunkt (Datum / Uhrzeit)**
24.02.2023

**Beobachtetes Verhalten**
Wenn man einem gegenüber sitzt (Lucky Plucker), hört man denjenigen nicht bei dem kleinsten Radius, obwohl im Teamspeak das Lämpchen aufleuchtet. 

**Erwartetes Verhalten**
 Man sollte den im besten Falle hören

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
 https://prnt.sc/L0xpmptrwKUJ

**Comment by TheOutburst** [comment]
Die Tische sind leider recht groß und die Bänke im Vergleich zu anderen Restaurants weit weg von den Tischen - daran können wir im ersten Moment nicht viel ändern
Auch die kleinste Voicerange werden wir nur für das Restaurant nicht anpassen.
Ich habe die Sitzposition zum nächsten Update aber näher an den Tisch gepackt ohne dass es zu ungewollten Nebenwirkungen kommt, damit kann man sich hören, wenn auch recht leise. Zum jetztigen Zeitpunkt die einizge Lösung, wenn auch noch immer nicht perfekt.
