### ISSUE TITLE
Abschlepp Bug

### ISSUE THREAD

**Issue by Cro20** [eiksch/statev_v2_issues#2804]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Ante_Sovic**

**Auftrittszeitpunkt (25.02.2023 / ca. 20:00 Uhr)**

**Fahrzeug wurde abschleppt und mein Char ist rumgebuggt**

**Fahrzeug abschleppen und normal mitziehen**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**https://youtu.be/YZOM7I-xjC0**

**Comment by simplycach** [comment]
Bitte einmal richtig ausfüllen ;)

**Comment by simplycach** [comment]
Welches Fahrzeug wurde abgeschleppt, bitte wenn du hast den genauen Namen.

**Comment by Cro20** [comment]
BCSO 404

**Comment by simplycach** [comment]
Sollte fixed sein, wenn nicht bitte nochmal einen Kommentar drunter schreiben.
