### ISSUE TITLE
Beim Joint drehen, wird der Tabak nicht weniger/verbraucht.

### ISSUE THREAD

**Issue by Chiko-Garcia** [eiksch/statev_v2_issues#2807]
Beim Joint drehen, wird der Tabak nicht weniger/verbraucht.

**Comment by simplycach** [comment]
Hast du eventuell ein Video davon ?

**Comment by Chiko-Garcia** [comment]
ich muss es dann noch mal machen und mach ein video dazu

**Comment by Chiko-Garcia** [comment]
Ok, hab gerade noch mal Probiert, tut mir leid, aber war von mir ein Denkfehler, wegen neuer Rezeptur

**Comment by simplycach** [comment]
Okey alles klar, wir hatten das eben auch gegen getestet.
