### ISSUE TITLE
Antrag feste Installation "Skaterail" vor Firma

### ISSUE THREAD

**Issue by CaleighRhodes** [eiksch/statev_v2_issues#2809]
**Character Name**
Caleigh Rhodes / Weberei Fuchsbau 🦊 / Firmenhash: pfEveMorningwoodRew_26

**Antragsinhalt**
Ich bitte hier um die feste Installation eines Skaterails als Absperrgitter vor meiner Firma (siehe Bilder, gerne kann es auch ein oder mehrere andere Items sein, Hauptsache, die Fläche zwischen Vorfahrtsschild und Baum ist abgesperrt). Grund ist, dass es leider immer noch Spieler gibt, die - statt in den dafür vorgesehenen Parkbuchten zu parken - über den Bürgersteig fahren, um den 24/7 neben meiner Firma zu erreichen. Unabhängig davon, dass ich das irgendwo als FailRP bewerte, stellt es auch eine Gefahr für mich dar, wenn ich meine Firma verlasse. Es ist nicht nur ein Mal passiert, dass Personen mich fast umgefahren haben. 

Ich habe es jedoch erstmal im Rp versucht zu lösen. Dazu gab es vor fast einem Jahr (28.2.22) eine Vor-Ort-Begehung mit Captain Errol Armstrong als Vertreter des SAPD und Richter Maxwell Ricks als Vertreter des SAMJ, bei der mir die Erlaubnis erteilt wurde, dort am Bordstein ein Gitter aufbauen zu lassen. Ich habe daraufhin die Firma des Spielers Greg Parker (SecuroServ) beauftragt, ein Angebot für die feste Installation des Gitters zu erstellen. Dieses Angebot kam, wurde von mir angenommen, bezahlt, Greg Parker bespielte das, sperrte die Stelle ab, goss Beton, bat mich, ein paar Tage nicht daran zu rütteln usw. - jetzt hat Greg den Server verlassen und mit ihm leider auch mein Schutzgeländer. :-( Eine andere Baufirma wird derzeit auf dem Server nicht bespielt.

Daher wäre meine Bitte, dass das Gitter fest installiert wird.

Hier die Rechnung und der Überweisungsträger:

https://drive.google.com/file/d/1__XHy7wBygwIFYWeKHyX8RAikg-1HyGE/view?usp=sharing

![rg securo](https://user-images.githubusercontent.com/74977218/221419109-38273d59-affd-412c-820a-96a4eb1b2a97.PNG)

Und hier die Situation vor Ort und der gewünschte Standpunkt des Rails:

![weg](https://user-images.githubusercontent.com/74977218/221419853-81bd94c6-db1f-4d3e-8a69-44644003ce1a.jpg)

![20221012130038_1](https://user-images.githubusercontent.com/74977218/221419429-a1444c98-6159-4b6b-aa9d-d2d50a669861.jpg)

Ich würde mich freuen und danke im Voraus für die Aufmerksamkeit.

**Comment by TheOutburst** [comment]
Spricht nichts dagegen was ingame hin zu stellen, aber wir mappen an Firmen nichts
