### ISSUE TITLE
Tulip nicht schiebbar

### ISSUE THREAD

**Issue by DrGrizzlY17** [eiksch/statev_v2_issues#2813]
**Character Name**
Trey_Jackson

**Beobachtetes Verhalten**
Man kann den Tulip nicht schieben übers XMenü
Die Option fehlt

**Erwartetes Verhalten**
Sollte man schieben können

**Schritte um den Fehler nachvollziehen zu können**
X Menü am Tulip

**Optional: Video / Bilder des Fehlers**
![image](https://user-images.githubusercontent.com/70150988/221828648-43b5d2b4-3575-466b-bafc-6700cd3125b7.png)

**Comment by SatyriaDine** [comment]
Da gab es schonmal ein Issue zu: #2767

Kann wohl leider nicht so einfach geändert werden ohne dass andere Probleme auftauchen
