### ISSUE TITLE
Kunden im Drive in werden nicht gehört. 

### ISSUE THREAD

**Issue by Smaty86** [eiksch/statev_v2_issues#2814]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```
Bei dem Restaurant WING STOP, restaurant_LS_wings, kann man nicht am Drive In Bestellen da man die Personen nicht hört. Nur wenn die Person schreit kann man Sie verstehen. Allerdings muss der Kellner dann zurück schreien aber dann wird er vom ganzen Restaurant gehört. 

kann das gefixt werden? 

**Character Name**

Tim_Rock
**Auftrittszeitpunkt (Datum / Uhrzeit)**

immer
**Beobachtetes Verhalten**

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by simplycach** [comment]
Ist uns bereits bekannt ;)

**Comment by TheOutburst** [comment]
Kurze Hintergrundinfo: es war bisher nicht vorgesehen, dass man aus einem Interieur heraus durch eine Öffnung die keine Türe ist hindurchreden kann.
Jetzt durch 2 Restaurants mit Drive in ist diese Funktion das erste mal benötigt, wird aber einige Zeit in Anspruch nehmen.
Ich will hier jetzt kein Prosponed / low prio Tag dran machen, aber rechnet mal nicht damit, dass das in der näheren Zukunft passiert.

**Comment by DonVitoDiangelo** [comment]
Das ist kein Feature welches wir aktuell nicht weiter verfolgen. Vllt. irgendwann, aber eher nein, daher closed.
