### ISSUE TITLE
Antrag auf Garagenpunkt unter Carport - SandyShores48

### ISSUE THREAD

**Issue by Bene-RonnyMoritz** [eiksch/statev_v2_issues#2815]
**Ronny_Moritz**

Grüße Grüße,

wollte mal nachfragen ob es möglich wäre, am Haus in Sandy Shores eine kleine Hausgarage hinzuzufügen. Das Grundstück selbst hat keine richtige Garage sondern nur ein Carport/Unterstand. Aber selbst im MirrorPark gibt es Grundstücke ohne optische Garage die einen Garagenpunkt haben.

Es geht dabei um das Haus "SandyShores48"
![GTA5 2023-03-01 18-47-22](https://user-images.githubusercontent.com/78343649/222221854-cabef9ca-82ff-4787-96a2-3ef4e394430b.png)
![GTA5 2023-03-01 18-47-39](https://user-images.githubusercontent.com/78343649/222221860-c89594e0-8a61-44cf-8f94-990ddc52e4dc.png)

**Comment by TheOutburst** [comment]
kommt next update rein

**Comment by Bene-RonnyMoritz** [comment]
ich danke dir <3
