### ISSUE TITLE
Tuningfehler Xenon werden immer verbaut

### ISSUE THREAD

**Issue by Erumeldor** [eiksch/statev_v2_issues#2817]
**Character Name**
Satoru_Tsuyoshi

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer, seit einigen Wochen / Monaten

**Beobachtetes Verhalten**
Beim Tuning vom meinem JesterRR wird bei allen Tunings die ich gerade ausprobiert habe immer Xenon-Scheinwerfer mitverbaut.
Das ist nur bei meinem JesterRR gerade der Fall. Hab davon aber IC schon vor Monaten gehört das so ein Bug existiert.
Es bringt auch nichts die Xenon aus dem Lager zu nehmen, dann meckert er das die benötigt werden.
Man sieht das als Mitarbeiter übrigens nicht. In der Liste unten stehen die Xenon nicht drin. Beim Kunden dann aber auf der kleinen Rechnung schon.
Fahrzeug ist unangemeldet, aber ich hab nur einen JesterRR ;)

**Erwartetes Verhalten**
Einfach kein Xenon abziehen.

**Schritte um den Fehler nachvollziehen zu können**
Meinen Jester nehmen, in die Werkstatt, und beispielsweise Auspuff oder Kotflügel tunen.

**Comment by PlayInc89** [comment]
Schreib mal bitte dein Kennzeichen hier rein.

**Comment by Erumeldor** [comment]
Wir haben es gelöst! Sollte mich fürs Test-Team bewerben ;)

Das System will tunnen, wenn die Xenon-Farbe eine andere ist wie vorher. Auch wenn gar keine Xenons verbaut sind.
Heißt: Xenon mal angeschaut, aber dann wieder auf Serie zurück, Farbe aber drin gelassen -> Jedes Tuning kostet 2 Xenon-Scheinwerfer. Lustigerweise aber immer erst nach dem 2. mal.
Man muss danach wieder auf die richtige Farbe umstellen, um ohne Xenon tunen zu dürfen.

Ich hab das ganze im Video aufgenommen.
Ich muss wohl irgendwann schonmal die Farbe geändert haben und da dann tatsächlich auch die Xenonscheinwerfer verbraucht haben (RIP), deshalb kann ich nicht auf Farbe- Serie sondern muss auf Farbe Ice Blue um "kostenlos" tunen zu können.
Hier das Video:
https://youtu.be/GaZ0MeuQkzA

PS: Kennzeichen wie gesagt keins dran.

**Comment by simplycach** [comment]
Vielen Dank, für die Hilfe.

**Comment by Erumeldor** [comment]
Gibt es hier irgendwie mal eine Chance das es gefixt wird?
Der Bug nervt uns schon seit einem halben Jahr und lässt regelmäßig Xenon verschwinden.
2x Xenon sind jedesmal etwa 1600$, die tun weh....

**Comment by simplycach** [comment]
Uns ist der Umfang des Bugs bekannt, aber aktuell gibt es keine weiteren Infos diesbezüglich. 
Wir sind dran ;)

**Comment by Erumeldor** [comment]
Es sind schon wieder 8 Xenon Scheinwerfer verschwunden, der Menge nach also save auch wieder für diesen Bug...
Könnte sich das nicht mal jemand anschauen, wäre supi :)

**Comment by TeubyDE** [comment]
Sind dran, erwarte kein Fix vor V3.
