### ISSUE TITLE
Bitte um Verlegung des Be und Entladepunktes

### ISSUE THREAD

**Issue by CoreForceee** [eiksch/statev_v2_issues#2819]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Kevin Grover

**Be- und Entladepunkt Verlegung**
https://pic.statev.de/image/beundendladepunktverlegung.cVP7J

**Erwartetes Verhalten**
Bitte den Punkt Verlegen laut Bild!
Da bei dem anderen auch manchmal das Problem ist das er bereits blockiert wird.

PLZ:  zwischen 5025 zu 5005
Bay City Ave
Vitus Street 3348
Firmenhash | pfJunVespucciCan7

**Optional: Video / Bilder des Fehlers**
https://pic.statev.de/image/beundendladepunktverlegung.cVP7J
![BeundEndladepunktverlegung](https://user-images.githubusercontent.com/18184855/222914598-7e99a34f-03d2-427b-998b-f34ad35e1818.png)

**Comment by TheOutburst** [comment]
warum auch immer der da rechts war, ist zum nächsten Update verschoben
