### ISSUE TITLE
Tuning verschoben bei Benefactor Schwarzer Kennzeichen: GZUZ 187

### ISSUE THREAD

**Issue by Maximilian63** [eiksch/statev_v2_issues#2820]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Max Clinton

**Auftrittszeitpunkt (Datum / Uhrzeit)**
04.03.2023 16:00 Uhr

**Beobachtetes Verhalten**
Nach dem Ausparken sind Teile verbaut die ich nicht angebracht habe.
Es ist der falsche Spoiler und Seitenschweller angebracht.
Mehr habe ich jetzt auf dem ersten Blick nicht gesehen, ob was anders ist als ich ihn das letzte mal eingeparkt hatte.

**Erwartetes Verhalten**
Das Tuning berichtigen bei dem Fahrzeug

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by simplycach** [comment]
Hast du ein Bild wie er vorher aussah und wie er jetzt aussieht für uns ?

**Comment by Maximilian63** [comment]
Habe leider keine Bilder wie er vorher ausgesehen hatte, kann euch aber gerne in der Werkstatt die Teile so dran machen wie er war und somit ein Foto machen von Soll/Ist Zustand
Würde euch das reichen ?

**Comment by simplycach** [comment]
Wenn es dir keine Umstände macht gern ;)

**Comment by Maximilian63** [comment]
Sorry hatte die Beschriftung vergessen, die oberen beiden Bilder zeigen wie er jetzt aussieht.
Die unteren zwei der Zustand wie er sein sollte

**Comment by Maximilian63** [comment]
Hallo zusammen,
Wollte frage wie hier der neue Stand ist 
Danke :)

**Comment by DonVitoDiangelo** [comment]
Ist der Fehler noch aktuell, oder hat sich das Problem bereits behoben durch ein Update von alt:v?

**Comment by Maximilian63** [comment]
Das Auto sieht auch noch so aus sie auf den ersten zwei Bilder.
Der Bug ist leider immer noch vorhanden, habe euch mal dazu auch ein Video erstellt, da es hierbei nicht nur um das plötzlich veränderte aussehen geht sondern auch um Teile die nicht mehr angebaut bzw. nicht mehr angezeigt werden können.
https://www.youtube.com/watch?v=gc3npZRAS9w
