### ISSUE TITLE
Bitte um Prüfung zur Ergänzung einer Garage für Haus #SandyShores8; East Joshua Road 8

### ISSUE THREAD

**Issue by Guoliveryh** [eiksch/statev_v2_issues#2821]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Kalle_Grabowski

kein Zeitbezug

kein Fehler

Liebes Dev-Team,
ich habe heute im Rahmen der 11. Handelskammerauktion das Wohnhaus #SandyShores8 (East Joshua Road 8) für $80.000 erworben. Da das Haus über einen überdachten Parkplatz verfügt, wollte ich höflich fragen, ob evtl. die Möglichkeit besteht, mir eine Garage "einzubauen". Baulich gibt das Gebäude dies aus meiner Sicht her und da die nächste öffentliche Garage noch ein ganzes Stück entfernt liegt, würdet ihr mir das Leben deutlich erleichtern. Um einen schnellen Überblick zu gewinnen, habe ich euch einige Bilder beigefügt.
Herzlichen Dank im Voraus & liebe Grüße,
Kalle Grabowski

kein Fehler

kein UI-Problem

kein Fehler, aber Bilder des Anwesens beigefügt

![20230304224347_1](https://user-images.githubusercontent.com/126990684/222932230-8df274ea-0af3-454c-9583-ca01c9b3b344.jpg)
![20230304224304_1](https://user-images.githubusercontent.com/126990684/222932222-299266f9-265e-48b2-b0f5-052d2c433c9e.jpg)
![20230304224338_1](https://user-images.githubusercontent.com/126990684/222932227-9e08049a-342f-4c68-82e5-f27bdfc163bd.jpg)

**Comment by TheOutburst** [comment]
next update ist da ne Garage drin

**Comment by Guoliveryh** [comment]
Super - vielen Dank!
