### ISSUE TITLE
Antrag auf Garagenpunkt

### ISSUE THREAD

**Issue by Marjuzz** [eiksch/statev_v2_issues#2824]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Alex Fait**

Hey StateV-Team,

wäre es möglich am Haus "AlexMurrietaHights_House_6" eine Hausgarage hinzuzufügen?
Eine Garage ist direkt links neben dem Haus.

Lieben Dank für die Überprüfung

Gruß
Marjuzz
![20230305183632_1](https://user-images.githubusercontent.com/127046687/222977669-bd94b452-1420-410e-a762-b9918f90b655.jpg)
![20230305185641_1](https://user-images.githubusercontent.com/127046687/222977679-aefb0ecc-b20c-4ab6-8b66-2ffaf3f247df.jpg)

**Comment by TheOutburst** [comment]
Hast next Update ne Garage
