### ISSUE TITLE
Antworten auf @-Anfragen im Dashboard

### ISSUE THREAD

**Issue by ingo-lorenz** [eiksch/statev_v2_issues#2825]
**Character Name**
Volker_Siebert

**Auftrittszeitpunkt (Datum / Uhrzeit)**
05.03.2023 20:20

**Beobachtetes Verhalten**
Ich habe über das Dashboard @ eine Nachricht an eine Anzeige geschrieben und die Antwort auf diese Anfrage landete als Konversation in der ersten Handynummer in der Liste, anstatt in der aktiven Nummer. Da ich eine 1025 als zusätzliche Nummer habe, steht diese oben und dort scheinen nun alle Antworten auf Dashboard-@-Anfrage zu landen. Die 1025 war zu keinem Zeitpunkt die aktive Nummer.

**Erwartetes Verhalten**
Die aktive Nummer beim Schreiben einer @-Anfrage im Dashboard mit speichern oder auswählbar machen, damit die Antworten bei der richtigen Nummer landen.

**Schritte um den Fehler nachvollziehen zu können**
Eine Anfrage auf eine Dashboard-Eintrag schreiben und mehrere Nummern haben.

**Optional: Video / Bilder des Fehlers**
Die Konversation von Michael_Mayer@statev.de hätte unter der 1822-38647989 landen sollen und nicht unter 1822-1025

**Comment by CaleighRhodes** [comment]
Der Fluch der Fraktions-Simkarten.

Es wird immer die Nummer genommen, welche der ältesten Sim-Karte zugeordnet ist, wenn du auf Dashboard-Anzeigen antwortest. Das wurde auch schon mehrfach angesprochen bzw. auch schon gemeldet, siehe #2768 

Workaround ist, einfach die Sim-Karte der Fraktion rausnehmen, wenn man auf eine solche Anfrage antworten will - vergisst man leider häufig.
