### ISSUE TITLE
Störende Zäune entfernen

### ISSUE THREAD

**Issue by FoxXxyLive** [eiksch/statev_v2_issues#2826]
Samy Nustrajev

Hey, wollte mal fragen ob man vielleicht diese störenden Zäune entfernen kann um so Platz für Achsen und LKW´s zu haben und die nicht andauernd weiter weg stellen oder einparken zu müssen. 

Es gibt zwar hinten eine Stellfläche jedoch ist da auch wieder das Problem, dass man gegen den verschiebbaren Zaun fahren muss um auf das Gelände zu kommen und sich damit meist das Fahrzeug zerstört und wieder in eine Werkstatt muss.

![Screenshot_12](https://user-images.githubusercontent.com/79162546/223130092-f36a45ef-75e1-4454-909f-6f8f60192218.png)
![Screenshot_13](https://user-images.githubusercontent.com/79162546/223130552-86bdc690-d9d5-4089-8b97-a6f7f62ea6da.png)

Danke für Eure Arbeit!

**Comment by TheOutburst** [comment]
Es wäre in Davis sicher besser, wenn da Autos & Achsen tendenziell weggeparkt und nicht abgestellt werden.
Abgesehen davon, dass man da auch so was parken kann werden wir das jetzt nicht durchs wegnehmen von Toren fördern.
