### ISSUE TITLE
Antrag auf Garage (Grapeseed)

### ISSUE THREAD

**Issue by l4m4rr224** [eiksch/statev_v2_issues#2827]
Grüße,

Ich wollte einmal nachfragen ob es möglich wäre mir einen Garagenpunkt an mein Haus zu setzen.
Es geht um den Haushash: SandyShores2

Ich bedanke mich im Vorraus
Lg
Anbei noch ein Bild ( Die Frau auf dem Bild ist nicht zu beachten ^^ )
![GTA5_24018jZCN0](https://user-images.githubusercontent.com/84271119/223556667-1f8b005d-94d9-49a1-a0a8-d3a190679b56.jpg)

**Comment by TheOutburst** [comment]
Sorry, aber das Haus hat weder ne Einfahrt noch nen Carport, ne Garage wo nen Loch im Zaun ist vor nem Fenster ist leider too mutch
