### ISSUE TITLE
Zusammenlegen von Be- und Entladepunkten

### ISSUE THREAD

**Issue by DylanDuncan** [eiksch/statev_v2_issues#2830]
Charaktername:
Dylan_Duncan

Hallo zusammen,
ich würde gerne die Verladepunkte von 4 Firmen die nebeneinander in einem großen Gebäude sind auf einen Verladepunkt setzen.
Den Verladepunkt habe ich so gewählt, dass man mit großen Fahrzeugen nicht großartig auf dem Parkplatz rangieren muss, sondern einfach durchfahren kann.

Firma 1: LS Frischezentrum / davis22
Firma 2 LS Frischezentrum Mühle / davis23
Firma 3: Shoqun Labs / davis24 
Firma 4: LS Frischezentrum #2 / davis25

Der zukünftige zentrale Be- und Entladepunkt soll der von Firma 2 ( LS Frischezentrum Mühle / davis23 ) sein.

![Beladepunkte1](https://user-images.githubusercontent.com/75174723/224317640-c9fd5cc0-4cce-4668-8337-c16859fcd98f.png)

![Beladepunkte2](https://user-images.githubusercontent.com/75174723/224317732-be7151ee-4dd7-45cf-a038-0f3b033659c5.png)

Vielen Dank :)

**Comment by TheOutburst** [comment]
Nee, die Punkte ergeben so wie sie sind schon Sinn.

**Comment by DylanDuncan** [comment]
Klar machen die Sinn, da es ein Firmenkomplex mit 2x Lager, Mühle und Metzgerei ist, würde ein Be- und Endladepunkt aber auch Sinn machen und weil wir in allen 4 Firmen Waren an- und verkaufen wäre es für alle einfacher.

Könnten wir den Punkt der 4. Firma dann bitte wie bei den anderen 3 Firmen vor das Gebäude setzen?
Aktuell müssen wir vom Parkplatz runterfahren und einmal ums Gebäude herum fahren. Ein Punkt vor der Firma damit alle 4 in einer Reihe sind wäre schon sehr hilfreich.
