### ISSUE TITLE
Kompressionsgefahr an der Hausgarage

### ISSUE THREAD

**Issue by Guoliveryh** [eiksch/statev_v2_issues#2831]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Kalle_Grabowski

kein Fehler

Liebes Dev-Team,
es handelt sich nicht um einen Fehler, vielmehr um eine Sorge bzw. ein potentielles Problem:
Ich wohne in der Immobilie "SandyShores8". Ganz in der Nähe befinden sich meine Firmen, wo ich täglich fleißig arbeite und häufig auch LKWs verwende. Manchmal parke ich vor allem Anhänger auf dem Firmengelände, weil ich bspw. Öl- und Large-Achse im Wechsel nutzen muss. Nun habe ich durch die kürzlich erworbene oben genannte Immobilie eine Garage ganz in der Nähe, die unter Umständen zur Ziel-Garage bei der automatischen Park-Prozedur während des Server-Neustarts wird (vgl. Abbildung1). Wenn dies passieren würde und bspw. die Öl-Achse am Haus automatisch eingeparkt wird, befürchte ich, dass beim Ausparken halb Sandy in einem großen Feuerball aufgeht, weil die Parkplatzüberdachung zu niedrig für LKWs ist (vgl. Abbildung2). Deshalb hier meine Frage: Lässt sich das evtl. vermeiden, dass größere Fahrzeuge automatisch in dieser Hausgarage eingeparkt werden? Oder wäre es alternativ möglich, den Park-Marker ein Stück vor dem Vordach zu platzieren (ungefähr so wie in Abbildung 3), damit es hier nicht zu unerwünschten Kollisionen kommt?
Herzlichen Dank im Voraus & viele Grüße,
Kalle

kein Fehler

kein Fehler

kein UI-Problem

Hier findet ihr die Abbildungen:

![Abb 1 - Problem](https://user-images.githubusercontent.com/126990684/224316801-aaee9dcc-5165-48f7-826c-f26e9b95fdb8.jpg)
![Abb  2 - Vordachhöhe](https://user-images.githubusercontent.com/126990684/224316822-7755051c-f0b0-4960-83f8-0bdefd16c182.jpg)
![Abb 3 - Markerplatzierung](https://user-images.githubusercontent.com/126990684/224316835-9478ccc6-4ea4-4287-9e30-df15889d41fb.png)

**Comment by PlayInc89** [comment]
Die Achsen sollten in den Öffentlichen Garagen landen.

**Comment by Guoliveryh** [comment]
Ok, vielen Dank für die schnelle Rückmeldung. Die Achsen waren allerdings nur ein Beispiel. Wie ist es mit den Zugmaschinen, dem Benson, dem Mixer, etc.? Diese Fahrzeuge passen leider auch nicht unters Vordach oder werden die dann auch in der öffentlichen Garage landen?

**Comment by Guoliveryh** [comment]
Update: Der Phantom Custom ist schonmal nicht betroffen, der ist soeben beim Neustart um 19:45 in die Garage Grapeseed geparkt worden und die Öl-Achse wurde gar nicht eingeparkt. (...Glück gehabt.. :P ) Das wird dann vermutlich bei den anderen Zugmaschinen und Achsen auch so sein. Wäre nur noch fraglich, ob das auch auf die kleineren LKWs wie Benson, Mixer, MTL etc. zutrifft.

**Comment by TheOutburst** [comment]
Moin Kalle,

wie PlayInc schon richitg sagte landen Achsen nicht in Hausgaragen. LKWs ebenso nicht. Demnach ist deine Sorge zwar verständlich, aber nicht valide da wir das schon bedacht haben.
