### ISSUE TITLE
Verschieben vom Be- und Entladepunkt

### ISSUE THREAD

**Issue by Imrizon** [eiksch/statev_v2_issues#2832]
**Charakter Name**
Marco_Mayer

Grüße zusammen,

ich würde gerne den verlade Punkt meiner Foundry versetzen lassen, da es mit einem Auflieger einfach ein
Krampf ist zu rangieren.

Firma:  🔥 M&F FOUNDRY GRAPESEED 🔥 // sandyshores7
Im Anhang finden sie das besagte Gebäude, ich habe im Bild auch ung. Aufgemalt, wo ich den gerne hin haben würde,
wenn das nicht gehen sollte, würde ich den verlade Punkt gerne vor der Tür haben.

![M F Foundry](https://user-images.githubusercontent.com/126988273/224400873-484f76c7-d762-4c57-8a92-4769cce7a918.JPG)

Ich bedanke mich im Voraus bei euch :)

**Comment by TheOutburst** [comment]
Ganz auf die Straße finde ich kacke, aber ich hab den mal bisschen nach vorne gezogen, das sollte auch mit der Achse gut erreichbar sein
Next update dann

**Comment by Imrizon** [comment]
Ich danke dir, bist der Beste!
