### ISSUE TITLE
Bitte um die Versetzung des Abladepunktes

### ISSUE THREAD

**Issue by FoxXxyLive** [eiksch/statev_v2_issues#2833]
**Character Name**
Samy Nustrajev

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer

**Beobachtetes Verhalten**
Der derzeitige Abladepunkt führt zu starken Problemen bei der Benutzung durch Achsen, jedes mal, wenn wir mit der Achse da abladen (was am Tag 20 mal vorkommt) ist es immens schwer richtig auf den Punkt zu fahren, da der Winkel sehr störend ist und man durch den Zaun nur schwer um die Ecke kommt. 
Auch beim rausfahren ist es meist ein Hindernis, wenn nicht sogar eine Katastrophe, da man keine Sicht nach hinten hat und gerade in Davis sehr viele Fahrzeuge lang fahren oder Verfolgungsjagden statt finden und man so meist andere Spieler unabsichtlich rammt. 

Nach vorn kann man auch nicht durchfahren, da die Straße vorn durch Fahrzeuge einer Gang blockiert werden. 

Firmenhash: davis15

Abladepunkt ALT: 
![Screenshot_12](https://user-images.githubusercontent.com/79162546/224512998-9476c4d0-c67f-45ce-bab6-39dcc8e19d26.png)

Abladepunkt NEU: 
![Screenshot_13](https://user-images.githubusercontent.com/79162546/224513015-a3cc2e40-e9dd-469c-8b3d-a234a5eba16e.png)

Danke!

**Comment by TheOutburst** [comment]
Die Abladepunkte der angrenzenden Firmen sind schon mit Absicht in der Gasse, damit die Straße möglichst frei bleibt - so wie überall wo es sich anbietet.
Wenn du einen Vorschlag in der Gasse hast damit man seitlich schauen kann wie gut man auf dem Punkt hast kann man den gerne verschieben, deswegen lasse ich das hier erstmal offen.

Und das die Gang den Ausgang der Gasse zuparkt ist ein Problem was sicher im RP lösbar ist.

**Comment by FoxXxyLive** [comment]
Das Labor links neben meinem, hat sein Abladepunkt auch genau da wo ich meinen gerne hätte (wie auf Bild 2 zu sehen ist), wieso ist das dann bei meinem Labor nicht erwünscht? 

Bezüglich der Gang habe ich es heute ausprobiert hinten durch zu fahren, jedoch kommt man da nicht um die Kurve da es zu eng ist und die Achse an der Wand entlang schleift oder hängen bleibt. 

Eine andere Möglichkeit wäre nur, wenn man die Zaunreihe links neben den Abladepunkten entfernt, da man so entspannter rangieren kann und einen besseren überblick beim ausparken hat.

**Comment by TheOutburst** [comment]
Weil das Labor links neben dir nicht angrenzend zur Gasse ist.

Das mit den Zäunen ist ja interessant, letzte Woche wolltest du den noch weg haben um da zu parken #2826 

Und wie es zu Unfällen kommt weil ihr in ner Gasse steht erschließt sich mir nicht

**Comment by FoxXxyLive** [comment]
Ah kann man nicht 2 verschiedene Anliegen haben die einem gleichen nutzen dienen? 

DIe Unfälle entstehen beim raus fahren nicht beim in der Gasse stehen.

**Comment by TheOutburst** [comment]
Ich habe dir glaube ich die Begründung per Discord ausreichend erklärt.
