### ISSUE TITLE
Fehlermeldung beim Klonen von SIM über Tablet und Handy

### ISSUE THREAD

**Issue by LiljaMorningstar** [eiksch/statev_v2_issues#2836]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Lilja Teller

**Auftrittszeitpunkt (Datum / Uhrzeit)**
13.08.2023 um 14:30 Uhr

**Beobachtetes Verhalten**
Wollte grade eine Sim Karte klonen als neue Firmennummer. Allerdings Funktioniert weder das Klonen über das Tablet obwohl eine leere Sim Karte im Inventar ist, sowie das klonen über das Handy. Bei dem Klonen über das Tablet kommt gar keine Fehlermeldung, bei dem klonen über das Handy erscheint immer die Fehlermeldung "Du benötigst eine leere Sim Karte"

**Erwartetes Verhalten**
Erwartetes verhalten wäre eine möglichkeit die Karte zu klonen. 

**Schritte um den Fehler nachvollziehen zu können**
1.) Leere Sim ins inventar
2.) Handy /Tablet nehmen 
3.) Karte klonen ohne erfolg

**Optional: Video / Bilder des Fehlers**
![simkarte](https://user-images.githubusercontent.com/76446293/224719698-d806dbac-d471-4c42-b3c8-d5ad4f855a15.PNG)
![Fehlermeldung](https://user-images.githubusercontent.com/76446293/224719721-40cf51d8-ee1e-4ab5-a799-04e9d90a0cf7.PNG)

**Comment by CaleighRhodes** [comment]
Bist du Besitzerin der Sim-Karte? Nur der Besitzer kann Karten klonen. Also der, der sie zuerst ausgepackt hat.

**Comment by LiljaMorningstar** [comment]
Jap bin ich. Hab ich vor einer stunde erst ausgepackt

**Comment by simplycach** [comment]
next update fixed
