### ISSUE TITLE
Antrag auf Garage (Mirrorpark)

### ISSUE THREAD

**Issue by Pregon** [eiksch/statev_v2_issues#2838]
Ronny Roberts & Jim Hill

Sehr geehrtes StateV-Team,

wäre es möglich beim Haus "house_Vinewood_9" eine Hausgarage hinzuzufügen? (Bild im Anhang)
Unter dem "Carport" wäre es recht passend, leider nur ein wenig Müll im weg.
Der Weg von der Straße würde auch perfekt hinführen mit dem runtergelassenen Bordstein.

Vielen Dank für eure Überprüfung

Freundliche Grüße und Schönen Abend
Pregon

P.S Der Müll unter dem "Carport" kann auch gern weg wenn das geht ^^

Bild:
![Screenshot_20230314_183505](https://user-images.githubusercontent.com/75855042/225092163-5cd9b68a-3b24-4d55-b6ad-4a1686e7e0c1.png)

**Comment by TheOutburst** [comment]
Bis auf den Farbeimer machen die Objekte beim weg nehmen leider Probleme, aber wenn man ein bisschen beim einparken aufpasst macht das keine Probleme.
Next update
