### ISSUE TITLE
AKMSU Nicht zerkratzbar

### ISSUE THREAD

**Issue by DrGrizzlY17** [eiksch/statev_v2_issues#2842]
**Beobachtetes Verhalten**
AKMSU Nicht Zerkratzbar

**Erwartetes Verhalten**
AKMSU sollte Zerkratzbar damit diese nicht immer zurückverfolgbar sind

**Schritte um den Fehler nachvollziehen zu können**
Versuchen die AKMSU zu Zerkratzen^^

**Comment by SHaagmann** [comment]
Wie du selbst schon in #2236 geschrieben hast anscheinend gewollt xD

**Comment by DrGrizzlY17** [comment]
Vielleicht hat es sich geändert :D Is ja schon nen Jahr her

**Comment by simplycach** [comment]
Ist so gewollt.
