### ISSUE TITLE
Verlegung Firmeneingang

### ISSUE THREAD

**Issue by halo235** [eiksch/statev_v2_issues#2843]
Char: Wolf_Hauptmann

Firma: BlackBay Mill - Blvd. Del Perro 5080
Firmenhash: pfJunRockFordHillsRew_7

Hallo,

ich würde euch gern darum bitten den Eingang meiner Mühle, wie auf dem Bild zu sehen ist, zu verlegen.

![mill_eingang1](https://user-images.githubusercontent.com/127630776/227765505-5477222b-80d1-4b37-bf18-c7fc08fc0cca.png)

Danke euch im Voraus! :)
Gruß

**Comment by TheOutburst** [comment]
Moin,

darf man fragen warum?

**Comment by halo235** [comment]
Hallo,
weil alle verlegungs-variationen des verladepunkts nicht optimal wären. Wenn der eingang so verlegt wird wie auf dem bild zu sehen, dann ist der weg zum verladepunkt ok. am liebsten wäre es mir wenn der verladepunkt mit dem meiner verpackungsfabrik, direkt neben an, verschmolzen wird. dieser müsste aber erst dafür verlegt werden. diese verlegung habe ich schon beantragt.

**Comment by TheOutburst** [comment]
Aaalso

bei deiner anderen Firma wurd der Verladepunkt von der Straße weg in eine Gasse verschoben, soweit so einfach und umsetzbar.
Aber wir verschieben jetzt nicht hier ne Firma auf die andere Seite von einem Häuserblock (nur weil da gerade Frei ist) - nur um dann im Anschluss den Verladepunkt passend zum neuen Ausgang zu verlegen.
