### ISSUE TITLE
Motorrad Outfits für Frauen ohne Hose

### ISSUE THREAD

**Issue by ChrisBraun-VIOV** [eiksch/statev_v2_issues#2844]
**Character Name**
Chris Branth

**Auftrittszeitpunkt (Datum / Uhrzeit)**
27.03.23 21:25

**Beobachtetes Verhalten**
Bei jedem Motorrad Outfit für Frauen fehlen die Hosen

**Erwartetes Verhalten**
Hose muss angezeigt werden

**Schritte um den Fehler nachvollziehen zu können**
Einfach im Katalog sich die Outfits anschauen 

<img width="603" alt="Bug Motorradoutfits Frauen" src="https://user-images.githubusercontent.com/65866140/228057518-433d3400-eb89-48d7-bebb-ebdb16022a43.png">

**Comment by PlayInc89** [comment]
![image](https://user-images.githubusercontent.com/70231715/228381516-41c1fe4f-b051-4f76-9ff1-80e818682aac.png)
Is halt nicht nur im Katalog so sondern wenn man so einen Anzieht
