### ISSUE TITLE
Durchs Fenster springen bei Lucky Plucker

### ISSUE THREAD

**Issue by Pregon** [eiksch/statev_v2_issues#2845]
Ronny Roberts

22.03 18:38

Durchs Fenster springen/sliden (Lucky Plucker)

Nicht durchs Fenster springen/sliden

Vors Fenster stellen bei Lucky Plucker und diesen Flip da machen (Name vergessen ^^)

https://user-images.githubusercontent.com/75855042/228303204-f2dcd15b-83f5-475b-8b29-37fb1e3c7788.mp4

Man kann btw auch ohne vorher zu landen schon an sich durchs Fenster springen

**Comment by simplycach** [comment]
Werden wir schlicht nichts dran ändern, wenn jemand diese Animation ausnutzen sollte im Support melden.
