### ISSUE TITLE
Keine Sim Karte einlegbar

### ISSUE THREAD

**Issue by nox142** [eiksch/statev_v2_issues#2847]
**Character Name**
Jona Lindner

**Auftrittszeitpunkt (Datum / Uhrzeit)**
01.04.2023 01:00

**Beobachtetes Verhalten**
Hatte meine Sim Karte aus dem Handy rausgenommen und wollte sie wieder einlegen. Dann erschien die Meldung, dass die Sim Karte bereits in Verwendung ist

**Erwartetes Verhalten**
Sim Karte einlegbar

**Schritte um den Fehler nachvollziehen zu können**
Sim Karte rausnehmen und wieder einlegen

**Comment by nox142** [comment]
Heute Morgen beim Einloggen war die Sim Karte dann verschwunden

**Comment by simplycach** [comment]
Komplett verschwunden mhm ok, also ist auch nicht wieder im Telefon gelandet ?

**Comment by nox142** [comment]
Genau, hab ich auch schon kontrolliert. Nirgendswo mehr auffindbar

**Comment by simplycach** [comment]
Der Fehler ist bei mir nicht aufgetreten. Eventuell aus versehen wegeschmissen ?

**Comment by nox142** [comment]
Ich hatte eigtl alle Werkstatt Sachen in meine Hellfire gelegt, weil ich ja sowieso nicht arbeiten konnte. Aber ist ja nicht weiter schlimm, kann ja neu gemacht werden, wenn die Sim Karten wieder funktionieren.

**Comment by simplycach** [comment]
Mit dem nächsten Update fixed.
