### ISSUE TITLE
Bei 850 in sandy shores wurde mir bei der begrünung ein baum platziert bei der parkplatz einfahrt 

### ISSUE THREAD

**Issue by DaAlki** [eiksch/statev_v2_issues#2848]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Jack Spooner 

Jack Spooner 
**Auftrittszeitpunkt (Datum / Uhrzeit)**

01.04.20230 11Uhr 
**Beobachtetes Verhalten**
Bei 850 wurde mir bei der zufahrt zu meinem haus eigenen Parkplatz ein Baum platziert.
Müsste jetzt immer über holzstämme drüber fahren um auf meinen Parkplatz zu kommen 

**Erwartetes Verhalten**
Der baum sollte da nicht stehen :-)  bzw vl etwas verschoben werden ?? 

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by simplycach** [comment]
Schick mal bitte ein Screenshot, Video damit wir es besser nachvollziehen können

**Comment by DaAlki** [comment]
![Grand Theft Auto V Screenshot 2023 04 01 - 11 24 06 30](https://user-images.githubusercontent.com/83837336/229277943-86c493ae-7ce9-4507-a0f1-54709b2c312e.png)
