### ISSUE TITLE
Einbrechen ohne Funktion

### ISSUE THREAD

**Issue by DrGrizzlY17** [eiksch/statev_v2_issues#2849]
**Character Name**
Trey_Jackson

**Auftrittszeitpunkt (Datum / Uhrzeit)**
1.4.23 13.50

**Optional: Video / Bilder des Fehlers**
https://www.youtube.com/watch?v=AV9uG120zD0

**Comment by simplycach** [comment]
Sind wir bereits dran, mit dem nächsten Update fixed.
