### ISSUE TITLE
Fehler beim Login HK-Webseite

### ISSUE THREAD

**Issue by ZillaaaTV** [eiksch/statev_v2_issues#2850]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Kann mich nicht mehr auf der HK Website einloggen komme immer wieder zum Login-Bildschirm und es sagt ich sei nicht eingeloggt. bin auch nicht alleine mit dem Fehler.

**Comment by ZillaaaTV** [comment]
Carljames_Tanner und der Fehler besteht bereits seit dem AltV Update

**Comment by CaleighRhodes** [comment]
Es macht mehr Sinn, den Fehler ins Issue, statt alles in den Betreff zu schreiben 😅

**Comment by simplycach** [comment]
Bitte vorübergehend beim Browser deiner Wahl anmelden: https://sahk.de/handelskammer/index.php

**Comment by ZillaaaTV** [comment]
Sorry ich reporte zum ersten mal bin etwas lost damit noch aber danke XD
