### ISSUE TITLE
Tuning verschwunden bzw. verschoben bei Sentinel XS + Jester classic

### ISSUE THREAD

**Issue by baka708** [eiksch/statev_v2_issues#2852]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name: Ulli Schwadulek**

**Auftrittszeitpunkt: 04.2023 (Datum / Uhrzeit)**

**Beobachtetes Verhalten:
Das Tuning beim Sentinel XS ist leider komplett verschwunden. Man kann auch leider keine Tuning Teile ändern oder verbauen. z.B. bei der Motorhaube ändert sich dann die Frontstoßstange. 

Ein ähnliches Problem besteht bei meinem Jester Classic. Auch hier ändern sich nicht die korrekten Teile in der WErkstatt. Außerdem ist IC aufgefallen das ich eine Carbon Motorhaube sehe, andere Spieler aber die Hochleistungshaube.
Die Problematik ist mir auch bei anderen Jester classic aufgefallen bei denen fehlt z.b. die vordere Stoßstange komplett aus meiner Sicht.

Ich nutze die aktuellste Version NVE zusammen mit den NVE Roads. Evtl hat das etwas damit zu tun.

Anbei noch ein vorher Bild vom Sentinel. Beim Jester weiss ich es nicht genau da es mir erst nach dem Kauf des Wagens aufgefallen ist das da was nicht stimmt. 
https://pic.statev.de/i/wulTC.png**

**Erwartetes Verhalten:
Selbsterklärend**

**Comment by simplycach** [comment]
Hast du noch ein Bild wie er jetzt aussieht ?

**Comment by baka708** [comment]
![Grand Theft Auto V Screenshot 2023 04 03 - 13 07 26 23](https://user-images.githubusercontent.com/110282299/229492437-0d2ad0f5-46c5-4de8-a605-baf4a2b8c905.png)
![Grand Theft Auto V Screenshot 2023 04 03 - 13 07 32 60](https://user-images.githubusercontent.com/110282299/229492471-65d6df44-0581-4f95-b735-65a1cce2a589.png)

So sieht er aktuell aus.

**Comment by DonVitoDiangelo** [comment]
Ist der Fehler noch aktuell, oder hat sich das Problem bereits behoben durch ein Update von alt:v?

**Comment by baka708** [comment]
Der Fehler ist nach wie vor unverändert

**Comment by baka708** [comment]
Gibt es zu dem Fehler schon was neues? Ist schade weil ich zumidnest den Sentinel garnicht nutzen kann.

**Comment by simplycach** [comment]
Tritt das Problem auch ohne Mods weiterhin auf ?
