### ISSUE TITLE
Bordstein reagiert extrem auf Fahrzeuge

### ISSUE THREAD

**Issue by Pregon** [eiksch/statev_v2_issues#2855]
Ronny Roberts

28.03.2023 15:26

Bordstein am Hafen zerstört Fahrzeug

Man kann über den Bordstein wie jeden anderen Fahrer

Mit einem Fahrzeug über die Ecke fahren (funktioniert soweit ich weiß mit verschiedenen)

https://user-images.githubusercontent.com/75855042/229753582-0aa41a12-cdd3-406f-b828-fe8d73f10b18.mp4

**Comment by TheOutburst** [comment]
Das Werkbankobjekt da rechts hat einen "Hammer" der durch Zufall in dieser Position auf der Straße ist, wir tauschen das Werkbankobjekt gegen ein besseres aus.
Solange gerne die "Große Werkbank" abbauen und aufs Update warten

**Comment by Pregon** [comment]
Passt, jetzt wieder danke
