### ISSUE TITLE
Fahrzeugfehler beim Rejoin (Falsche Zuordnung des Standorts) 

### ISSUE THREAD

**Issue by Pregon** [eiksch/statev_v2_issues#2857]
Ronny Roberts

02.03.2023 16:23

Das Fahrzeug war unsichtbar nach Gamecrash.
Nach/Beim einsteigen wurde klar, dass es einfach nur dem Tunnel darunter zugeordnet wurde, somit wurde der Teil der Map angezeigt der lädt, wenn man da unten im Tunnel ist.
Nach rausfahren aus dem Bereich war die Map wieder zu sehen

Das Auto ist von Anfang an sichtbar und wird der oberen Straße zugeordnet

Keine Ahnung wie genau man das nachstellen will, aber vielleicht an der Stelle das Game leaven, während man im Fahrzeug ist und dann wieder beitritt

https://user-images.githubusercontent.com/75855042/229758621-b61eb0aa-7f21-4d23-8efb-bbfad905331c.mp4

**Comment by simplycach** [comment]
Wird vermutlich ein einmaliger Fehler sein, das wird man nicht unbedingt nachgestellt bekommen. Einfach mal beobachten bitte und zur Not einen neuen Bugtracker eröffnen.
