### ISSUE TITLE
Kuruma folierung unerlaubt verändert + lässt sich dann nicht ändern

### ISSUE THREAD

**Issue by Persi3001** [eiksch/statev_v2_issues#2861]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Anton Pers

Anton Pers nur ich
**Auftrittszeitpunkt (Datum / Uhrzeit)**

23:57 4.4.23
**Beobachtetes Verhalten**
Habe mich gewundert warum mein Kuruma eine andere Folierung hatte als sonst, bin dann in die werkstatt gefahren wo ich arbeite wollte gucken was mit der folierung los ist da konnte ich keine andere mir vorzeigen lassen sobald ich weitergeklickt habe war halt folie ganz weg

**Erwartetes Verhalten**
Folie hätte nicht einfach verschwinden dürfen bzw. die Folie solle sich mir beim tunen vorzeigen lassen (habe noch nicht ausprobiert was passiert wenn ich mir da eine nehme ob die dann einfach drauf geht oder sonst einfach nix angezeigt wird.)

**Schritte um den Fehler nachvollziehen zu können**
Karin Kuruma nehmen > Werkstatt fahren > tuning > folierungen > einfach rumklicken wird sich nichts ändern

**Optional: Video / Bilder des Fehlers**

https://user-images.githubusercontent.com/129906271/229935456-0cca678f-fffb-4b3a-92d4-ac9b2c38cc10.mp4

**Comment by DonVitoDiangelo** [comment]
Ist der Fehler noch aktuell, oder hat sich das Problem bereits behoben durch ein Update von alt:v?

**Comment by Persi3001** [comment]
gerade geguckt ist immernoch da

**Comment by Persi3001** [comment]
kann es halt immernoch nicht ändern
