### ISSUE TITLE
Automatisches Rolltor #2

### ISSUE THREAD

**Issue by Patrick-Snooze** [eiksch/statev_v2_issues#2862]
**Character Name**
Patrick Snooze

**Auftrittszeitpunkt (Datum / Uhrzeit)**
05.04.23

**Beobachtetes Verhalten**
Tor öffnet sich nicht egal welches Fahrzeug, habe es ja damals schon in einem anderen "Bug" gemeldet auch das Video dazu gpostet.
Wollte aber nochmal ein eigenes Thema raus machen, muss doch eine möglichkeit geben dies zubehben.

Hatte sich ja damals schon jemand angeguckt, aber das entfernen würde wohl gehen aber das Sound vom Rolltor würde bleiben, meine frage ist nun wäre es nicht möglich wenn ihr dort einfach "Leitkegel" hinstellt, den genau das habe ich versucht aber sobald ich aus die Range fahre und zurückfahre ist das Tor trotzdem zu. (siehe Screen)

**Erwartetes Verhalten**
Tor sollte sich öffnen, wenn man mit einem Fahrzeug vorfährt

**Schritte um den Fehler nachvollziehen zu können**
Fahrzeug nehmen und vorfahren

**Optional: Video / Bilder des Fehlers**
https://youtu.be/D7lcGV-vSD4

![20230405093905_1](https://user-images.githubusercontent.com/74994851/230016497-f447e760-d80e-4eca-b646-d293c19f3161.jpg)

Ist halt echt nervig immer erst das Tor mit dem Fahrzeug zu berühren damit es sich öffnet.

gr33tz
Patrick

**Comment by simplycach** [comment]
Das ist eine Mechanik von GTA da werden wir leider nicht so viel machen können. Was hilft ist, dass du mit deinem Fahrzeug gegen dieses Tor leicht fährst, dann geht es auf. Wenn man halt dieses Tor entfernen würde, wie du schon sagst bleibt der Sound. 

[https://github.com/eiksch/statev_v2_issues/issues/2761](url)

Die Thematik wurde ja auch schon mal aufgegriffen.
