### ISSUE TITLE
Towtruck large abschleppen buggy

### ISSUE THREAD

**Issue by Mytex88** [eiksch/statev_v2_issues#2864]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Rafael Pereira

**Auftrittszeitpunkt (Datum / Uhrzeit)**

06.04.2023 17:30

**Beobachtetes Verhalten**

Haben mit einem Towtruck large versucht einen Phantom Custom und einen Barracks abzuschleppen, leider wurde mit dem Haken kein triggerpunkt gefunden. Es wurde von vorne und hinten an den Fahrzeugen getestet mehrfach auf unterschiedlichen höhen

**Erwartetes Verhalten**

Der Abschlepphaken sollte sich am Fahrzeug fest machen dass man das Fahrzeug abschleppen kann.

**Schritte um den Fehler nachvollziehen zu können**

Mit Towtruck large an Phantom Custom bzw Barracks ranfahren und das Fahrzeug versuchen abzuschleppen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by simplycach** [comment]
Habe es gerade selber ausprobiert, funktioniert ohne Probleme, sowohl mit dem Phantom als auch mit dem Barracks.

**Comment by Mytex88** [comment]
Hmm komisch haben nämlich mehrere Leute mit dem Fahrzeug jetzt probiert und hatten das Problem auch, vor 2 Minuten mit einem Pounder.

**Comment by PlayInc89** [comment]
Abschlepphacken runter gemacht ?

**Comment by Mytex88** [comment]
Ja

**Comment by Mytex88** [comment]
kann es sein das es eventuell nur dieser Towtruck ist?

**Comment by simplycach** [comment]
Bitte wenn dieser Fehler auftritt ein Video machen und uns zur Verfügung stellen, damit wir es nachvollziehen könne.

**Comment by Mytex88** [comment]
Video kommt gleich

**Comment by Mytex88** [comment]
https://youtu.be/ZsSS-a6hC1U

**Comment by simplycach** [comment]
Einmal bitte die Kennzeichen von beiden Fahrzeugen

**Comment by Mytex88** [comment]
LS TAS 3 
TOWTRUCK
LS RP 1 (mein Packer) wo es auch nicht ging

**Comment by simplycach** [comment]
Konnte nicht reproduziert werden.

**Comment by Dean-Gallagher** [comment]
habe den Bug ebend selbst gesehen und erlebt. 

Burrito war defekt, rote MKL, so defekt das man nicht mehr einsteigen konnte, Towtruck konnte ihn nicht anhängen

**Comment by Derison** [comment]
@Mytex88 @Dean-Gallagher Habt ihr irgendwelche Grafikmods drauf?

**Comment by CaleighRhodes** [comment]
Aktuell kriegt man mit dem kleinsten Towtruck gar nix angehangen, völlig egal, ob Copkarre oder was anderes.

Ich selber nutze nur Reshade, war aber auch bei Kollegen so, die keine Grafikmod drauf haben.

**Comment by Dean-Gallagher** [comment]
Nope, keine Grafikmods nur auf maxi settings

**Comment by TeubyDE** [comment]
Wie im Server Status mitgeteilt, sollte das Problem behoben sein.
