### ISSUE TITLE
Falsche Menü Preise im Restaurant 

### ISSUE THREAD

**Issue by Smaty86** [eiksch/statev_v2_issues#2866]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Tim Rock 
Restaurant WING STOP 

Die Menü Preise werden falsch angezeigt. Alle Gerichte haben einen Cent Endpreis von 29, 49 oder auch 99 Cent. Wenn man ohne Bedienung bestellt enden viele Preise auf 45 Cent wenn man mit Bedienung bestellt enden die Preise auf 3 Cent oder 93 Cent

**Auftrittszeitpunkt (Datum / Uhrzeit)**
 07.0.4 17:15 Uhr

**Beobachtetes Verhalten**
Die Menü Preise werden falsch angezeigt. Alle Gerichte haben einen Cent Endpreis von 29, 49 oder auch 99 Cent. Wenn man ohne Bedienung bestellt enden viele Preise auf 45 Cent wenn man mit Bedienung bestellt enden die Preise auf 3 Cent oder 93 Cent
![3cent](https://user-images.githubusercontent.com/76659094/230635023-17d6b041-b321-488d-af65-402d6c2df064.png)

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Smaty86** [comment]
![theke](https://user-images.githubusercontent.com/76659094/230635256-9aa61d66-e6e4-44c0-a2fa-408018a330aa.png)

**Comment by Smaty86** [comment]
Die Theken Preise werden richtig angezeigt

**Comment by PlayInc89** [comment]
Ohne Bedienung musst du mit 5 Multiplizieren  mit Bedienung mit 7 Das Heißt Wasser an der Theke 3,59$ Ohne Bedienung 17,95$ und mit Bedienung 23,13$. Also das was ich da an deinen Screenshots sehe ist da alles in Ordnung.
