### ISSUE TITLE
Vapid Towtruck Large 125 PS Bug

### ISSUE THREAD

**Issue by WunderBaum9** [eiksch/statev_v2_issues#2867]
David_Ostrowski

**Auftrittszeitpunkt (Datum / Uhrzeit)**
08.04.2023 20:51

**Beobachtetes Verhalten**
Der Towtruck Large kann keine Autos mehr abschleppen. Haben es mit paar Autos versucht leider kein Erfolg.

**Erwartetes Verhalten**
Das der Hacken von dem Abschlepper wieder geht.

**Schritte um den Fehler nachvollziehen zu können**
Einfach hinten ranfahren hacken runter machen.

**Optional: Video / Bilder des Fehlers**
https://www.youtube.com/watch?v=we_Boi-CIy0

**Comment by PlayInc89** [comment]
#2864
