### ISSUE TITLE
Bob Mulet Fehler beim Check, ob die benötigten Ressourcen fürs Haareschneiden vorhanden sind.

### ISSUE THREAD

**Issue by Parityisreal** [eiksch/statev_v2_issues#2871]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Parity Corleone / Viola Corleone**

**10.04 / 09.04 **

**Wenn man sich eine Frisur ausgesucht hat und diese dann schneiden will, kommt der Fehler, dass Handtücher fehlen, obwohl genug vorhanden sind.**

**Das die Items im Lager korrekt gecheckt werden und man die Frisur schneiden kann.**

**Kunde setzt sich hin / man wählt die Frisur aus / Man stellt die Rechnung aus / "Fehler - zu wenig Handtücher vorhanden" **

**Comment by TeubyDE** [comment]
(at)QA: Bitte einmal prüfen ob es soweit reproduziert werden kann. Danke.

**Comment by simplycach** [comment]
> ## WICHTIGE INFORMATION!!:
> ```
> Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
> ```
> 
> **Parity Corleone / Viola Corleone**
> 
> **10.04 / 09.04 **
> 
> **Wenn man sich eine Frisur ausgesucht hat und diese dann schneiden will, kommt der Fehler, dass Handtücher fehlen, obwohl genug vorhanden sind.**
> 
> **Das die Items im Lager korrekt gecheckt werden und man die Frisur schneiden kann.**
> 
> **Kunde setzt sich hin / man wählt die Frisur aus / Man stellt die Rechnung aus / "Fehler - zu wenig Handtücher vorhanden" **

Ist der Fehler nochmal aufgetreten ? Wir konnten es jetzt nicht reproduzieren.

**Comment by Parityisreal** [comment]
Bis jetzt ist der Fehler nicht nochmal aufgetreten.
