### ISSUE TITLE
Xenon Lichter an Fahrzeugen zurückgesetzt

### ISSUE THREAD

**Issue by Persi3001** [eiksch/statev_v2_issues#2872]
Anton Pers

Anton Pers
**Auftrittszeitpunkt (Datum / Uhrzeit)**
11.4.23  14:45 -15:29

**Beobachtetes Verhalten**
Bei allen mein Fahrzeugen haben sich die Xenon Lichter zurücksetzt auf Serie

**Erwartetes Verhalten**
das sollte eigentlich nicht so sein

**Schritte um den Fehler nachvollziehen zu können**
weiß ich nicht ist mir halt vorhin aufgefallen bei mein kuruma wo sein grünen licht hin ist

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
Nachher:
![bug](https://user-images.githubusercontent.com/129906271/231178847-c38ad730-5507-448e-9d72-f41e7fba23a9.PNG)
Vorher:
https://pic.statev.de/i/QM1jq.jpg

**Comment by Statev-Bonsai** [comment]
dito ist bei mir auch so, die werden immer zurückgesetzt..

**Comment by PlayInc89** [comment]
Habt ihr in den Letzten Tagen in der Werkstatt Tuning machen lassen ?

**Comment by Statev-Bonsai** [comment]
nein, das ist seid dem vorletzten update so..

**Comment by PlayInc89** [comment]
Hab jetzt mal bei meinen Fahrzeugen geschaut ich hab nichts....

**Comment by Persi3001** [comment]
was machen wir da, soll ich mir die Lichter vom Support wiedergeben lassen? dann verschwinden die wieder oder bleiben scheint ja aktuell irgendwie nur ein Einzelfall zu sein

**Comment by Statev-Bonsai** [comment]
habe heute ein neues fahrzeug erworben und die lichtfarbe ändern lassen, da wurde es auch wieder zurückgesetzt.. das ein/ausparken setzt es kurzzeitig auf normal zustand zurück...

**Comment by Persi3001** [comment]
Ich glaube da besteht ein zusammenhang mit NVE oder QuantV, da ich mit kollegen OOC gesprochen habe wo sich die lichtfarbe erst auf serie zurücksetzt wenn ich in die nähe komme, da ich ein mix paket habe mit NVE und QuantV und diverse Sound veränderungen

**Comment by Statev-Bonsai** [comment]
ich nutze keinerlei mods etc...

**Comment by Persi3001** [comment]
habe meine grafikmod heute rausgenommen, lichter sind wieder da

**Comment by Statev-Bonsai** [comment]
Ausgeparkt--> Lichter Rot.... Streaming Range verlassen und zurück gefahren--> Lichter Weiss

![Screenshot_33](https://user-images.githubusercontent.com/70241137/234407045-42d256c9-9dc5-4989-bc75-6254dc3906c2.jpg)

![Screenshot_34](https://user-images.githubusercontent.com/70241137/234407063-89d15a0d-1a45-45de-82b3-133b95ba8c54.jpg)

**Comment by Statev-Bonsai** [comment]
@DonVitoDiangelo habt ihr schon mal geschaut woran es liegt, weil es noch auf to investigate steht...

**Comment by Persistence123** [comment]
hast du die grafikmod von gonzo drauf?

**Comment by Statev-Bonsai** [comment]
das liegt an keiner mod etc... habe nen cleanes gta, habe sogar bilder geliefert zu dem problem... ^^

**Comment by ChrisBraun-VIOV** [comment]
ja ich hatte die von Gonzo drauf, Aber komplett deinstalliert und es hat sich nichts geändert. Selbst ein und ausparken hat nicht geholfen.
