### ISSUE TITLE
Produktion von Tütchen Gras

### ISSUE THREAD

**Issue by struthioo** [eiksch/statev_v2_issues#2873]
**Buba Young**

**13.04.23 / 7:30**

**Bei der Herstellung von Tütchen Gras wird nur 1 kleiner Druckverschlussbeutel entfernt.**

**Da man am Ende 12x pro Herschtellung bekommt sollten auch 12 kleine Druckverschlussbeutel entfernt/ genutzt werden und nicht nur eines.**

**Comment by TheOutburst** [comment]
das ist ok so
