### ISSUE TITLE
Abladepunkte der Entfernten Restaurants

### ISSUE THREAD

**Issue by SHaagmann** [eiksch/statev_v2_issues#2874]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Andrew Lucas
**Auftrittszeitpunkt (Datum / Uhrzeit)**

Seit entfernung der alten Restaurants
**Beobachtetes Verhalten**

Die Abladepunkte sind noch vorhanden
**Erwartetes Verhalten**

Sollten weg sein, solange nicht noch ne andere Firma drauf zugreift
**Optional: Video / Bilder des Fehlers**

Einfach als Beispiel Restaurant in Sandy und Harmonie
![image](https://user-images.githubusercontent.com/58612983/231750798-cb60d79a-d75a-4ded-866d-7823c9be4ecf.png)
![image](https://user-images.githubusercontent.com/58612983/231751204-ce7d0a20-ebd8-44dd-a6c1-18e2331d0d1f.png)

**Comment by TheOutburst** [comment]
Good Point, next Update
