### ISSUE TITLE
Kofferraum Weevil Custom

### ISSUE THREAD

**Issue by Statev-Bonsai** [eiksch/statev_v2_issues#2875]
Ich würde mir wünschen wenn man das Volumen des Kofferaums deutlich erhöht, das Fahrzeug hat einen vollwertigen Kofferraum (Heckmotor) aber nur 20kg Volumen, Motorräder haben das gleiche Volumen..
Anbei ein Bild des Kofferraums..

![Screenshot_23](https://user-images.githubusercontent.com/70241137/231799221-5b26bbf4-d3dc-4ef7-a2e5-dd1e95a0d242.jpg)

**Comment by DonVitoDiangelo** [comment]
next update
