### ISSUE TITLE
Esstische setzen mit Freunden im Interior Luxury Apartment Modern Design

### ISSUE THREAD

**Issue by Beartox** [eiksch/statev_v2_issues#2878]
**Character Name**
Tobias_Schlueter

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Im Haus drin jedes Mal

**Beobachtetes Verhalten**
Kann mich am großen Esstisch nicht mit y hinsetzen

**Erwartetes Verhalten**
Dass man sich da hinsetzen kann, mit Freuden.

**Schritte um den Fehler nachvollziehen zu können**
ist in dem Haus Interior Luxury Apartment Modern Design

**Comment by simplycach** [comment]
Schick mal bitte ein Video was du genau meinst.

**Comment by Beartox** [comment]
Meine genau frage, war damit gemeint, ob man denn Tisch wie auf dem Bild mit dem Haus Interior Luxury Apartment Modern Design genau so machen könnte, dass man sich sitzen kann wie bei der Einrichtung High Class Apartment (Bordaux) was man auf Bild 2 sehen kann:

**Luxury Apartment Modern Design**
![1](https://user-images.githubusercontent.com/79170045/232973614-08c04eee-0127-4d2c-8ee4-58c43ff4922b.png)

**Bild 2 High Class Apartment (Bordaux)**
![2](https://user-images.githubusercontent.com/79170045/232973616-334ed682-18ed-4af5-b5d4-787f6d4f33d0.png)

**Comment by Beartox** [comment]
Meine genaue Frage war, ob man denn Esstisch, denn man auf Bild eins sieht, was das Haus Interior Luxury Apartment Modern Design ist, genau so hinbekommt, dass man sich setzten, kann, wie auf Bild zwei zu sehen ist, was das haus Interior High Class Apartment (Bordaux) ist, sodass man sich auch mit freunden an den Tisch setzen kann 

**Bild 1 Luxury Apartment Modern Design**
![1](https://user-images.githubusercontent.com/79170045/232973614-08c04eee-0127-4d2c-8ee4-58c43ff4922b.png)

**BIld 2 High Class Apartment (Bordaux)**
![2](https://user-images.githubusercontent.com/79170045/232973616-334ed682-18ed-4af5-b5d4-787f6d4f33d0.png)

**Comment by TeubyDE** [comment]
@GD: Möglich?

**Comment by DonVitoDiangelo** [comment]
Klar, Dulach macht alles möglich. ♥
