### ISSUE TITLE
Antrag auf Garage

### ISSUE THREAD

**Issue by TheMoonicorn** [eiksch/statev_v2_issues#2879]
Hello, ich würde gerne eine Garage für mein Haus in Paleto Bay beantragen.
Ich würde mich sehr drüber freuen, da es den Inventar Transfer vom Auto ins Haus um vieles vereinfachen würde.
Mir würden auch 2 Parkplätze reichen, da diese ungefähr der Größe der Auffahrt entsprechen.
Ebenso habe ich schon einige Häuser gesehen, die ähnliche Auffahrten haben wie meines und eine Garage besitzen, weswegen ich das einmal anfragen wollte.

![20230323211842_1](https://user-images.githubusercontent.com/70480671/232855391-9567ad6f-6cbe-4e93-86df-78fd431c1a26.jpg)

Haushash: paletobay27

**Comment by TeubyDE** [comment]
@TheMoonicorn Hat das Haus ein Carport oder eine Garage?

**Comment by TheMoonicorn** [comment]
@TeubyDE Nein, hat es nicht. Mir ist jedoch aufgefallen, dass immer mehr Häuser ohne Garage oder Carport  eine Garage besitzen. Einige Häuser im Mirrorpark oder die Omerta Villa besitzen eine Garage. Beis

**Comment by TheMoonicorn** [comment]
@TeubyDE Nein, hat es nicht. Mir ist jedoch aufgefallen, dass immer mehr Häuser ohne Garage oder Carport eine Garage besitzen. Einige Häuser im Mirrorpark oder die Omerta Villa besitzen eine Garage. [Beispiel](https://github.com/eiksch/statev_v2_issues/issues/2678) Daher wollte ich das auch für mein Haus anfragen, da es keine besitzt und es vieles vereinfachen und auch weniger Autos natürlich rumstehen würden.

**Comment by TeubyDE** [comment]
Glaube gibt 2-3 ausnahmen wo es warum auch immer gemacht worden ist.
In deinem Fall wird es aber leider keine Garage geben.
