### ISSUE TITLE
Antrag auf Entfernung von Pflanzen beim Yellow Jack INN

### ISSUE THREAD

**Issue by JonaeysDE** [eiksch/statev_v2_issues#2880]
Character Name: Zed Wert

In der Mitte des Parkplatzes vom Yellow Jack INN sind Pflanzen, die gerne entfernt werden sollen, um diesen Platz zu nutzen. Auf Verweis stelle ich hier nun ein Antrag, falls dies möglich ist.

Mit Grüßen

**Comment by simplycach** [comment]
Bitte mal ein Screenshot mit anfügen, damit man es besser beurteilen kann.

**Comment by JonaeysDE** [comment]
![Screenshot (590)](https://user-images.githubusercontent.com/131297605/233469315-a520f648-8713-4a7f-882a-4ae9b32285c2.png)
