### ISSUE TITLE
Tuning vom Bobcat nach Server Restart zurückgesetzt

### ISSUE THREAD

**Issue by TheRevenger12** [eiksch/statev_v2_issues#2881]
-Frank,Winston
-Einziger Char

**Auftrittszeitpunkt
20.04.2023 17:06

**Beobachtetes Verhalten**
Nach einloggen und ausparken aus der Garage am Haus (Nikola Place 25) des Bobcats (Kennzeichen :Blackbetty) ist mir aufgefallen das die Felgen und Reifen wieder auf Standard zurück gesetzt waren.

**Erwartetes Verhalten**
Fahrzeug verbleibt mit Tuning

**Schritte um den Fehler nachvollziehen zu können**
Keine

**Optional: Video / Bilder des Fehlers**
Belege für Zahlungen für das Tuning im November 2022.
Einziger Beweis ist ein Thumbnail aus 2022 aber man erkennt bei genauerem hinsehen das die Felgen und Reifen zurückgesetzt wurden.
Zusätzlich das Fahrzeug im jetzigen Zustand 
![20230420172447_1](https://user-images.githubusercontent.com/119755866/233421046-0dc07977-f26a-4040-88d9-f3fdbe526f21.jpg)

![sludgies bobcat 1](https://user-images.githubusercontent.com/119755866/233420759-31e49948-2da5-4212-b5c9-4fd1ec4aa197.JPG)
![sludgies bobcat 2](https://user-images.githubusercontent.com/119755866/233420764-972147d6-e81f-4f52-bd88-3474fd1b4980.JPG)
![Bobcat](https://user-images.githubusercontent.com/119755866/233421833-87090125-4afc-43eb-ac82-e762c230d66d.jpg)

**Comment by DonVitoDiangelo** [comment]
Leider nicht nachvollziehbar. Ich gehe aktuell davon aus, das es hier durch ein GTA oder alt:v Update Verschiebungen bei den Felgen für das Vehicle kam. Das können wir aber nicht beeinflussen oder ändern. Es ist auch kein weiterer Fall eines solchen Fehlers bekannt, sry.
