### ISSUE TITLE
Unsichtbarkeit im Auto durch Popcorn

### ISSUE THREAD

**Issue by SatyriaDine** [eiksch/statev_v2_issues#2886]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Sofia_Black

**Auftrittszeitpunkt (Datum / Uhrzeit)**
zuerst aufgefallen am 01.05.2023 ca 22Uhr, reproduziert am 02.05.2023 16:30Uhr

**Beobachtetes Verhalten**
Wenn man das Item Popcorn im Inventar hat und nutzt und man dann in ein Auto steigt wird der Charakter unsichtbar.  
Am 01.05. war es so dass ich das Popcorn angeklickt habe, nach ein paar Sekunden als Beifahrer in ein Auto gestiegen bin und mein Charakter dann unsichtbar und halb unter der Map war. Ein kurzer Neustart des Spiels hat geholfen. 
Nochmals am 02.05. getestet um es zu reproduzieren, dort bin ich aber wie im Video zu sehen als Fahrer eingestiegen und konnte ganz normal wieder aussteigen. 

**Erwartetes Verhalten**
Dass man nicht unsichtbar wird oder unter der Map verschwindet

**Schritte um den Fehler nachvollziehen zu können**
Item Popcorn im Inventar, mit Rechtsklick benutzen, mit dem item in der Hand in ein Auto einsteigen

**Optional: Video / Bilder des Fehlers**
Video vom 01.05. : https://www.youtube.com/watch?v=o0RofQE2XOU

Video vom 02.05. : https://www.youtube.com/watch?v=v2KtxvZnb4c

**Comment by TeubyDE** [comment]
Also das siehst schon gerade beim ersten Video sehr nach einem lokalen Thema aus.
Mal schauen was unser QA da rausfindet ;)

**Comment by TheOutburst** [comment]
Kein lokales Problem, Animation Flag war von uns aus suboptimal gewählt. Next update fixed
