### ISSUE TITLE
Farbreset bei Fahrzeugen

### ISSUE THREAD

**Issue by SHaagmann** [eiksch/statev_v2_issues#2887]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Andrew Lucas
**Auftrittszeitpunkt (Datum / Uhrzeit)**

ca. 19:27
**Beobachtetes Verhalten**

Die Primärfarbe des Bikes hat sich von Schwarz auf das Standard Grau geändert
**Erwartetes Verhalten**

Sollte nicht so sein
**Schritte um den Fehler nachvollziehen zu können**

Bis jetzt keine Ahnung aber schon 2x vorgekommen bei unterschiedlichen Bikes (Mit der gleichen Lackierung)
**Optional: Video / Bilder des Fehlers**

![image](https://user-images.githubusercontent.com/58612983/235740028-c43f2b88-c5cb-4ceb-a929-4025182e699b.png)
https://streamable.com/a1s9mw

**Comment by simplycach** [comment]
Ist Fehler erneut wieder aufgetreten ?

**Comment by SHaagmann** [comment]
Ist bis jetzt nicht mehr aufgetreten, falls es doch nochmal passiert und ich merke, dass es aktiv Reproduzierbar ist mache ich nen neuen eintrag
