### ISSUE TITLE
Jugular verhältnismäßig zu langsam

### ISSUE THREAD

**Issue by GymKong** [eiksch/statev_v2_issues#2889]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Travis Edwards

Travis Edwards
**Auftrittszeitpunkt (Datum / Uhrzeit)**
All Time
**Beobachtetes Verhalten**
Möchte gerne über diesen Weg ein Feedback bzw. eine Anregung bzgl. der Geschwindigkeit vom Jugular anmerken. Es gibt vergleichbare Fahrzeuge in der Preisklasse(ebenfalls mit 4 Türen), die tatsächlich schneller sind als der Jugular. Ebenso, gibt es Fahrzeuge, die sogar weniger kosten aber ebenso 4 Türen besitzen und eine höher Geschwindigkeit aufweisen. Als ich den Jugular gekauft und zum ersten mal gefahren bin, war ich tatsächlich sehr geschockt, dass dieser so langsam ist für ein Kaufpreis von 148k. 

Bsp. Komoda/Sultan Classic bieten für 110k mehr Tuningmöglichkeiten, Beschleunigung als auch Endgeschwindigkeit.

**Erwartetes Verhalten**
Schnelle Beschleunigung, als auch Endgeschwindigkeit für den Jugular.

**Schritte um den Fehler nachvollziehen zu können**
Ausprobieren.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1440p

**Optional: Video / Bilder des Fehlers**

**Comment by PlayInc89** [comment]
Da hab ich mal eine Frage muss der Preis immer die Geschwindigkeit angeben ?

**Comment by Dean-Gallagher** [comment]
Der Jugular war noch nie der schnellste von allen 4 Türern, er war schon immer einer der schlechtesten hat dafür aber andere vorteile im direkt vergleich wo die anderen halt schlechter sind.

**Comment by GymKong** [comment]
@Dean-Gallagher 
Welche Vorteile kannst du da nennen?

**Comment by Dasak0** [comment]
Ja stimme dir teils zu. Zwar wie schon gesagt ist Geld nicht gleich Geschwindigkeit aber manche Fahrzeuge sind vielleicht etwas zu schnell, manche zu langsam. Gibt Supersportler die 300k Kosten auf highperformance ausgelegt sind und von viersitzer abgezogen werden. Das Verhältnis stimmt nicht mehr ganz.

Ist nur die Frage ist der Jugular zu langsam oder die anderen zu schnell

**Comment by SatyriaDine** [comment]
Zum Thema Jugular kann ich euch von meinem Jugular berichten, der zieht auf gerader Strecke mit Bodenwellen in der Stadt easy seine 260-270. Würde da nun dran rumgeschraubt werden würde der jenseits der 300 fahren, denke nicht dass das so gewollt ist. 

Ich bin ganz klar der Meinung der Jugular ist so wie er ist schon gut so.

**Comment by TheOutburst** [comment]
#85
Das Auto wurd seitdem von unserer Seite nicht angepasst.
Wir haben aber zwischenzeitlucg circa. 19 Faktoren was Fahrzeughandling & Geschwindigkeit beeinflusst, die ich hier nicht weiter offenlegen werde.
Ob zwischenzeitliche Alt:V oder GTA:O Updates was am Jugular verändert haben können wir wie immer nicht bei der Masse an Fahrzeuge hinwegblickend final sagen, aber das Ergebnis regt bei uns nicht zu Handlungsbedarf an.
