### ISSUE TITLE
AltV UI verrutscht nach oben und bleibt oben bei Aufruf einer Webseite im StateNet

### ISSUE THREAD

**Issue by shoxmox** [eiksch/statev_v2_issues#2890]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Char: Antonio Knauff

04.05.2023 21:45

AltV UI rutscht nach oben hin weg wenn ich auf die Webseite der MexScur Sicherheitsfirma auf Seite zwei des Tablets klicke und dann auf die Navigationsreiter "About" oder "Karriere" gehe.
Das UI ist dann kaum mehr zu bedienen (X-Menu).
UI kann irgendwie mit dem Funkgerät teilweise wieder in die richtige Position geholt werden bei mehrmaligem Aufrufen.

Sollte nicht passieren.

siehe oben

Auflösung 1440p

Video kann ich bei Wunsch anhängen/erstellen

**Comment by KingMarcel** [comment]
Hey @shoxmox, kannst du bitte das Video dazu anhängen?

**Comment by Daniel-Meister-508** [comment]
Hallo zusammen,

das passiert auch bei andren Webseiten.
hier ein Clip dazu
https://youtu.be/Ku506_4qJQ4

**Comment by shoxmox** [comment]
Danke dir für das Video.
Ebenfalls reproduzierbar bspw. mit dem Lotto Hotel auf "Jetzt teilnehmen" klicken

**Comment by EricForster** [comment]
Hallo zusammen,

wenn ich auf die Seiten gehe passiert dort gar nichts.
https://www.canva.com/design/DAFiRbnmhyc/PWgnPquAslKibnFAxTDt4Q/watch?utm_content=DAFiRbnmhyc&utm_campaign=celebratory_first_publish&utm_medium=link&utm_source=celebratory_first_publish

**Comment by EricForster** [comment]
Gerad nochmal mit Funkgerät getestet erst dann kommt das mit dem verschieben der UI.
Sobald man "U" drückt dann das Inventar und das Funkgerät ins Inventar legt ist alles wieder normal.

Vllt hilft das weiter.
