### ISSUE TITLE
Ausstempeln im SAMS

### ISSUE THREAD

**Issue by Kruemel93** [eiksch/statev_v2_issues#2892]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Penelope Perez**

Wollte außer Dienst gehen allerdings kam jedesmal die Meldung "Bitte nimm deine Waffe aus der Hand!"

**07.05.2023 21:00 Uhr**

**Beobachtetes Verhalten**

**Erwartetes Verhalten**

Das man sich ganz normal ausstempeln kann da ich keinerlei Waffe in der Handy hatte, weder Tablett noch Telefon und auch alles aus dem Inventar slots heraus genommen habe.

**Schritte um den Fehler nachvollziehen zu können**

War im SAMS im Dienst wollte mich ausstempeln in der Umkleide dann kam sie Meldung "Bitte nimm die Waffe aus deiner Hand!". Nur nach reloggen konnte ich mich dann erst ausstemeln.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![ausstemplen](https://user-images.githubusercontent.com/132847171/236697933-a5ee809a-b00c-4dfa-81bc-eb6ab238612b.png)

**Comment by simplycach** [comment]
Hattest du vorher eine Waffe ausgerüstet, bzw. eine Signalfacke oder einen Ball geworfen etc. ?

**Comment by Kruemel93** [comment]
Nein hatte ich nicht, was mir aufgefallen ist hab eine Zigarette immer noch in der Hand nach dem Rauchen von den Redwood Zigaretten und das so lange ich nicht relogge.
![Zigarette](https://user-images.githubusercontent.com/132847171/236700292-bd5ba9a8-3ed3-4b0a-a252-3be334318b62.png)

**Comment by simplycach** [comment]
Nach dem Relogg war die Zigarette dann weg und du konntest dich ausstempeln ohne Probleme ?

**Comment by Kruemel93** [comment]
Ja genau. Selbst durch Animation beenden ging es nicht sondern nur durch reloggen.
