### ISSUE TITLE
Haus ausgang falsch gesetzt

### ISSUE THREAD

**Issue by Persistence123** [eiksch/statev_v2_issues#2895]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Anton_Pers
**Auftrittszeitpunkt (Datum / Uhrzeit)**
13.5.23 17:40

**Beobachtetes Verhalten**
Hausausgang ist falsch

**Erwartetes Verhalten**
Ich gehe in das Haus hinen und komme auch dann da wieder raus wo ich reingegangen bin

**Schritte um den Fehler nachvollziehen zu können**
in das Haus reingehen und wieder rausgehen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
WQHD

**Optional: Video / Bilder des Fehlers**
https://medal.tv/de/games/gta-v/clips/197NRMZaU0UFnG/QcuSBk245rFI?invite=cr-MSxSbE8sLA

**Comment by TheOutburst** [comment]
Lass mich raten: du kannst in das Hotel wo du raus kommst auch wieder rein laufen und hast auch in beiden das gleiche Inventar?
@Persistence123

**Comment by Persistence123** [comment]
ja genau

**Comment by Persistence123** [comment]
also ich miete  1 wohnung kriege aber 2 wohnungen auch wenn man dann vorne guckt an den punkt wo man alle wohnungen sieht steht das ich 2 miete

**Comment by TheOutburst** [comment]
Die 2. Wohnung ist dann mitm nächsten Update auch tatsächlich ne eigene Wohnung
