### ISSUE TITLE
Pounder hat keine Werbung mehr an den Seiten

### ISSUE THREAD

**Issue by M4c-M4ni4c** [eiksch/statev_v2_issues#2896]
**Character Name**
Ronny Mcleod

**Auftrittszeitpunkt (Datum / Uhrzeit)**
13.05.2023 ca.18uhr

**Beobachtetes Verhalten**
Der normale Pounder hat keine Werbung an den Seiten mehr(man kann ins innere schauen und sieht dann die rückwand von der anderen seite)

**Erwartetes Verhalten**
Das der Pounder die Werbung dran hat wie vorher.

**Schritte um den Fehler nachvollziehen zu können**
Normalen Pounder ausparken

**Optional: Video / Bilder des Fehlers**
![image](https://github.com/eiksch/statev_v2_issues/assets/52389841/b287cfd5-6c7b-4499-875c-9093b32a3926)

![image](https://github.com/eiksch/statev_v2_issues/assets/52389841/ad0d49b9-92b9-4e03-bbba-2656d4525858)

**Comment by PlayInc89** [comment]
Ein und wieder Ausparken oder es wurde über das Extra Menü entfernt.

**Comment by M4c-M4ni4c** [comment]
ein und ausparken hatte nicht geholfen, ich guck mal wenn ich den wieder bei mir hab ob da was in den extras drin ist^^

**Comment by PlayInc89** [comment]
Ich hab jetzt nochmal bei uns auf dem Dev Server nachgeschaut das liegt definitiv an den Extras. Hat man kein Extra verbaut hat man auch keine Wand an dem Kasten.

**Comment by Dean-Gallagher** [comment]
Nein das ist ein Tuning teil, es wird eine Folierung aufgebracht die aussieht wie der innenraum. kein bug ^^
