### ISSUE TITLE
Außentische Redneck können nicht bedient werden.

### ISSUE THREAD

**Issue by badshah23** [eiksch/statev_v2_issues#2897]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Yuri Greene
**Auftrittszeitpunkt (Datum / Uhrzeit)**

14.05.2023 9:39
**Beobachtetes Verhalten**

auch wenn man eingestempelt ist, wird wenn jemand an den Tischen am Bus sitzt das normale Menü geöffnet zum sofortbestellen. Es wird keine "Klingel" ausgelöst. Wenn ich mich aber eingestempelt selber an den Tisch setzte und "klingel" dann wird es mir links angezeigt das jemand die Bedienung gerufen hat.

**Erwartetes Verhalten**

es sollte immer die Bedienung "gerufen" werden

**Schritte um den Fehler nachvollziehen zu können**

Eingestempelt im Restaurant warten und ein Gast setzt sich an die Aussentische und "klingelt"

**Comment by simplycach** [comment]
Ich habe es gerade mal getestet und bei mir funktioniert es ohne Probleme. Hast du eventuell ein Video für uns ?

**Comment by badshah23** [comment]
Nein hab ich nicht. Also wenn man am Bus steht dann ist alles IO und man bekommt die Mitteilung. Wenn man am Restaurant oder im steht dann geht beim Gast das Sofortmenü auf.

**Comment by simplycach** [comment]
Alles klar wir schauen uns das mal an.

**Comment by CaleighRhodes** [comment]
@simplycach  das muss aber was mit dem Update von gestern zu tun haben, als wir Freitag Abend als Gäste im Redneck waren, saßen wir im Bus, die Bedienung stand gegenüber am Restauranteingang und wir haben das Bestellmenü bekommen. Vielleich so als Hinweis.

**Comment by CoreForceee** [comment]
Es ist auch beim aktuellen Zeitpunkt (18-22 Uhr) Wenn jemand dort Essen möchte und jmd im Dienst ist und sich dieser gerade im Restaurant befindet, können sie während dieser Uhrzeit ohne Kellner essen^^ da das Menü sofort aufklappt
