### ISSUE TITLE
Problem mit den SAPD Coquette's

### ISSUE THREAD

**Issue by MaCaR23** [eiksch/statev_v2_issues#2898]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Harami Hawsawi

**Auftrittszeitpunkt (Datum / Uhrzeit)**
16.05.2023 ca. 20:30 Uhr

**Beobachtetes Verhalten**
Die Coquettes werden im MRPD mit zu viel Schwung gespawned zb. im Davis PD läuft es ganz anders ab. Durch diesen Schwung werden die Fahrzeuge stark beeinflusst, dabei werden sie erstens Beschädigt, was bei Einsatzbedingten Fahrzeugen welche eher weniger auf der Straße sind schon enorm whack ist und zweitens das Fahrverhalten macht die Coquettes deutlich anfälliger für Bunnyhops & ggf. Überschläge.

**Erwartetes Verhalten**
Spawnverhalten wie im Davis PD, reibungslos und ohne den schadensfrohen Schwung

**Schritte um den Fehler nachvollziehen zu können**
Die Coquette in der MRPD Garage spawnen, kann vllt 3,4 Anläufe brauchen bis der Schaden entsteht , anschließend etwas rumfahren und das ganze Prozedere zum Vergleich im Davis PD wiederholen

**Comment by simplycach** [comment]
Hast du eventuell ein Video davon ?

**Comment by MaCaR23** [comment]
Hab kein Video gemacht, kann es aber nochmal nachholen

**Comment by simplycach** [comment]
Ich guck mir das mal an, wenn ich es dringend brauche melde ich mich ;)

**Comment by simplycach** [comment]
Mit dem nächsten Update fixed.
