### ISSUE TITLE
Zusammenführen von Be-/Entladepunkt

### ISSUE THREAD

**Issue by FoxXxyLive** [eiksch/statev_v2_issues#2899]
Wie auf dem Bildern zu sehen, würde ich mich freuen, wenn man die Be-/Entlade Punkte verschieben könnte, sodass wir mit dem Firmenkomplex nur einen be und entladepunkt hätten.

Ort:
Red Desert Ave. Postcode:5016/5175

Bild:er:
![Screenshot_23](https://github.com/eiksch/statev_v2_issues/assets/79162546/5a7add9a-14d6-45fe-8272-a49b5a6916db)
![Screenshot_26](https://
![Screenshot_25](https://github.com/eiksch/statev_v2_issues/assets/79162546/f8fae69b-f277-438a-b289-2f84e951eb3f)
github.com
![Screenshot_28](https://github.com/eiksch/statev_v2_issues/assets/79162546/beb52760-894a-4b14-8401-c3196dcd6532)
![Screenshot_27](https://github.com/eiksch/statev_v2_issues/assets/79162546/556f1517-d588-4a83-85a9-7e1df7fb5ea4)
/eiksch/statev_v2_issues/assets/79162546/c917f683-10cb-4c9d-9b4f-35a1faf7f759)

Toll wäre es, wenn alle 4 Punkte zusammen nach oben (Screenshot 25) oder nach unten (Screenshot 27) gesetzt werden könnten. 

Vorteile dabei wären die Entlastung beim rangieren, da man schon häufiger mal hängenbleiben und so die Fahrzeuge beschädigen kann, weniger Behinderung des Verkehrs für schnellere be und entladung, da auch das PD vermehrt da durch fährt, wenn Sie auf Streife sind oder eine Verfolgungsjagd haben, auch da das Bahama Mamas genau gegenüber liegt kann es schonmal zu starkem Verkehr und starken Menschenmassen kommen. 
So könnte man Unfälle und auch Gamecrashes/ starke desyncs vermeiden.

Danke.

**Comment by TheOutburst** [comment]
Nein, sowas machen wir nichtmehr, alleine aus dem RP Gedannken.

**Comment by FoxXxyLive** [comment]
Wie meinst du aus dem RP Gedanken?

**Comment by FoxXxyLive** [comment]
Wir haben ja die Firmen vom Staat abgekauft für 1,7 Millionen, also würde es ja rein RP technisch Sinn ergeben, dass das "Bauamt" zum Beispiel die Abladepunkte verlegt oder nicht?
