### ISSUE TITLE
Md Cafe Müll Bug

### ISSUE THREAD

**Issue by Gamer99LL** [eiksch/statev_v2_issues#2900]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Janis wasser**
 Janis wasser

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**

Man kann bei dem Md cafe die Tablets nicht wegräumen 
**Erwartetes Verhalten**

man sollte mit . das aufheben und ins inventar bekommen 
**Schritte um den Fehler nachvollziehen zu können**

Was beim md essen ( hinsetzten und bestellen)
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by TheOutburst** [comment]
next update fixed

**Comment by Gamer99LL** [comment]
Guten abend das problem wurde leider nicht behoben nach dem update kann ich immer noch nicht das besteckt aka die tablets aufheben

**Comment by Gamer99LL** [comment]
Also ich kann sie nicht aufheben nach mehren versuchen also man steht vom tisch auf dann laufe ich zb als kellner dahin und kann sie nicht entfernen wenn man selbst sitzt kann man sie aufheben aber auch nur wenn man es bestellt hat und es direkt aufhebt
