### ISSUE TITLE
Garage hinzufügen + Objekte entfernen - Westmirror Drive 21

### ISSUE THREAD

**Issue by Knippsa** [eiksch/statev_v2_issues#2901]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Kalle_Knutsen**

**Ich würde das o.g. Haus gerne erwerben. Wäre es bitte möglich beim Haus Westmirror Drive 21 eine Garage oben auf der Auffahrt hinzuzufügen? Denke die Auffahrt ist dafür optimal und für den Kaufpreis auch gerechtfertigt. Außerdem wäre es gut, wenn dann das Sales Schild entfernt wird und die Sitzecke auf der Veranda ebenfalls, da diese lose ist.**

**https://pic.statev.de/i/H6h2zV.jpg)**

**Comment by Knippsa** [comment]
Nein, ohne Garage finde ich das dann einfach zu teuer. Daher würde ich es nur kaufen, wenn ich wüsste, dass eine Garage möglich ist.

**Comment by simplycach** [comment]
Habe das mal weiter gegeben.

**Comment by Knippsa** [comment]
Danke

**Comment by TheOutburst** [comment]
Garage kriegen wir hin
Sales Schild kommt weg
Sitzecke geht nur der Tisch weg, da man sich auf die Sitze mit Y setzen kann

**Comment by Knippsa** [comment]
okay machen wir so TheOutburst :) Danke.

**Comment by Knippsa** [comment]
Haus ist gekauft
