### ISSUE TITLE
Be- und Entladepunkt Verlegung

### ISSUE THREAD

**Issue by xXCoCoNuTx3** [eiksch/statev_v2_issues#2902]
Character Name; Vivien Ortega

Be- und Entladepunkt Verlegung
https://pic.statev.de/image/beundentladepunkt.H6vMo2

Erwartetes Verhalten
Bitte den Punkt Verlegen laut Bild.

PLZ: 5044 (Links)
Movie Star Way / San Andreas Avenue
Blvd. Del Perro 50
Firmenhash | pfEveMorningwoodRew_23
(Den für das Lager aber auf dem alten Punkt lassen) 

Optional: Video / Bilder des Fehlers
https://pic.statev.de/image/beundentladepunkt.H6vMo2

**Comment by TheOutburst** [comment]
Sicher, dass der Firmenhash pfEveMorningwoodRew_23 und nicht pfGroupAllRew_94 ist?
@xXCoCoNuTx3

**Comment by xXCoCoNuTx3** [comment]
Huch Sorry ja ist pfGroupAllRew_94

**Comment by TheOutburst** [comment]
ich glaube zwar du wirst mit der Position nicht glücklich werden weil vorne und hinten Verkehrsschilder sind, aber der Punkt ist dann next update angepasst
