### ISSUE TITLE
Anzeuge Bug beim Tanken

### ISSUE THREAD

**Issue by SHaagmann** [eiksch/statev_v2_issues#2905]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Andrew Lucas
**Auftrittszeitpunkt (Datum / Uhrzeit)**

21.05 15:00 aber eig schon seit längerer Zeit
**Beobachtetes Verhalten**

Wenn man Exakt 10L Tankt werden 100L angezeigt im UI
**Erwartetes Verhalten**

Es werden die 10L angezeigt
**Schritte um den Fehler nachvollziehen zu können**

10L Tanken
**Optional: Video / Bilder des Fehlers**

![image](https://github.com/eiksch/statev_v2_issues/assets/58612983/6322d662-b520-453f-940b-d8c4340643e9)

**Comment by simplycach** [comment]
Konnte ich bisher nicht nachstellen, wenn der Fehler nochmal auftritt bitte nochmal in den Bugtracker schreiben. Eventuell mit einem Video.

**Comment by SHaagmann** [comment]
Ist schon seit Ewigkeiten und schon zig Male aufgetreten musst halt genau 10L tanken

**Comment by SHaagmann** [comment]
![image](https://github.com/eiksch/statev_v2_issues/assets/58612983/741e1b43-2dcd-4d17-8f50-5737fca72b1f)
Gerade nocheinmal nachgestellt. Beim nachstellen am besten min 10,1 L aus dem tank raushaben damit auch genau 10 getankt werden (Shadow Play war irgendwie aus Video kann ich dir reinschicken wenn es beim nächsten mal natürlich passier)

**Comment by SHaagmann** [comment]
Ok konnte es gerade nachstellen mit Video: https://streamable.com/ibxlo5
