### ISSUE TITLE
Unsichtbares Objekt auf der Straße

### ISSUE THREAD

**Issue by Dean-Gallagher** [eiksch/statev_v2_issues#2906]
Unsichtbares Objekt. Hat Hibox, sieh Bild mit Buffalo S hinten Rechts. Location im 2. Screen
Du fahren drüber, Auto machen so, Unfall 

Aktuell abgesperrt von uns. 

https://pic.statev.de/i/H62DQA.jpg
https://pic.statev.de/i/H625nU.jpg

**Comment by PlayInc89** [comment]
https://i.imgur.com/LPc6kwZ.png

Ist von GTA selbst kann man also nix machen.
