### ISSUE TITLE
Friseur Zeiten

### ISSUE THREAD

**Issue by AndoMalius** [eiksch/statev_v2_issues#2908]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Eddie Trumbull

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer

**Beobachtetes Verhalten**
Zeiten beim Friseur sind deutlich zu lange, bei mir war es Färben mit Bart schneiden, Dauer 45min. Dauert länger als im Reallife, mir und auch dem Ausführenden ging dann nach 30min doch etwas die Luft aus und es fehlt auch schwer über die Dauer das RP so in die länge zu ziehen.

**Erwartetes Verhalten**
Zeiten gehören deutlich verkürzt

**Schritte um den Fehler nachvollziehen zu können**
Haare schneiden lassen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by CaleighRhodes** [comment]
Also im Reallife musste die Farbe auch mindestens 30 Minuten einwirken lassen... 😉

**Comment by AndoMalius** [comment]
Dann sie es halt im vergleich zu Fahrzeug Reparaturen oder Tattos, nen Fahrzeug mit Totalschaden haste in 5min repariert und nen Tattoo haste auch in 10min. Da ist die Dauer beim Friseur schon krass hoch.

**Comment by PlayInc89** [comment]
Da es sich hier um keinen Bug handelt werde ich das Thema schließen. Bitte schreibe dein Anliegen doch ins Forum.
