### ISSUE TITLE
Beantragung einer Garage

### ISSUE THREAD

**Issue by Smaty86** [eiksch/statev_v2_issues#2909]
## WICHTIGE INFORMATION!!:

Hallo, 

ich würde gerne für mein Haus (house_MirrorPark_13) eine Garage beantragen. Ich würde mich sehr über eine positive Entscheidung freuen. 

<img src=https://pic.statev.de/i/H6MboI.png>

Hier ein Beispiel eines anderen Hauses der Nachbarschaft 

<img src=https://pic.statev.de/i/H6MApq.png>

Danke für eure Mühe 

Liebe Grüße 

Tim Rock

**Comment by TheOutburst** [comment]
jup, next update ists drin
