### ISSUE TITLE
Bitte um das entfernen eines  Zaunes 

### ISSUE THREAD

**Issue by kabelstapel** [eiksch/statev_v2_issues#2911]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Jason Bean  
haus  KryptRangoRew_House_1
          Roy Lowenstein Blvd. 33b
**Auftrittszeitpunkt (Datum / Uhrzeit)**

26,05,23
**Beobachtetes Verhalten**

ich habe an meinem Haus einen weisen Zaun über den ich immer klettern muss wenn ich in meinen garten gehen möchte .als ich heute Ausversehen mit ein wenig zu viel Eifer in die auffahrt gehfahren bin habe ich gesehen das der zAun auch kaputt gehen kann .
**Erwartetes Verhalten**

ich würde mir wünschen das der weise zaun entfernt wird so das ich ohne probleme und kletter einlagen in meinen garten komme
**Schritte um den Fehler nachvollziehen zu können**

zaun entfernen 
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Screenshot 2023-05-26 220202](https://github.com/eiksch/statev_v2_issues/assets/133334452/fd85e00b-2f8b-460d-85b8-75f974832eb3)
![Screenshot 2023-05-26 220128](https://github.com/eiksch/statev_v2_issues/assets/133334452/ea641bf1-bdad-4809-ad06-a00e42a4cfa0)

**Comment by TheOutburst** [comment]
jup, die gehen weg
da ein Zauntoor alleine dumm aussiehst haste next update nen breiten Durchgang zum Garten
