### ISSUE TITLE
Bitte um Entfernung von Gegenständen 

### ISSUE THREAD

**Issue by Wayne1705** [eiksch/statev_v2_issues#2912]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Norbert Frisch
Haushas : SandyShores17
Haus: Mariana Drive 17

**Auftrittszeitpunkt (Datum / Uhrzeit)**
27.05.2023

**Beobachtetes Verhalten**
Auf der Dachterasse stehen 2 Stühle , Tisch mit Radio . Meine Frage ist kann man die 4 Sachen Entfernen ? Da man so nicht viel auf der Dachterasse  machen kann .
![Bild_2023-05-27_225840123](https://github.com/eiksch/statev_v2_issues/assets/134811010/011031d5-2fb5-4910-8f97-9d5c444cff88)

**Comment by Wayne1705** [comment]
Grüße könntest ja mal Porbieren ob der radio weg geht wenn nicht muss du es halt so lassen danke für die info

**Comment by TheOutburst** [comment]
Tisch + Radio ist next update wech, Stühle müssen wie gesagt leider bleiben
