### ISSUE TITLE
Bilder von StatePic laden bei Lifeinvader nicht

### ISSUE THREAD

**Issue by Bonnie-Barrow** [eiksch/statev_v2_issues#2913]
Bonnie Barrow
Justin Gering

Auftrittszeitpunkt (Datum / Uhrzeit)
erstmals am 08.05

**Beobachtetes Verhalten**
Bilder werden wie gewohnt auf StatePic hochgeladen. Der Link wird dann bei Social eingetragen. 
Beim Eintragen erscheinen dann wie gewöhnlich drei Ladepunkte, die dann aber auch wieder sofort verschwinden.
Weder bei der Vorschau, noch beim Post selbst wird das Bild dann angezeigt.

Das Problem tritt mit neuen Bildern auf, aber auch beim erneuten Hochladen der Flyer, die in der Vergangenheit jedoch funktioniert haben. Generell laden alle Bilder nicht, die nach dem 08.05 hochgeladen wurden.

Beispiele:
Neues Bild / geht nicht: https://pic.statev.de/image/98y0u.H6a1x2
Flyer, der erneut hochgeladen wurde / geht nicht: https://pic.statev.de/image/2000er.H6aE8A
Flyer, der vor dem 08.05 hochgeladen wurde / geht: https://pic.statev.de/image/black-and-white.c06Nk

**Erwartetes Verhalten**
Bilder sollten auf Social sichtbar sein

**Comment by simplycach** [comment]
Also ich habe das mal ebend mit deinen Links ausprobiert immer Original - URL verwendet und es ging problemlos, wenn es bei dir weiterhin nicht klappen sollte, setzten wir uns mal zusammen ;)

**Comment by simplycach** [comment]
Problem besteht weiterhin mit PNG Bildern.

**Comment by KingMarcel** [comment]
Alle 3 Bilder lassen sich nutzen, wenn man folgendes, wie im social Placeholder zu sehen
https://gyazo.com/ba0e3fdd5ec87b1bf5564471804ddd13
nutzt:

https://pic.statev.de/image/98y0u.H6a1x2  => H6a1x2 oder https://pic.statev.de/i/H6a1x2
https://pic.statev.de/image/2000er.H6aE8A => H6aE8A oder https://pic.statev.de/i/H6aE8A 
https://pic.statev.de/image/black-and-white.c06Nk => c06Nk oder https://pic.statev.de/i/c06Nk

**Comment by KingMarcel** [comment]
Hab das System noch angepasst, dass die 6 Stelligen Bilder links auch funktionieren.
Bedeutet, z.B. https://pic.statev.de/image/98y0u.H6a1x2 oder 98y0u.H6a1x2 ist nun auch ein gültiges Bild
@Bonnie-Barrow
