### ISSUE TITLE
Animation bei Farb Dosen falsch/anders

### ISSUE THREAD

**Issue by M4c-M4ni4c** [eiksch/statev_v2_issues#2914]
**Character Name**
Ronny Mcleod

**Auftrittszeitpunkt (Datum / Uhrzeit)**
30.05.2023

**Beobachtetes Verhalten**
Animation bei Dosen sind seit letztem Update anders/falsch

**Erwartetes Verhalten**
Die alte Animation wieder wie sie vor dem Update war(Siehe Bild)

**Schritte um den Fehler nachvollziehen zu können**
Dose nehmen und Rechtsklick darauf machen um sie in die Hand zu nehmen(Animation auszuführen)

**Optional: Video / Bilder des Fehlers**
![image](https://github.com/eiksch/statev_v2_issues/assets/52389841/56880270-f0a0-4aee-a749-19f81a2c6267)

**Comment by M4c-M4ni4c** [comment]
ist genauso beim Putzlappen auch dort ist diese komische animation drin

**Comment by TheOutburst** [comment]
Notiz an mich: Flag prüfen
