### ISSUE TITLE
Hausgarage West Mirror Dr. 6

### ISSUE THREAD

**Issue by Jann7k** [eiksch/statev_v2_issues#2915]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Zane Walker**

**Unbekannt - öfters in der Vergangenheit**

**Fahrzeug buggt beim Ausparken in Garagentor und wird beschädigt**

**Fahrzeug wird aus Garage ausgeparkt und steht in der Einfahrt**

**Caracara in Hausgarage West Mirror Dr. 6 einparken und im Anschluss ausparken**

**1920x1080**

**Optional: Video / Bilder des Fehlers**

**Comment by PlayInc89** [comment]
Hast du nen Video oder Bilder ?

**Comment by TheOutburst** [comment]
Adresse ist next update fixed
Garagenpunkt 2 Meter nach vorne gezogen

**Comment by Jann7k** [comment]
War auf der Arbeit, konnte deswegen jetzt erst gucken, hast es aber scheinbar schon. Ich bedanke mich :)
