### ISSUE TITLE
Lackieranimation hat sich geändert

### ISSUE THREAD

**Issue by Erumeldor** [eiksch/statev_v2_issues#2917]
**Character Name**
Satoru Tsuyoshi, aber unerheblich

**Beobachtetes Verhalten**
Die Animation wenn man eine Lackdose anklickt hat sich geändert. 
Die neue ist eigentlich nicht mehr verwendbar, weil sie einfach scheiße aussieht.

**Erwartetes Verhalten**
Alte Animation (in der Hocke sitzend was lackieren) wieder zurück.
Es gibt noch die separaten Animationen "Spraydose" und "Spraydose (schütteln)", die sind auch gut. Die "Spraydose" ist aber komplett im stehen und daher nur für große Fahrzeuge geeignet. Das "Spraydose (schütteln)" ist dann cool um sich zu bewegen.
Aber das in der Hocke (das alte anklicken) war praktisch für PKW lackieren.

**Schritte um den Fehler nachvollziehen zu können**
Lackdose anklicken und nicht lachen ;)

**Optional: Video / Bilder des Fehlers**
![image](https://github.com/eiksch/statev_v2_issues/assets/21212905/cf9bb9b6-f6fd-4624-948f-0d2c0c1b2160)
![image](https://github.com/eiksch/statev_v2_issues/assets/21212905/8b60dcd1-bce6-4231-922c-80098e077050)

**Comment by SHaagmann** [comment]
Duplikat von: #2914 

Also das ist nichtmal nen uralter Antrag also kurz reinschauen siehste direkt...

**Comment by Erumeldor** [comment]
Hmm, mein Fehler. Hab nach Lack, Lackieren, etc. gesucht 👼
