### ISSUE TITLE
Service ändert Xenon-Farbe

### ISSUE THREAD

**Issue by CaleighRhodes** [eiksch/statev_v2_issues#2918]
**Character Name**
Caleigh Rhodes, Wothor Akori, Ulli Schwadulek

**Auftrittszeitpunkt (Datum / Uhrzeit)**
02.06.2023 / ca. 22:30 Uhr

**Beobachtetes Verhalten**
Sultan RS ausgelesen, Ölfilter als Fehler bekommen. Ölfilter getauscht. Auf einmal hatte das Fahrzeug nach Beendigung des Vorgangs nicht mehr, wie vorher, Serien-Xenons sondern orangefarbene ( Angry - 7 ). Die Xenons sind somit von Serie auf den letztmöglichen Slot gesprungen. Kurios dabei war, dass wir keine Xenon-Bauteile im Lager hatten, um genau solche Bugs zu vermeiden.

**Erwartetes Verhalten**
Kein Wechsel der Xenon-Farbe bei Service-Arbeiten.

**Comment by simplycach** [comment]
Auto mal wieder eingeparkt, sind die richtigen dann wieder vorhanden ?

**Comment by CaleighRhodes** [comment]
Ja, hatten wir über das Werkstattmenü gemacht, da große Werkstatt. Blieb gleich. Auch im Autohaus beim Ein- und Ausparken blieben sie gleich.
Allerdings sagte mir jemand anders, dass das manchmal ne Weile dauert und sie sich dann selbst zurücksetzen auf die ursprüngliche Farbe.
So lange habe ich es aber nicht ausprobiert und vom Grundsatz her ist es auch was, was es (wenn möglich) zu lösen gilt, weil wie erklär ich dem Mitspieler im RP, dass sich die Xenons irgendwann zurück setzen, wenn sie nach einem Service ne andere Farbe haben... ^^

**Comment by simplycach** [comment]
Wir sind dran, bitte erwarte kein Fix vor V3. 

LG. Simplycach
