### ISSUE TITLE
Telefonat wird beendet am Marktplatz

### ISSUE THREAD

**Issue by CannaDE** [eiksch/statev_v2_issues#2919]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Johannes Kessel

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer, jederzeit reproduzierbar

**Beobachtetes Verhalten**
Sobald man am telefonieren ist und den Marktplatz besucht, im Marktplatz nach einem Artikel mit einem "n" im Namen sucht, beendet der Charakter das derzeitige Telefonat.

**Erwartetes Verhalten**
Das Telefonat sollte dennoch aktiv gehalten werden, auch wenn man ein Item mit einem "n" im Namen sucht.

**Schritte um den Fehler nachvollziehen zu können**
- Marktplatz während des Telefonats öffnen
- Ein Artikel mit "n" suchen, z.b. "verpackteN"
- Der Charakter beendet das aktuelle Telefonat

**Comment by simplycach** [comment]
Bereits bekannt, und es gibt ein aktives Ticket #2877
