### ISSUE TITLE
Antrag auf Versetzung des Entladepunktes und des Eingangs

### ISSUE THREAD

**Issue by nox142** [eiksch/statev_v2_issues#2920]
Name: Jona Lindner
FirmenHash: pfWestVine35

Rote Markierungen: Ich würde gerne den Entladepunkt auf den Hof verlegen, das ist auch der Entladepunkt für das Lager (Mein Eigentum) und die Mühle. Der derzeitige Entladepunkt wird leider regelmäßig von parkenden Fahrzeugen blockiert, da dieser sich direkt auf dem Parkplatz befindet.

Grüne Markierungen: Und wenn es gleichzeitig möglich wäre, würde ich gerne den Eingang eine Tür weiter nach vorne verlegen.

![Screenshot_34](https://github.com/eiksch/statev_v2_issues/assets/79390131/340b7d6d-d7c6-4a5a-a551-fc65f6ea9ee9)

Vielen Dank im vor raus

**Comment by TheOutburst** [comment]
Moin,
Marker von versch Firmen führen wir schon länger nichtmehr zusammen
Ich kann dir den Umladepunkt aber hinter die Firma in die Gasse oder seitlich an den Bürgerseteig setzen, um das Parkproblem zu beheben
![grafik](https://github.com/eiksch/statev_v2_issues/assets/70150675/a2e790fe-a35f-4787-8d1b-f12943089c0d)

**Comment by nox142** [comment]
In der Gasse ist es etwas Eng, daher eher nicht :D
Dann gerne einfach an einen von den beiden Stellen

https://prnt.sc/B5MMD8CGDycH

Ich denke den Punkt nur ein paar Meter weiter setzen wird zu Eng mit der Kreuzung oder?

**Comment by TheOutburst** [comment]
next update
