### ISSUE TITLE
Antrag auf Entfernung der Eisenstange vor dem Greenscreen im Filmstudio

### ISSUE THREAD

**Issue by RoyMckellar** [eiksch/statev_v2_issues#2924]
Im Filmstudio steht vor dem Greenscreen ein Geländer das beim filmen stört.
Kann man das enfernen?

Danke MfG Roy

**Comment by DonVitoDiangelo** [comment]
Kann man bestimmt. Ist notiert und irgendwann bekommen wir das sicherlich hin. Aber rechne jetzt nicht schnellstmöglich damit. :)

**Comment by RoyMckellar** [comment]
Super, ich will mit dem Restaurant in Sandy ein Werbevideo drehen.
Dann werde ich die Tage mal ein paar Statisten suchen.
Danke

Am Sa., 17. Juni 2023 um 07:47 Uhr schrieb DonVitoDiangelo <
***@***.***>:
