### ISSUE TITLE
Aussehen Large Trailer seit dem letzten Alt:V Patch

### ISSUE THREAD

**Issue by SatyriaDine** [eiksch/statev_v2_issues#2925]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Sofia_Black

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit dem letzten Alt:V Update am 15.06.2023

**Beobachtetes Verhalten**
Der normale Large Trailer ist ein blauer Planen-Auflieger und kein grauer Container-Auflieger 

**Erwartetes Verhalten**
Dass der Trailer wieder der graue Container ist

**Schritte um den Fehler nachvollziehen zu können**
Large Trailer ausparken

**Optional: Video / Bilder des Fehlers**
![Screenshot_669](https://github.com/eiksch/statev_v2_issues/assets/84275938/4e740b19-d4df-4113-a3af-730bca174440)

![Screenshot_670](https://github.com/eiksch/statev_v2_issues/assets/84275938/b7f7d03e-5915-47e1-880c-dedc49b61473)

**Comment by CaleighRhodes** [comment]
Ist doch cool, NOSTALGIE! So sah der auch vor StateV V2 aus :D

**Comment by CoreForceee** [comment]
Muss sagen finde diesen Trailer auch schöner wie den anderen :D
Könnte man eig so lassen ;)
