### ISSUE TITLE
Fehlerhafter Spawnpunkt Garage Del Perro 

### ISSUE THREAD

**Issue by FoxXxyLive** [eiksch/statev_v2_issues#2926]
**Auftrittszeitpunkt (Datum / Uhrzeit)**
jedesmal beim Ausparken

**Beobachtetes Verhalten**

sobald man den Pounder Custom bei der Garage in Del Perro ausparkt kippt er auf die Seite und der Motor ist defekt 

**Erwartetes Verhalten**

normales Ausparkverhalten, wie bei anderen Garagen

**Schritte um den Fehler nachvollziehen zu können**

Pounder Custom aus der Garage 21/32 ausparken 

Screenshot: http://prntscr.com/K0YLQB0UZLQ-

**Comment by simplycach** [comment]
Konnte ich bisher nicht so nachstellen, mal bitte beobachten und wenn es nochmal auftritt ggf. mit Video bitte aufnehmen ;)
