### ISSUE TITLE
Spaten beim Ockern

### ISSUE THREAD

**Issue by RoyMckellar** [eiksch/statev_v2_issues#2927]
Ich habe, seit dem der Spaten im Spiel ist mein Ocker wie folgt gefarmt.

Erst habe ich den Spaten in die Hand genommen und dann mit "E" die Aktion beim Ockersammeln gestartet. Ich blieb stehen und die Spatenanimation lief ab. / Sieht halt besser aus und geht nicht so ins Kreuz.

Jetzt ist es so, das wenn ich den Spaten benute und dann "E" drücke geht er mit dem Spaten inkl. Animaton in die Hocke und farmt wie alle anderen auch. Nur eben mit Spaten und Animaton.
Ist das beabsichtigt?

Gewünscht währe es wenn ich weiterhin mit dem Spaten im Stehen arbeiten könnte.

**Comment by PlayInc89** [comment]
![Screenshot_2bg](https://github.com/eiksch/statev_v2_issues/assets/70231715/b9169a71-8e03-45ed-bc17-b6836d9f66b5)

Klappt doch Spaten in die Hand nehmen und dann mit E ocker Abbauen

**Comment by RoyMckellar** [comment]
Hat bei mir nicht geklappt, werde ich gleich mal probieren.

**Comment by RoyMckellar** [comment]
Ich bin der Einzige der das mit dem Spaten macht und jetzt geht es nicht mehr bei mir.
https://youtu.be/OJ_-5-ZjIL0

**Comment by PlayInc89** [comment]
Irgendwelche Grafikmods installiert ?

**Comment by RoyMckellar** [comment]
Ich habe gar nichts an Mods installiert. Ich werde morgen nach
Serverneustart noch mal schauen und dann sag ich Bescheid.
Pandasomnia ***@***.***> schrieb am Sa. 17. Juni 2023 um
17:34:

**Comment by RoyMckellar** [comment]
Ich habe das jetzt noch mal beim Tabakfeld mnit dem Spaten versuch, aber ich gehe immer noch in Hocke. Dann habe ich meinen Cache vom AltV gelöscht und neu heruntergeladen und habe das selbe Problem. Der Roy kommt nicht mehr mit dem Spaten klar und geht immer mit ihm in die Hocke. 

Frage: Sollte ich GTA neu Installieren?
MfG Roy

**Comment by PlayInc89** [comment]
Eher weniger könnte durch das alt:V updatet irgendwas spinnen. Einfach mal bissl Geduld haben.

**Comment by RoyMckellar** [comment]
Es geht wieder! Danke für dieses Projekt

**Comment by PlayInc89** [comment]
Ja Super dann kann ich ja den Beitrag Schließen
