### ISSUE TITLE
Western Company Gargoyle(Race) extrem schnell mit Wheelie

### ISSUE THREAD

**Issue by SirAres** [eiksch/statev_v2_issues#2928]
**Character Name**

Whyte_Hyland 

**Auftrittszeitpunkt (Datum / Uhrzeit)**

16.06.2023 gegen 00:00 Uhr 

**Beobachtetes Verhalten**

Das Motorrad Western Company Gargoyle (Race) wird extrem schnell wenn man einen Wheelie macht.
Die normal Geschwindigkeit beträgt ~210 Km/h. Durch den Wheelie mit den Bodenwellen kann man das 
Motorrad bis zu ~310 Km/h beschleunigen.

**Erwartetes Verhalten**

Dass das Fahrzeug zwar schneller durch den Wheelie wird aber nicht so extrem viel.

**Schritte um den Fehler nachvollziehen zu können**

Man nehme sich eine Western Company Gargoyle (Race) und macht auf dem Highway einen Wheelie und fährt
währenddessen über Bodenwellen.

**Optional: Video / Bilder des Fehlers**

https://www.youtube.com/watch?v=Ea-mmwqxsd0

**Comment by simplycach** [comment]
Dein Video ist Privat gestellt.

**Comment by simplycach** [comment]
> **Character Name**
> 
> Whyte_Hyland
> 
> **Auftrittszeitpunkt (Datum / Uhrzeit)**
> 
> 16.06.2023 gegen 00:00 Uhr
> 
> **Beobachtetes Verhalten**
> 
> Das Motorrad Western Company Gargoyle (Race) wird extrem schnell wenn man einen Wheelie macht. Die normal Geschwindigkeit beträgt ~210 Km/h. Durch den Wheelie mit den Bodenwellen kann man das Motorrad bis zu ~310 Km/h beschleunigen.
> 
> **Erwartetes Verhalten**
> 
> Dass das Fahrzeug zwar schneller durch den Wheelie wird aber nicht so extrem viel.
> 
> **Schritte um den Fehler nachvollziehen zu können**
> 
> Man nehme sich eine Western Company Gargoyle (Race) und macht auf dem Highway einen Wheelie und fährt währenddessen über Bodenwellen.
> 
> **Optional: Video / Bilder des Fehlers**
> 
> https://www.youtube.com/watch?v=Ea-mmwqxsd0

Dein Video ist Privat gestellt. Darüber hinaus ist zu sagen, wenn man die ganze mit dem Bike einen Wheelie fährt gefährdet man das Leben seines Chars schon deutlich. Sprich sehe ich da eher keinen Handlungsbedarf.
