### ISSUE TITLE
Tuning Bug beim Sentinel Classic Widebody

### ISSUE THREAD

**Issue by ReallyTheJerry** [eiksch/statev_v2_issues#2929]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Nathan Barddock**

**22.06.2023 18:20**

**Beim Tuning ist mir aufgefallen das die Komponenten die zu Tunen sind nicht mit der Anzeige übereinstimmen. Als Beispiel wenn ich die Vordere Stoßstange ändern möchte ändert sich die Motorhaube und bei der hinteren Stoßstange die Seiten Schweller. Dabei werden auch die dinge berechnet die im Tuning Register benötigt werden Sprich ich ändere im Register den front Grill angezeigt wird eine neue Stoßstange aber zahle dafür nur die Stoßstange und würde somit Geld sparen**

****

****

****

**Bilder vom Live Tuning**

![Screenshot (207)](https://github.com/eiksch/statev_v2_issues/assets/137430091/61edc189-917b-46cb-82a2-097edeef99db)
![Screenshot (206)](https://github.com/eiksch/statev_v2_issues/assets/137430091/e2f30ea9-a2a0-4c3e-a8a5-69391303b662)
![Screenshot (205)](https://github.com/eiksch/statev_v2_issues/assets/137430091/d3e1cc0f-8ae4-4adc-a244-5e79a1c22c1f)
![Screenshot (204)](https://github.com/eiksch/statev_v2_issues/assets/137430091/3cfad3ce-3614-41d4-a772-b169ad423d34)
![Screenshot (203)](https://github.com/eiksch/statev_v2_issues/assets/137430091/3af43133-c8e4-4591-acfd-bc51e6c86046)
![Screenshot (202)](https://github.com/eiksch/statev_v2_issues/assets/137430091/c96557c7-ef41-4fc4-96ac-7c1e6fe8beb5)

![Screenshot (210)](https://github.com/eiksch/statev_v2_issues/assets/137430091/7df7d3f5-8a24-43cc-822b-adf93a3d856e)
![Screenshot (211)](https://github.com/eiksch/statev_v2_issues/assets/137430091/04e26681-632b-4e94-b7cb-9bd8038aa70b)

**Comment by simplycach** [comment]
Wir sind dran, bitte erwarte kein Fix vor V3. 

LG simplycach
