### ISSUE TITLE
MTL Öltanker verschwunden

### ISSUE THREAD

**Issue by Markado1986** [eiksch/statev_v2_issues#2931]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Carlo Diaz**

**Ende Mai 25.05.-01.06.2023**

**Der von mir gemietete MTL Öltanker, steht mir nicht mehr zur Verfügung. Warum?**

**Er sollte in meinem Besitz sein wie der Bohdi**

**Man findet ihn nicht mehr auf StateV NET unter Fahrzeuge und auch nicht mehr IC im Handy**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Markado1986** [comment]
Ich weis absolut nicht was mit dem ÖL Tanker passiert ist.

**Comment by simplycach** [comment]
Also wenn er jetzt verschwunden ist, hast du dann mal probiert nochmal einen neuen zu mieten ?

**Comment by simplycach** [comment]
Bisher keine Antwort erhalten somit gehe ich von aus, dass sich das Problem erledigt hat. Wenn das Problem weiter besteht, bitte nochmal in den Bugtracker schreiben.
