### ISSUE TITLE
Fehlende Alarmmeldung bei Einbruch

### ISSUE THREAD

**Issue by SauerkirscheJM** [eiksch/statev_v2_issues#2932]
Hallo zusammen,

gestern (27.06.2023) wurde bei meinem Char eingebrochen (um 21 uhr rum oder etwas später)
Azula Rise 
Ineseno Road 57
Haushash: SamsonCountryRew_House_13

Ich war zu der Zeit IC und habe keine Meldung dazu bekommen. Mir wurde jetzt OOC zugetragen, dass das ein Bug ist und man das melden soll.
Deswegen schreibe ich.

Den Einbruch sieht man hier: https://www.twitch.tv/videos/1857292385?t=01h25m04s
Und IC wusste mein Char auch davon, weil Josef mit seiner Freundin Shirin gesprochen hat und ihr bescheid gesagt hat. Zu der Zeit war Azula mit Shirin unterwegs und Shirin hat es Azula gesagt: https://www.twitch.tv/videos/1857292385?t=01h11m16s
Und natürlich war das Haus später dann auch aufgeschlossen, als wir dort waren um das Auto zu tauschen.

Bei Fragen gerne bescheid geben.

Viele Grüße

**Comment by TheOutburst** [comment]
Da ist wer auch immer dir das gesagt hat falsch informiert, das ist kein Bug

**Comment by SauerkirscheJM** [comment]
Hatte im Discord ein Ticket geschrieben und mri wurde gesagt, ich soll es hier psoten ^^"
