### ISSUE TITLE
Hasen Rucksack is verbugt

### ISSUE THREAD

**Issue by StateV2Marie** [eiksch/statev_v2_issues#2933]
Also es geht um den Hasenrucksack [https://pic.statev.de/image/screenshot-2023-07-01-162907.HHaSfD](url)    Wenn man ihn auf setzt sieht man ihn nich mehr und man hat am Hals FIB stehen man sieht es hier. [https://pic.statev.de/image/screenshot-2023-07-01-162742.HHaacV](url)  ich hoffe ihr bekommt es wieder heil mag mein hasen rucksack behalten bitte. Danke im vorraus.

**Comment by simplycach** [comment]
Ich kann die Bilder leider nicht öffnen, kannst du bitte nochmal über die Links schauen :)

**Comment by CaleighRhodes** [comment]
> Ich kann die Bilder leider nicht öffnen, kannst du bitte nochmal über die Links schauen :)

Du musst einfach die Links kopieren und in die Browserzeile einfügen. Kp wie Marie das immer schafft, dass man die Links nie aufrufen kann ^^
