### ISSUE TITLE
Ich kann meinen Walkstyle nicht ändern

### ISSUE THREAD

**Issue by Benny2001-boop** [eiksch/statev_v2_issues#2934]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Uranov Kjmsky

**Auftrittszeitpunkt (Datum / Uhrzeit)**

01.07.2023 / 20:40 Uhr

**Beobachtetes Verhalten**

Ich kann den Gehstil nicht mit der + Taste ändern da diese das gleiche tut wie die #  Taste und zwar das Overlay ausblendet

**Erwartetes Verhalten**

Das ich mit der + Taste meine Gehstil ändern kann

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

Wenn ich beide Tasten drücke blende ich das Overlay aus

**Optional: Video / Bilder des Fehlers**

**Comment by simplycach** [comment]
Geht bei mir ohne Probleme, eventuell mal das Spiel neu starten.

**Comment by Benny2001-boop** [comment]
Geht auch nach mehrfachen neustart nicht. Die Tasteen sind halt mit dem gleichen belegt
