### ISSUE TITLE
Garage von Haus "West Mirror Driver 35" / keine Fahrzeuge oder zu wenig Plätze

### ISSUE THREAD

**Issue by JonesMorgan2020** [eiksch/statev_v2_issues#2937]
Jones Morgan

Auftrittszeitpunkt (Datum / Uhrzeit)
01.07.2023 ~ 17 Uhr

Beobachtetes Verhalten

- Fahrzeuge sind laut Tablet im West Mirror Driver 35 in der Garage aber vor Ort kann keines in der Garage angezeigt werden
- nachdem die Fahrzeuge durch den Support umgeparkt werden **kann man nur noch 5 anstatt 6 Fahrzeuge einparken - es kommt die Meldung Garage voll**

Erwartetes Verhalten
Dass man die Fahrzeuge in der Garage sieht und auch **alle 6 Plätze nutzbar sind**

Schritte um den Fehler nachvollziehen zu können
Fahrzeug einparken

Optional: Video / Bilder des Fehlers
![Fehler Garage 1](https://github.com/eiksch/statev_v2_issues/assets/76733801/66ffba25-4cc6-4d24-8533-8bc4575f7f96)
![Fehler Garage 2](https://github.com/eiksch/statev_v2_issues/assets/76733801/dbb7684a-ad21-47d3-994a-f09647300ce7)

Problem nach Update vom 01.07.2023 / 21 Uhr //nach wie vor vorhanden

**Comment by simplycach** [comment]
Wir benötigen bitte einmal den Haus-Hash

**Comment by JonesMorgan2020** [comment]
GroupAllRew_House_4
Hat aber vorhin (gegen 10 Uhr) als ich es getestet habe funktioniert und ich konnt dann das 6. Fahrzeug ein und auch wieder ausparken

**Comment by TheOutburst** [comment]
Da gabs ne Verschiebung, bitte mit den Kennzeichen in den Support gehen und in eine öffentliche Garage einparken lassen
