### ISSUE TITLE
College Jacket lässt sich nicht auspacken

### ISSUE THREAD

**Issue by ChrisBraun-VIOV** [eiksch/statev_v2_issues#2938]
**Character Name**
Chris Branth

**Auftrittszeitpunkt (Datum / Uhrzeit)**
02.07.2023 14:39

**Beobachtetes Verhalten**
Neue Collegejacke [F] Black-White College Jacket hergestellt, in die Maschine gepackt und im Computer festgestellt, dass ich diese nicht entpacken kann

**Erwartetes Verhalten**
Jacke auspacken können

**Comment by PlayInc89** [comment]
@Enemyaa  @Jaz1441

**Comment by ChrisBraun-VIOV** [comment]
Das gleiche übrigens auch bei den F Black Camo T-Shirts

**Comment by CoreForceee** [comment]
die neuen T-Shirts für die Damen kann man ebenso nicht auspacken (bsp.: [F] Black Happy Moon Tee verpackt, [F] Red Happy Moon Tee verpackt, [F] White Happy Moon Tee verpackt)

grüße

**Comment by ChrisBraun-VIOV** [comment]
Wie ist hier der aktuelle Stand?
