### ISSUE TITLE
house_Vinewood_9: Fahrzeuge laut Tablet in Garage, aber unausparkbar

### ISSUE THREAD

**Issue by Pregon** [eiksch/statev_v2_issues#2939]
Ronny Roberts & Jim Hill

01.07.2023, irgendwann Abends

Jim Hill wollte Fahrzeuge von uns aus der Garage vom House Hash house_Vinewood_9 ausparken, die Fahrzeuge standen jedoch nicht in der Garage zur Verfügung (Autos bereits durch Support ausgeparkt)
Nun stehen noch 2 Fahrzeuge von Ronny Roberts in der Garage (Scorcher und Carbon RS, Kennzeichen "RONBIKE 3"), welche nicht in der Übersicht auftauchen.

Erwartet: Fahrzeuge stehen in der Garage zur Verfügung, wenn diese laut Tablet dort drin stehen.

Auf Bild 2 kann die Sanchez ignoriert werden, wichtig sind dabei die äußeren Fahrzeuge

![image](https://github.com/eiksch/statev_v2_issues/assets/75855042/95ecf6fa-4374-492f-ae1f-8327f7a1aa99)
![image](https://github.com/eiksch/statev_v2_issues/assets/75855042/0854ed88-be10-47ac-8d5d-f55a49a3d01b)

**Comment by PlayInc89** [comment]
In den Support oder Ticket aufmachen müssen in eine Öffentliche Garage eingeparkt werden
