### ISSUE TITLE
Antrag auf Zusammlegung von Entladestellen bzw. Verlegung.

### ISSUE THREAD

**Issue by AlecNova** [eiksch/statev_v2_issues#2940]
Name: Alec Nova
Firmenhash pfAkiTextileCityRew_4 und Firmenhash    pfAkiTextileCityRew_3

https://gyazo.com/14fd5244c9786e5f20c7338563a8d7ea

Ist es möglich einfach für beide Firmen einen Abladepunkt zu setzen? Wenn dies nicht gewollt ist, so würde ich darum bitten, zumindest den vorderen Punkt anzupassen. (also vom Gehweg runter)

LG Alec

**Comment by TheOutburst** [comment]
Sowas machen wir schon länger nichtmehr, sorry

**Comment by AlecNova** [comment]
Aso schade. Aber den einen Punkt auf die selbe Höhe zu setzen geht auch nicht? Weil so muss man immer mit jedem Fahrzeug auf den Bürgersteig drauffahren. Trotzdem Danke für die Mühe.
