### ISSUE TITLE
Old Graham Flachmann lässt sich nicht mehr befüllen...

### ISSUE THREAD

**Issue by Statev-Bonsai** [eiksch/statev_v2_issues#2941]
s.o.

![Screenshot_14](https://github.com/eiksch/statev_v2_issues/assets/70241137/11fa1750-4611-4e2b-ba6e-da08cc4a8384)

**Comment by simplycach** [comment]
Der Flachmann den du da hast ist doch schon befüllt mit Old Graham ? Funktioniert auch mit der leeren Flasche, sie zu befüllen.
