### ISSUE TITLE
Antrag auf Verschiebung des Ausgangspunktes (Paleto)

### ISSUE THREAD

**Issue by Pregon** [eiksch/statev_v2_issues#2945]
Ronny Roberts

Sehr geehrtes StateV-Team,

wäre es möglich beim Haus "paletobay22" den Spawnpunkt beim verlassen des Hauses unter das Dach zu setzen und nicht so weit davor?

Vielen Dank für eure Überprüfung

Freundliche Grüße
Pregon

![Ausgangspunkt](https://github.com/eiksch/statev_v2_issues/assets/75855042/0411ded6-7846-4dae-9d01-3251d211350e)

**Comment by TheOutburst** [comment]
next update changed
