### ISSUE TITLE
Produktionscomputer 24/7 "defekt"

### ISSUE THREAD

**Issue by epichalt** [eiksch/statev_v2_issues#2946]
Shop6

Wenn ich an den "Computer" gehe und "E" drücke passiert nichts. Andere haben e# ebenfalls bereits getestet. 

Keine Fehlermeldung,, nichts
![image](https://github.com/eiksch/statev_v2_issues/assets/16436981/0c6db54d-1861-479c-bb94-8274bfa7cf3a)

**Comment by TheOutburst** [comment]
Kannst du bitte nochmal E drücken, danach F8 und einen Screenshot davon hier rein stellen?

**Comment by CoreForceee** [comment]
also bei mir funktioniert der 24/7 Computer ohne probleme, war erst gestern Abend dort am Entpacken :S

**Comment by epichalt** [comment]
@CoreForceee 
wusste nicht, dass du bei uns eingestellt bist?!

@TheOutburst 
![image](https://github.com/eiksch/statev_v2_issues/assets/16436981/db79a21f-767b-4303-9e75-b42d4a476f72)
22:01:29][Warning] STOPANIM  undefined false false false false false false false undefined undefined  false false
[22:01:29] nailbandTick stopped
[22:01:38] InteractionID: 77b2c256-a5cd-481e-980f-bf8559dc4b09 InteractionRadius 1.75
[22:01:46] InteractionID: 77b2c256-a5cd-481e-980f-bf8559dc4b09 InteractionRadius 1.75
[22:01:52] InteractionID: 77b2c256-a5cd-481e-980f-bf8559dc4b09 InteractionRadius 1.75

**Comment by TheOutburst** [comment]
Gut Ding will Weile haben
Ihr könnt wieder Produzieren
