### ISSUE TITLE
Laptop VWare doppelt im Herstellungscomputer

### ISSUE THREAD

**Issue by SatyriaDine** [eiksch/statev_v2_issues#2947]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Sofia Black

**Auftrittszeitpunkt (Datum / Uhrzeit)**
erstmals bemerkt am 09.07.2023 ca 16Uhr
**Beobachtetes Verhalten**
Im Crime-Produktionscomputer ist 2 mal die Produktion vom VWare Laptop aufgelistet

**Erwartetes Verhalten**
Nur eine Möglichkeit einen VWare Laptop herzustellen 

**Schritte um den Fehler nachvollziehen zu können**
Produktionscomputer im Crimelager öffnen und nach Laptop (VWare) suchen

**Optional: Video / Bilder des Fehlers**

![Screenshot_161](https://github.com/eiksch/statev_v2_issues/assets/84275938/56fc01f5-484b-4769-9b6c-7469d5a8fb2a)

**Comment by TheOutburst** [comment]
oops
next update fixed
