### ISSUE TITLE
"Garage ist voll" obwohl keine Fahrzeuge eingeparkt sind

### ISSUE THREAD

**Issue by M4c-M4ni4c** [eiksch/statev_v2_issues#2948]
**Character Name**
Ronny Mcleod

**Auftrittszeitpunkt (Datum / Uhrzeit)**
09.07.2023 19:40

**Beobachtetes Verhalten**
Garage ist voll obwohl keine Fahrzeuge sich darin befinden
GroupAllRew_House_3
West Mirrir Drive 34

**Erwartetes Verhalten**
So wie vorher das Fahrzeuge eingeparkt werden können

**Schritte um den Fehler nachvollziehen zu können**
Fahrzeug versuchen einzuparken am Haus

**Optional: Video / Bilder des Fehlers**
![image](https://github.com/eiksch/statev_v2_issues/assets/52389841/652221b7-6355-405c-8152-67d2d873f37b)
![image](https://github.com/eiksch/statev_v2_issues/assets/52389841/80077c48-83f6-4f98-92ba-9901ec166d59)

**Comment by TheOutburst** [comment]
Bitte mit allen Kennzeichen die in dem Haus drin sein sollten in den Discord / Ts Support, da werden dir die Autos wieder zur Verfügung gestellt

**Comment by M4c-M4ni4c** [comment]
Es sind keine Fahrzeuge mehr eingeparkt dass hab ich ja schon gemacht aber ich kann nichts einparken obwohl nix drin ist
