### ISSUE TITLE
Bedienung bedient nach 18 Uhr wenn jemand einegestempelt ist

### ISSUE THREAD

**Issue by Blacklady2k** [eiksch/statev_v2_issues#2949]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
 Lia_Vesco

**Auftrittszeitpunkt (Datum / Uhrzeit)**
10.07.23 18.56

**Beobachtetes Verhalten**
Ab 18 Uhr sollen normalerweise die Gäste nur am Tisch essen können, wenn ein Spieler eingestempelt ist. De Dame die drinnen an der Kasse steht sollte ab 18 uhr ausgestellt sein. Heute war es so das Gäste sich an den Tisch gesetzt haben und ein Spieler war zwar eingestellt aber nicht in der Nähe vom PLucker und dann konnten die Gäste trotzdem am Tisch bestellen.  

**Erwartetes Verhalten**
 Ab 18 Uhr können die Gäste nur essen am Tisch bestellen, wenn ein Spieler eingestellt am Plucker/Restaurant steht.  

**Schritte um den Fehler nachvollziehen zu können**
 Spieler stempelt sich ein , fährt weg und Gast setzt sich hin und drückt E um die karte zu bekommen. 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
 Beschreibe Schritt für Schritt wie man den Fehler nachstellen kann 

**Optional: Video / Bilder des Fehlers**

**Comment by simplycach** [comment]
Wie weit ist denn der Spieler vom Restaurant weggewesen?

Wenn ein Spieler eingestempelt ist zu dieser Zeit sollten trotzdem alle Funktion (Npc etc.) möglich sein.

**Comment by EricForster** [comment]
Ich war in der Zeit als das passiert sein soll bei der Tequi-La-La Garage. Dort habe ich auch keine Benachrichtigung bekommen das jemand was bestellen will (ist eigentlich auch logisch).

Meines Verständnis sollte eigentlich das System nicht greifen das sich Leute einfach hinsetzen können und dann von alleine essen können.

**Comment by Davy-Bays** [comment]
Beim Roadhouse Diner ist gestern das gleiche passiert.
Der eingestempelte Kellner war unwissend, außerhalb der Reichweite der "Klingel"  und dadurch konnten Gäste nach 18 Uhr ohne direkte Bedienung an den Tischen essen.

**Comment by simplycach** [comment]
Hey, wäre es möglich, wenn dieser Fehler erneut auftritt ihr ein Video machen könntet ? 

Würde mir sehr helfen. 

LG Simplycach
