### ISSUE TITLE
Fallschirme öffnen ein Glücksspiel

### ISSUE THREAD

**Issue by Dasak0** [eiksch/statev_v2_issues#2950]
Paul Garcia und Kylie Garcia

**Auftrittszeitpunkt (Datum / Uhrzeit)**
10.7.23 Uhrzeit nicht mehr bekannt und 11.7.23 gegen 14.02 Uhr 

**Beobachtetes Verhalten**
Fallschrim lies sich nicht öffnen egal was man versuchte.

**Erwartetes Verhalten**
Fallschirm sollte sich öffnen? ^^ 

**Schritte um den Fehler nachvollziehen zu können**
Am gestrigen Tage sprangen wir beide vom Mazebanktower dort funktionierte es noch. Beim zweiten mal ließ sich der Fallschirm nicht mehr öffnen bei Kylie Garcia. Daraufhin dachte ich es wäre ein Fehler ihrer Seits gewesen. Am heutigen Tage wollten wir es vom mount Chilliad versuchen, und wie man im Video sieht öffnet sich keiner der Fallschirme. Wir hatten uns vorher kurz vorher einmal schlafen gelegt um irgendwelche Bugs schon zu vermeiden. Dann haben wir den Fallschirm angezogen und sind auch direkt gesprungen. Fallschirm wurde am Rücken angezeigt aber ließ sich nicht öffnen. 
Sprich Problem ist jetzt dreimal passiert an verschiedenen Orten. 

**Optional: Video / Bilder des Fehlers**

https://clipchamp.com/watch/PnQ3a7i4rkH?utm_source=share&utm_medium=social&utm_campaign=watch

so sollte es ja normalerweise aussehen:
https://clipchamp.com/watch/8bpN6lFUGUU?utm_source=share&utm_medium=social&utm_campaign=watch

**Comment by simplycach** [comment]
Ist ein Fehler seitens Altv. Können wir leider nichts machen.
