### ISSUE TITLE
Top Falsch beschrieftet?

### ISSUE THREAD

**Issue by StateV2Marie** [eiksch/statev_v2_issues#2952]
Hallo wolt mir heut so nen neues oberteil kaufen aber als ichs dan gekauft habe hab ich gemerkt es is falsch beschrieftet is, ist da schon was gemeldet worden? ich zeig euch gern welches es ist.  [https://pic.statev.de/image/screenshot-2023-07-12-175024.HHwEv2](url)  und [https://pic.statev.de/image/screenshot-2023-07-12-175051.HHwJBP](url)  nun bin ich nich sicher was ich da gekauft habe sry, ich lass es auch so lang bis es behoben is im auto liegen.

**Comment by SHaagmann** [comment]
Wie kriegst du es eig immer hin die Links falsch zu machen? wenn du schon die Funktion nutzt einfach dieses "url" austauschen...

**Comment by StateV2Marie** [comment]
ich weiß nich gehe oben auf link und da setz ich dan den link rein sorry weiß es nich

**Comment by Enemyaa** [comment]
@StateV2Marie 
Ich kann die Bilder nicht sehen und mehr Infos gibt es hier nicht.

**Comment by SHaagmann** [comment]
@Enemyaa [Bild1]([https://pic.statev.de/image/screenshot-2023-07-12-175024.HHwEv2](https://github.com/eiksch/statev_v2_issues/issues/url)) und [Bild2]([https://pic.statev.de/image/screenshot-2023-07-12-175051.HHwJBP](https://github.com/eiksch/statev_v2_issues/issues/url))
