### ISSUE TITLE
Tablet verschiebt sich bei gewissen Aktionen

### ISSUE THREAD

**Issue by FunnyBuddys** [eiksch/statev_v2_issues#2955]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Ranjid_Boniakale

**Auftrittszeitpunkt (Datum / Uhrzeit)**

17.07.2023 - 16:13

**Beobachtetes Verhalten**
Beim öffnen des Handbuches aufm Tablet und dem betätigen des Reiters "3 Gesetze" verschiebt sich das ganze Tablet über die Funk-Raushol-Animation nach oben.

**Erwartetes Verhalten**
Dass das ganze nicht verschoben wird.

**Schritte um den Fehler nachvollziehen zu können**

1. Funkgerät ausrüsten
2. Tablet öffnen
3. Handbuch öffnen
4. Im Inhaltsverzeichnis Gesetze auswählen
5. Tadaa

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

1920x1080

**Optional: Video / Bilder des Fehlers**

Mit Vunk-Gerät

https://github.com/eiksch/statev_v2_issues/assets/16995710/2e8d2138-ef8f-4264-bc55-5325d71c4905

Ohne Vunk-Gerät

https://github.com/eiksch/statev_v2_issues/assets/16995710/e3ca034f-7188-4d84-80fc-8c3af8d44f47

**Comment by KingMarcel** [comment]
https://github.com/eiksch/statev_v2_issues/issues/2890
