### ISSUE TITLE
Hausgarage Verbugt

### ISSUE THREAD

**Issue by Bronze6** [eiksch/statev_v2_issues#2956]
**Character Name**
Nico_Bronze
Xavier_Martinez
Jacky_Martinez
Jason_Rains

**Auftrittszeitpunkt (Datum / Uhrzeit)**
aktuell/
seit 11.07.2023

**Beobachtetes Verhalten**
Erneut eingeparkte Fahrzeuge funktionieren sind aber im West Mirror Drive 4
Die Fahrzeuge an denen wir nicht dran kommen im sind laut StateNET im Westmirror Drive 4
Hat da jemand einfach ein Leerzeichen hinzugefügt? :)

**Optional: Video / Bilder des Fehlers**
![image](https://github.com/eiksch/statev_v2_issues/assets/74800637/dc565e46-4760-4fc4-8545-1768bfd44ff0)
![image](https://github.com/eiksch/statev_v2_issues/assets/74800637/68d042c1-a079-439c-bc27-c2d23125042c)

**Comment by TheOutburst** [comment]
Jau, den Hut darf ich mir aufziehen
Hab dir die Betty in die Diamond Garage gepackt, wenn du mir die anderen Kennzeichen + Besitzer schreibst parke ich die auch um.

**Comment by Bronze6** [comment]
vielen lieben dank
Jacky_Martinez T20 Kennzeichen Jacky wäre noch offen
