### ISSUE TITLE
Firmeneinfahrt

### ISSUE THREAD

**Issue by Auralein** [eiksch/statev_v2_issues#2957]
**Character Name**
Lily Rose

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer xD

**Beobachtetes Verhalten**
Pounder passt nur mit absoluter Millimeter-Arbeit durch die Einfahrt, schabt aber oben rechts an den Elektroleisten und danach links am Baum -> hohe Gefahr, dass der Pounder dabei kaputt geht. Phantom passt da gar nicht erst durch :(
Ebenso geht das Tor von dem Zaun oft nur auf, wenn man es mit dem Auto anstupst -> Gefahr, dass das Auto ebenfalls beschädigt wird.

**Erwartetes Verhalten**
Fahrzeuge passen zu den Firmen durch ohne Schaden zu nehmen.

Gibt es da die Möglichkeit die EInfahrt irgendwie breiter zu machen (und das Tor zu entfernen?) Mein Lager ist in diesem Bereich auch tatsächlich nicht das einzige Gebäude dort, ich meine da sind noch 2 von der HK.

![](https://i.gyazo.com/29512dc2cca9e2715f15923799df419f.jpg)

![](https://i.gyazo.com/2eb5c021ac76cf9712320bae8482ddaf.jpg)

![](https://i.gyazo.com/f2a5214b31a1f7e52d0cbf13c0010aae.png)

**Comment by simplycach** [comment]
Hey Lily,

Also von der Technische Seite ist es leider nicht möglich, dass man die Einfahrt breiter baut bzw. den Pfeiler oben drüber entfernen kann. 

Die Thematik mit den Toren ist ein Problem von GTA V da können wir leider auch nicht viel machen. 

Das Problem mit dem Baum werde ich mal weiter geben eventuell ist dort ja was möglich, versprechen kann ich dir nichts. 

LG simplycach

**Comment by Auralein** [comment]
Aloha,

das dachte ich mir tatsächlich auch c:
ist es denn möglich die Firma an sich zu versetzen? Der Standort war mir an sich nicht so wichtig, ich brauchte nur eine recht abgelegene Firma mit Parkplatz damit meine Fahrzeuge nicht im Weg sind... ich hasse es wenn Phantoms auf Hauptstraßen stehen wegen der Entladepunkte... ich würde auch ein geeignetes Gebäude selber suchen, wenn die möglichkeit bestünde..

Danke! :)
