### ISSUE TITLE
Brute Stokade [potenziell wohl auch Phantom] Buggen bei Schilder Kollision

### ISSUE THREAD

**Issue by EvilGateway** [eiksch/statev_v2_issues#2959]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Kira_Gateway

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Dauerhaft nachstellbar zuletzt 25.07.2023 19:23

**Beobachtetes Verhalten**
Hallo Ihr alle.

Ich habe ne Problematik mit dem Stokade.

Ich denke es ist einfach zu erklären das das Fahrzeug gegen Dumpfe Aufschläge durch seine Enormen Stoßfänger gut gepolstert ist und daher mehr aushält als ein normaler Sport PKW. Dafür hat er ja hohen Verlust bei Beschleunigung und Max. Tempo.
Er ist nicht unsterblich, was Game Mechanik mäßig absolut Richtung und Wichtig ist.

Jedoch habe ich in einem Abstand von 2 Jahren den Stokade als Fahrzeug angefasst.
Und irgendwer muss was an seinem Code oder so gemacht haben.

Bei Zusammenstößen mit Fahrzeugen, leichtem Schleifen an Wänden oder der Kollision mit Ampeln erleidet der Stockade zwar weiterhin Schaden. Hält aber gut was aus und der Schaden der entsteht kommt sofort.
Alles gut.

Nehme ich nun mit der Front oder Heckstoßstange jedoch einen kleinen Holzpfahl oder ein Straßenschild mit und das auch nur in Schrittgeschwindigkeit, zerbröselt oder fällt das Objekt zwar weg, aber während der Fahr hört man die ganze Zeit so ein rütteln als würde man immer wider gegen etwas fahren.

So nach 4 Kilometer fahrt kommt dann die Gelbe und schnell danach die Rote Motorkontrollleuchte.

Ich habe kein Problem damit das ein Straßenschild Schäden hinterlässt. Soll es ja.
Aber es nervt das der Schadenseffekt sich wie ein Bug anfühlt und so verzögert kommt.
Wenn ich z.B. (testweiße geprüft) den Wagen in die Garage stelle und wider raus hole ist dieser Feststeckeffekt beim Fahren weg.

Wäre echt toll wenn die Schadensverteilung sich wieder realistisch anfühlt für die Art des Fahrzeug und seiner Primär vorgesehenen Nutzung als sicherer Kleintransporter und das eben eine Kollision mit einem Fahrzeug wider gefürchteter als das links abbiege Schild ist.

Ich danke euch jetzt schon mal und einen Schönen Tag noch.

Eurer EVIL.

**Erwartetes Verhalten**
Kein Verbuggtes unsichtbares Hängen von Geisterschildern / Direkte Schäden am Fahrzeug und dann wieder gut.

**Schritte um den Fehler nachvollziehen zu können**
Stockade (Geldtransporter) nehmen und egal ob schnell oder ganz leicht ein Straßenschild, Ampelkopf, Holzpfahl mitnehmen.

**Comment by TheOutburst** [comment]
TL;DR:
der Stockade geht schneller kaputt als vorher, normales fahren reicht aus, dass er Schaden kriegt

**Comment by EvilGateway** [comment]
Das ist ja auch gut. 

Mir geht es ja nicht darum das es kein Gottfahrzeug ist, sondern nur darum das ich Problemlos mit 100 Einen Phantom umkippen kann, aber ein holzpfeiler der mit der Hinterseite des Fahrzeug leicht gestriffen hat zum Motorschaden führt nach einigen Metern fahren.

Es fühlt sich einfach nicht RP mäßig anngenehm an.
