### ISSUE TITLE
Nach Regelwerksfragen fehlt UI zum Character Erstellung

### ISSUE THREAD

**Issue by Duergy** [eiksch/statev_v2_issues#2960]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Ralf Richter

**Auftrittszeitpunkt (Datum / Uhrzeit)**
27.07.2023 - 9:18 
**Beobachtetes Verhalten**
Nach Beantwortung der Regel fragen fehlt einiges in der Charakter Erstellung 

**Erwartetes Verhalten**
Bedienelemente etc.sollten da sein
**Schritte um den Fehler nachvollziehen zu können**
Regelwerks Fragen erfolgreich beantwortet und dann zu Charakter Erstellung

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920 x 1080 (Fenstermodus)
**Optional: Video / Bilder des Fehlers**
https://drive.google.com/file/d/1PA0iR0uKXhPDNECB7eB30JA4d0tSXNEd/view?usp=sharing

**Comment by SHaagmann** [comment]
N Einfacher Restart reicht dann sollte alles gehen

**Comment by simplycach** [comment]
Wie Sven schon geschrieben hat ist dieser Fehler nach einem Neustart des Spiels behoben. 

Wenn weitere Probleme auftreten sollten, melde dich gerne nochmal oder ggf. im Support.
