### ISSUE TITLE
Antrag für Port zum Balkon

### ISSUE THREAD

**Issue by Synthesiata** [eiksch/statev_v2_issues#2961]
Liebes Bauteam, 
ich, Nora Bates bitte um einen Portpunkt bei meinem Haus hash: SamsonCountryRew_House_15 
zum Balkon, damit ich diesen auch verwenden kann.
Das Haus befindet sich in Chumash bei 7063.
Vielen Lieben Dank für ihre Mühe!
Liebe Grüße          Nora

**Comment by TheOutburst** [comment]
next update ists drin

**Comment by Synthesiata** [comment]
danke euch:)
