### ISSUE TITLE
Website Link tot

### ISSUE THREAD

**Issue by RoyMckellar** [eiksch/statev_v2_issues#2962]
## WICHTIGE INFORMATION!!:
Auf der Website SteateV.de ist folgender Link tot. https://cdn.altv.mp/altv-release.zip

**Erwartetes Verhalten**
Link geht auf https://cdn.alt-mp.com/launcher/release/x64_win32/altv.exe

mfg

**Comment by simplycach** [comment]
Funktioniert schon länger nicht mehr, einfach die Altv.exe von AltV runterladen. 

https://altv.mp/#/downloads

**Comment by simplycach** [comment]
Sind dran.

**Comment by KingMarcel** [comment]
Ist korrigiert, danke für die Meldung.
