### ISSUE TITLE
Runden Anzahl beim Kartfahren falsch angezeigt

### ISSUE THREAD

**Issue by Pregon** [eiksch/statev_v2_issues#2963]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```
**Character Name**
Ronny Roberts

**Auftrittszeitpunkt (Datum / Uhrzeit)**
3.8.23 15:00

**Beobachtetes Verhalten**
An der Kartbahn steht noch die Runden Anzahl 3 drin

**Erwartetes Verhalten**
Auf 4 erhöhen

**Optional: Video / Bilder des Fehlers**
![image](https://github.com/eiksch/statev_v2_issues/assets/75855042/ca2536c4-df94-40f2-86a8-c4757d7d6ff3)

**Comment by simplycach** [comment]
Mir fehlen da irgendwie paar mehr Infos, wieso genau 4 ?

**Comment by Pregon** [comment]
Kann ich das entfernte question label als Frage beantwortet sehen?

**Comment by simplycach** [comment]
> Kann ich das entfernte question label als Frage beantwortet sehen?

Betrifft dich nicht weiter ja ;)

**Comment by TheOutburst** [comment]
next update füxed
