### ISSUE TITLE
Bauantrag für Portpunkt

### ISSUE THREAD

**Issue by AlecNova** [eiksch/statev_v2_issues#2964]
Hallo liebes Gamedesign Team,

ich wollte in Erfahrung bringen, ob es möglich wäre, einen Portpunkt von der unteren Etage (Rahmen 3) in die obere (Rahmen 4) zu bekommen? Wie auf den Bildern zu sehen, wären passende Türen dafür vorhanden. <img src="https://pic.statev.de/i/HIx27R.jpg" alt="HIx27R.jpg" border="0" />  <img src="https://pic.statev.de/i/HIxNBT.jpg" alt="HIxNBT.jpg" border="0" />

Den Müll (Rahmen 2) zu entfernen würde nur temporär was bringen, weil ich denke, sobald man ihn berührt, er wieder auftauchen würde, so weit ich das aus anderen Anträgen herausgelesen habe. Sollte ich mich irren und dies wäre vernünftig möglich würde ich mich freuen, wenn dieser entfernt wird. <img src="https://pic.statev.de/i/HIxrHB.png" alt="HIxrHB.png" border="0" />

(Rahmen 1) kann ignoriert werden, weil ich vorne keine Tür habe, die es logisch machen würde, dort einen Port nach hinten zu haben.

Wenn etwas nicht ganz verständlich ist, gerne Rückfragen stellen. Ich hoffe, ich konnte es vernünftig darlegen bzw. erklären.

LG Alec Nova

Charaktername: Alec Nova

Haushash: 	house_VinewoodHills_11

**Comment by TheOutburst** [comment]
Du hast es richtig gelesen, dass der Müll nicht weg zu machen ist
Teleport zur oberen Etage und zurück ist next update drin
