### ISSUE TITLE
Anfrage Hausgarage Paleto Bay

### ISSUE THREAD

**Issue by SgtBoaz-Terry** [eiksch/statev_v2_issues#2965]
Terry_Jones

Huhu,

wäre es möglich mir eine Garage am Haus zu implementieren und auch das FOR-SALE-Schild zu entfernen (jeweils markiert)?
Eine Einfahrt ist vorhanden, jedoch kein passendes "Garagenmodel". 

Daten Haus:
https://pic.statev.de/image/HIxCps

Ansicht Haus:
https://pic.statev.de/image/HIxMLt

Nachbarhaus mit gleicher Konstellation, wo eine Garage existiert:
https://pic.statev.de/image/HIxayn

Beste Grüße vom Terry :D

**Comment by TheOutburst** [comment]
next update
