### ISSUE TITLE
Neue Oberteile für Damen lassen sich nicht entpacken

### ISSUE THREAD

**Issue by CoreForceee** [eiksch/statev_v2_issues#2966]
**Character Name**
Kevin Grover

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Jederzeit seit Einführung der Kleidung

**Beobachtetes Verhalten**
Die Oberteile welche mit dem Update hinzugefügt worden sind lassen sich leider immer noch nicht entpacken
hier ein paar Beispiele
[F] Babyblue College Jacket Verpackt 
  | [F] Black Camo T-Shirt Verpackt
  | [F] Black Happy Moon Tee Verpackt 
  | [F] Black-White College Jacket Verpackt 
  | [F] Bordeaux Red College Jacket Verpackt 
  | [F] Dark Gray College Jacket Verpackt 
  | [F] Gray College Jacket Verpackt 
  | [F] Lawn Green College Jacket Verpackt 
  | [F] Purple College Jacket Verpackt
  | [F] Red College Jacket Verpackt 
  | [F] Red Happy Moon Tee Verpackt 
  | [F] Teal College Jacket Verpackt 
  | [F] Turquoise College Jacket Verpackt 
  | [F] White College Jacket Verpackt 
  | [F] White Happy Moon Tee Verpackt

**Erwartetes Verhalten**
Die Oberteile sollte man entpacken können

**Schritte um den Fehler nachvollziehen zu können**
Die Verpackte Kleidung wird von der Schneiderei geliefert und in die Maschine im Kleiderladen gelegt, dort werden Sie aber nicht im Produktionscomputer angeführt.

**Comment by simplycach** [comment]
Besteht der Fehler immer noch ?

**Comment by CoreForceee** [comment]
Also gestern Abend konnte man sie noch nicht entpacken!
LG
