### ISSUE TITLE
Corsita Tuning

### ISSUE THREAD

**Issue by MaCaR23** [eiksch/statev_v2_issues#2967]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Harami Hawsawi

**Auftrittszeitpunkt (Datum / Uhrzeit)**
02.08.2023 / ca 22 Uhr

**Beobachtetes Verhalten**
Das Tuning für die Corsita hat bei SAC nicht funktioniert, da unabhängig von der Veränderung gefühlt immer ein Riesenspoiler drauf war, welcher wiederum nicht mehr entfernt werden konnte, waren weitere Tuningteile sehr durchgemischt. Beim durchschauen der Seitenschweller wurde auf einmal das Dach anders.

**Erwartetes Verhalten**
Ein funktionierendes Tuning bzw. Tuningmöglichkeit

**Schritte um den Fehler nachvollziehen zu können**
Die Corsita bei SAC unterbringen und Tuningmöglichkeit durchschauen.

**Comment by simplycach** [comment]
Wir sind dran, bitte erwarte kein Fix vor V3.

LG. Simplycach
