### ISSUE TITLE
Beantragung einer Hebebühne

### ISSUE THREAD

**Issue by SandyLive89** [eiksch/statev_v2_issues#2968]
Char Name : Sandy Miller

Hallo , anbei sende ich euch hier eine beantragung (siehe Link)  für unsere Werkstatt in Paleto Bay.

 [https://docdro.id/JjbuGrk](url)

**Comment by TheOutburst** [comment]
Moin,

die Aufteilung zwischen LKW & nicht LKW Werkstätten hat einen Sinn und bleibt so wie es ist - auch wenn die Werkstattdichte im Norden sehr dünn ist.
Außerdem ist das hier kein IC Bereich
