### ISSUE TITLE
Waffen können nicht abgekratzt werden 

### ISSUE THREAD

**Issue by SandyLive89** [eiksch/statev_v2_issues#2969]
Charname Sandy Miller

**Auftrittszeitpunkt **
Immer wieder

**Beobachtetes Verhalten**
Waffen von vor 2-4 Jahren können nicht abgekratzt werden ob Taurus , AK47 , Mini Utzi etc 

**Erwartetes Verhalten**
Das sie abgekratzt werden können so wie die anderen auch

**Comment by TheOutburst** [comment]
In der Zwischenzeit wurde die Logik für die Seriennummern überarbeitet, Waffen die so alt sind wurden beim abkratzen leider nicht berücksicht.
Da es aber recht wenige sind und die Käufer auch kaum noch spielen (Ausnahmen bestätigen die Regel) wurde damals diese Entscheidung getroffen
