### ISSUE TITLE
Antrag auf Garage für ein haus in der Southside

### ISSUE THREAD

**Issue by TyriqStone** [eiksch/statev_v2_issues#2970]
Hallo liebes Team, 

Ich hätte für mein Haus in der south gerne einen Garagen punkt da die Garage dahinter noch zum haus gehört, der Eingang für die Garage ist dahinter in einer schmalen Gasse.
Ich habe euch 3 screenshots hinzugefügt dass ihr wisst worum es geht.

LG Tyriq

Haus hash: house_EastLS_43
Char name: Tyriq_Stone.

https://prnt.sc/LjM2CpOiX_tB

https://prnt.sc/9HCyhJy4Yi2F

https://prnt.sc/KQ7EzzEsBB6n

**Comment by TheOutburst** [comment]
Auch wenn es mir in den Fingern gejuckt hat dir den Punkt in den Garten zu setzen - da wo das Garagentor ist - haste next update nen Garagenmarker in der Gasse
