### ISSUE TITLE
For Sale Schild entfernen

### ISSUE THREAD

**Issue by AnneliReagean** [eiksch/statev_v2_issues#2971]
Hallöchen,

wäre es möglich das for Sale Schild im Nicola Place 21 zu entfernen? Wir wohnen da jetzt schon einige Monate und dieses Schild ist überflüssig. 

https://pic.statev.de/image/20230806171821-1.HIlFeB

Vielen Dank im vorraus fürs lesen (oder entfernen =) )

**Comment by TheOutburst** [comment]
Die kann man nicht entfernen

**Comment by TheOutburst** [comment]
nt
