### ISSUE TITLE
Antrag Entfernung "for Sale" Schild  house_MirrorPark_19

### ISSUE THREAD

**Issue by Glitcherprise** [eiksch/statev_v2_issues#2973]
Hallo liebes Team, 

Ich würde mich freuen wenn das unschöne "For Sale" Schild von meinem (Matthias_Neumeister) Grundstück( house_Mirrorpark_19 )
entfernt werden könnte Lg
![For sale](https://github.com/eiksch/statev_v2_issues/assets/141832962/1d5a68a8-a30d-491e-ba01-167e1d23820d)
![adresse](https://github.com/eiksch/statev_v2_issues/assets/141832962/a2e1360c-5b95-4541-bdfa-b8f912a5f861)

**Comment by simplycach** [comment]
Die kann man leider nicht entfernen.
