### ISSUE TITLE
Leggings, haut bugt durch

### ISSUE THREAD

**Issue by M4c-M4ni4c** [eiksch/statev_v2_issues#2975]
**Character Name**
Kira Casitelo

**Auftrittszeitpunkt (Datum / Uhrzeit)**
11.08.2023 20uhr

**Beobachtetes Verhalten**
Leggings bugt durch die haut durch.

**Erwartetes Verhalten**
Das die leggings normal aussieht und nicht als ob sie löcher hat

**Schritte um den Fehler nachvollziehen zu können**
Leggings anziehen

**Optional: Video / Bilder des Fehlers**
![image](https://github.com/eiksch/statev_v2_issues/assets/52389841/96cc602d-d79f-4919-9ef8-e1cf24038917)
![image](https://github.com/eiksch/statev_v2_issues/assets/52389841/c5bb6d97-5102-4e9c-a23c-8fb7bb2bf0c7)

**Comment by SatyriaDine** [comment]
Schon länger so :) 

https://github.com/eiksch/statev_v2_issues/issues/2602
