### ISSUE TITLE
Grundstücke mit Garage ohne nachvollziehbare Garage

### ISSUE THREAD

**Issue by EmilyLodge** [eiksch/statev_v2_issues#2977]
[## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Emily Lodge**

Emily Lodge
**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**

Ich besitze ein Haus in Paleto (Procopio Drive 7), was keine Garage besitzt (besitzt wie man sieht nur eine auffahrt, kein Carport..). Jedoch ist mir bei anderen Grundstücken aufgefallen die auch nur eine Auffahrt besitzen, dass die über eine Garage verfügen. Da wollte ich mal nachfragen, ob eine Nachrüstung an meinem Haus möglich ist bzw. warum die anderen eine haben aber meins nicht 
**Erwartetes Verhalten**

Entweder alle bekommen eine Garage oder die Häuser die eine offensichtliche Garage haben, erhalten eine.
**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://pic.statev.de/image/screenshot-4.HI8tUT - Mein Haus 
https://pic.statev.de/image/screenshot-1.HI8wtc
https://pic.statev.de/image/screenshot-3.HI8ToB
https://pic.statev.de/image/screenshot-18746.HI8Z0R

**Comment by Cro20** [comment]
Vielleicht wäre es auch bei  Procopio Blvd. 0 möglich ?

**Comment by simplycach** [comment]
> Vielleicht wäre es auch bei  Procopio Blvd. 0 auch möglich ?

Am besten einen eigenen Bugtracker aufmachen mit Bildern.

**Comment by simplycach** [comment]
> [## WICHTIGE INFORMATION!!:
> 
> ```
> 
> Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
> 
> ```
> 
> 
> 
> 
> 
> **Emily Lodge**
> 
> 
> 
> Emily Lodge
> 
> **Auftrittszeitpunkt (Datum / Uhrzeit)**
> 
> 
> 
> 
> 
> **Beobachtetes Verhalten**
> 
> 
> 
> Ich besitze ein Haus in Paleto (Procopio Drive 7), was keine Garage besitzt (besitzt wie man sieht nur eine auffahrt, kein Carport..). Jedoch ist mir bei anderen Grundstücken aufgefallen die auch nur eine Auffahrt besitzen, dass die über eine Garage verfügen. Da wollte ich mal nachfragen, ob eine Nachrüstung an meinem Haus möglich ist bzw. warum die anderen eine haben aber meins nicht 
> 
> **Erwartetes Verhalten**
> 
> 
> 
> Entweder alle bekommen eine Garage oder die Häuser die eine offensichtliche Garage haben, erhalten eine.
> 
> **Schritte um den Fehler nachvollziehen zu können**
> 
> 
> 
> 
> 
> **Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
> 
> 
> 
> 
> 
> **Optional: Video / Bilder des Fehlers**
> 
> 
> 
> https://pic.statev.de/image/screenshot-4.HI8tUT - Mein Haus 
> 
> https://pic.statev.de/image/screenshot-1.HI8wtc
> 
> https://pic.statev.de/image/screenshot-3.HI8ToB
> 
> https://pic.statev.de/image/screenshot-18746.HI8Z0R

Das können wir bestimmt einrichten, ich habe das mal weiter gegeben. 

LG simplycach
