### ISSUE TITLE
Antrag auf Bau einer Garage

### ISSUE THREAD

**Issue by Tyson0211** [eiksch/statev_v2_issues#2978]
Tyson Taylor

Hallo,
ich möchte gerne den Bau einer Garage beantragen.
Ein Carport gehört zu dem Haus, was dafür sehr gut genutzt werden kann.
Vielen Dank schonmal im Vorraus, für Eure Bemühungen.

Hier die Adresse von dem Objekt:
Haushash: SandyShores39
Adresse: Cat-Claw Ave.39

LG
Tyson

**Comment by simplycach** [comment]
Hast du zufällig mal ein Screenshot von deinem Haus ?

**Comment by Tyson0211** [comment]
Huhu, hier hätte ich ein Bild

https://pic.statev.de/image/haus-sandy.HIkCcu

**Comment by TheOutburst** [comment]
das isn Trailer, bei aller Liebe aber der kriegt keine Garage
