### ISSUE TITLE
Tuningbugg Sentinel

### ISSUE THREAD

**Issue by Skepji** [eiksch/statev_v2_issues#2979]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name** Daniel Pierce

**Auftrittszeitpunkt (Datum / Uhrzeit)** 14.08.23 / ca 14:30 Uhr

**Beobachtetes Verhalten** Hab mein Fahrzeug ausgeparkt und bemerkt das es etwas anderes Tuning hat. Bin dann in die Werkstatt und wollte die Stoßstange ändern lassen in die Primärfarbe und hat sich alles verändert am Fahrzeug.

**Erwartetes Verhalten** Das mein Auto so ausgeparkt wird wie ich es vorher hatte. 

**Schritte um den Fehler nachvollziehen zu können** Denke das irgendwas in der Datenbank falsch gelaufen ist oder durch altv Updates

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers** https://youtu.be/VD5XzeeZ0IE

**Comment by simplycach** [comment]
Wie lange ist es her, dass du das Fahrzeug zuletzt ausgeparkt hast?

**Comment by Skepji** [comment]
Auch etwas her. Also das jetzt von dem Video und davor bestimmt auch so 3 Monate

**Comment by simplycach** [comment]
Okey, habe ich mal mit aufgenommen, bitte erwarte kein Fix vor V3. 

Eventuell müssen wir sogar auf ein Update seitens AltV warten.
