### ISSUE TITLE
Antrag für den Bau einer kleinen Garage

### ISSUE THREAD

**Issue by FoxXxyLive** [eiksch/statev_v2_issues#2980]
Samy Nustrajev

Hey, ich würde gerne eine kleine Garage für das Haus beantragen, da die nächste öffentliche wirklich sehr weit weg ist und der Verkäufer meinte auch es wäre schon abgeklärt und man könnte da eine kleine hinbekommen? 
Ich wäre euch sehr dankbar, muss nichts großes sein, gebe mich mit allem zufreiden :)

Hausdaten: Haushash: SandyShores58

Screenshot: https://prnt.sc/JG8oYkjRGptL

Danke schonmal im voraus :)

**Comment by FoxXxyLive** [comment]
Perfekt baust du mir eine hin bitte? 
Hahaha Schade, ich dachte das bekommst du auch hin^^

**Comment by simplycach** [comment]
Also damit es keine Missverständnisse gibt, wir werden dort kein extra Gebäude bzw. Garage bauen. 

Es wird ein Punkt wo dein Fahrzeug erscheint, wenn du es ausparkst oder wo du es einparken kannst. 

LG simplycach

**Comment by FoxXxyLive** [comment]
Ja klar das weiß ich, danke dir
