### ISSUE TITLE
Antrag auf Bau einer Kleinen Garage

### ISSUE THREAD

**Issue by Daniel-Meister-508** [eiksch/statev_v2_issues#2981]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Daniel Meister**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**

Hallo zusammen,

Ich wollte mal nachfragen, ob es hier an meinem Haus eine Möglichkeit besteht, dass man dort eine Hausgarage hinzufügen kann, da andere Häuser auch eine Garage ohne nachvollziehbare Garage haben. 

Haushash: paletobay12 -   Procopio Drive 12

Vielen Dank schon mal im Voraus

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://prnt.sc/trEFp1_ZfUeU -> Mein Haus
https://prnt.sc/HPIXUQ8-u5Nb -> Mein Haus´

https://pic.statev.de/image/screenshot-1.HI8wtc -> Beispiel Bild / Haus
https://pic.statev.de/image/screenshot-3.HI8ToB- > Beispiel Bild / Haus

**Comment by TheOutburst** [comment]
also Fotograf wirste schonma nicht, aber mitm nächsten Update haste immerhin ne Garage
