### ISSUE TITLE
Garagenpunkt verlegen

### ISSUE THREAD

**Issue by ChapWinchester** [eiksch/statev_v2_issues#2982]
Würde gerne mein Garagenpunkt verlegen in Grove Street.

Straße:  Grove Street 25
Hash:  house_DevisMidLS_28

Bitte um Verlegung auf dem Fußweg Einfahrt.
![image](https://github.com/eiksch/statev_v2_issues/assets/78925037/77249930-172e-4ed9-8c17-0fefbb1ab237)

Danke im Voraus
Gruß Chap

**Comment by simplycach** [comment]
Warum möchtest du es verlegen ?

**Comment by ChapWinchester** [comment]
Ich wollte im hinteren Bereich eine Grillbereich machen so das, das Parken oder Ausparken nicht blockiert wird. Wenn der Punkt an Gehweg ist kann ich hinten Objekte stellen wie liege kleiner Pool und der gleichen.


 
 
  Am Sa., Aug. 19, 2023 at 9:58 schrieb ***@***.***>:   


Warum möchtest du es verlegen ?

**Comment by simplycach** [comment]
Sehe ich jetzt nicht als notwendig an, du hast ja genug Platz drumherum.
