### ISSUE TITLE
Haus bug 

### ISSUE THREAD

**Issue by Lexywhite** [eiksch/statev_v2_issues#2986]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Lexy_White**

25.08.2023  22:48 Uhr 25.08.2023 22:48 - 26.08.2023 14 Uhr 
 Haus per Kredit gekauft alle rechte vom Kreditgeber erhalten. Kann die Rechte allerdings nicht nutzen. Kein Zugriff auf das Lager oder die Garage oder die Türe aufzuschließen 

**Erwartetes Verhalten**
Da ich alle rechte zu dem Haus habe möchte ich gerne auch den berechtigten Zugriff zum Lager tum Haus und zur Garage haben 

**Schritte um den Fehler nachvollziehen zu können**
House_vinewoodhills_50

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://pic.statev.de/image/screenshot-224.HI7QmV
https://pic.statev.de/image/screenshot-226.HI7ZeS
https://pic.statev.de/image/screenshot-223.HI7T1g

**Comment by Lexywhite** [comment]
> ## WICHTIGE INFORMATION!!:
> ```
> Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
> ```
> 
> **Lexy_White**
> 
> 25.08.2023 22:48 Uhr 25.08.2023 22:48 - 26.08.2023 14 Uhr Haus per Kredit gekauft alle rechte vom Kreditgeber erhalten. Kann die Rechte allerdings nicht nutzen. Kein Zugriff auf das Lager oder die Garage oder die Türe aufzuschließen
> 
> **Erwartetes Verhalten** Da ich alle rechte zu dem Haus habe möchte ich gerne auch den berechtigten Zugriff zum Lager tum Haus und zur Garage haben
> 
> **Schritte um den Fehler nachvollziehen zu können** House_vinewoodhills_50
> 
> **Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
> 
> **Optional: Video / Bilder des Fehlers** https://pic.statev.de/image/screenshot-224.HI7QmV https://pic.statev.de/image/screenshot-226.HI7ZeS https://pic.statev.de/image/screenshot-223.HI7T1g

**Comment by simplycach** [comment]
Wir schauen uns das mal an.

**Comment by Lexywhite** [comment]
okay  danke weil alle rechte sind vergeben aber ich kann nicht mal die Türe auf sperren   die Garage kann man benutzen bzw man kann ein Auto einpacken bekommt es aber nicht mehr raus

**Comment by Lexywhite** [comment]
ich sollte noch diese bilder euch zukommen lassen 

https://pic.statev.de/image/haus-2.HIFK5B
https://pic.statev.de/image/haus1.HIFIAc

**Comment by Lexywhite** [comment]
Hallo, ich habe etwas wegen dem Haus Bug zu melden, eigentlich liegt es nur daran dass das Haus auf einer anderen Adresse läuft.. wir haben jetzt die anderen schlüssel und kommen ins Haus und haben alle Rechte, können auf die Garage zu greifen.. Wir hatten vorher schlüssel zu house_vinewoodhills50   aber das haus war   JunWestCoastRew_House_13.. jetzt haben wir auch die passenden schlüssel und rechte erhalten

**Comment by simplycach** [comment]
Alles klar, wissen wir bescheid.
