### ISSUE TITLE
Hausproblem Mitbewohner 

### ISSUE THREAD

**Issue by loelchn** [eiksch/statev_v2_issues#2987]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

 James Ackles

**Auftrittszeitpunkt (Datum / Uhrzeit)** 

25.08.2023 abends

**Beobachtetes Verhalten**

Haus gekauft  Haushash | house_VinewoodHills - Mitbewohner haben nach Eintragung und Rechte Vergebung kein Zugriff auf das Haus, es ist als wären diese nicht im Tablet eingetragen.  Ich als Besitzer kann wie gewohnt darauf zugreifen.

**Erwartetes Verhalten**

Normale Nutzung, nach Rechtevergebung wie ein Hausbeitzer, Aufsperren / Absperren Garagennutzung Inventar usw..

**Schritte um den Fehler nachvollziehen zu können**

Kann jeden einladen, der das nachprüfen kann.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

/

**Optional: Video / Bilder des Fehlers**

Kann ich nicht, da es bei mir Funktioniert.

**Comment by simplycach** [comment]
Habt ihr mal probiert, die Mitbewohner zu löschen und erneut einzutragen ?

**Comment by loelchn** [comment]
Ja, habe ich 1x

**Comment by simplycach** [comment]
Okey, dann werden wir uns das mal anschauen. Handelt es sich dabei um dasselbe Haus wie aus diesem Bugtracker #2986 ?

**Comment by Lexywhite** [comment]
Ja ist das selbe Haus

**Comment by simplycach** [comment]
Ok

**Comment by loelchn** [comment]
War im Discord Support, und sollte hier die Sache posten, sry wegen Doppelpost :/

**Comment by simplycach** [comment]
Ja es reicht im Normalfall aber aus, wenn einer den Fehler meldet.

**Comment by Lexywhite** [comment]
Hallo, ich habe etwas wegen dem Haus Bug zu melden, eigentlich liegt es nur daran dass das Haus auf einer anderen Adresse läuft.. wir haben jetzt die anderen schlüssel und kommen ins Haus und haben alle Rechte, können auf die Garage zu greifen.. Wir hatten vorher schlüssel zu house_vinewoodhills50   aber das haus war   JunWestCoastRew_House_13.. jetzt haben wir auch die passenden schlüssel und rechte erhalten
