### ISSUE TITLE
Tuning Verschoben Sentinel Classic

### ISSUE THREAD

**Issue by ManuelLadner** [eiksch/statev_v2_issues#2989]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Manuel_Ladner**

** immer und immer wieder**

**Tuning wieder mal fehlerhaft wie bereits bekannt**

**tuning sollte so sein wie ich das getuned habe **

**auto bzw bilder ansehen**

**ausparken anschauen bzw in der werkstatt anschauen das alles verschoben ist**

**Optional: Video / Bilder des Fehlers**

![20230903160213_1](https://github.com/eiksch/statev_v2_issues/assets/77968842/3e51700f-5684-4799-9078-ab87ca38fb00)
![20230903160221_1](https://github.com/eiksch/statev_v2_issues/assets/77968842/58575b3a-9f3f-4300-8bff-40b52df745c7)
![20230903160229_1](https://github.com/eiksch/statev_v2_issues/assets/77968842/bace8b1b-0c10-4c59-986e-d7f11f5a2196)
![20230903160300_1](https://github.com/eiksch/statev_v2_issues/assets/77968842/2bf75fd0-463a-4dfc-92d0-39d0aaef99cc)

**Comment by simplycach** [comment]
Ist bereits bekannt, danke dir trotzdem für die Meldung des Bugs, bitte erwarte aber kein Fix vor V3.

**Comment by ManuelLadner** [comment]
wird eh nicht mehr gefixt oder?

**Comment by eiksch** [comment]
wir reworken das tuning und die autos zu v3 komplett, im aktuellen Stand wirds definitiv leider nicht mehr behoben.
