### ISSUE TITLE
Versetzung des Verladepunktes

### ISSUE THREAD

**Issue by StateVSergio** [eiksch/statev_v2_issues#2991]
Sergio Mendoza
________________________________________________________
Firmenhash  downtowncab1  

Firmenname 🆁🟠🅽 - RAFFINERIE - AM ÖLFELD

 Tangerine Street 46a

ACHTUNG: Taxi HQ hat selben hash und Straße wegen damals undso.
________________________________________________________

Zulieferer beschädigen sich ihre LKW's am Dach teilweise wenn man vorwärts zu schnell auf den Punkt fährt.

Ich erhoffe mir eine sichere Anfahrt für die Lieferranten.

Am besten den Abladepunkt nach rechts auf höhe der beiden Container verlegen.

<img src="https://pic.statev.de/i/HI2AqC.jpg">

**Comment by simplycach** [comment]
Hey, vielen Dank für den Hinweis, ich kann dir aber nicht versprechen, dass ein fix vor V3 erscheinen wird.
