### ISSUE TITLE
Ausparkpunkt falsch, längere Autos hängen fest

### ISSUE THREAD

**Issue by Weddn** [eiksch/statev_v2_issues#2992]
Jo_Kalua

03.10.2023 - 17:45 Uhr

Beim Ausparken des Fahrzeuges aus der Garage buggt das Auto immer wieder in der Garage. Das ist schon 2 mal passiert. Eventuell kann man den Punkt verschieben, damit längere Autos nicht mehr da hängen bleiben.

house_Vinewood_32

Erwartetes Verhalten:
Normales Ausparken :(

Schritte um den Fehler nachvollziehen zu können:
- Paragon aus der Garage ausparken

Optional: Video / Bilder des Fehlers:
https://www.youtube.com/watch?v=745WIA3iTFQ

**Comment by simplycach** [comment]
Vielen Dank für den Hinweis, ich kann dir aber leider nicht versprechen, dass ein fix vor V3 kommt.
