### ISSUE TITLE
[BUG] Fahrzeug fährt zu Schnell [Fehlercode: P0007] 

### ISSUE THREAD

**Issue by PapaGambo** [eiksch/statev_v2_issues#2993]
**Character Name**
Angel Guzman

**Beobachtetes Verhalten**
Mir ist aufgefallen das der Fehlercode: "P0007" Die Bescheinigung sowie die End Geschwinndigkeit massiv verändert.

**Optional: Video / Bilder des Fehlers**
https://www.youtube.com/watch?v=NFKYKmnPq18

**Comment by epichalt** [comment]
Ist kein Bug und müsste aber P000F sein. 
Fahrzeug verbraucht dadurch auch deutlich mehr. Find es auch net so geil, aber manche fahren damit seit Ewigkeiten so rum und lassen den Fehler nicht reparieren
