### ISSUE TITLE
Halloween "Lucy's alte Puppe" falsche Transportgruppe

### ISSUE THREAD

**Issue by DrGrizzlY17** [eiksch/statev_v2_issues#2994]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Trey Jackson

**Beobachtetes Verhalten**
Item is nicht lootbar

![image](https://github.com/eiksch/statev_v2_issues/assets/70150988/ce880a43-72e6-466f-94b3-697f669dc1db)

**Comment by simplycach** [comment]
Ist kein Bug, ist aktuell so gewollt.
