### ISSUE TITLE
[SAMMEL-TICKET] Hotel-Statenet Bugs

### ISSUE THREAD

**Issue by AlexSchneiders** [eiksch/statev_v2_issues#942]
**Alex_Schneiders**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Ab dem 28.12.2020 - 22:54

**Beobachtetes Verhalten**
In der Wohnungsübersicht des Hotelzimmers JunRockFordHillsRew_Hotel_1_3 ist das letzte angegebene Datum bzgl. der letzten Zahlung fehlerhaft. Es wird ein falsches Datum und eine falsche Uhrzeit angezeigt, obwohl der Mieter erst kürzlich abgerechnet wurde.

**Erwartetes Verhalten**
Datum und Uhrzeit sollten sich automatisch aktualisieren, sobald der Mieter die letzte Zahlung getätigt hat.

**Schritte um den Fehler nachvollziehen zu können**
-
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
-
**Optional: Video / Bilder des Fehlers**

Wohnungsübersicht
![Screenshot 2020-12-31 211016](https://user-images.githubusercontent.com/74858882/103424457-b058cd80-4bac-11eb-987a-c02e22538034.png)

Letzte Zahlung
![Screenshot 2020-12-31 211306](https://user-images.githubusercontent.com/74858882/103424521-0e85b080-4bad-11eb-98ce-7e615b04e063.png)

**Comment by TeubyDE** [comment]
Sammeltickets werden abgeschafft. Sollte noch was offen sein -> neuer Eintrag verfassen
