### ISSUE TITLE
WERKSTATT: Xenon-Lichter werden automatisch verbaut bzw. auf Serie zurückgesetzt

### ISSUE THREAD

**Issue by LautaroTesto** [eiksch/statev_v2_issues#986]
**Lautaro Testo**

**Auftrittszeitpunkt (Datum / Uhrzeit)**  21:30Uhr  06.01.2021

**Beobachtetes Verhalten** (Werkstatt) Beim Tuning werden die Xenon-Lichter ( wurde Frontgrill & Auspuff getuned) wieder auf Serie zurück gesetzt. Wurden auch aus dem Lager auch entnommen 2x Xenon-Lichter.

**Erwartetes Verhalten**  Kein Bau von Xenon-Lichter, wenn es nicht gewählt ist.

**Schritte um den Fehler nachvollziehen zu können** Tunig wurde ausgewählt > beliebiges Teil wurde ausgesucht und verbaut > es wurde festgestellt das Xenon auf "Serie" zurück ist, ohne das es ausgewählt wurde

**Comment by Dean-Gallagher** [comment]
Ich kann es Reproduzieren.

Fahrzeug muss Xenons verbaut haben!

Auto fährt auf Rep punkt. Motor abschalten (mit laufenden muss noch getestet werden)
Fahrzeug reppen. 
Nach der Rep aufschließen um zu sehen ob die Xenons wieder resetet worden auf serien farbe. 
Wenn dies passiert ist und man nun etwas tuned außer xenons, verbraucht es automatisch aus dem Lager Xenon lichter und die Xenon lichter auf Serie bleiben so. 

Parkt man das Auto wieder ein eh man etwas tuned, ist der Bug umgangen da dadurch die Xenons wieder zu dem werden, was auch auf dem Auto ist.
